const{test,expect}=require('@playwright/test');const{login,api,response,choice,selectUser,group,project}=require('./parity-settings-stage2-helpers.cjs');
test('group required custom field blocks save and corrected enabled disabled states persist',async({page},info)=>{
 page.setDefaultTimeout(10000);await login(page,'admin');const g=await group(page,'custom');await page.goto('/group/'+g._id);await page.getByRole('tab',{name:'分组设置',exact:true}).click();await page.getByPlaceholder('请输入分组名称').fill(g.group_name+' edited');await page.getByPlaceholder('请输入分组描述').fill('Synthetic custom description');await page.locator('.panel-group .ant-switch').click();await expect(page.getByText('自定义字段名称不能为空',{exact:true})).toBeVisible();let writes=0;page.on('request',r=>{if(new URL(r.url()).pathname==='/api/group/up'&&r.method()==='POST')writes++});await page.getByRole('button',{name:/保\s*存/}).click();await expect(page.getByText('自定义字段名称不能为空',{exact:true})).toBeVisible();expect((await api(page,'/api/group/get?id='+g._id)).group_name).toBe(g.group_name);expect(writes).toBe(0);
 await page.getByPlaceholder('请输入自定义字段名称').fill('Synthetic review field');await response(page,'/api/group/up',()=>page.getByRole('button',{name:/保\s*存/}).click());await page.reload();await page.getByRole('tab',{name:'分组设置',exact:true}).click();await expect(page.getByPlaceholder('请输入分组名称')).toHaveValue(g.group_name+' edited');expect(await api(page,'/api/group/get?id='+g._id)).toMatchObject({group_desc:'Synthetic custom description',custom_field1:{name:'Synthetic review field',enable:true}});await page.locator('.panel-group .ant-switch').click();await response(page,'/api/group/up',()=>page.getByRole('button',{name:/保\s*存/}).click());await page.reload();await page.getByRole('tab',{name:'分组设置',exact:true}).click();expect((await api(page,'/api/group/get?id='+g._id)).custom_field1.enable).toBe(false);await page.screenshot({path:info.outputPath('custom-field.png'),fullPage:true});
});
for(const [role,label]of [['owner','组长'],['dev','开发者'],['guest','访客']])test('group exact selected '+role+' add cancel reopen duplicate',async({page},info)=>{
 page.setDefaultTimeout(10000);await login(page,'admin');const g=await group(page,'member-'+role);await login(page);await page.goto('/group/'+g._id);await page.getByRole('tab',{name:'成员列表',exact:true}).click();const dialog=page.getByRole('dialog');await page.getByRole('button',{name:/添加成员$/}).click();await selectUser(page,dialog,'developer');await dialog.getByRole('button',{name:/取\s*消/}).click();expect((await api(page,'/api/group/get_member_list?id='+g._id)).map(x=>x.uid)).toEqual([910002]);await page.getByRole('button',{name:/添加成员$/}).click();await selectUser(page,dialog,'outsider');await choice(page,dialog.locator('.ant-select').last(),label);await response(page,'/api/group/add_member',()=>dialog.getByRole('button',{name:/确\s*定/}).click());let rows=await api(page,'/api/group/get_member_list?id='+g._id);expect(rows.map(x=>x.uid).sort()).toEqual([910002,910004]);expect(rows.find(x=>x.uid===910004).role).toBe(role);
 await page.getByRole('button',{name:/添加成员$/}).click();await selectUser(page,dialog,'outsider');await choice(page,dialog.locator('.ant-select').last(),label);const result=await response(page,'/api/group/add_member',()=>dialog.getByRole('button',{name:/确\s*定/}).click());expect(result.add_members).toHaveLength(0);expect(result.exist_members).toHaveLength(1);await page.reload();await page.getByRole('tab',{name:'成员列表',exact:true}).click();await expect(page.getByRole('row').filter({has:page.getByText('Synthetic outsider',{exact:true})})).toHaveCount(1);await page.screenshot({path:info.outputPath('group-'+role+'.png'),fullPage:true});
});
test('group role changes alter inherited project rights on next request',async({page,browser},info)=>{
 page.setDefaultTimeout(10000);await login(page,'admin');const g=await group(page,'inherited');await login(page);const p=await project(page,'inherited',g._id);await api(page,'/api/group/add_member',{id:g._id,member_uids:[910003],role:'dev'});await page.goto('/group/'+g._id);await page.getByRole('tab',{name:'成员列表',exact:true}).click();const row=page.getByRole('row').filter({has:page.getByText('Synthetic developer',{exact:true})});const c=await browser.newContext({baseURL:info.project.use.baseURL,viewport:{width:1920,height:1080}});try{const dev=await c.newPage();await login(dev,'developer');for(const [role,label,allowed]of [['guest','访客',false],['owner','组长',true],['dev','开发者',false]]){await response(page,'/api/group/change_member_role',()=>choice(page,row.locator('.ant-select'),label));await dev.goto('/project/'+p._id+'/members');expect((await api(dev,'/api/project/get?id='+p._id)).role).toBe(role);const r=await(await dev.request.post('/api/project/up',{data:{id:p._id,desc:'Synthetic inherited '+role}})).json();expect(r.errcode===0).toBe(allowed);if(allowed)expect((await api(page,'/api/project/get?id='+p._id)).desc).toBe('Synthetic inherited '+role);}await dev.screenshot({path:info.outputPath('inherited-dev.png'),fullPage:true});}finally{await c.close();}
});
