const {test,expect}=require('@playwright/test');
test.beforeEach(async({page})=>page.setDefaultTimeout(12000));
async function api(page,url,data){const r= data===undefined?await page.request.get(url):await page.request.post(url,{data});expect(r.status(),url).toBe(200);const b=await r.json();expect(b.errcode,url).toBe(0);return b.data;}
async function login(page,role='owner'){await page.context().clearCookies();await page.goto('/login');await page.getByPlaceholder('Email',{exact:true}).fill(role+'@ui-parity.invalid');await page.getByPlaceholder('Password',{exact:true}).fill('SyntheticParityOnly_901000!');await page.getByRole('button',{name:/^登\s*录$/}).click();await expect(page).toHaveURL(/group/);}
async function setup(page,count=2){await login(page);const p=await api(page,'/api/project/add',{name:'Synthetic B closure '+Date.now(),group_id:901000,project_type:'private'});await api(page,'/api/project/up',{id:p._id,env:[{name:'local',domain:'http://127.0.0.1:3000/mock/'+p._id}]});const cat=(await api(page,'/api/interface/getCatMenu?project_id='+p._id))[0];const i=await api(page,'/api/interface/add',{project_id:p._id,catid:cat._id,title:'Closure source',path:'/closure',method:'GET'});await api(page,'/api/interface/up',{id:i._id,res_body_type:'json',res_body_is_json_schema:false,res_body:'{"code":0,"text":"合成测试"}',req_query:[{name:'first',required:'0',desc:'first',example:'one'},{name:'second',required:'0',desc:'second',example:'two'}]});const col=await api(page,'/api/col/add_col',{project_id:p._id,name:'Closure collection'});const cases=[];for(let n=0;n<count;n++)cases.push(await api(page,'/api/col/add_case',{project_id:p._id,col_id:col._id,interface_id:i._id,casename:'Closure case '+n}));const fixture={project:p._id,iface:i._id,col:col._id,cases};page.scopeBFixture=fixture;return fixture;}
async function saveResponse(page,path,action){const wait=page.waitForResponse(r=>new URL(r.url()).pathname===path);await action();const b=await(await wait).json();expect(b.errcode,path).toBe(0);return b.data;}
async function select(page,loc,text){await loc.scrollIntoViewIfNeeded();await loc.click();const input=loc.locator('input');if(await input.isEditable()){await input.fill(text);await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');}else{await page.locator('.ant-select-dropdown:visible .ant-select-item-option-content').getByText(text,{exact:true}).click();}await expect(loc).toContainText(text);}
async function ace(page,root,text){await expect(root).toBeVisible();await expect(root.locator('.ace_content')).toContainText('code');await root.locator('textarea').focus();await page.keyboard.press('Meta+A');await page.keyboard.insertText(text);await expect(root.locator('.ace_content')).toContainText(text);}




test('advanced Mock chooses most specific enabled expectation through create edit disable and delete',async({page},info)=>{const f=await setup(page,0);await page.goto(`/project/${f.project}/interface/api/${f.iface}`);await page.getByText('高级Mock',{exact:true}).click();async function create(name,params){await page.getByRole('button',{name:'添加期望',exact:true}).click();const d=page.getByRole('dialog');await d.getByPlaceholder('请输入期望名称',{exact:true}).fill(name);for(let i=0;i<params.length;i++){if(i)await d.getByRole('button',{name:/添加参数/}).click();const row=d.locator('.paramsArr').nth(i);await row.locator('input').first().fill(params[i][0]);await row.getByPlaceholder('参数值').fill(params[i][1]);}await d.locator('.headers').first().locator('input').first().fill('X-Fixture-Priority');await d.locator('.headers').first().getByPlaceholder('参数值').fill(name);await saveResponse(page,'/api/plugin/advmock/case/save',()=>d.getByRole('button',{name:/确\s*定/}).click());await expect(d).toHaveCount(0);}
 await create('broad',[['tier','one']]);await create('specific',[['tier','one'],['flavor','two']]);const matched=async query=>{const response=await page.request.get('/mock/'+f.project+'/closure?'+query);expect(response.status()).toBe(200);expect((await response.json()).code).toBe(0);return response.headers()['x-fixture-priority'];};expect(await matched('tier=one')).toBe('broad');expect(await matched('tier=one&flavor=two')).toBe('specific');const row=page.getByRole('row').filter({has:page.getByText('broad',{exact:true})});await row.getByRole('button',{name:/编\s*辑/}).click();let d=page.getByRole('dialog');for(const [key,value] of [['flavor','two'],['extra','three']]){await d.getByRole('button',{name:/添加参数/}).click();const p=d.locator('.paramsArr').last();await p.locator('input').first().fill(key);await p.getByPlaceholder('参数值').fill(value);}await saveResponse(page,'/api/plugin/advmock/case/save',()=>d.getByRole('button',{name:/确\s*定/}).click());expect(await matched('tier=one&flavor=two&extra=three')).toBe('broad');await saveResponse(page,'/api/plugin/advmock/case/hide',()=>row.getByRole('button',{name:'已开启',exact:true}).click());expect(await matched('tier=one&flavor=two&extra=three')).toBe('specific');await page.reload();await page.getByText('高级Mock',{exact:true}).click();expect(await matched('tier=one&flavor=two&extra=three')).toBe('specific');const stored=await api(page,'/api/plugin/advmock/case/list?interface_id='+f.iface);expect(stored).toHaveLength(2);await row.getByRole('button',{name:/删\s*除/}).click();await page.getByRole('button',{name:/取\s*消$/}).click();expect(await api(page,'/api/plugin/advmock/case/list?interface_id='+f.iface)).toHaveLength(2);await row.getByRole('button',{name:/删\s*除/}).click();await saveResponse(page,'/api/plugin/advmock/case/del',()=>page.getByRole('button',{name:/确\s*定$/}).click());await expect(row).toHaveCount(0);expect(await matched('tier=one&flavor=two&extra=three')).toBe('specific');await page.screenshot({path:info.outputPath('mock-priority.png'),animations:'disabled'});await info.attach('priority-result',{body:JSON.stringify({project:f.project,interface:f.iface,rule:'max matched parameter count, enabled only',manualReorder:'no such control in either version'}),contentType:'application/json'});
 const{expected}=require('./parity-collections-guard.cjs'),e=expected(info.project.name),{execFileSync}=require('node:child_process'),prefix=info.project.name==='new'?'await ':'';const js=`var marker=${prefix}db.getCollection('_ui_parity_fixture').findOne({_id:'yapi-ui-parity-v1'});if(!marker||marker.run!=='fastb1003'||marker.synthetic!==true||marker.fixtureSha256!==${JSON.stringify(e.hash)})throw Error('Wrong fixture');var rows=${prefix}db.adv_mock_case.find({interface_id:${f.iface}},{_id:1,name:1,params:1,headers:1,enable:1}).toArray();print(JSON.stringify(rows))`;const raw=execFileSync('docker',['exec',e.mongo,info.project.name==='new'?'mongosh':'mongo','--quiet',e.database,'--eval',info.project.name==='new'?'(async()=>{'+js+'})()':js],{encoding:'utf8'});const rows=JSON.parse(raw.trim());expect(rows).toHaveLength(1);expect(rows[0].name).toBe('specific');await info.attach('synthetic-db-mock-priority',{body:JSON.stringify(rows),contentType:'application/json'});
});
