const {test,expect}=require('@playwright/test');
test.beforeEach(async({page})=>page.setDefaultTimeout(12000));
async function api(page,url,data){const r= data===undefined?await page.request.get(url):await page.request.post(url,{data});expect(r.status(),url).toBe(200);const b=await r.json();expect(b.errcode,url).toBe(0);return b.data;}
async function login(page,role='owner'){await page.context().clearCookies();await page.goto('/login');await page.getByPlaceholder('Email',{exact:true}).fill(role+'@ui-parity.invalid');await page.getByPlaceholder('Password',{exact:true}).fill('SyntheticParityOnly_901000!');await page.getByRole('button',{name:/^登\s*录$/}).click();await expect(page).toHaveURL(/group/);}
async function setup(page,count=2){await login(page);const p=await api(page,'/api/project/add',{name:'Synthetic B closure '+Date.now(),group_id:901000,project_type:'private'});await api(page,'/api/project/up',{id:p._id,env:[{name:'local',domain:'http://127.0.0.1:3000/mock/'+p._id}]});const cat=(await api(page,'/api/interface/getCatMenu?project_id='+p._id))[0];const i=await api(page,'/api/interface/add',{project_id:p._id,catid:cat._id,title:'Closure source',path:'/closure',method:'GET'});await api(page,'/api/interface/up',{id:i._id,res_body_type:'json',res_body_is_json_schema:false,res_body:'{"code":0,"text":"合成测试"}',req_query:[{name:'first',required:'0',desc:'first',example:'one'},{name:'second',required:'0',desc:'second',example:'two'}]});const col=await api(page,'/api/col/add_col',{project_id:p._id,name:'Closure collection'});const cases=[];for(let n=0;n<count;n++)cases.push(await api(page,'/api/col/add_case',{project_id:p._id,col_id:col._id,interface_id:i._id,casename:'Closure case '+n}));const fixture={project:p._id,iface:i._id,col:col._id,cases};page.scopeBFixture=fixture;return fixture;}
async function saveResponse(page,path,action){const wait=page.waitForResponse(r=>new URL(r.url()).pathname===path);await action();const b=await(await wait).json();expect(b.errcode,path).toBe(0);return b.data;}
async function select(page,loc,text){await loc.scrollIntoViewIfNeeded();await loc.click();const input=loc.locator('input');if(await input.isEditable()){await input.fill(text);await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');}else{await page.locator('.ant-select-dropdown:visible .ant-select-item-option-content').getByText(text,{exact:true}).click();}await expect(loc).toContainText(text);}
async function ace(page,root,text){await expect(root).toBeVisible();await expect(root.locator('.ace_content')).toContainText('code');await root.locator('textarea').focus();await page.keyboard.press('Meta+A');await page.keyboard.insertText(text);await expect(root.locator('.ace_content')).toContainText(text);}




async function treeDrag(page,source,target){const a=await source.boundingBox(),b=await target.boundingBox();await page.mouse.move(a.x+30,a.y+a.height/2);await page.mouse.down();await page.mouse.move(b.x+110,b.y+b.height*0.75,{steps:10});await page.waitForTimeout(700);await page.mouse.up();}
async function readCol(page,id){const r=await page.request.get('/api/col/case_list?col_id='+id),b=await r.json();expect(b.errcode).toBe(0);return b.colData;}
async function openImport(page){const tree=page.locator('.menu-title').filter({has:page.getByText('Closure collection',{exact:true})});await tree.hover();await tree.locator('.anticon-plus').click();const d=page.getByRole('dialog',{name:'导入接口到集合'});await expect(d.getByText('公共分类',{exact:true})).toBeVisible();const collapsed=d.locator('.ant-table-row-expand-icon-collapsed,.ant-table-row-collapsed');if(await collapsed.count())await collapsed.first().click();return d;}
test('rules cancel reopen and all builtin toggles values persist exact collection',async({page},info)=>{
 const f=await setup(page,1);await page.goto(`/project/${f.project}/interface/col/${f.col}`);await expect(page.getByRole('cell',{name:'Closure case 0',exact:true})).toBeVisible();
 const before=await readCol(page,f.col),d=page.getByRole('dialog',{name:'通用规则配置'}),open=()=>page.getByRole('button',{name:'通用规则配置',exact:true}).click();
 await open();await d.getByPlaceholder('字段名',{exact:true}).fill('discard');await d.locator('.ant-switch').nth(0).click();await d.getByRole('button',{name:/取\s*消$/}).click();await open();await expect(d.getByPlaceholder('字段名',{exact:true})).toHaveValue(before.checkResponseField.name);expect((await readCol(page,f.col)).checkHttpCodeIs200).toBe(before.checkHttpCodeIs200);
 for(let i=0;i<3;i++)await d.locator('.ant-switch').nth(i).click();await d.getByPlaceholder('字段名',{exact:true}).fill('text');await d.getByPlaceholder('值',{exact:true}).fill('合成测试');
 await saveResponse(page,'/api/col/up_col',()=>d.getByRole('button',{name:/确\s*定$/}).click());await expect(d).toHaveCount(0);await page.reload();await open();
 const after=await readCol(page,f.col);expect(after.checkHttpCodeIs200).toBe(!before.checkHttpCodeIs200);expect(after.checkResponseSchema).toBe(!before.checkResponseSchema);expect(after.checkResponseField).toEqual({name:'text',value:'合成测试',enable:!before.checkResponseField.enable});for(const [i,v]of[[0,after.checkHttpCodeIs200],[1,after.checkResponseField.enable],[2,after.checkResponseSchema]])await expect(d.locator('.ant-switch').nth(i)).toHaveAttribute('aria-checked',String(v));
 await d.getByRole('button',{name:/取\s*消$/}).click();await page.screenshot({path:info.outputPath('rules-persisted.png'),animations:'disabled'});
});
test('import category status source cancel and repeated submit use only visible selected IDs',async({page},info)=>{
 const f=await setup(page,0),source=await api(page,'/api/project/add',{name:'Other import source '+Date.now(),group_id:901000,project_type:'private'}),cat=(await api(page,'/api/interface/getCatMenu?project_id='+f.project))[0];
 const done=await api(page,'/api/interface/add',{project_id:f.project,catid:cat._id,title:'Completed synthetic',path:'/completed',method:'GET'});await api(page,'/api/interface/up',{id:done._id,status:'done'});
 await page.goto(`/project/${f.project}/interface/col/${f.col}`);let d=await openImport(page);const category=()=>d.getByRole('row').filter({has:page.getByText(cat.name,{exact:true})});await category().getByRole('checkbox').check();await d.getByRole('button',{name:/取\s*消$/}).click();expect(await api(page,'/api/col/case_list?col_id='+f.col)).toHaveLength(0);
 d=await openImport(page);await expect(d.getByRole('checkbox',{checked:true})).toHaveCount(0);await category().getByRole('checkbox').check();await d.getByRole('columnheader').filter({hasText:'状态'}).locator('.ant-table-filter-trigger').click();const drop=page.locator('.ant-dropdown:visible');await drop.getByText('未完成',{exact:true}).click();await drop.getByRole('button',{name:/确\s*定|OK/}).click();await expect(d.getByText('Completed synthetic',{exact:true})).toHaveCount(0);await expect(d.getByRole('checkbox',{checked:true})).toHaveCount(0);await category().getByRole('checkbox').check();
 let writes=0;await page.route('**/api/col/add_case_list',async r=>{writes++;expect(r.request().postDataJSON().interface_list).toEqual([f.iface]);await new Promise(resolve=>setTimeout(resolve,200));await r.continue();});await saveResponse(page,'/api/col/add_case_list',()=>d.getByRole('button',{name:/确\s*定$/}).dblclick({delay:15}));await expect(d).toHaveCount(0);expect(writes).toBe(1);expect((await api(page,'/api/col/case_list?col_id='+f.col)).map(x=>x.interface_id)).toEqual([f.iface]);await page.unroute('**/api/col/add_case_list');await page.reload();d=await openImport(page);await expect(d.getByRole('checkbox',{checked:true})).toHaveCount(0);
 await d.getByRole('row').filter({has:page.getByText('Closure source',{exact:true})}).getByRole('checkbox').check();await select(page,d.locator('.select-project .ant-select'),source.name);await expect(d.getByRole('checkbox',{checked:true})).toHaveCount(0);await d.getByRole('button',{name:/取\s*消$/}).click();expect((await api(page,'/api/col/case_list?col_id='+f.col)).map(x=>x.interface_id)).toEqual([f.iface]);await page.screenshot({path:info.outputPath('import-exact-selection.png'),animations:'disabled'});
});
test.afterEach(async({page},info)=>{
 const f=page.scopeBFixture;if(!f)return;const {expected}=require('./parity-collections-guard.cjs'),e=expected(info.project.name),{execFileSync}=require('node:child_process'),prefix=info.project.name==='new'?'await ':'';
 const js=`var marker=${prefix}db.getCollection('_ui_parity_fixture').findOne({_id:'yapi-ui-parity-v1'});if(!marker||marker.run!=='fastb1003'||marker.synthetic!==true||marker.fixtureSha256!==${JSON.stringify(e.hash)})throw Error('Wrong fixture');var cols=${prefix}db.interface_col.find({project_id:${f.project}},{name:1,desc:1,project_id:1,index:1,checkHttpCodeIs200:1,checkResponseField:1,checkResponseSchema:1,test_report:1}).toArray();var cases=${prefix}db.interface_case.find({project_id:${f.project}},{casename:1,col_id:1,interface_id:1,index:1}).toArray();var project=${prefix}db.project.findOne({_id:${f.project}},{env:1,is_mock_open:1});print(JSON.stringify({cols:cols,cases:cases,global:project.env.map(function(e){return {name:e.name,global:e.global}}),is_mock_open:project.is_mock_open}))`;
 const raw=execFileSync('docker',['exec',e.mongo,info.project.name==='new'?'mongosh':'mongo','--quiet',e.database,'--eval',info.project.name==='new'?'(async()=>{'+js+'})()':js],{encoding:'utf8'});const stored=JSON.parse(raw.trim());const cases=await api(page,'/api/col/case_list?col_id='+f.col);expect(stored.cases.filter(c=>c.col_id===f.col).map(c=>c._id).sort()).toEqual(cases.map(c=>c._id).sort());expect((stored.cols.find(c=>c._id===f.col)||{}).test_report||'').toBe((await readCol(page,f.col)).test_report||'');await info.attach('synthetic-lifecycle-db-readback',{body:JSON.stringify(stored),contentType:'application/json'});
});

test('tree case cross collection drag and collection order persist target ownership',async({page},info)=>{
 const f=await setup(page,2),other=await api(page,'/api/col/add_col',{project_id:f.project,name:'Destination collection'});await page.goto(`/project/${f.project}/interface/col/${f.col}`);await expect(page.getByRole('cell',{name:'Closure case 0',exact:true})).toBeVisible();
 const source=page.locator('.menu-title[title="Closure case 0"]'),destination=page.locator('.menu-title').filter({has:page.getByText('Destination collection',{exact:true})});
 await saveResponse(page,'/api/col/up_case',()=>treeDrag(page,source,destination));await expect.poll(async()=>(await api(page,'/api/col/case_list?col_id='+other._id)).map(x=>x._id)).toEqual([f.cases[0]._id]);expect((await api(page,'/api/col/case?caseid='+f.cases[0]._id)).project_id).toBe(f.project);expect((await api(page,'/api/col/case_list?col_id='+f.col)).map(x=>x._id)).toEqual([f.cases[1]._id]);await page.reload();
 await saveResponse(page,'/api/col/up_col_index',()=>treeDrag(page,destination,page.locator('.menu-title').filter({has:page.getByText('Closure collection',{exact:true})})));const order=(await api(page,'/api/col/list?project_id='+f.project)).map(x=>x._id);expect(order.indexOf(other._id)).toBeLessThan(order.indexOf(f.col));await page.reload();expect((await api(page,'/api/col/list?project_id='+f.project)).map(x=>x._id)).toEqual(order);await destination.click();await expect(page.getByRole('cell',{name:'Closure case 0',exact:true})).toBeVisible();await expect(page.getByRole('cell',{name:'Closure case 1',exact:true})).toHaveCount(0);await page.screenshot({path:info.outputPath('tree-cross-owner-order.png'),animations:'disabled'});
});

test('tree rename cancel delete cancel reopen and repeated clone affect only selected case',async({page},info)=>{
 const f=await setup(page,2);await page.goto(`/project/${f.project}/interface/col/${f.col}`);await expect(page.getByRole('cell',{name:'Closure case 1',exact:true})).toBeVisible();const collection=page.locator('.menu-title').filter({has:page.getByText('Closure collection',{exact:true})});await collection.hover();await collection.locator('.anticon-edit').click();let d=page.getByRole('dialog');await d.locator('input').first().fill('Discarded collection name');await d.getByRole('button',{name:/取\s*消$/}).click();await collection.hover();await collection.locator('.anticon-edit').click();await expect(d.locator('input').first()).toHaveValue('Closure collection');await d.locator('.ant-modal-close').click();
 const selected=page.locator('.menu-title[title="Closure case 0"]');await selected.hover();await selected.locator('.anticon-delete').click();d=page.getByRole('dialog');await d.getByRole('button',{name:/取\s*消$/}).click();expect((await api(page,'/api/col/case_list?col_id='+f.col)).map(x=>x._id).sort()).toEqual(f.cases.map(x=>x._id).sort());
 let copies=0;await page.route('**/api/col/add_case',async r=>{copies++;await new Promise(resolve=>setTimeout(resolve,250));await r.continue();});await selected.hover();await selected.locator('.anticon-copy').dblclick({delay:15});await expect.poll(async()=>(await api(page,'/api/col/case_list?col_id='+f.col)).length).toBe(3);expect(copies).toBe(1);await page.reload();await expect(page.locator('.menu-title[title="Closure case 0_copy"]')).toBeVisible();const stored=await api(page,'/api/col/case_list?col_id='+f.col);expect(stored.filter(x=>x.casename==='Closure case 0_copy')).toHaveLength(1);expect(stored.find(x=>x._id===f.cases[1]._id).casename).toBe('Closure case 1');await selected.hover();await selected.locator('.anticon-delete').click();await saveResponse(page,'/api/col/del_case',()=>page.getByRole('dialog').getByRole('button',{name:/确\s*认$/}).click());await page.reload();expect((await api(page,'/api/col/case_list?col_id='+f.col)).map(x=>x.casename).sort()).toEqual(['Closure case 0_copy','Closure case 1']);await page.screenshot({path:info.outputPath('tree-target-only.png'),animations:'disabled'});
});


test('reports distinguish HTTP assertion and schema failure then clear stale result for passing rerun',async({page},info)=>{
 const f=await setup(page,1);await api(page,'/api/interface/up',{id:f.iface,res_body_is_json_schema:true,res_body:JSON.stringify({type:'object',required:['code'],properties:{code:{type:'number'}}})});
 for(const kind of ['http','field','schema']){
  await api(page,'/api/col/up_col',{col_id:f.col,checkHttpCodeIs200:kind==='http',checkResponseField:{enable:kind==='field',name:'code',value:'0'},checkResponseSchema:kind==='schema'});
  const mock=await api(page,'/api/plugin/advmock/case/save',{project_id:f.project,interface_id:f.iface,name:'Synthetic '+kind,code:kind==='http'?404:200,delay:0,params:{},headers:[{name:'X-Report',value:kind}],res_body:JSON.stringify({code:kind==='schema'?'bad-type':7,text:'Synthetic '+kind})});
  await page.goto(`/project/${f.project}/interface/col/${f.col}`);await expect(page.getByRole('cell',{name:'Closure case 0',exact:true})).toBeVisible();await saveResponse(page,'/api/col/up_col',()=>page.getByRole('button',{name:'开始测试',exact:true}).click());await page.getByRole('button',{name:'测试报告',exact:true}).click();const d=page.getByRole('dialog',{name:'测试报告',exact:true});await d.getByRole('tab',{name:'Response',exact:true}).click();await expect(d.locator('.case-report-pane:visible')).toContainText(kind==='http'?'404':'200');await expect(d.locator('.case-report-pane:visible')).toContainText('x-report');await expect(d.locator('.case-report-pane:visible')).toContainText('Synthetic '+kind);await d.getByRole('tab',{name:'验证结果',exact:true}).click();const pane=d.locator('.case-report-pane:visible');await expect(pane).toContainText(kind==='http'?/Http|http/:kind==='field'?/字段|code/:/schema|Schema|数据结构|number/);await expect(pane).not.toContainText('验证通过');await page.screenshot({path:info.outputPath('report-'+kind+'.png'),animations:'disabled'});await d.locator('.ant-modal-close').click();await api(page,'/api/plugin/advmock/case/del',{id:mock._id});
 }
 await api(page,'/api/col/up_col',{col_id:f.col,checkHttpCodeIs200:true,checkResponseField:{enable:false,name:'code',value:'0'},checkResponseSchema:false});await page.reload();let release,entered;const gate=new Promise(r=>release=r),start=new Promise(r=>entered=r);await page.route('**/api/interface/proxy',async r=>{entered();await gate;await r.continue();});const saved=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/col/up_col');await page.getByRole('button',{name:'开始测试',exact:true}).click();await start;await expect(page.getByRole('button',{name:'测试报告',exact:true})).toHaveCount(0);release();expect((await(await saved).json()).errcode).toBe(0);await page.reload();await page.getByRole('button',{name:'测试报告',exact:true}).click();await page.getByRole('tab',{name:'验证结果',exact:true}).click();await expect(page.getByRole('dialog').locator('.case-report-pane:visible')).toContainText('验证通过');await page.screenshot({path:info.outputPath('report-passing-refresh.png'),animations:'disabled'});
});

test('disabled global Mock script cannot alter ordinary Mock response',async({page},info)=>{
 const f=await setup(page,0);await api(page,'/api/project/up',{id:f.project,is_mock_open:false,project_mock_script:'throw new Error("Synthetic disabled script must never execute");'});const project=await api(page,'/api/project/get?id='+f.project);expect(project.is_mock_open).toBe(false);expect(project.project_mock_script).toContain('must never execute');
 await page.goto(`/project/${f.project}/interface/api/${f.iface}`);await page.getByText('运行',{exact:true}).click();await saveResponse(page,'/api/interface/proxy',()=>page.getByRole('button',{name:/^发\s*送$/}).click());await expect(page.locator('.pretty-editor-body')).toContainText('合成测试');await expect(page.locator('.res-code')).toContainText('200');const result=await(await page.request.get('/mock/'+f.project+'/closure')).json();expect(result).toEqual({code:0,text:'合成测试'});await page.reload();await page.getByText('运行',{exact:true}).click();await saveResponse(page,'/api/interface/proxy',()=>page.getByRole('button',{name:/^发\s*送$/}).click());await expect(page.locator('.pretty-editor-body')).toContainText('合成测试');await page.screenshot({path:info.outputPath('disabled-global-mock-ordinary-request.png'),animations:'disabled'});
});

test('import explicit repeated choice creates one case per selection and forbidden batch inserts nothing',async({page},info)=>{
 const f=await setup(page,0);await page.goto(`/project/${f.project}/interface/col/${f.col}`);
 for(let n=1;n<=2;n++){const d=await openImport(page);await d.getByRole('row').filter({has:page.getByText('Closure source',{exact:true})}).getByRole('checkbox').check();await saveResponse(page,'/api/col/add_case_list',()=>d.getByRole('button',{name:/确\s*定$/}).click());await expect(d).toHaveCount(0);const rows=await api(page,'/api/col/case_list?col_id='+f.col);expect(rows).toHaveLength(n);expect(rows.every(x=>x.interface_id===f.iface&&x.project_id===f.project)).toBe(true);expect(new Set(rows.map(x=>x._id)).size).toBe(n);}
 const privateProject=await api(page,'/api/project/add',{name:'Private denied source '+Date.now(),group_id:901000,project_type:'private'}),cat=(await api(page,'/api/interface/getCatMenu?project_id='+privateProject._id))[0],privateApi=await api(page,'/api/interface/add',{project_id:privateProject._id,catid:cat._id,title:'Private source forbidden',path:'/denied',method:'GET'});
 await api(page,'/api/project/add_member',{id:f.project,member_uids:[910004],role:'dev'});await login(page,'outsider');await page.goto(`/project/${f.project}/interface/col/${f.col}`);const d=await openImport(page);await d.getByRole('row').filter({has:page.getByText('Closure source',{exact:true})}).getByRole('checkbox').check();await page.route('**/api/col/add_case_list',r=>r.continue({postData:JSON.stringify({...r.request().postDataJSON(),interface_list:[f.iface,privateApi._id]})}));const wait=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/col/add_case_list');await d.getByRole('button',{name:/确\s*定$/}).click();const denied=await(await wait).json();expect(denied.errcode).not.toBe(0);await expect(d).toBeVisible();await expect(page.locator('.ant-message-error')).toBeVisible();expect(await api(page,'/api/col/case_list?col_id='+f.col)).toHaveLength(2);await d.getByRole('button',{name:/取\s*消$/}).click();await page.reload();expect(await api(page,'/api/col/case_list?col_id='+f.col)).toHaveLength(2);await page.screenshot({path:info.outputPath('import-private-source-atomic-denial.png'),animations:'disabled'});
});

test('filtered tree drag uses visible IDs instead of unfiltered indexes',async({page},info)=>{
 const f=await setup(page,3);await api(page,'/api/col/up_case_index',f.cases.map((c,index)=>({id:c._id,index})));for(let n=0;n<3;n++)await api(page,'/api/col/up_case',{id:f.cases[n]._id,casename:n?'Visible '+n:'Hidden neighbor'});await page.goto(`/project/${f.project}/interface/col/${f.col}`);await page.getByPlaceholder('搜索测试集合',{exact:true}).fill('Visible');await expect(page.locator('.menu-title[title="Hidden neighbor"]')).toHaveCount(0);await saveResponse(page,'/api/col/up_case_index',()=>treeDrag(page,page.locator('.menu-title[title="Visible 2"]'),page.locator('.menu-title[title="Visible 1"]')));const wanted=[f.cases[0]._id,f.cases[2]._id,f.cases[1]._id];expect((await api(page,'/api/col/case_list?col_id='+f.col)).map(x=>x._id)).toEqual(wanted);await page.getByPlaceholder('搜索测试集合',{exact:true}).fill('');await page.reload();expect((await api(page,'/api/col/case_list?col_id='+f.col)).map(x=>x._id)).toEqual(wanted);await expect(page.locator('.menu-title[title="Hidden neighbor"]')).toBeVisible();await page.screenshot({path:info.outputPath('filtered-tree-exact-IDs.png'),animations:'disabled'});
});

test('global variable create edit delete in settings changes real collection request',async({page},info)=>{
 const f=await setup(page,1);await api(page,'/api/project/up',{id:f.project,env:[{name:'echo',domain:'http://parity-fast-collections-echo:3001',header:[{name:'x-parity-synthetic',value:'fastb1003'}],global:[]}]});
 const field=(index,key)=>page.locator('[id="'+(info.project.name==='old'?`global[${index}].${key}`:`global_${index}_${key}`)+'"]');
 const settings=async()=>{await page.goto(`/project/${f.project}/setting`);await page.getByRole('tab',{name:'环境配置',exact:true}).click();await page.getByText('echo',{exact:true}).click();await expect(page.getByPlaceholder('请输入环境名称')).toHaveValue('echo');};
 await settings();await field(0,'name').fill('seed');await field(0,'value').fill('created-value');await saveResponse(page,'/api/project/up_env',()=>page.getByRole('button',{name:/保\s*存$/}).click());
 await page.goto(`/project/${f.project}/interface/case/${f.cases[0]._id}`);await page.locator('#req_query_0').fill('{{ global.seed }}');await saveResponse(page,'/api/col/up_case',()=>page.getByRole('button',{name:/更\s*新$/}).click());
 const run=async value=>{await page.goto(`/project/${f.project}/interface/col/${f.col}`);await expect(page.getByRole('cell',{name:'Closure case 0',exact:true})).toBeVisible();await page.locator('.case-env .ant-select').click();await page.locator('.ant-select-dropdown:visible').getByText('echo: http://parity-fast-collections-echo:3001',{exact:true}).click();await saveResponse(page,'/api/col/up_col',()=>page.getByRole('button',{name:'开始测试',exact:true}).click());const report=JSON.parse((await readCol(page,f.col)).test_report);expect(report[f.cases[0]._id].res_body.query.first).toBe(value);};
 await run('created-value');await settings();await expect(field(0,'value')).toHaveValue('created-value');await field(0,'value').fill('edited-value');await saveResponse(page,'/api/project/up_env',()=>page.getByRole('button',{name:/保\s*存$/}).click());await run('edited-value');await settings();await expect(field(0,'value')).toHaveValue('edited-value');await field(0,'name').locator('xpath=ancestor::div[contains(@class,"ant-row")][.//*[contains(@class,"dynamic-delete-button")]][1]').locator('.dynamic-delete-button').click();await saveResponse(page,'/api/project/up_env',()=>page.getByRole('button',{name:/保\s*存$/}).click());await settings();await expect(field(0,'name')).toHaveValue('');const stored=await api(page,'/api/project/get?id='+f.project);expect(stored.env[0].global).toEqual([]);await page.screenshot({path:info.outputPath('global-variable-deleted.png'),animations:'disabled'});
});

test('request script syntax annotation is visible without autosave or execution',async({page},info)=>{
 const f=await setup(page,0),before=await api(page,'/api/project/get?id='+f.project);await page.goto(`/project/${f.project}/setting`);await page.getByRole('tab',{name:'请求配置',exact:true}).click();let writes=0,runs=0;page.on('request',r=>{const p=new URL(r.url()).pathname;if(r.method()==='POST'&&p.startsWith('/api/project/'))writes++;if(p==='/api/interface/proxy'||p==='/api/col/run_script')runs++;});const editor=page.locator('.request-editor').first();await editor.locator('textarea').focus();await page.keyboard.press('Meta+A');await page.keyboard.insertText('function broken( {');await expect(editor.locator('.ace_error')).toBeVisible({timeout:10000});expect(writes).toBe(0);expect(runs).toBe(0);await page.screenshot({path:info.outputPath('request-syntax-draft-error.png'),animations:'disabled'});await page.reload();expect((await api(page,'/api/project/get?id='+f.project)).pre_script||'').toBe(before.pre_script||'');
});


for(const phase of ['post','refresh'])for(const destination of ['route','unmount'])test(`clone delayed ${phase} then ${destination} cannot navigate or overwrite destination`,async({page},info)=>{
 const f=await setup(page,2);await page.goto(`/project/${f.project}/interface/col/${f.col}`);await expect(page.getByRole('cell',{name:'Closure case 0',exact:true})).toBeVisible();
 await page.evaluate(()=>{window.parityNavigation=[];const original=history.pushState;history.pushState=function(...args){window.parityNavigation.push({path:args[2],stack:new Error().stack});return original.apply(this,args);};});
 let release,entered;const gate=new Promise(r=>release=r),start=new Promise(r=>entered=r);let writes=0,done=false;
 page.on('request',r=>{if(new URL(r.url()).pathname==='/api/col/add_case')writes++;});
 const pattern=phase==='post'?'**/api/col/add_case':'**/api/col/list?*';
 await page.route(pattern,async r=>{const response=await r.fetch();expect((await response.json()).errcode).toBe(0);entered();await gate;await r.fulfill({response});done=true;});
 const node=page.locator('.menu-title[title="Closure case 0"]');await node.hover();await node.locator('.anticon-copy').click();await start;
 if(destination==='route'){await page.locator('.menu-title[title="Closure case 1"]').click();await expect(page).toHaveURL(new RegExp('/interface/case/'+f.cases[1]._id+'$'));}
 else {await page.locator(`a[href="/project/${f.project}/setting"]`).click();await expect(page).toHaveURL(/\/setting$/);}
 const url=page.url();release();await expect.poll(()=>done).toBe(true);await page.waitForTimeout(350);await info.attach('navigation-calls',{body:JSON.stringify(await page.evaluate(()=>window.parityNavigation)),contentType:'application/json'});expect(page.url()).toBe(url);expect(writes).toBe(1);
 expect((await api(page,'/api/col/case_list?col_id='+f.col)).filter(x=>x.casename==='Closure case 0_copy')).toHaveLength(1);
 await page.screenshot({path:info.outputPath(`clone-${phase}-${destination}.png`),animations:'disabled'});
});


test('collection rows map exact case source status and chosen environment after run and reload',async({page},info)=>{
 const f=await setup(page,1),source=await api(page,'/api/interface/get?id='+f.iface);
 const other=await api(page,'/api/interface/add',{project_id:f.project,catid:source.catid,title:'Second table source',path:'/table-second',method:'GET'});
 await api(page,'/api/interface/up',{id:other._id,res_body_type:'json',res_body_is_json_schema:false,res_body:'{"row":"second"}'});
 const c=await api(page,'/api/col/add_case',{project_id:f.project,col_id:f.col,interface_id:other._id,casename:'Table second case'});
 await api(page,'/api/plugin/advmock/case/save',{project_id:f.project,interface_id:other._id,name:'Second row failure',code:404,delay:0,params:{},headers:[],res_body:'{"row":"second"}'});
 await api(page,'/api/col/up_col',{col_id:f.col,checkHttpCodeIs200:true,checkResponseField:{enable:false,name:'code',value:'0'},checkResponseSchema:false});
 await page.goto(`/project/${f.project}/interface/col/${f.col}`);await expect(page.getByRole('cell',{name:'Closure case 0',exact:true})).toBeVisible();
 await page.locator('.case-env .ant-select').click();await page.locator('.ant-select-dropdown:visible').getByText(`local: http://127.0.0.1:3000/mock/${f.project}`,{exact:true}).click();
 const rows=[{id:f.cases[0]._id,name:'Closure case 0',iface:f.iface,path:'/closure',icon:'.anticon-check-circle'},{id:c._id,name:'Table second case',iface:other._id,path:'/table-second',icon:'.anticon-exclamation-circle'}];
 await saveResponse(page,'/api/col/up_col',()=>page.getByRole('button',{name:'开始测试',exact:true}).click());
 for(const reload of [false,true]){if(reload)await page.reload();for(const row of rows){const tr=page.getByRole('row').filter({has:page.getByRole('cell',{name:row.name,exact:true})});await expect(tr.getByRole('link',{name:row.name,exact:true})).toHaveAttribute('href',`/project/${f.project}/interface/case/${row.id}`);await expect(tr.getByRole('link',{name:row.path,exact:true})).toHaveAttribute('href',`/project/${f.project}/interface/api/${row.iface}`);await expect(tr).toContainText(String(row.id));await expect(tr.locator(row.icon)).toBeVisible();await expect(tr.getByRole('checkbox')).toHaveCount(0);}
 const report=JSON.parse((await readCol(page,f.col)).test_report);for(const row of rows)expect(report[row.id].url).toContain(`/mock/${f.project}${row.path}`);
 }
 await page.screenshot({path:info.outputPath('collection-row-mapping.png'),animations:'disabled'});
 const first=page.getByRole('row').filter({has:page.getByRole('cell',{name:rows[0].name,exact:true})});await first.getByRole('link',{name:rows[0].name,exact:true}).click();await expect(page).toHaveURL(new RegExp('/interface/case/'+rows[0].id+'$'));await page.goBack();await page.getByRole('link',{name:'/table-second',exact:true}).click();await expect(page).toHaveURL(new RegExp('/interface/api/'+other._id+'$'));
});
