const {test,expect}=require('@playwright/test');
async function setup(page,request,info,role,json5=false,body={}){
 page.setDefaultTimeout(12000);const password='SyntheticParityOnly_901000!';expect((await(await request.post('/api/user/login',{data:{email:'owner@ui-parity.invalid',password}})).json()).errcode).toBe(0);async function api(path,data){const result=await(await request.post(path,{data})).json();expect(result.errcode).toBe(0);return result.data;}
 const project=await api('/api/project/add',{name:'Synthetic body '+Date.now(),group_id:901000,project_type:'private'});await api('/api/project/up',{id:project._id,is_json5:json5});await api('/api/project/add_member',{id:project._id,member_uids:[910003],role:'dev'});await api('/api/project/add_member',{id:project._id,member_uids:[910004],role:'guest'});const cat=(await(await request.get('/api/interface/getCatMenu?project_id='+project._id)).json()).data[0];const item=await api('/api/interface/add',{project_id:project._id,catid:cat._id,title:'Synthetic body fixture',path:'/body',method:'POST',tag:[],req_body_type:'raw',req_body_other:'Synthetic request raw',req_body_is_json_schema:false,req_body_form:[{name:'hidden',type:'text',example:'stale',required:'1'}],res_body_type:'raw',res_body:'Synthetic response raw',res_body_is_json_schema:false,...body});await info.attach('body-fixture',{body:JSON.stringify({project:project._id,id:item._id,role,json5}),contentType:'application/json'});
 await page.goto('/login');await page.getByPlaceholder('Email',{exact:true}).fill((role==='guest'?'outsider':role)+'@ui-parity.invalid');await page.getByPlaceholder('Password',{exact:true}).fill(password);await page.getByRole('button',{name:/^登\s*录$/}).click();await expect(page).toHaveURL(/\/group/);await page.goto('/project/'+project._id+'/interface/api/'+item._id);await page.getByRole('tab',{name:'编辑',exact:true}).click();await expect(page.locator('#title')).toBeVisible();const read=async()=>{const r=await(await request.get('/api/interface/get?id='+item._id)).json();expect(r.errcode).toBe(0);return r.data;};const before=await read();const observations=[];
 async function save(){const wait=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/interface/up'&&r.request().method()==='POST');await expect(page.getByRole('button',{name:/^保\s*存$/})).toBeEnabled();await page.getByRole('button',{name:/^保\s*存$/}).click();const response=await wait,result=await response.json(),payload=response.request().postDataJSON(),after=await read();observations.push({result,payload,after});if(role==='guest'){expect(result.errcode).not.toBe(0);await expect(page.getByText(/没有权限/).first()).toBeVisible();for(const k of ['req_body_type','req_body_other','req_body_form','res_body_type','res_body'])expect(after[k]).toEqual(before[k]);}else if(info.project.name==='new'){expect(result.errcode).toBe(0);await expect(page.getByText('保存成功').first()).toBeVisible();}else{expect([0,40011]).toContain(result.errcode);await expect(page.getByText(result.errcode===0?'保存成功':'服务器出错...',{exact:true}).first()).toBeVisible();}return {result,payload,after};}
 return {project,item,api,read,before,save,observations};
}
function field(page,version,key){const id=version==='old'?key:key.replace(/[.\[\]]/g,'_').replace(/__+/g,'_').replace(/_$/,'');return page.locator('[id="'+id+'"]');}

for(const role of ['owner','developer','guest'])test('interface preview metadata copy parameters schema and refresh '+role,async({page,context,request},info)=>{
 const long='Synthetic long description '+('longword-'.repeat(65));const schema={type:'object',properties:{nested:{type:'object',description:'Nested object',properties:{leaf:{type:'string',description:long,format:'email',minLength:3,maxLength:80,default:'a',enum:['a','b']}},required:['leaf']}}};
 const f=await setup(page,request,info,role,false,{title:'Synthetic preview metadata',status:'done',path:'/preview/:itemId',req_params:[{name:'itemId',example:'path-123',desc:'Path description'}],req_query:[{name:'queryRequired',required:'1',example:'query-example',desc:'Query description'},{name:'queryOptional',required:'0',example:'optional',desc:'Optional query'}],req_headers:[{name:'X-Synthetic',required:'1',value:'header-value',desc:'Header description'}],req_body_type:'form',req_body_form:[{name:'bodyText',type:'text',required:'1',example:'body-example',desc:'Body description'},{name:'bodyFile',type:'file',required:'0',desc:'File description'}],res_body_type:'json',res_body_is_json_schema:true,res_body:JSON.stringify(schema)});
 await f.api('/api/project/up',{id:f.project._id,basepath:'/synthetic-base'});await page.reload();await page.getByRole('tab',{name:'预览',exact:true}).first().click();const view=page.locator('.caseContainer'),panel=view.locator('.panel-view');await expect(panel).toContainText('Synthetic preview metadata');await info.attach('view-label-layout',{body:JSON.stringify(await panel.locator('.colKey').evaluateAll(es=>es.map(e=>({text:e.textContent,width:e.getBoundingClientRect().width,x:e.getBoundingClientRect().x,flex:getComputedStyle(e).flex})))),contentType:'application/json'});expect(await panel.locator('.colKey').evaluateAll(es=>es.every(e=>e.getBoundingClientRect().width===100))).toBe(true);await expect(panel.getByRole('link',{name:'Synthetic owner',exact:true})).toHaveAttribute('href','/user/profile/910002');await expect(panel).toContainText('已完成');await expect(panel).toContainText(/\d{4}-\d{2}-\d{2}/);const path=panel.getByText('/synthetic-base/preview/:itemId',{exact:true});await expect(path).toBeVisible();await context.grantPermissions(['clipboard-read','clipboard-write']);for(let n=0;n<2;n++){await path.hover();await panel.locator('.interface-url-icon').click();await expect(page.getByText('已经成功复制到剪切板').first()).toBeVisible();expect(await page.evaluate(()=>navigator.clipboard.readText())).toBe('/synthetic-base/preview/:itemId');}
 const paths=view.locator('.colHeader').filter({hasText:'路径参数：'}),headers=view.locator('.colHeader').filter({hasText:'Headers：'});await expect(paths).toContainText('path-123');await expect(paths).toContainText('Path description');await expect(headers).toContainText('header-value');await expect(headers).toContainText('Header description');await expect(view.locator('.colQuery').locator('tr').filter({hasText:'queryRequired'})).toContainText('是');await expect(view.locator('.colQuery').locator('tr').filter({hasText:'queryOptional'})).toContainText('否');await expect(view.locator('.colBody').locator('tr').filter({hasText:'bodyFile'})).toContainText('文件');await expect(view.locator('.colBody').locator('tr').filter({hasText:'bodyText'})).toContainText('body-example');
 const nested=view.locator('tr').filter({has:page.getByText('nested',{exact:true})}),leaf=view.locator('tr').filter({has:page.getByText('leaf',{exact:true})});await expect(leaf).toBeHidden();await nested.locator('.ant-table-row-expand-icon').click();await expect(leaf).toBeVisible();await expect(leaf).toContainText('必须');await expect(leaf).toContainText('email');await expect(leaf).toContainText('最大长度');await expect(leaf).toContainText(long);await nested.locator('.ant-table-row-expand-icon').click();await expect(leaf).toBeHidden();await nested.locator('.ant-table-row-expand-icon').click();await expect(leaf).toBeVisible();await view.scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath('interface-preview.png'),fullPage:true});const layout=await view.evaluate(e=>({document:document.documentElement.scrollWidth,viewport:innerWidth,view:e.clientWidth,scroll:e.scrollWidth}));await info.attach('view-layout',{body:JSON.stringify(layout),contentType:'application/json'});expect(layout.document).toBe(layout.viewport);await page.reload();await expect(panel).toContainText('/synthetic-base/preview/:itemId');expect((await f.read()).res_body).toBe(JSON.stringify(schema));await info.attach('view-final',{body:JSON.stringify({id:f.item._id,project:f.project._id,role,after:await f.read()}),contentType:'application/json'});
});
for(const role of ['owner','developer','guest'])test('interface preview strips dangerous attributes while retaining formatting '+role,async({page,request},info)=>{
 const f=await setup(page,request,info,role,false,{desc:'<h2>Safe heading</h2><ul><li>Safe list</li></ul><p onclick="window.__syntheticUnsafe=true">Safe paragraph</p><a href="javascript:window.__syntheticUnsafe=true">Safe link</a>',markdown:''});await page.getByRole('tab',{name:'预览',exact:true}).first().click();const content=page.locator('.caseContainer > .tui-editor-contents');await expect(content.locator('h2')).toHaveText('Safe heading');await expect(content.locator('ul')).toHaveCSS('list-style-type','disc');const unsafe=await content.locator('[onclick],[href^="javascript:"]').count();if(info.project.name==='new')expect(unsafe).toBe(0);await info.attach('view-sanitizer',{body:JSON.stringify({id:f.item._id,role,unsafe,status:unsafe?'failed':'passed'}),contentType:'application/json'});await content.scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath('safe-view.png')});await page.reload();if(info.project.name==='new')await expect(content.locator('[onclick],[href^="javascript:"]')).toHaveCount(0);
});
