const {test,expect}=require('@playwright/test');
for(const role of ['owner','developer','guest'])test('create validation methods cancel close escape and duplicate '+role,async({page,request},info)=>{
 page.setDefaultTimeout(12000);const password='SyntheticParityOnly_901000!';expect((await(await request.post('/api/user/login',{data:{email:'owner@ui-parity.invalid',password}})).json()).errcode).toBe(0);
 async function api(path,data){const r=await(await request.post(path,{data})).json();expect(r.errcode).toBe(0);return r.data;}
 const p=await api('/api/project/add',{name:'Synthetic create boundaries '+role+' '+Date.now(),group_id:901000,project_type:'private'});if(role!=='owner')await api('/api/project/add_member',{id:p._id,member_uids:[role==='guest'?910004:910003],role:role==='guest'?'guest':'dev'});
 await api('/api/interface/add_cat',{project_id:p._id,name:'Creation target'});const menu=async()=>{const r=await(await request.get('/api/interface/list_menu?project_id='+p._id)).json();expect(r.errcode).toBe(0);return r.data;};const cat=(await menu()).find(c=>c.name==='Creation target');await info.attach('create-fixture',{body:JSON.stringify({project:p._id,cat:cat._id,role}),contentType:'application/json'});
 await page.goto('/login');await page.getByPlaceholder('Email',{exact:true}).fill((role==='guest'?'outsider':role)+'@ui-parity.invalid');await page.getByPlaceholder('Password',{exact:true}).fill(password);await page.getByRole('button',{name:/^登\s*录$/}).click();await expect(page).toHaveURL(/\/group/);await page.goto('/project/'+p._id+'/interface/api');
 const node=page.locator('.container-title').filter({has:page.locator('a.interface-item').filter({hasText:/^Creation target$/})});const modal=page.locator('.ant-modal:visible');async function open(){await page.waitForTimeout(400);await page.mouse.move(1000,400);if(role==='developer'){await node.getByRole('link').click();await page.getByRole('button',{name:'添加接口',exact:true}).click();}else{await node.hover();await node.locator('.anticon-plus').click();}await expect(modal.getByPlaceholder('接口名称',{exact:true})).toBeVisible();await page.waitForTimeout(300);}
 let writes=0;page.on('request',r=>{if(new URL(r.url()).pathname==='/api/interface/add'&&r.method()==='POST')writes++;});
 for(const close of ['cancel','close','escape']){await open();await modal.getByPlaceholder('接口名称',{exact:true}).fill('Discarded '+close);await modal.getByPlaceholder('/path',{exact:true}).fill('/discarded');if(close==='cancel')await modal.getByRole('button',{name:/取\s*消/}).click();else if(close==='close')await modal.locator('.ant-modal-close').click();else await modal.getByPlaceholder('/path',{exact:true}).press('Escape');await expect(modal).toHaveCount(0);expect(writes).toBe(0);expect((await menu()).flatMap(c=>c.list)).toEqual([]);}
 await open();await expect(modal.getByPlaceholder('接口名称',{exact:true})).toHaveValue('');await expect(modal.getByPlaceholder('/path',{exact:true})).toHaveValue('');await modal.getByRole('button',{name:/提\s*交/}).click();await expect(modal.getByText('请输入接口路径!',{exact:true})).toBeVisible();await expect(modal.getByText(/请输入接口名称，长度不超过/)).toBeVisible();expect(writes).toBe(0);
 await modal.getByPlaceholder('接口名称',{exact:true}).fill('x'.repeat(101));await modal.getByPlaceholder('/path',{exact:true}).fill('/validation');await modal.getByPlaceholder('接口名称',{exact:true}).press('Tab');await expect(modal.getByText(/请输入接口名称，长度不超过/)).toBeVisible();await expect(modal.getByRole('button',{name:/提\s*交/})).toBeDisabled();await modal.getByRole('button',{name:/取\s*消/}).click();
 const methods=['GET','POST','PUT','DELETE','HEAD','OPTIONS','PATCH'];for(const method of methods){await open();await modal.getByPlaceholder('接口名称',{exact:true}).fill('Create '+method);await modal.getByPlaceholder('/path',{exact:true}).fill('/create-'+method.toLowerCase());const select=modal.locator('.ant-select').last();await select.click();await page.waitForTimeout(300);await page.locator('.ant-select-dropdown:visible').getByText(method,{exact:true}).last().click();if(info.project.name==='new'&&role!=='guest'&&method==='GET'){for(const failure of ['network','http']){await page.route('**/api/interface/add',route=>failure==='network'?route.abort('failed'):route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({errcode:503,errmsg:'Synthetic create unavailable'})}));await modal.getByRole('button',{name:/提\s*交/}).click();await expect(page.getByText(failure==='network'?'接口创建失败，请重试':'Synthetic create unavailable',{exact:true}).first()).toBeVisible();await expect(modal.getByRole('button',{name:/提\s*交/})).toBeEnabled();await expect(modal.getByPlaceholder('接口名称',{exact:true})).toHaveValue('Create GET');expect((await menu()).flatMap(c=>c.list)).toEqual([]);await page.unroute('**/api/interface/add');}}
 const pending=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/interface/add'&&r.request().method()==='POST');await modal.getByRole('button',{name:/提\s*交/}).click();const result=await(await pending).json();expect(result.errcode===0).toBe(role!=='guest');if(role==='guest'){await expect(page.getByText(/没有权限/).first()).toBeVisible();await modal.getByRole('button',{name:/取\s*消/}).click();}else{await expect(page.getByText('接口添加成功').first()).toBeVisible();await expect(page).toHaveURL(new RegExp('/'+result.data._id+'$'));const stored=(await(await request.get('/api/interface/get?id='+result.data._id)).json());expect(stored.errcode).toBe(0);expect(stored.data.method).toBe(method);expect(stored.data.catid).toBe(cat._id);}}
 expect((await menu()).flatMap(c=>c.list).length).toBe(role==='guest'?0:7);
 if(role!=='guest'){await open();await modal.getByPlaceholder('接口名称',{exact:true}).fill('Duplicate GET');await modal.getByPlaceholder('/path',{exact:true}).fill('/create-get');const pending=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/interface/add'&&r.request().method()==='POST');await modal.getByRole('button',{name:/提\s*交/}).click();const result=await(await pending).json();expect(result.errcode).not.toBe(0);await expect(page.getByText(result.errmsg,{exact:false}).first()).toBeVisible();await expect(modal).toBeVisible();expect((await menu()).flatMap(c=>c.list).length).toBe(7);await modal.getByRole('button',{name:/取\s*消/}).click();}
 await open();await modal.getByPlaceholder('接口名称',{exact:true}).fill('Rapid submit');await modal.getByPlaceholder('/path',{exact:true}).fill('/rapid-submit');let release;const gate=new Promise(resolve=>release=resolve);const responses=[];const record=async r=>{if(new URL(r.url()).pathname==='/api/interface/add'&&r.request().method()==='POST')responses.push((await r.json()).errcode);};page.on('response',record);await page.route('**/api/interface/add',async route=>{const result=await route.fetch();await gate;await route.fulfill({response:result});});await modal.getByRole('button',{name:/提\s*交/}).dblclick();release();await expect.poll(()=>responses.length).toBeGreaterThan(0);await page.waitForTimeout(400);await page.unroute('**/api/interface/add');page.off('response',record);const rapid=(await menu()).flatMap(c=>c.list).filter(i=>i.path==='/rapid-submit');await info.attach('rapid-submit',{body:JSON.stringify({responses,count:rapid.length}),contentType:'application/json'});if(role==='guest'){await expect(page.getByText(/没有权限/).first()).toBeVisible();expect(rapid.length).toBe(0);await modal.getByRole('button',{name:/取\s*消/}).click();}else{await expect(page.getByText('接口添加成功').first()).toBeVisible();if(info.project.name==='new'){expect(rapid.length).toBe(1);expect(responses).toEqual([0]);}else expect(rapid.length).toBeGreaterThan(0);}
 await page.reload();await node.getByRole('link').click();await expect(page.locator('.table-interfacelist tbody tr')).toHaveCount(role==='guest'?(info.project.name==='old'?0:1):7+rapid.length);await page.screenshot({path:info.outputPath('creation-boundaries-final.png')});await info.attach('create-final',{body:JSON.stringify(await menu()),contentType:'application/json'});
});
