const {test,expect}=require('@playwright/test');
const fs=require('node:fs/promises');
async function login(page,role='owner'){await page.goto('/login');await page.getByPlaceholder('Email',{exact:true}).fill(role+'@ui-parity.invalid');await page.getByPlaceholder('Password',{exact:true}).fill('SyntheticParityOnly_901000!');await page.getByRole('button',{name:/^登\s*录$/}).click();await expect(page).toHaveURL(/\/group/);}
async function select(page,locator,text){await locator.click();await page.locator('.ant-select-dropdown:visible').getByText(text,{exact:true}).last().click();}
for(const role of ['owner','developer'])test('exports all installed formats '+role,async({page,context},info)=>{
 page.setDefaultTimeout(12000);await login(page,role);await page.goto('/project/901001/data');await expect(page.getByRole('heading',{name:'数据导出',exact:true})).toBeVisible();const chooser=page.locator('.dataImportTile .ant-select').nth(1);
 for(const format of ['html','markdown','json','swaggerjson']){
  await select(page,chooser,format);const link=page.locator('.export-content a');const href=await link.getAttribute('href');
  const response=context.waitForEvent('response',{predicate:r=>r.url().includes(new URL(href,info.project.use.baseURL).pathname)&&r.request().method()==='GET'});
  const downloadPromise=page.waitForEvent('download',{timeout:3000}).catch(()=>null);await link.click();const r=await response;expect(r.status()).toBe(200);const download=await downloadPromise;
  let body;if(download){const path=info.outputPath(role+'-'+format+'-'+download.suggestedFilename());await download.saveAs(path);body=await fs.readFile(path,'utf8');}else body=await r.text();
  expect(body.length).toBeGreaterThan(100);expect(body).toContain('Nested');if(format==='json')expect(Array.isArray(JSON.parse(body))).toBe(true);if(format==='swaggerjson')expect(JSON.parse(body).swagger).toBe('2.0');
  await info.attach('export-'+format,{body:JSON.stringify({href,contentType:r.headers()['content-type'],disposition:r.headers()['content-disposition'],bytes:Buffer.byteLength(body)}),contentType:'application/json'});
  for(const popup of context.pages())if(popup!==page)await popup.close();
 }
 await page.getByRole('heading',{name:'数据导出',exact:true}).click();await expect(page.locator('.ant-select-dropdown:visible')).toHaveCount(0);await page.screenshot({path:info.outputPath('data-export-page.png'),fullPage:true});
});
async function responseFor(page,path,action){const pending=page.waitForResponse(r=>new URL(r.url()).pathname===path);await action();const r=await pending;expect(r.status()).toBe(200);const b=await r.json();expect(b.errcode,JSON.stringify(b)).toBe(0);return b.data;}
for(const role of ['owner','developer','outsider'])test('group role settings boundaries '+role,async({page},info)=>{
 page.setDefaultTimeout(12000);await login(page,role);await page.goto('/group/901000');await expect(page.getByRole('tab',{name:'项目列表',exact:true})).toBeVisible();
 const before=(await(await page.request.get('/api/group/get?id=901000')).json()).data;
 if(role==='owner'){
  await page.getByRole('tab',{name:'分组设置',exact:true}).click();await expect(page.getByPlaceholder('请输入分组名称')).toHaveValue(before.group_name);await expect(page.getByRole('button',{name:/查\s*看/})).toHaveCount(0);
  await page.getByPlaceholder('请输入分组描述').fill('Synthetic owner edit '+info.project.name);await responseFor(page,'/api/group/up',()=>page.getByRole('button',{name:/保\s*存/}).click());await page.reload();await page.getByRole('tab',{name:'分组设置',exact:true}).click();await expect(page.getByPlaceholder('请输入分组描述')).toHaveValue('Synthetic owner edit '+info.project.name);await page.getByPlaceholder('请输入分组描述').fill(before.group_desc||'');await responseFor(page,'/api/group/up',()=>page.getByRole('button',{name:/保\s*存/}).click());
 }else{
  await expect(page.getByRole('tab',{name:'分组设置',exact:true})).toHaveCount(0);const denied=await(await page.request.post('/api/group/up',{data:{id:901000,group_name:'Unauthorized synthetic change'}})).json();expect(denied.errcode).not.toBe(0);const after=(await(await page.request.get('/api/group/get?id=901000')).json()).data;expect(after.group_name).toBe(before.group_name);
 }
 await page.screenshot({path:info.outputPath('group-'+role+'.png'),fullPage:true});
});
async function fixtureProject(page,info,kind){const name='Synthetic '+kind+' '+info.project.name+' '+Date.now();const b=await(await page.request.post('/api/project/add',{data:{name,desc:'Synthetic local parity disposable fixture',group_id:901000,project_type:'private'}})).json();expect(b.errcode).toBe(0);await info.attach('fixture-project',{body:JSON.stringify({id:b.data._id,name}),contentType:'application/json'});return b.data._id;}
test('import every installed file format normal and duplicate',async({page},info)=>{
 page.setDefaultTimeout(12000);await login(page);const id=await fixtureProject(page,info,'imports');
 const formats=[['Swagger',{swagger:'2.0',info:{title:'Synthetic swagger',version:'1'},paths:{'/import-swagger':{get:{summary:'Synthetic Swagger',responses:{200:{description:'ok',schema:{type:'object',properties:{ok:{type:'boolean'}}}}}}}}}],['json',[{name:'Synthetic imported',desc:'Unicode 中文',list:[{title:'Synthetic JSON',method:'GET',path:'/import-json',res_body:'{"type":"object","properties":{}}',res_body_is_json_schema:true}]}]],['Postman',{id:'synthetic',name:'Synthetic Postman',requests:[{id:'synthetic-get',name:'Synthetic Postman GET',method:'GET',url:'https://synthetic.invalid/import-postman',headers:'',data:[],dataMode:'params'}],folders:[]}],['HAR',{log:{version:'1.2',creator:{name:'Synthetic',version:'1'},entries:[{request:{method:'GET',url:'https://synthetic.invalid/import-har',headers:[],queryString:[],cookies:[]},response:{status:200,headers:[],cookies:[],content:{mimeType:'application/json',text:'{"ok":true}'}}}]}}]];
 for(const [format,data]of formats){await page.goto('/project/'+id+'/data');await select(page,page.locator('.dataImportTile .ant-select').first(),format);await select(page,page.locator('.catidSelect .ant-select').first(),'公共分类');for(const mode of ['智能合并','完全覆盖','普通模式'])await select(page,page.locator('.dataSync .ant-select').first(),mode);const input=page.locator('input[type=file]');const body=Buffer.from(JSON.stringify(data));await responseFor(page,'/api/interface/add',()=>input.setInputFiles({name:'synthetic-'+format+'.json',mimeType:'application/json',buffer:body}));await expect(page.locator('.ant-spin-spinning')).toHaveCount(0);const before=(await(await page.request.get('/api/interface/list_menu?project_id='+id)).json()).data.flatMap(c=>c.list);expect(before.some(x=>x.path==='/import-'+(format==='Swagger'?'swagger':format==='Postman'?'postman':format==='HAR'?'har':'json'))).toBe(true);const repeat=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/interface/add'&&r.request().method()==='POST');await input.setInputFiles({name:'synthetic-repeat-'+format+'.json',mimeType:'application/json',buffer:body});const repeated=await(await repeat).json();expect(repeated.errcode).not.toBe(0);const after=(await(await page.request.get('/api/interface/list_menu?project_id='+id)).json()).data.flatMap(c=>c.list);expect(after.length).toBe(before.length);}
 await page.getByRole('heading',{name:/数据导入/}).click();await expect(page.locator('.ant-select-dropdown:visible')).toHaveCount(0);await page.screenshot({path:info.outputPath('import-formats-complete.png'),fullPage:true});
});
test('import smart merge preserves annotations and overwrite cancel confirm is scoped',async({page},info)=>{
 page.setDefaultTimeout(12000);await login(page);const id=await fixtureProject(page,info,'merge');const cats=(await(await page.request.get('/api/interface/getCatMenu?project_id='+id)).json()).data;const cat=cats[0];
 const before={type:'object',properties:{keep:{type:'string',description:'Manual annotation',mock:{mock:'manual'}}}};const incoming={type:'object',properties:{keep:{type:'string'},added:{type:'integer'}}};const seed={project_id:id,catid:cat._id,title:'Synthetic merge target',path:'/merge-target',method:'GET',res_body:JSON.stringify(before),res_body_is_json_schema:true};const saved=await(await page.request.post('/api/interface/add',{data:seed})).json();expect(saved.errcode).toBe(0);const untouched=await(await page.request.post('/api/interface/add',{data:{...seed,title:'Untouched neighbor',path:'/untouched-neighbor'}})).json();expect(untouched.errcode).toBe(0);
 await page.goto('/project/'+id+'/data');await select(page,page.locator('.dataImportTile .ant-select').first(),'json');await select(page,page.locator('.dataSync .ant-select').first(),'智能合并');const payload=[{name:cat.name,desc:'Synthetic',list:[{...seed,title:'Merged target',res_body:JSON.stringify(incoming)}]}];const file={name:'synthetic-merge.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(payload))};await responseFor(page,'/api/interface/save',()=>page.locator('input[type=file]').setInputFiles(file));const merged=(await(await page.request.get('/api/interface/get?id='+saved.data._id)).json()).data;expect(JSON.parse(merged.res_body).properties.keep.description).toBe('Manual annotation');expect(JSON.parse(merged.res_body).properties.added.type).toBe('integer');
 await page.reload();await select(page,page.locator('.dataImportTile .ant-select').first(),'json');await select(page,page.locator('.dataSync .ant-select').first(),'完全覆盖');await page.locator('input[type=file]').setInputFiles(file);await expect(page.getByText('您确认要进行数据同步吗？',{exact:true}).last()).toBeVisible();await page.getByRole('button',{name:/取\s*消/}).click();expect(JSON.parse((await(await page.request.get('/api/interface/get?id='+saved.data._id)).json()).data.res_body).properties.keep.description).toBe('Manual annotation');
 await select(page,page.locator('.dataSync .ant-select').first(),'完全覆盖');await page.locator('input[type=file]').setInputFiles({...file,name:'synthetic-overwrite.json'});await expect(page.getByText('您确认要进行数据同步吗？',{exact:true}).last()).toBeVisible();await responseFor(page,'/api/interface/save',()=>page.getByRole('button',{name:/确\s*认/}).click());expect(JSON.parse((await(await page.request.get('/api/interface/get?id='+saved.data._id)).json()).data.res_body)).toEqual(incoming);expect(JSON.parse((await(await page.request.get('/api/interface/get?id='+untouched.data._id)).json()).data.res_body)).toEqual(before);await expect(page.locator('.ant-spin-spinning')).toHaveCount(0);await page.screenshot({path:info.outputPath('merge-overwrite-scoped.png'),fullPage:true});
});
async function exported(page,context,info){const link=page.locator('.export-content a'),href=await link.getAttribute('href');const response=context.waitForEvent('response',{predicate:r=>r.url().includes(new URL(href,info.project.use.baseURL).pathname)});const download=page.waitForEvent('download',{timeout:3000}).catch(()=>null);await link.click();const r=await response;expect(r.status()).toBe(200);const dl=await download;const body=dl?await fs.readFile(await dl.path(),'utf8'):await r.text();for(const popup of context.pages())if(popup!==page)await popup.close();return body;}
test('export filters category public visibility wiki and Unicode',async({page,context},info)=>{
 page.setDefaultTimeout(12000);await login(page);const id=await fixtureProject(page,info,'exports');const cats=(await(await page.request.get('/api/interface/getCatMenu?project_id='+id)).json()).data;const other=await(await page.request.post('/api/interface/add_cat',{data:{project_id:id,name:'Other category'}})).json();expect(other.errcode).toBe(0);
 for(const [title,path,catid,api_opened]of[['Public 中文','/public-long-'+('abc'.repeat(50)),cats[0]._id,true],['Private same category','/private',cats[0]._id,false],['Private other category','/other',other.data._id,false]]){const r=await(await page.request.post('/api/interface/add',{data:{project_id:id,catid,title,path,api_opened,method:'GET'}})).json();expect(r.errcode).toBe(0)}
 const w=await(await page.request.post('/api/plugin/wiki_desc/up',{data:{project_id:id,desc:'<p>SYNTHETIC_WIKI_中文</p>',markdown:'SYNTHETIC_WIKI_中文',email_notice:false}})).json();expect(w.errcode).toBe(0);
 await page.goto('/project/'+id+'/data');const format=page.locator('.dataImportTile .ant-select').nth(1),category=page.locator('.catidSelect .ant-select').nth(1);await select(page,format,'json');const titles=body=>JSON.parse(body).flatMap(c=>c.list).map(x=>x.title).sort();expect(titles(await exported(page,context,info))).toEqual(['Private other category','Private same category','Public 中文']);await page.getByRole('radio',{name:'公开接口',exact:true}).check();expect(titles(await exported(page,context,info))).toEqual(['Public 中文']);await select(page,category,'Other category');expect(titles(await exported(page,context,info))).toEqual([]);await page.getByRole('radio',{name:'全部接口',exact:true}).check();expect(titles(await exported(page,context,info))).toEqual(['Private other category']);await select(page,category,'全部分类');
 for(const f of ['html','markdown']){await select(page,format,f);await page.getByRole('checkbox',{name:/附加 wiki/}).uncheck();expect(await exported(page,context,info)).not.toContain('SYNTHETIC_WIKI_中文');await page.getByRole('checkbox',{name:/附加 wiki/}).check();expect(await exported(page,context,info)).toContain('SYNTHETIC_WIKI_中文');}
 await page.screenshot({path:info.outputPath('export-filter-wiki.png'),fullPage:true});
 expect((await(await page.request.post('/api/user/login',{data:{email:'outsider@ui-parity.invalid',password:'SyntheticParityOnly_901000!'}})).json()).errcode).toBe(0);for(const endpoint of ['/api/plugin/export?type=json&pid=','/api/plugin/exportSwagger?type=OpenAPIV2&pid=']){const denied=await(await page.request.get(endpoint+id)).json();if(info.project.name==='new')expect(denied.errcode).toBeGreaterThan(0);else await info.attach('legacy-private-export-disclosure',{body:JSON.stringify({endpoint,leaks:Array.isArray(denied)||denied.swagger==='2.0'}),contentType:'application/json'});}
});
