const {test,expect}=require('@playwright/test');

async function verifyRemarkDb(info,id,after){const {execFileSync}=require('node:child_process'),version=info.project.name;expect(['old','new']).toContain(version);expect(Number.isSafeInteger(id)).toBe(true);const script='db=db.getSiblingDB("parity_fast_interfaces_'+version+'");print(JSON.stringify(db.interface.findOne({_id:'+id+'},{_id:1,desc:1,markdown:1})));';const row=JSON.parse(execFileSync('docker',['exec','parity-fast-interfaces-mongo-'+version,version==='old'?'mongo':'mongosh','--quiet','--eval',script],{encoding:'utf8'}));expect(row.desc).toBe(after.desc);expect(row.markdown).toBe(after.markdown);await info.attach('remark-db-readback',{body:JSON.stringify(row),contentType:'application/json'});}

async function setup(page,request,info,role,json5=false,body={}){
 page.setDefaultTimeout(12000);const password='SyntheticParityOnly_901000!';expect((await(await request.post('/api/user/login',{data:{email:'owner@ui-parity.invalid',password}})).json()).errcode).toBe(0);async function api(path,data){const result=await(await request.post(path,{data})).json();expect(result.errcode).toBe(0);return result.data;}
 const project=await api('/api/project/add',{name:'Synthetic body '+Date.now(),group_id:901000,project_type:'private'});await api('/api/project/up',{id:project._id,is_json5:json5});await api('/api/project/add_member',{id:project._id,member_uids:[910003],role:'dev'});await api('/api/project/add_member',{id:project._id,member_uids:[910004],role:'guest'});const cat=(await(await request.get('/api/interface/getCatMenu?project_id='+project._id)).json()).data[0];const item=await api('/api/interface/add',{project_id:project._id,catid:cat._id,title:'Synthetic body fixture',path:'/body',method:'POST',tag:[],req_body_type:'raw',req_body_other:'Synthetic request raw',req_body_is_json_schema:false,req_body_form:[{name:'hidden',type:'text',example:'stale',required:'1'}],res_body_type:'raw',res_body:'Synthetic response raw',res_body_is_json_schema:false,...body});await info.attach('body-fixture',{body:JSON.stringify({project:project._id,id:item._id,role,json5}),contentType:'application/json'});
 await page.goto('/login');await page.getByPlaceholder('Email',{exact:true}).fill((role==='guest'?'outsider':role)+'@ui-parity.invalid');await page.getByPlaceholder('Password',{exact:true}).fill(password);await page.getByRole('button',{name:/^登\s*录$/}).click();await expect(page).toHaveURL(/\/group/);await page.goto('/project/'+project._id+'/interface/api/'+item._id);await page.getByRole('tab',{name:'编辑',exact:true}).click();await expect(page.locator('#title')).toBeVisible();const read=async()=>{const r=await(await request.get('/api/interface/get?id='+item._id)).json();expect(r.errcode).toBe(0);return r.data;};const before=await read();const observations=[];
 async function save(){const wait=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/interface/up'&&r.request().method()==='POST');await expect(page.getByRole('button',{name:/^保\s*存$/})).toBeEnabled();await page.getByRole('button',{name:/^保\s*存$/}).click();const response=await wait,result=await response.json(),payload=response.request().postDataJSON(),after=await read();observations.push({result,payload,after});if(role==='guest'){expect(result.errcode).not.toBe(0);await expect(page.getByText(/没有权限/).first()).toBeVisible();for(const k of ['req_body_type','req_body_other','req_body_form','res_body_type','res_body'])expect(after[k]).toEqual(before[k]);}else if(info.project.name==='new'){expect(result.errcode).toBe(0);await expect(page.getByText('保存成功').first()).toBeVisible();}else{expect([0,40011]).toContain(result.errcode);await expect(page.getByText(result.errcode===0?'保存成功':'服务器出错...',{exact:true}).first()).toBeVisible();}return {result,payload,after};}
 return {project,item,api,read,before,save,observations};
}



for(const role of ['owner','developer','guest'])test('remark popup cancel reopen apply and reload '+role,async({page,request},info)=>{
test.setTimeout(120000);const f=await setup(page,request,info,role,false,{desc:'<p>Original popup note</p>',markdown:'Original popup note',res_body_type:'json',res_body_is_json_schema:true,res_body:'{"type":"object","properties":{}}'}),remark=page.locator('#desc'),editable=remark.locator('[contenteditable=true]:visible'),old=info.project.name==='old';
const button=n=>remark.locator('button.'+(old?'tui-':'')+n),popup=n=>remark.locator((old?'.te-popup-add-':'.toastui-editor-popup-add-')+n+':visible');
async function reset(){await remark.getByText('Markdown',{exact:true}).click();const md=old?remark.locator('.CodeMirror textarea').first():remark.locator('.toastui-editor-md-container [contenteditable=true]');await md.focus();await page.keyboard.press('ControlOrMeta+A');await page.keyboard.insertText('Synthetic popup note');await remark.getByText('WYSIWYG',{exact:true}).click();await editable.click();await page.keyboard.press('ControlOrMeta+End');}
async function save(kind,selector){await expect(editable.locator(selector).first()).toBeVisible();const result=await f.save();await verifyRemarkDb(info,f.item._id,result.after);if(role!=='guest'){expect(result.after.markdown).toBe(result.payload.markdown);expect(result.after.desc).toBe(result.payload.desc);}else expect(result.after.markdown).toBe('Original popup note');await page.reload();await page.getByRole('tab',{name:'编辑',exact:true}).click();if(role!=='guest')await expect(editable.locator(selector).first()).toBeVisible();else await expect(editable).toContainText('Original popup note');await info.attach('popup-'+kind,{body:JSON.stringify({id:f.item._id,after:result.after}),contentType:'application/json'});}
await reset();await button('heading').click();const heading=remark.locator(old?'.te-heading-add:visible':'.toastui-editor-popup-add-heading:visible');await heading.getByText('Heading 2',{exact:true}).click();await save('heading','h2');
await reset();await button('link').click();await popup('link').locator(old?'.te-link-text-input':'#toastuiLinkTextInput').fill('Cancelled link');await popup('link').getByRole('button',{name:'Cancel',exact:true}).click();await expect(editable.locator('a')).toHaveCount(0);await button('link').click();await popup('link').locator(old?'.te-link-text-input':'#toastuiLinkTextInput').fill('Local synthetic link');await popup('link').locator(old?'.te-url-input':'#toastuiLinkUrlInput').fill('/project/'+f.project._id+'/interface/api');await popup('link').getByRole('button',{name:'OK',exact:true}).click();await save('link','a');
await reset();await button('image').click();await popup('image').getByText('URL',{exact:true}).click();await popup('image').locator(old?'.te-alt-text-input':'#toastuiAltTextInput').fill('Cancelled image');await popup('image').getByRole('button',{name:'Cancel',exact:true}).click();await expect(editable.locator('img')).toHaveCount(0);await button('image').click();await popup('image').getByText('URL',{exact:true}).click();await popup('image').locator(old?'.te-image-url-input':'#toastuiImageUrlInput').fill('data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9ZlS8AAAAASUVORK5CYII=');await popup('image').locator(old?'.te-alt-text-input':'#toastuiAltTextInput').fill('Synthetic pixel');await popup('image').getByRole('button',{name:'OK',exact:true}).click();await save('image','img');
await reset();await button('table').click();if(old){const grid=popup('table').locator('.te-table-selection');await grid.hover({position:{x:25,y:25}});await grid.click({position:{x:25,y:25}});}else {const cell=await popup('table').locator('.toastui-editor-table-row').nth(1).locator('.toastui-editor-table-cell').nth(1).boundingBox();await page.mouse.click(cell.x+cell.width/2,cell.y+cell.height/2);}await save('table','table');
await remark.scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath('popup-final.png')});await info.attach('popup-final',{body:JSON.stringify({id:f.item._id,role,observations:f.observations}),contentType:'application/json'});
});
