const {test,expect}=require('@playwright/test');
test.beforeEach(async({page})=>page.setDefaultTimeout(12000));
async function api(page,url,data){const r= data===undefined?await page.request.get(url):await page.request.post(url,{data});expect(r.status(),url).toBe(200);const b=await r.json();expect(b.errcode,url).toBe(0);return b.data;}
async function login(page,role='owner'){await page.context().clearCookies();await page.goto('/login');await page.getByPlaceholder('Email',{exact:true}).fill(role+'@ui-parity.invalid');await page.getByPlaceholder('Password',{exact:true}).fill('SyntheticParityOnly_901000!');await page.getByRole('button',{name:/^登\s*录$/}).click();await expect(page).toHaveURL(/group/);}
async function setup(page,count=2){await login(page);const p=await api(page,'/api/project/add',{name:'Synthetic B closure '+Date.now(),group_id:901000,project_type:'private'});await api(page,'/api/project/up',{id:p._id,env:[{name:'local',domain:'http://127.0.0.1:3000/mock/'+p._id}]});const cat=(await api(page,'/api/interface/getCatMenu?project_id='+p._id))[0];const i=await api(page,'/api/interface/add',{project_id:p._id,catid:cat._id,title:'Closure source',path:'/closure',method:'GET'});await api(page,'/api/interface/up',{id:i._id,res_body_type:'json',res_body_is_json_schema:false,res_body:'{"code":0,"text":"合成测试"}',req_query:[{name:'first',required:'0',desc:'first',example:'one'},{name:'second',required:'0',desc:'second',example:'two'}]});const col=await api(page,'/api/col/add_col',{project_id:p._id,name:'Closure collection'});const cases=[];for(let n=0;n<count;n++)cases.push(await api(page,'/api/col/add_case',{project_id:p._id,col_id:col._id,interface_id:i._id,casename:'Closure case '+n}));const fixture={project:p._id,iface:i._id,col:col._id,cases};page.scopeBFixture=fixture;return fixture;}
async function saveResponse(page,path,action){const wait=page.waitForResponse(r=>new URL(r.url()).pathname===path);await action();const b=await(await wait).json();expect(b.errcode,path).toBe(0);return b.data;}
async function select(page,loc,text){await loc.scrollIntoViewIfNeeded();await loc.click();const input=loc.locator('input');if(await input.isEditable()){await input.fill(text);await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');}else{await page.locator('.ant-select-dropdown:visible .ant-select-item-option-content').getByText(text,{exact:true}).click();}await expect(loc).toContainText(text);}
async function ace(page,root,text){await expect(root).toBeVisible();await expect(root.locator('.ace_content')).toContainText('code');await root.locator('textarea').focus();await page.keyboard.press('Meta+A');await page.keyboard.insertText(text);await expect(root.locator('.ace_content')).toContainText(text);}




async function openEnv(page){await page.locator('.postman .url .ant-select').nth(1).click();await page.getByRole('button',{name:'环境配置',exact:true}).click();return page.getByRole('dialog',{name:'环境设置',exact:true});}
test('imported case edits source environment only and propagates save cancel deletion to actual run',async({page},info)=>{
 const source=await setup(page,0);await api(page,'/api/project/up',{id:source.project,project_type:'public',env:[{name:'source',domain:'http://127.0.0.1:3000/mock/'+source.project},{name:'backup',domain:'http://127.0.0.1:3000/mock/'+source.project}]});
 const target=await setup(page,0);const original=(await api(page,'/api/project/get?id='+target.project)).env;const c=await api(page,'/api/col/add_case',{project_id:target.project,col_id:target.col,interface_id:source.iface,casename:'Imported source environment'});
 await page.goto(`/project/${target.project}/interface/case/${c._id}`);await expect(page.locator('.edit-case-name input')).toHaveValue('Imported source environment');let d=await openEnv(page);await expect(d.getByPlaceholder('请输入环境域名')).toHaveValue('127.0.0.1:3000/mock/'+source.project);await expect(page.locator('.ant-select-dropdown:visible')).toHaveCount(0);
 await d.getByPlaceholder('请输入环境域名').fill('127.0.0.1:3000/discarded');await d.locator('.ant-modal-close').click();d=await openEnv(page);await expect(d.getByPlaceholder('请输入环境域名')).toHaveValue('127.0.0.1:3000/mock/'+source.project);await d.getByPlaceholder('请输入环境域名').fill('127.0.0.1:3000/mock/'+source.project+'/');
 const payloads=[];page.on('request',r=>{if(new URL(r.url()).pathname==='/api/project/up_env')payloads.push(r.postDataJSON().id)});await saveResponse(page,'/api/project/up_env',()=>d.getByRole('button',{name:/保\s*存/}).click());await expect(d).toHaveCount(0);expect(payloads).toEqual([source.project]);expect((await api(page,'/api/project/get?id='+target.project)).env).toEqual(original);
 await expect(page.locator('.postman .url')).toContainText('source');const result=await saveResponse(page,'/api/interface/proxy',()=>page.getByRole('button',{name:/^发\s*送$/}).click());expect(result.res.body.text).toBe('合成测试');await expect(page.locator('.pretty-editor-body')).toContainText('合成测试');
 d=await openEnv(page);const row=d.locator('.menu-item').filter({hasText:'source'});await row.hover();await row.locator('.interface-delete-icon').click();await page.getByRole('button',{name:/取\s*消$/}).click();expect((await api(page,'/api/project/get?id='+source.project)).env).toHaveLength(2);await row.hover();await row.locator('.interface-delete-icon').click();await saveResponse(page,'/api/project/up_env',()=>page.getByRole('button',{name:/确\s*定$/}).click());await expect(d.locator('.env-name')).toHaveText(['backup']);await d.locator('.ant-modal-close').click();await expect(page.locator('.postman .url')).toContainText('backup');await expect(page.locator('.postman .url')).not.toContainText('source：');
 await saveResponse(page,'/api/col/up_case',()=>page.getByRole('button',{name:/更\s*新/}).click());await page.reload();await expect(page.locator('.postman .url')).toContainText('backup');expect((await api(page,'/api/col/case?caseid='+c._id)).case_env).toBe('backup');expect((await api(page,'/api/project/get?id='+target.project)).env).toEqual(original);await page.screenshot({path:info.outputPath('imported-env-reconciled.png'),animations:'disabled'});
 const {expected}=require('./parity-collections-guard.cjs'),e=expected(info.project.name),{execFileSync}=require('node:child_process');for(const n of[source.project,target.project,c._id])expect(Number.isSafeInteger(n)).toBe(true);const prefix=info.project.name==='new'?'await ':'';const js=`var marker=${prefix}db.getCollection('_ui_parity_fixture').findOne({_id:'yapi-ui-parity-v1'});if(!marker||marker.synthetic!==true||marker.run!=='fastb1003'||marker.fixtureSha256!==${JSON.stringify(e.hash)})throw Error('Wrong fixture');var source=${prefix}db.project.findOne({_id:${source.project}},{env:1});var target=${prefix}db.project.findOne({_id:${target.project}},{env:1});var record=${prefix}db.interface_case.findOne({_id:${c._id}},{case_env:1,project_id:1});print(JSON.stringify({source,target,record}))`;const raw=execFileSync('docker',['exec',e.mongo,info.project.name==='new'?'mongosh':'mongo','--quiet',e.database,'--eval',info.project.name==='new'?'(async()=>{'+js+'})()':js],{encoding:'utf8'});const readback=JSON.parse(raw.trim());expect(readback.source.env.map(x=>x.name)).toEqual(['backup']);expect(readback.record.case_env).toBe('backup');expect(readback.record.project_id).toBe(target.project);expect(readback.target.env).toEqual(original);await info.attach('synthetic-db-env-readback',{body:JSON.stringify(readback),contentType:'application/json'});
 await info.attach('synthetic-env-ids',{body:JSON.stringify({source:source.project,target:target.project,case:c._id}),contentType:'application/json'});
});
