const {test,expect}=require('@playwright/test');
async function login(page,role='owner'){await page.goto('/login');await page.getByPlaceholder('Email',{exact:true}).fill(role+'@ui-parity.invalid');await page.getByPlaceholder('Password',{exact:true}).fill('SyntheticParityOnly_901000!');await page.getByRole('button',{name:/^登\s*录$/}).click();await expect(page).toHaveURL(/\/group/);}
async function read(page,id){const b=await(await page.request.get('/api/project/get?id='+id)).json();expect(b.errcode).toBe(0);return b.data;}
async function save(page,action){const p=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/project/up'&&r.request().method()==='POST');await action();expect((await(await p).json()).errcode).toBe(0);}
test('project metadata booleans tags repeated save reload and scoped danger cancel',async({page},info)=>{
 page.setDefaultTimeout(10000);await login(page);const b=await(await page.request.post('/api/project/add',{data:{name:'Synthetic settings '+info.project.name+' '+Date.now(),group_id:901000,project_type:'private'}})).json();expect(b.errcode).toBe(0);const id=b.data._id;
 await page.goto('/project/'+id+'/setting');const name='Synthetic edited '+id;await page.locator('#name').fill(name);await page.locator('#basepath').fill('/synthetic-base');await page.locator('#desc').fill('Synthetic description 中文');await page.getByPlaceholder('请输入 tag 名称').last().fill('Synthetic tag');await page.getByPlaceholder('请输入tag 描述信息').first().fill('Synthetic tag description');
 for(const key of ['strice','is_json5','switch_notice']){const el=page.locator('#'+key);if(await el.getAttribute('aria-checked')!=='true')await el.click();}
 await save(page,()=>page.getByRole('button',{name:/保\s*存/}).click());await save(page,()=>page.getByRole('button',{name:/保\s*存/}).click());await page.reload();await expect(page.locator('#name')).toHaveValue(name);await expect(page.locator('#basepath')).toHaveValue('/synthetic-base');const data=await read(page,id);expect(data).toMatchObject({name,basepath:'/synthetic-base',desc:'Synthetic description 中文',strice:true,is_json5:true,switch_notice:true});expect(data.tag.map(({name,desc})=>({name,desc}))).toEqual([{name:'Synthetic tag',desc:'Synthetic tag description'}]);
 await page.getByRole('button',{name:/查\s*看/}).click();await page.getByRole('button',{name:/^删\s*除$/}).click();await page.getByRole('button',{name:/取\s*消/}).click();expect((await read(page,id)).name).toBe(name);await page.getByRole('button',{name:/^删\s*除$/}).click();await page.locator('#project_name').fill('wrong-name');await page.getByRole('button',{name:/确\s*定/}).click();await expect(page.getByText('项目名称有误',{exact:true})).toBeVisible();await page.getByRole('button',{name:/取\s*消/}).click();expect((await read(page,901001)).name).toBe('Synthetic parity project');await page.screenshot({path:info.outputPath('project-settings.png'),fullPage:true});
});
for(const role of ['owner','developer'])test('existing synthetic token display cancel and services project switching '+role,async({page},info)=>{
 page.setDefaultTimeout(10000);await login(page,role);let tokens=[];let mutations=0;page.on('request',r=>{if(r.url().includes('update_token'))mutations++});
 for(const id of [901001,901005]){await page.goto('/project/'+id+'/setting');await page.getByRole('tab',{name:'token配置',exact:true}).click();await expect(page.locator('.token-message')).toHaveText(/^.+$/);const token=await page.locator('.token-message').textContent();expect(token).toMatch(/^.+$/);tokens.push(token);if(role==='owner'){await page.locator('.project-token .anticon-reload').click();await page.getByRole('button',{name:/取\s*消/}).click();await expect(page.locator('.token-message')).toHaveText(token);}else await expect(page.locator('.project-token .anticon-reload')).toHaveCount(0);
 await expect(page.getByRole('tab',{name:'生成 ts services',exact:true})).toHaveCount(1);await page.getByRole('tab',{name:'生成 ts services',exact:true}).click();await expect(page.locator('.project-services')).toContainText('pid='+id+'&status=all&token='+token);await expect(page.locator('.project-services')).toContainText('sm2tsservice --clear');await expect(page.locator('.project-services a')).toHaveAttribute('href','https://github.com/gogoyqj/sm2tsservice');if(tokens.length===2)await expect(page.locator('.project-services')).not.toContainText(tokens[0]);await page.screenshot({path:info.outputPath('services-'+id+'.png'),fullPage:true});}
 expect(tokens[0]).not.toBe(tokens[1]);expect(mutations).toBe(0);
});
test('services instructions narrow layout and generated output authorization',async({page,browser},info)=>{
 page.setDefaultTimeout(10000);await login(page);await page.goto('/project/901001/setting');await page.getByRole('tab',{name:'生成 ts services',exact:true}).click();await expect(page.locator('.project-services')).toContainText('sm2tsservice --clear');await expect.poll(async()=>{const t=await page.locator('.project-services').textContent();return /token=([^"\s]+)/.test(t)}).toBe(true);const text=await page.locator('.project-services').textContent();const remote=JSON.parse((await page.locator('.project-services pre').nth(2).textContent()).trim()).remoteUrl;const response=await page.request.get(remote);expect(response.status()).toBe(200);const output=await response.json();expect(Array.isArray(output)).toBe(true);expect(JSON.stringify(output)).toContain('Nested');
 await page.setViewportSize({width:800,height:1080});await expect(page.locator('.project-services a')).toBeVisible();const size=await page.evaluate(()=>({width:window.innerWidth,scroll:document.documentElement.scrollWidth}));expect(size.scroll).toBeLessThanOrEqual(size.width);const code=page.locator('.project-services pre').nth(2);await code.hover();await page.mouse.wheel(2000,0);await expect.poll(()=>code.evaluate(el=>el.scrollLeft)).toBeGreaterThan(0);await page.screenshot({path:info.outputPath('services-narrow.png'),fullPage:true});
 const c=await browser.newContext({baseURL:info.project.use.baseURL});try{const p=await c.newPage();await login(p,'outsider');const u=new URL(remote);u.searchParams.delete('token');const denied=await(await p.request.get(u.toString())).json();expect(denied.errcode).not.toBe(0);}finally{await c.close();}
});
test('both request scripts and global mock toggle save exact values across reload',async({page},info)=>{
 page.setDefaultTimeout(10000);await login(page);const made=await(await page.request.post('/api/project/add',{data:{name:'Synthetic scripts '+Date.now(),group_id:901000,project_type:'private'}})).json();expect(made.errcode).toBe(0);const id=made.data._id;await page.goto('/project/'+id+'/setting');await page.getByRole('tab',{name:'请求配置',exact:true}).click();const values=['// synthetic request\nvar a = 1;','// synthetic response\nvar b = 2;'];for(let i=0;i<2;i++){await page.locator('.ace_text-input:visible').nth(i).focus();await page.keyboard.press('Meta+A');await page.keyboard.insertText(values[i]);}await save(page,()=>page.getByRole('button',{name:/保\s*存/}).click());await page.reload();await page.getByRole('tab',{name:'请求配置',exact:true}).click();expect(await read(page,id)).toMatchObject({pre_script:values[0],after_script:values[1]});await expect(page.locator('.ace_content:visible').nth(0)).toContainText('var a = 1;');await expect(page.locator('.ace_content:visible').nth(1)).toContainText('var b = 2;');
 await page.getByRole('tab',{name:'全局mock脚本',exact:true}).click();const editor=page.locator('.ace_text-input:visible');await editor.focus();await page.keyboard.press('Meta+A');await page.keyboard.insertText('// synthetic global mock');const toggle=page.locator('.ant-switch:visible');if(!(await toggle.getAttribute('class')).includes('ant-switch-checked'))await toggle.click();await save(page,()=>page.getByRole('button',{name:/保\s*存/}).click());await page.reload();await page.getByRole('tab',{name:'全局mock脚本',exact:true}).click();expect(await read(page,id)).toMatchObject({is_mock_open:true,project_mock_script:'// synthetic global mock'});await page.locator('.ant-switch:visible').click();await save(page,()=>page.getByRole('button',{name:/保\s*存/}).click());await page.reload();await page.getByRole('tab',{name:'全局mock脚本',exact:true}).click();expect(await read(page,id)).toMatchObject({is_mock_open:false,project_mock_script:'// synthetic global mock'});await page.screenshot({path:info.outputPath('mock-disabled.png'),fullPage:true});
});
test('guest cannot discover token tab',async({page},info)=>{
 page.setDefaultTimeout(10000);await login(page);const made=await(await page.request.post('/api/project/add',{data:{name:'Synthetic guest token gate '+Date.now(),group_id:901000,project_type:'private'}})).json();expect(made.errcode).toBe(0);const id=made.data._id;expect((await(await page.request.post('/api/project/add_member',{data:{id,member_uids:[910004],role:'guest'}})).json()).errcode).toBe(0);await login(page,'outsider');await page.goto('/project/'+id+'/setting');await expect(page.getByRole('tab',{name:'项目配置',exact:true})).toBeVisible();await expect(page.getByRole('tab',{name:'token配置',exact:true})).toHaveCount(0);await page.screenshot({path:info.outputPath('guest-token-gate.png'),fullPage:true});
});
