const {test,expect}=require('@playwright/test');

async function verifyRemarkDb(info,id,after){const {execFileSync}=require('node:child_process'),version=info.project.name;expect(['old','new']).toContain(version);expect(Number.isSafeInteger(id)).toBe(true);const script='db=db.getSiblingDB("parity_fast_interfaces_'+version+'");print(JSON.stringify(db.interface.findOne({_id:'+id+'},{_id:1,desc:1,markdown:1})));';const row=JSON.parse(execFileSync('docker',['exec','parity-fast-interfaces-mongo-'+version,version==='old'?'mongo':'mongosh','--quiet','--eval',script],{encoding:'utf8'}));expect(row.desc).toBe(after.desc);expect(row.markdown).toBe(after.markdown);await info.attach('remark-db-readback',{body:JSON.stringify(row),contentType:'application/json'});}

async function setup(page,request,info,role,json5=false,body={}){
 page.setDefaultTimeout(12000);const password='SyntheticParityOnly_901000!';expect((await(await request.post('/api/user/login',{data:{email:'owner@ui-parity.invalid',password}})).json()).errcode).toBe(0);async function api(path,data){const result=await(await request.post(path,{data})).json();expect(result.errcode).toBe(0);return result.data;}
 const project=await api('/api/project/add',{name:'Synthetic body '+Date.now(),group_id:901000,project_type:'private'});await api('/api/project/up',{id:project._id,is_json5:json5});await api('/api/project/add_member',{id:project._id,member_uids:[910003],role:'dev'});await api('/api/project/add_member',{id:project._id,member_uids:[910004],role:'guest'});const cat=(await(await request.get('/api/interface/getCatMenu?project_id='+project._id)).json()).data[0];const item=await api('/api/interface/add',{project_id:project._id,catid:cat._id,title:'Synthetic body fixture',path:'/body',method:'POST',tag:[],req_body_type:'raw',req_body_other:'Synthetic request raw',req_body_is_json_schema:false,req_body_form:[{name:'hidden',type:'text',example:'stale',required:'1'}],res_body_type:'raw',res_body:'Synthetic response raw',res_body_is_json_schema:false,...body});await info.attach('body-fixture',{body:JSON.stringify({project:project._id,id:item._id,role,json5}),contentType:'application/json'});
 await page.goto('/login');await page.getByPlaceholder('Email',{exact:true}).fill((role==='guest'?'outsider':role)+'@ui-parity.invalid');await page.getByPlaceholder('Password',{exact:true}).fill(password);await page.getByRole('button',{name:/^登\s*录$/}).click();await expect(page).toHaveURL(/\/group/);await page.goto('/project/'+project._id+'/interface/api/'+item._id);await page.getByRole('tab',{name:'编辑',exact:true}).click();await expect(page.locator('#title')).toBeVisible();const read=async()=>{const r=await(await request.get('/api/interface/get?id='+item._id)).json();expect(r.errcode).toBe(0);return r.data;};const before=await read();const observations=[];
 async function save(){const wait=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/interface/up'&&r.request().method()==='POST');await expect(page.getByRole('button',{name:/^保\s*存$/})).toBeEnabled();await page.getByRole('button',{name:/^保\s*存$/}).click();const response=await wait,result=await response.json(),payload=response.request().postDataJSON(),after=await read();observations.push({result,payload,after});if(role==='guest'){expect(result.errcode).not.toBe(0);await expect(page.getByText(/没有权限/).first()).toBeVisible();for(const k of ['req_body_type','req_body_other','req_body_form','res_body_type','res_body'])expect(after[k]).toEqual(before[k]);}else if(info.project.name==='new'){expect(result.errcode).toBe(0);await expect(page.getByText('保存成功').first()).toBeVisible();}else{expect([0,40011]).toContain(result.errcode);await expect(page.getByText(result.errcode===0?'保存成功':'服务器出错...',{exact:true}).first()).toBeVisible();}return {result,payload,after};}
 return {project,item,api,read,before,save,observations};
}


for(const role of ['owner','developer','guest'])test('existing remark content preview style '+role,async({page,request},info)=>{
 const html='<h2>Synthetic documentation</h2><p>中文说明 and English. No customer data.</p><ul><li><p>Nested schemas</p><ul><li><p>Nested child</p></li></ul></li><li><p>Long descriptions wrap predictably.</p></li></ul><ol><li><p>First numbered item</p><ol><li><p>Nested number</p></li></ol></li><li><p>Second numbered item</p></li></ol><blockquote><p>Synthetic quote</p></blockquote><p>Inline <code>sample()</code></p><pre><code>const sample = 1;\nconsole.log(sample);</code></pre><table><thead><tr><th>Name</th><th>Value</th></tr></thead><tbody><tr><td>Synthetic</td><td>1</td></tr></tbody></table>';
 const f=await setup(page,request,info,role,false,{desc:html,markdown:''});await page.getByRole('tab',{name:'预览',exact:true}).first().click();const content=page.locator('.caseContainer > .tui-editor-contents');await expect(content).toContainText('Nested child');await content.scrollIntoViewIfNeeded();const styles=await content.evaluate(e=>[...e.querySelectorAll('h2,ul,ol,li,p,blockquote,pre,code,table,th,td')].map(n=>{const c=getComputedStyle(n);return {tag:n.tagName,text:n.textContent,list:c.listStyleType,padding:c.paddingLeft,margin:c.margin,font:c.fontSize,weight:c.fontWeight,border:c.border,background:c.backgroundColor,whiteSpace:c.whiteSpace,before:getComputedStyle(n,'::before').content};}));if(info.project.name==='old')await info.attach('legacy-content-css',{body:JSON.stringify(await page.evaluate(()=>[...document.styleSheets].flatMap(sheet=>{try{return [...sheet.cssRules].filter(r=>r.selectorText&&r.selectorText.split(',').some(s=>s.trim().startsWith('.tui-editor-contents'))).map(r=>({selector:r.selectorText,style:r.style.cssText}));}catch(e){return [];}}))),contentType:'application/json'});await info.attach('remark-styles',{body:JSON.stringify(styles),contentType:'application/json'});for(const ul of styles.filter(x=>x.tag==='UL')){expect(ul.list).toBe('disc');expect(ul.padding).toBe('17px');}for(const ol of styles.filter(x=>x.tag==='OL')){expect(ol.list).toBe('decimal');expect(ol.padding).toBe('17px');}expect(styles.find(x=>x.tag==='PRE').background).toBe('rgb(245, 247, 248)');expect(styles.find(x=>x.tag==='TD').border).toBe('1px solid rgb(234, 234, 234)');await page.screenshot({path:info.outputPath('remark-preview.png')});await page.reload();await expect(content).toContainText('Nested child');expect((await f.read()).desc).toBe(html);await page.getByRole('tab',{name:'编辑',exact:true}).click();const editable=page.locator('#desc [contenteditable=true]:visible');await editable.click();await page.keyboard.press('ControlOrMeta+End');await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');await page.keyboard.insertText('Synthetic saved content');const saved=await f.save();await verifyRemarkDb(info,f.item._id,saved.after);await page.getByRole('tab',{name:'预览',exact:true}).first().click();if(role==='guest'&&info.project.name==='new'){const modal=page.locator('.ant-modal:visible');await modal.getByRole('button',{name:/确\s*定/}).click();}await expect(content.locator('ul').first()).toHaveCSS('list-style-type','disc');await expect(content.locator('ol').first()).toHaveCSS('padding-left','17px');await expect(content.locator('td').first()).toHaveCSS('border-left-width','1px');expect(await content.locator('th').first().evaluate(e=>getComputedStyle(e.querySelector('p')||e).color)).toBe('rgb(255, 255, 255)');await page.reload();await expect(content.locator('ul').first()).toHaveCSS('list-style-type','disc');await content.scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath('remark-saved-preview.png')});
});
