const {test,expect}=require('@playwright/test');
for(const role of ['owner','developer','guest'])test('category create edit interface copy delete and cancel '+role,async({page,request},info)=>{
 page.setDefaultTimeout(12000);const password='SyntheticParityOnly_901000!';expect((await(await request.post('/api/user/login',{data:{email:'owner@ui-parity.invalid',password}})).json()).errcode).toBe(0);
 async function api(path,data){const r=await(await request.post(path,{data})).json();expect(r.errcode).toBe(0);return r.data;}
 const p=await api('/api/project/add',{name:'Synthetic category flows '+role+' '+Date.now(),group_id:901000,project_type:'private'});if(role!=='owner')await api('/api/project/add_member',{id:p._id,member_uids:[role==='guest'?910004:910003],role:role==='guest'?'guest':'dev'});
 await info.attach('fixture',{body:JSON.stringify({project:p._id}),contentType:'application/json'});await page.goto('/login');await page.getByPlaceholder('Email',{exact:true}).fill((role==='guest'?'outsider':role)+'@ui-parity.invalid');await page.getByPlaceholder('Password',{exact:true}).fill(password);await page.getByRole('button',{name:/^登\s*录$/}).click();await expect(page).toHaveURL(/\/group/);await page.goto('/project/'+p._id+'/interface/api');
 const modal=page.locator('.ant-modal:visible');const cats=async()=>{const r=await(await request.get('/api/interface/getCatMenu?project_id='+p._id)).json();expect(r.errcode).toBe(0);return r.data;};
 async function response(path,click){const r=page.waitForResponse(r=>new URL(r.url()).pathname===path&&r.request().method()==='POST');await click();return (await r).json();}
 await page.getByRole('button',{name:'添加分类',exact:true}).click();await modal.getByPlaceholder('分类名称',{exact:true}).fill('discard category');await modal.getByRole('button',{name:/取\s*消/}).click();await expect(modal).toHaveCount(0);expect((await cats()).length).toBe(1);
 await page.getByRole('button',{name:'添加分类',exact:true}).click();await modal.getByPlaceholder('分类名称',{exact:true}).fill('Category A');await modal.getByPlaceholder('备注',{exact:true}).fill('Category description');const created=await response('/api/interface/add_cat',()=>modal.getByRole('button',{name:/提\s*交/}).click());
 if(role==='guest'){expect(created.errcode).not.toBe(0);await expect(page.getByText(/没有权限/).first()).toBeVisible();expect((await cats()).length).toBe(1);await modal.getByRole('button',{name:/取\s*消/}).click();await expect(modal).toHaveCount(0);
 const seededCat=await api('/api/interface/add_cat',{project_id:p._id,name:'Guest protected',desc:'original desc'});const c=(await cats()).find(x=>x.name==='Guest protected');const item=await api('/api/interface/add',{project_id:p._id,catid:c._id,title:'Guest protected API',path:'/guest-protected',method:'GET',res_body_type:'json',res_body_is_json_schema:true,res_body:'{"type":"object","properties":{}}'});await info.attach('guest-protected',{body:JSON.stringify({cat:c._id,id:item._id}),contentType:'application/json'});await page.goto('/project/'+p._id+'/interface/api/'+item._id);await expect(node('Guest protected API')).toBeVisible();await page.waitForTimeout(400);
 await node('Guest protected').hover();await node('Guest protected').locator('.anticon-edit').click();await modal.getByPlaceholder('分类名称',{exact:true}).fill('Denied rename');const deniedEdit=await response('/api/interface/up_cat',()=>modal.getByRole('button',{name:/提\s*交/}).click());expect(deniedEdit.errcode).not.toBe(0);await expect(page.getByText(/没有权限/).first()).toBeVisible();await modal.getByRole('button',{name:/取\s*消/}).click();await expect(modal).toHaveCount(0);expect((await cats()).find(x=>x._id===c._id).name).toBe('Guest protected');
 await node('Guest protected').hover();await node('Guest protected').locator('.anticon-plus').click();await modal.getByPlaceholder('接口名称',{exact:true}).fill('Denied API');await modal.getByPlaceholder('/path',{exact:true}).fill('/denied');const deniedAdd=await response('/api/interface/add',()=>modal.getByRole('button',{name:/提\s*交/}).click());expect(deniedAdd.errcode).not.toBe(0);await expect(page.getByText(/没有权限/).first()).toBeVisible();await modal.getByRole('button',{name:/取\s*消/}).click();await expect(modal).toHaveCount(0);
 await node('Guest protected API').hover();const deniedCopy=await response('/api/interface/add',()=>node('Guest protected API').locator('.anticon-copy').click());expect(deniedCopy.errcode).not.toBe(0);await expect(page.getByText(/没有权限/).first()).toBeVisible();
 await node('Guest protected API').hover();await node('Guest protected API').locator('.anticon-delete').click();const deniedDelete=await response('/api/interface/del',()=>modal.getByRole('button',{name:/确\s*认/}).click());expect(deniedDelete.errcode).not.toBe(0);await expect(modal).toBeVisible();await modal.getByRole('button',{name:/取\s*消/}).click();await expect(modal).toHaveCount(0);expect((await(await request.get('/api/interface/get?id='+item._id)).json()).data._id).toBe(item._id);
 await node('Guest protected').hover();await node('Guest protected').locator('.anticon-delete').click();const deniedCatDelete=await response('/api/interface/del_cat',()=>modal.getByRole('button',{name:/确\s*认/}).click());expect(deniedCatDelete.errcode).not.toBe(0);await expect(modal).toBeVisible();await modal.getByRole('button',{name:/取\s*消/}).click();await expect(modal).toHaveCount(0);expect((await cats()).some(x=>x._id===c._id)).toBe(true);await page.reload();await node('Guest protected').getByRole('link').click();await expect(page.locator('.table-interfacelist')).toContainText('Guest protected API');await page.screenshot({path:info.outputPath('guest-menu-denials.png')});return;}
 expect(created.errcode).toBe(0);await expect(page.getByText('接口分类添加成功').first()).toBeVisible();await expect(modal).toHaveCount(0);const cat=(await cats()).find(c=>c.name==='Category A');expect(cat.desc).toBe('Category description');await info.attach('category',{body:JSON.stringify({id:cat._id}),contentType:'application/json'});
 function node(name){return page.locator('.container-title').filter({has:page.locator('a.interface-item').filter({hasText:new RegExp('^'+name+'$')})});}
 await node('Category A').getByRole('link').click();await expect(page).toHaveURL(new RegExp('cat_'+cat._id+'$'));await node('Category A').hover();await node('Category A').locator('.anticon-edit').click();await modal.getByPlaceholder('分类名称',{exact:true}).fill('Category renamed');await modal.getByPlaceholder('备注',{exact:true}).fill('Edited description');const edited=await response('/api/interface/up_cat',()=>modal.getByRole('button',{name:/提\s*交/}).click());expect(edited.errcode).toBe(0);await expect(page.getByText('接口分类更新成功').first()).toBeVisible();await expect(modal).toHaveCount(0);expect((await cats()).find(c=>c._id===cat._id).desc).toBe('Edited description');
 await node('Category renamed').hover();await node('Category renamed').locator('.anticon-plus').click();await modal.getByPlaceholder('接口名称',{exact:true}).fill('Synthetic copied interface');await modal.getByPlaceholder('/path',{exact:true}).fill('/synthetic-copy');const added=await response('/api/interface/add',()=>modal.getByRole('button',{name:/提\s*交/}).click());expect(added.errcode).toBe(0);const id=added.data._id;await expect(page.getByText('接口添加成功').first()).toBeVisible();await expect(page).toHaveURL(new RegExp('/'+id+'$'));await expect(modal).toHaveCount(0);
 await page.waitForTimeout(500);await page.mouse.move(1000,400);await node('Synthetic copied interface').hover();const copied=await response('/api/interface/add',()=>node('Synthetic copied interface').locator('.anticon-copy').click());expect(copied.errcode).toBe(0);const copyId=copied.data._id;expect(copyId).not.toBe(id);await expect(page).toHaveURL(new RegExp('/'+copyId+'$'));const copy=(await(await request.get('/api/interface/get?id='+copyId)).json()).data;expect(copy.catid).toBe(cat._id);expect(copy.title).toBe('Synthetic copied interface_copy');expect(copy.path).toMatch(/^\/synthetic-copy_\d+$/);await info.attach('interfaces',{body:JSON.stringify({id,copyId}),contentType:'application/json'});
 await node('Synthetic copied interface_copy').hover();await node('Synthetic copied interface_copy').locator('.anticon-delete').click();await modal.getByRole('button',{name:/取\s*消/}).click();await expect(modal).toHaveCount(0);expect((await(await request.get('/api/interface/get?id='+copyId)).json()).data._id).toBe(copyId);
 await node('Synthetic copied interface_copy').hover();await node('Synthetic copied interface_copy').locator('.anticon-delete').click();const deleted=await response('/api/interface/del',()=>modal.getByRole('button',{name:/确\s*认/}).click());expect(deleted.errcode).toBe(0);await expect(node('Synthetic copied interface_copy')).toHaveCount(0);await expect(page).toHaveURL(new RegExp('cat_'+cat._id+'$'));await page.reload();await expect(node('Synthetic copied interface')).toBeVisible();await expect(node('Synthetic copied interface_copy')).toHaveCount(0);
 await page.screenshot({path:info.outputPath('category-copy-delete.png')});await node('Category renamed').hover();await node('Category renamed').locator('.anticon-delete').click();await modal.getByRole('button',{name:/取\s*消/}).click();await expect(modal).toHaveCount(0);expect((await cats()).some(c=>c._id===cat._id)).toBe(true);await node('Category renamed').hover();await node('Category renamed').locator('.anticon-delete').click();const removed=await response('/api/interface/del_cat',()=>modal.getByRole('button',{name:/确\s*认/}).click());expect(removed.errcode).toBe(0);await expect(node('Category renamed')).toHaveCount(0);expect((await cats()).some(c=>c._id===cat._id)).toBe(false);await page.reload();await expect(node('Category renamed')).toHaveCount(0);
});

for(const role of ['owner','developer','guest'])test('category reorder and interface move persist '+role,async({page,request},info)=>{
 page.setDefaultTimeout(12000);const password='SyntheticParityOnly_901000!';expect((await(await request.post('/api/user/login',{data:{email:'owner@ui-parity.invalid',password}})).json()).errcode).toBe(0);async function api(path,data){const r=await(await request.post(path,{data})).json();expect(r.errcode).toBe(0);return r.data;}
 const p=await api('/api/project/add',{name:'Synthetic drag '+role+' '+Date.now(),group_id:901000,project_type:'private'});if(role!=='owner')await api('/api/project/add_member',{id:p._id,member_uids:[role==='guest'?910004:910003],role:role==='guest'?'guest':'dev'});const a=await api('/api/interface/add_cat',{project_id:p._id,name:'Drag A',desc:'source'});const b=await api('/api/interface/add_cat',{project_id:p._id,name:'Drag B',desc:'target'});const initial=(await(await request.get('/api/interface/list_menu?project_id='+p._id)).json()).data;const ca=initial.find(c=>c.name==='Drag A'),cb=initial.find(c=>c.name==='Drag B');const i=await api('/api/interface/add',{project_id:p._id,catid:ca._id,title:'Movable interface',path:'/movable',method:'GET',tag:[],res_body_type:'json',res_body_is_json_schema:true,res_body:'{"type":"object","properties":{}}'});await info.attach('fixture',{body:JSON.stringify({project:p._id,catA:ca._id,catB:cb._id,id:i._id}),contentType:'application/json'});
 await page.goto('/login');await page.getByPlaceholder('Email',{exact:true}).fill((role==='guest'?'outsider':role)+'@ui-parity.invalid');await page.getByPlaceholder('Password',{exact:true}).fill(password);await page.getByRole('button',{name:/^登\s*录$/}).click();await expect(page).toHaveURL(/\/group/);await page.goto('/project/'+p._id+'/interface/api/'+i._id);function link(name){return page.locator('a.interface-item').filter({hasText:new RegExp('^'+name+'$')});}await expect(link('Movable interface')).toBeVisible();await page.waitForTimeout(400);async function drag(source,target,position){const src=info.project.name==='new'?page.locator('.ant-tree-treenode').filter({has:link(source)}).locator('.ant-tree-draggable-icon'):page.locator('.ant-tree-node-content-wrapper').filter({has:link(source)});const dst=link(target);const a=await src.boundingBox(),b=await dst.boundingBox();await page.mouse.move(a.x+a.width/2,a.y+a.height/2);await page.mouse.down();await page.mouse.move(a.x+a.width/2+10,a.y+a.height/2+5,{steps:5});await page.mouse.move(b.x+(position?position.x:b.width/2),b.y+(position?position.y:b.height-3),{steps:12});await page.waitForTimeout(350);await page.mouse.move(b.x+(position?position.x:b.width/2)+1,b.y+(position?position.y:b.height-3));await page.mouse.up();}
 const move=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/interface/up'&&r.request().method()==='POST');await drag('Movable interface','Drag B');const moved=await(await move).json();await info.attach('move-response',{body:JSON.stringify({errcode:moved.errcode}),contentType:'application/json'});expect(moved.errcode===0).toBe(role!=='guest');if(role==='guest'&&info.project.name==='new')await expect(page.getByText(/没有权限/).first()).toBeVisible();const stored=(await(await request.get('/api/interface/get?id='+i._id)).json()).data;expect(stored.catid).toBe(role==='guest'?ca._id:cb._id);await page.reload();await expect(link('Movable interface')).toBeVisible();
 const order=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/interface/up_cat_index');await drag('Drag B','Drag A',{x:20,y:1});const ordered=await(await order).json();await info.attach('order-response',{body:JSON.stringify({errcode:ordered.errcode}),contentType:'application/json'});expect(ordered.errcode===0).toBe(role!=='guest'||info.project.name==='old');if(role==='guest'&&info.project.name==='new')await expect(page.getByText(/没有权限/).first()).toBeVisible();await page.reload();const final=(await(await request.get('/api/interface/list_menu?project_id='+p._id)).json()).data;const names=final.map(c=>c.name);expect(names.indexOf('Drag B')<names.indexOf('Drag A')).toBe(role!=='guest'||info.project.name==='old');await page.screenshot({path:info.outputPath('category-drag-final.png')});
});

test('sort batches reject mixed ownership guest and revoked membership without writes',async({page,request},info)=>{
 const password='SyntheticParityOnly_901000!';expect((await(await request.post('/api/user/login',{data:{email:'owner@ui-parity.invalid',password}})).json()).errcode).toBe(0);async function api(path,data){const r=await(await request.post(path,{data})).json();expect(r.errcode).toBe(0);return r.data;}
 const projects=[],cats=[],interfaces=[];for(const suffix of ['A','B']){const p=await api('/api/project/add',{name:'Synthetic sort boundaries '+suffix+' '+Date.now(),group_id:901000,project_type:'private'});projects.push(p._id);const c=(await(await request.get('/api/interface/getCatMenu?project_id='+p._id)).json()).data[0];cats.push(c._id);interfaces.push((await api('/api/interface/add',{project_id:p._id,catid:c._id,title:'Sort target '+suffix,path:'/sort-boundary',method:'GET',tag:[],res_body_type:'json',res_body_is_json_schema:true,res_body:'{"type":"object","properties":{}}'}))._id);}
 await info.attach('sort-fixture',{body:JSON.stringify({projects,cats,interfaces}),contentType:'application/json'});
 async function values(){const data=[];for(const p of projects){const r=await(await request.get('/api/interface/list_menu?project_id='+p)).json();expect(r.errcode).toBe(0);data.push(r.data.map(c=>({id:c._id,index:c.index,list:c.list.map(i=>({id:i._id,index:i.index}))})));}return data;}
 async function attempt(context,kind,items,label){const before=await values();const r=await(await context.post('/api/interface/'+kind,{data:items})).json();await info.attach(label+'-'+kind,{body:JSON.stringify({errcode:r.errcode}),contentType:'application/json'});if(info.project.name==='new'){expect(r.errcode).not.toBe(0);expect(await values()).toEqual(before);}else expect(r.errcode).toBe(0);}
 for(const [kind,ids]of [['up_index',interfaces],['up_cat_index',cats]])await attempt(request,kind,[{id:ids[0],index:40,project_id:projects[0]},{id:ids[1],index:41,project_id:projects[0]}],'mixed');
 await api('/api/project/add_member',{id:projects[0],member_uids:[910004],role:'guest'});expect((await(await page.request.post('/api/user/login',{data:{email:'outsider@ui-parity.invalid',password}})).json()).errcode).toBe(0);
 for(const[kind,ids]of [['up_index',interfaces],['up_cat_index',cats]])await attempt(page.request,kind,[{id:ids[0],index:50}],'guest');
 await api('/api/project/add_member',{id:projects[0],member_uids:[910003],role:'dev'});expect((await(await page.request.post('/api/user/login',{data:{email:'developer@ui-parity.invalid',password}})).json()).errcode).toBe(0);for(const[kind,ids]of [['up_index',interfaces],['up_cat_index',cats]]){const r=await(await page.request.post('/api/interface/'+kind,{data:[{id:ids[0],index:60}]})).json();expect(r.errcode).toBe(0);}
 await api('/api/project/del_member',{id:projects[0],member_uid:910003});for(const[kind,ids]of [['up_index',interfaces],['up_cat_index',cats]])await attempt(page.request,kind,[{id:ids[0],index:70}],'revoked');
 await info.attach('final-sort-values',{body:JSON.stringify(await values()),contentType:'application/json'});
});
