const {test,expect}=require('@playwright/test');
for(const role of ['owner','developer','guest'])test('interface tag modal cancel save and unsaved fields '+role,async({page,request},info)=>{
 page.setDefaultTimeout(12000);
 const password='SyntheticParityOnly_901000!';
 expect((await(await request.post('/api/user/login',{data:{email:'owner@ui-parity.invalid',password}})).json()).errcode).toBe(0);
 async function api(path,data){const r=await(await request.post(path,{data})).json();expect(r.errcode).toBe(0);return r.data;}
 const p=await api('/api/project/add',{name:'Synthetic interface tags '+role+' '+Date.now(),group_id:901000,project_type:'private'});
 if(role!=='owner')await api('/api/project/add_member',{id:p._id,member_uids:[role==='guest'?910004:910003],role:role==='guest'?'guest':'dev'});
 await api('/api/project/up_tag',{id:p._id,tag:[{name:'alpha',desc:'alpha description'},{name:'beta',desc:'beta description'}]});
 const cats=(await(await request.get('/api/interface/getCatMenu?project_id='+p._id)).json()).data;
 const i=await api('/api/interface/add',{project_id:p._id,catid:cats[0]._id,title:'Synthetic original title',path:'/tags',method:'GET',tag:['alpha'],req_query:[{name:'before',example:'original'}],res_body_type:'json',res_body_is_json_schema:true,res_body:'{"type":"object","properties":{}}'});
 await info.attach('fixture',{body:JSON.stringify({project:p._id,id:i._id}),contentType:'application/json'});
 await page.goto('/login');await page.getByPlaceholder('Email',{exact:true}).fill((role==='guest'?'outsider':role)+'@ui-parity.invalid');await page.getByPlaceholder('Password',{exact:true}).fill(password);await page.getByRole('button',{name:/^登\s*录$/}).click();await expect(page).toHaveURL(/\/group/);
 await page.goto('/project/'+p._id+'/interface/api/'+i._id);await page.getByRole('tab',{name:'编辑',exact:true}).click();const title=page.locator('#title');await title.fill('Synthetic unsaved title');const query=page.locator(info.project.name==='old'?'[id="req_query[0].example"]':'#req_query_0_example');await query.fill('unsaved query');
 const select=page.locator('.ant-form-item').filter({has:page.locator('label').filter({hasText:/^Tag$/})}).locator('.ant-select');
 await expect(select).toContainText('alpha');
 async function open(){await select.click();const button=page.getByRole('button',{name:'Tag设置',exact:true});await expect(button).toBeVisible();await page.waitForTimeout(350);const box=await button.boundingBox();await page.mouse.click(box.x+box.width/2,box.y+box.height/2);await expect(page.locator('.ant-modal:visible')).toBeVisible();await page.waitForTimeout(350);}
 const modal=page.locator('.ant-modal:visible');
 await open();await page.screenshot({path:info.outputPath('tag-modal-open.png')});await modal.getByPlaceholder('请输入 tag 名称').last().fill('cancelled');await modal.getByRole('button',{name:/取\s*消/}).click();await expect(modal).toHaveCount(0);await expect(title).toHaveValue('Synthetic unsaved title');
 const current=async()=> (await(await request.get('/api/project/get?id='+p._id)).json()).data.tag;
 expect((await current()).map(t=>t.name).sort()).toEqual(['alpha','beta']);
 await open();if(info.project.name==='new')await expect(modal.getByPlaceholder('请输入 tag 名称').filter({visible:true})).toHaveCount(3);await info.attach('cancel-reopen-draft',{body:JSON.stringify(await modal.getByPlaceholder('请输入 tag 名称').evaluateAll(es=>es.map(e=>e.value))),contentType:'application/json'});await modal.getByPlaceholder('请输入 tag 名称').last().fill('closed');await modal.locator('.ant-modal-close').click();await expect(modal).toHaveCount(0);expect((await current()).map(t=>t.name).sort()).toEqual(['alpha','beta']);await open();if(info.project.name==='new')await expect(modal.getByPlaceholder('请输入 tag 名称')).toHaveCount(3);await modal.getByPlaceholder('请输入 tag 名称').last().fill('escaped');await modal.getByPlaceholder('请输入 tag 名称').last().press('Escape');await expect(modal).toHaveCount(0);expect((await current()).map(t=>t.name).sort()).toEqual(['alpha','beta']);await open();if(info.project.name==='new')await expect(modal.getByPlaceholder('请输入 tag 名称')).toHaveCount(3);await modal.getByPlaceholder('请输入 tag 名称').last().fill('added');await modal.getByPlaceholder('请输入tag 描述信息').nth((await modal.getByPlaceholder('请输入 tag 名称').count())-2).fill('added description');
 const pending=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/project/up_tag');await modal.getByRole('button',{name:/^保\s*存$/}).click();const saved=await(await pending).json();
 if(role==='guest'){expect(saved.errcode).not.toBe(0);await expect(page.getByText(/没有权限/).first()).toBeVisible();expect((await current()).map(t=>t.name).sort()).toEqual(['alpha','beta']);if(info.project.name==='new'){await expect(modal).toBeVisible();await expect(modal.getByPlaceholder('请输入 tag 名称').nth(2)).toHaveValue('added');const retry=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/project/up_tag');await modal.getByRole('button',{name:/^保\s*存$/}).click();expect((await(await retry).json()).errcode).not.toBe(0);await expect(modal).toBeVisible();expect((await current()).map(t=>t.name).sort()).toEqual(['alpha','beta']);await modal.getByRole('button',{name:/取\s*消/}).click();}}
 else{expect(saved.errcode).toBe(0);await expect(page.getByText('保存成功').first()).toBeVisible();expect((await current()).some(t=>t.name==='added'&&t.desc==='added description')).toBe(true);}
 await expect(title).toHaveValue('Synthetic unsaved title');await expect(query).toHaveValue('unsaved query');await info.attach('persisted-tags',{body:JSON.stringify(await current()),contentType:'application/json'});await select.click();await expect(page.getByText('alpha',{exact:true}).first()).toBeVisible();if(role!=='guest')await expect(page.getByText('added',{exact:true}).last()).toBeVisible();await title.click();await open();if(role!=='guest'){await expect(modal.getByPlaceholder('请输入 tag 名称').filter({visible:true})).toHaveCount(info.project.name==='new'?4:7);}await modal.getByPlaceholder('请输入tag 描述信息').first().fill('discard description');await modal.getByRole('button',{name:/取\s*消/}).click();
 expect((await(await request.get('/api/interface/get?id='+i._id)).json()).data.title).toBe('Synthetic original title');
 await page.evaluate(()=>window.scrollTo(0,0));await page.screenshot({path:info.outputPath('tag-modal-unsaved-fields.png')});
 await page.reload();await page.getByRole('tab',{name:'编辑',exact:true}).click();await expect(title).toHaveValue('Synthetic original title');
 await expect(select).toContainText('alpha');await select.click();await page.locator('.ant-select-dropdown-menu-item, .ant-select-item-option').filter({hasText:/^beta$/}).click();await title.click();await expect(select).toContainText('beta');const chip=select.locator('.ant-select-selection__choice, .ant-select-selection-item').filter({hasText:'alpha'});await chip.locator('.ant-select-selection__choice__remove, .ant-select-selection-item-remove').click();await title.click();await expect(select).not.toContainText('alpha');
 const update=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/interface/up');await page.getByRole('button',{name:/^保\s*存$/}).click();const updated=await(await update).json();if(role==='guest'){expect(updated.errcode).not.toBe(0);await expect(page.getByText(/没有权限/).first()).toBeVisible();}else if(info.project.name==='old'){expect(updated.errcode).toBe(40011);await expect(page.getByText(updated.errmsg,{exact:true}).first()).toBeVisible();await info.attach('legacy-save-failed',{body:JSON.stringify({errcode:updated.errcode,errmsg:updated.errmsg}),contentType:'application/json'});}else{expect(updated.errcode).toBe(0);await expect(page.getByText('保存成功').first()).toBeVisible();}
 const persisted=(await(await request.get('/api/interface/get?id='+i._id)).json());expect(persisted.errcode).toBe(0);expect(persisted.data.tag).toEqual(role==='guest'?['alpha']:['beta']);await page.reload();await page.getByRole('tab',{name:'编辑',exact:true}).click();await expect(select).toContainText(role==='guest'?'alpha':'beta');
});
