const {test,expect}=require('@playwright/test');
async function setup(page,request,info,role,json5=false,body={}){
 page.setDefaultTimeout(12000);const password='SyntheticParityOnly_901000!';expect((await(await request.post('/api/user/login',{data:{email:'owner@ui-parity.invalid',password}})).json()).errcode).toBe(0);async function api(path,data){const result=await(await request.post(path,{data})).json();expect(result.errcode).toBe(0);return result.data;}
 const project=await api('/api/project/add',{name:'Synthetic body '+Date.now(),group_id:901000,project_type:'private'});await api('/api/project/up',{id:project._id,is_json5:json5});await api('/api/project/add_member',{id:project._id,member_uids:[910003],role:'dev'});await api('/api/project/add_member',{id:project._id,member_uids:[910004],role:'guest'});const cat=(await(await request.get('/api/interface/getCatMenu?project_id='+project._id)).json()).data[0];const item=await api('/api/interface/add',{project_id:project._id,catid:cat._id,title:'Synthetic body fixture',path:'/body',method:'POST',tag:[],req_body_type:'raw',req_body_other:'Synthetic request raw',req_body_is_json_schema:false,req_body_form:[{name:'hidden',type:'text',example:'stale',required:'1'}],res_body_type:'raw',res_body:'Synthetic response raw',res_body_is_json_schema:false,...body});await info.attach('body-fixture',{body:JSON.stringify({project:project._id,id:item._id,role,json5}),contentType:'application/json'});
 await page.goto('/login');await page.getByPlaceholder('Email',{exact:true}).fill((role==='guest'?'outsider':role)+'@ui-parity.invalid');await page.getByPlaceholder('Password',{exact:true}).fill(password);await page.getByRole('button',{name:/^登\s*录$/}).click();await expect(page).toHaveURL(/\/group/);await page.goto('/project/'+project._id+'/interface/api/'+item._id);await page.getByRole('tab',{name:'编辑',exact:true}).click();await expect(page.locator('#title')).toBeVisible();const read=async()=>{const r=await(await request.get('/api/interface/get?id='+item._id)).json();expect(r.errcode).toBe(0);return r.data;};const before=await read();const observations=[];
 async function save(){const wait=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/interface/up'&&r.request().method()==='POST');await expect(page.getByRole('button',{name:/^保\s*存$/})).toBeEnabled();await page.getByRole('button',{name:/^保\s*存$/}).click();const response=await wait,result=await response.json(),payload=response.request().postDataJSON(),after=await read();observations.push({result,payload,after});if(role==='guest'){expect(result.errcode).not.toBe(0);await expect(page.getByText(/没有权限/).first()).toBeVisible();for(const k of ['req_body_type','req_body_other','req_body_form','res_body_type','res_body'])expect(after[k]).toEqual(before[k]);}else if(info.project.name==='new'){expect(result.errcode).toBe(0);await expect(page.getByText('保存成功').first()).toBeVisible();}else{expect([0,40011]).toContain(result.errcode);await expect(page.getByText(result.errcode===0?'保存成功':'服务器出错...',{exact:true}).first()).toBeVisible();}return {result,payload,after};}
 return {project,item,api,read,before,save,observations};
}
function field(page,version,key){const id=version==='old'?key:key.replace(/[.\[\]]/g,'_').replace(/__+/g,'_').replace(/_$/,'');return page.locator('[id="'+id+'"]');}

for(const role of ['owner','developer','guest'])test('unsaved tab route Back Forward repeated prompt and editor cleanup '+role,async({page,request},info)=>{
 test.setTimeout(60000);const f=await setup(page,request,info,role,false,{title:'First synthetic record',desc:'<p>First note</p>',markdown:'First note'});const second=await f.api('/api/interface/add',{project_id:f.project._id,catid:f.item.catid,title:'Second synthetic record',path:'/second-record',method:'GET',desc:'<p>Second note</p>',markdown:'Second note'});await page.goto('/project/'+f.project._id+'/interface/api/'+second._id);await page.locator('a.interface-item').getByText('First synthetic record',{exact:true}).click();await page.getByRole('tab',{name:'编辑',exact:true}).click();const modal=page.locator('.ant-modal:visible'),title=page.locator('#title'),editable=page.locator('#desc [contenteditable=true]:visible');await title.fill('Unsaved first draft');await page.getByRole('tab',{name:'预览',exact:true}).first().click();await expect(modal).toHaveCount(1);await modal.getByRole('button',{name:/取\s*消/}).click();await expect(title).toHaveValue('Unsaved first draft');await page.locator('a.interface-item').getByText('Second synthetic record',{exact:true}).click();await expect(modal).toHaveCount(1);await modal.getByRole('button',{name:/取\s*消/}).click();await expect(title).toHaveValue('Unsaved first draft');
 const firstUrl=page.url();const back=page.goBack({timeout:3000}).catch(()=>null);await expect(modal).toHaveCount(1);const again=page.goBack({timeout:3000}).catch(()=>null);await page.waitForTimeout(150);await expect(modal).toHaveCount(1);await modal.getByRole('button',{name:/取\s*消/}).click();await Promise.all([back,again]);await expect(page).toHaveURL(firstUrl);await expect(title).toHaveValue('Unsaved first draft');
 const leave=page.goBack({timeout:3000}).catch(()=>null);await expect(modal).toHaveCount(1);await modal.getByRole('button',{name:/确\s*定/}).click();await leave;await expect(page).toHaveURL(new RegExp('/'+second._id+'$'));await expect(page.locator('#desc')).toHaveCount(0);await page.goForward();await expect(page).toHaveURL(firstUrl);await page.getByRole('tab',{name:'编辑',exact:true}).click();await expect(title).toHaveValue('First synthetic record');await expect(editable).toHaveText('First note');
 for(let n=0;n<2;n++){await page.locator('a.interface-item').getByText('Second synthetic record',{exact:true}).click();await page.getByRole('tab',{name:'编辑',exact:true}).click();await expect(editable).toHaveText('Second note');await expect(page.locator('#desc .tui-editor-defaultUI,#desc .toastui-editor-defaultUI')).toHaveCount(1);await page.locator('a.interface-item').getByText('First synthetic record',{exact:true}).click();await page.getByRole('tab',{name:'编辑',exact:true}).click();await expect(editable).toHaveText('First note');await expect(page.locator('#desc .tui-editor-defaultUI,#desc .toastui-editor-defaultUI')).toHaveCount(1);}
 expect((await f.read()).title).toBe('First synthetic record');await editable.scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath('unsaved-editor-cleanup.png')});await info.attach('unsaved-final',{body:JSON.stringify({id:f.item._id,second:second._id,role,after:await f.read()}),contentType:'application/json'});
});
for(const role of ['owner','developer','guest'])test('unsaved native reload close warning tracks dirty save and discard '+role,async({page,request},info)=>{
 const f=await setup(page,request,info,role,false,{title:'Reload original'});let warnings=0;page.on('dialog',async dialog=>{if(dialog.type()==='beforeunload')warnings++;await dialog.dismiss();});await page.locator('#title').fill('Reload draft');await page.reload({timeout:3000}).catch(()=>null);
 if(info.project.name==='old'&&warnings===0){await info.attach('legacy-native-warning',{body:JSON.stringify({id:f.item._id,status:'failed',warning:false}),contentType:'application/json'});expect((await f.read()).title).toBe('Reload original');return;}
 expect(warnings).toBe(1);await expect(page.locator('#title')).toHaveValue('Reload draft');const saved=await f.save();expect(saved.after.title).toBe(role==='guest'?'Reload original':'Reload draft');
 if(role==='guest'){await page.getByRole('tab',{name:'预览',exact:true}).first().click();await page.locator('.ant-modal:visible').getByRole('button',{name:/确\s*定/}).click();}
 const previous=warnings;await page.reload();expect(warnings).toBe(previous);await page.getByRole('tab',{name:'编辑',exact:true}).click();await page.locator('#title').fill('Close draft');await page.close({runBeforeUnload:true});await expect.poll(()=>warnings).toBe(previous+1);expect(page.isClosed()).toBe(false);await expect(page.locator('#title')).toHaveValue('Close draft');await page.getByRole('tab',{name:'预览',exact:true}).first().click();await page.locator('.ant-modal:visible').getByRole('button',{name:/确\s*定/}).click();await page.close({runBeforeUnload:true});await expect.poll(()=>page.isClosed()).toBe(true);expect(warnings).toBe(previous+1);await info.attach('native-warning-final',{body:JSON.stringify({id:f.item._id,role,warnings,after:await f.read()}),contentType:'application/json'});
});

for(const role of ['owner','developer','guest'])test('rich editor repeated clean mount switch and cleanup '+role,async({page,request},info)=>{
 const f=await setup(page,request,info,role,false,{title:'First clean record',desc:'<p>First note</p>',markdown:'First note'});
 const second=await f.api('/api/interface/add',{project_id:f.project._id,catid:f.item.catid,title:'Second clean record',path:'/second-clean',method:'GET',desc:'<p>Second note</p>',markdown:'Second note'});
 await page.reload();await page.getByRole('tab',{name:'编辑',exact:true}).click();
 for(let n=0;n<3;n++)for(const [title,note] of [['Second clean record','Second note'],['First clean record','First note']]){
  await page.locator('a.interface-item').getByText(title,{exact:true}).click();await page.getByRole('tab',{name:'编辑',exact:true}).click();
  await expect(page.locator('#desc [contenteditable=true]:visible')).toHaveText(note);await expect(page.locator('#desc .tui-editor-defaultUI,#desc .toastui-editor-defaultUI')).toHaveCount(1);await expect(page.locator('.ant-modal:visible')).toHaveCount(0);
 }
 expect((await f.read()).title).toBe('First clean record');await page.locator('#desc').scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath('clean-mount.png')});await info.attach('clean-mount-final',{body:JSON.stringify({id:f.item._id,second:second._id,role,after:await f.read()}),contentType:'application/json'});
});
for(const role of ['owner','developer','guest'])test('unsaved single Back Forward cancel confirm '+role,async({page,request},info)=>{
 test.setTimeout(60000);const f=await setup(page,request,info,role,false,{title:'First synthetic record',desc:'<p>First note</p>',markdown:'First note'});const second=await f.api('/api/interface/add',{project_id:f.project._id,catid:f.item.catid,title:'Second synthetic record',path:'/second-record',method:'GET',desc:'<p>Second note</p>',markdown:'Second note'});await page.goto('/project/'+f.project._id+'/interface/api/'+second._id);await page.locator('a.interface-item').getByText('First synthetic record',{exact:true}).click();await page.getByRole('tab',{name:'编辑',exact:true}).click();const modal=page.locator('.ant-modal:visible'),title=page.locator('#title'),editable=page.locator('#desc [contenteditable=true]:visible');await title.fill('Unsaved first draft');await page.getByRole('tab',{name:'预览',exact:true}).first().click();await expect(modal).toHaveCount(1);await modal.getByRole('button',{name:/取\s*消/}).click();await expect(title).toHaveValue('Unsaved first draft');await page.locator('a.interface-item').getByText('Second synthetic record',{exact:true}).click();await expect(modal).toHaveCount(1);await modal.getByRole('button',{name:/取\s*消/}).click();await expect(title).toHaveValue('Unsaved first draft');
 const firstUrl=page.url();const back=page.goBack({timeout:3000}).catch(()=>null);await expect(modal).toHaveCount(1);await modal.getByRole('button',{name:/取\s*消/}).click();await back;await expect(page).toHaveURL(firstUrl);await expect(title).toHaveValue('Unsaved first draft');
 const leave=page.goBack({timeout:3000}).catch(()=>null);await expect(modal).toHaveCount(1);await modal.getByRole('button',{name:/确\s*定/}).click();await leave;await expect(page).toHaveURL(new RegExp('/'+second._id+'$'));await expect(page.locator('#desc')).toHaveCount(0);await page.goForward();await expect(page).toHaveURL(firstUrl);await page.getByRole('tab',{name:'编辑',exact:true}).click();await expect(title).toHaveValue('First synthetic record');await expect(editable).toHaveText('First note');
 for(let n=0;n<2;n++){await page.locator('a.interface-item').getByText('Second synthetic record',{exact:true}).click();await page.getByRole('tab',{name:'编辑',exact:true}).click();await expect(editable).toHaveText('Second note');await expect(page.locator('#desc .tui-editor-defaultUI,#desc .toastui-editor-defaultUI')).toHaveCount(1);await page.locator('a.interface-item').getByText('First synthetic record',{exact:true}).click();await page.getByRole('tab',{name:'编辑',exact:true}).click();await expect(editable).toHaveText('First note');await expect(page.locator('#desc .tui-editor-defaultUI,#desc .toastui-editor-defaultUI')).toHaveCount(1);}
 expect((await f.read()).title).toBe('First synthetic record');await editable.scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath('unsaved-editor-cleanup.png')});await info.attach('unsaved-final',{body:JSON.stringify({id:f.item._id,second:second._id,role,after:await f.read()}),contentType:'application/json'});
});
