const {test,expect}=require('@playwright/test');
async function login(page,role){await page.goto('/login');await page.getByPlaceholder('Email',{exact:true}).fill(role+'@ui-parity.invalid');await page.getByPlaceholder('Password',{exact:true}).fill('SyntheticParityOnly_901000!');await page.getByRole('button',{name:/^登\s*录$/}).click();await expect(page).toHaveURL(/\/group/);}
for(const role of ['owner','developer'])test('bulk cancel reopen parse and query body isolation '+role,async({page},info)=>{
page.setDefaultTimeout(12000);await login(page,role);await page.goto('/project/901001/interface/api/901016');await page.getByRole('tab',{name:'编辑',exact:true}).click();
const text=page.getByPlaceholder('每行一个name:examples');
async function open(section){await page.waitForTimeout(400);await page.getByText(section,{exact:true}).click();await page.getByText('批量添加',{exact:true}).filter({visible:true}).click();await expect(text).toBeVisible();await page.waitForTimeout(350);}
await open('Query');const initial=await text.inputValue();await text.fill('discard:no');await page.getByRole('button',{name:/取\s*消/}).click();await open('Query');await expect(text).toHaveValue(initial);await page.locator('.ant-modal:visible .ant-modal-close').click();
if(info.project.name==='new'){await open('Query');await text.fill('\n\n');await page.getByRole('button',{name:/^导\s*入$/}).click();await open('Query');await expect(text).toHaveValue('');await text.fill(initial);await page.getByRole('button',{name:/^导\s*入$/}).click();}await open('Query');await text.fill('alpha:one:two\nbeta:中文\nmalformed\n\n');await page.getByRole('button',{name:/^导\s*入$/}).click();if(info.project.name==='new'){await expect(page.getByText('第 3 行格式错误，请输入 name:example，参数名称不能为空',{exact:true})).toBeVisible();await expect(text).toHaveValue('alpha:one:two\nbeta:中文\nmalformed\n\n');await page.getByRole('button',{name:/取\s*消/}).click();await open('Query');await expect(text).toHaveValue(initial);await text.fill('alpha:one:two\nbeta:中文\n\n');await page.getByRole('button',{name:/^导\s*入$/}).click();}await open('Query');await expect(text).toHaveValue('alpha:one:two\nbeta:中文\n');await page.getByRole('button',{name:/^导\s*入$/}).click();
await open('Body');await expect(text).not.toHaveValue('alpha:one:two\nbeta:中文\n');await text.fill('bodyOnly:three:four');await page.getByRole('button',{name:/^导\s*入$/}).click();
const pending=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname==='/api/interface/up');await page.getByRole('button',{name:/保\s*存/}).click();expect((await(await pending).json()).errcode).toBe(0);await expect(page.getByText('保存成功',{exact:false}).first()).toBeVisible();
const reply=await(await page.request.get('/api/interface/get?id=901016')).json();expect(reply.errcode).toBe(0);expect(reply.data.req_query.map(x=>[x.name,x.example])).toEqual([['alpha','one:two'],['beta','中文']]);expect(reply.data.req_body_form.map(x=>[x.name,x.example])).toEqual([['bodyOnly','three:four']]);await page.reload();await page.getByRole('tab',{name:'编辑',exact:true}).click();await open('Query');await expect(text).toHaveValue('alpha:one:two\nbeta:中文\n');await page.screenshot({path:info.outputPath('bulk-query.png'),fullPage:false});await page.getByRole('button',{name:/取\s*消/}).click();await open('Body');await expect(text).toHaveValue('bodyOnly:three:four\n');await page.getByRole('button',{name:/取\s*消/}).click();await expect(text).toBeHidden();await page.screenshot({path:info.outputPath('body-editor.png'),fullPage:false});
});
function field(page,version,key){if(key.startsWith('req_headers[')&&key.endsWith('.name'))return page.locator('.interface-edit-item-content:visible').nth(Number(key.match(/\[(\d+)\]/)[1])).locator('input').first();const id=version==='old'?key:key.replace(/[.\[\]]/g,'_').replace(/__+/g,'_').replace(/_$/,'');return page.locator('[id="'+id+'"]');}
for(const role of ['owner','developer'])test('parameter row add remove preserve values '+role,async({page},info)=>{
 page.setDefaultTimeout(12000);await login(page,role);const original=(await(await page.request.get('/api/interface/get?id=901016')).json()).data;const fixture={...original,title:'Synthetic rows '+role,path:'/rows-'+role+'-'+Date.now(),tag:[],req_query:[{name:'keep',example:'one',desc:'keep-desc',required:'0'}],req_headers:[{name:'Content-Type',value:'application/x-www-form-urlencoded',required:'1'}],req_body_form:[{name:'keepBody',type:'text',required:'1',example:'body-example',desc:'body-desc'}]};delete fixture._id;const added=await(await page.request.post('/api/interface/add',{data:fixture})).json();expect(added.errcode).toBe(0);const id=added.data._id;await info.attach('synthetic-id',{body:JSON.stringify({id}),contentType:'application/json'});await page.goto('/project/901001/interface/api/'+id);await page.getByRole('tab',{name:'编辑',exact:true}).click();
 for(const [tab,key,button,valKey]of [['Query','req_query','添加Query参数','example'],['Headers','req_headers','添加Header','value'],['Body','req_body_form','添加form参数','example']]){
  await page.getByText(tab,{exact:true}).click();await page.getByRole('button',{name:button,exact:true}).click();await field(page,info.project.name,key+'[1].name').fill('discard');await field(page,info.project.name,key+'[1].'+valKey).fill('discard-value');await page.getByRole('button',{name:button,exact:true}).click();await field(page,info.project.name,key+'[2].name').fill('survivor-'+key);await field(page,info.project.name,key+'[2].'+valKey).fill('survivor-value-'+key);await page.locator('.interface-edit-item-content:visible').nth(1).locator('.interface-edit-del-icon').click();await expect(field(page,info.project.name,key+'[1].name')).toHaveValue('survivor-'+key);await expect(field(page,info.project.name,key+'[1].'+valKey)).toHaveValue('survivor-value-'+key);
 }
 const pending=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname==='/api/interface/up');await page.getByRole('button',{name:/保\s*存/}).click();expect((await(await pending).json()).errcode).toBe(0);await expect(page.getByText('保存成功',{exact:false}).first()).toBeVisible();const saved=(await(await page.request.get('/api/interface/get?id='+id)).json()).data;
 for(const key of ['req_query','req_headers','req_body_form']){expect(saved[key]).toHaveLength(2);expect(saved[key][0].name).toBe(fixture[key][0].name);expect(saved[key][1].name).toBe('survivor-'+key);expect(saved[key][1][key==='req_headers'?'value':'example']).toBe('survivor-value-'+key);}
 await page.reload();await page.getByRole('tab',{name:'编辑',exact:true}).click();for(const[tab,key]of [['Query','req_query'],['Headers','req_headers'],['Body','req_body_form']]){await page.getByText(tab,{exact:true}).click();await expect(field(page,info.project.name,key+'[1].name')).toHaveValue('survivor-'+key);}await page.screenshot({path:info.outputPath('parameter-rows.png'),fullPage:false});
});
test('guest parameter save rejected and persisted rows unchanged',async({page,request},info)=>{
 page.setDefaultTimeout(12000);expect((await(await request.post('/api/user/login',{data:{email:'owner@ui-parity.invalid',password:'SyntheticParityOnly_901000!'}})).json()).errcode).toBe(0);const members=(await(await request.get('/api/project/get_member_list?id=901001')).json()).data;const existing=members.find(m=>m.uid===910004);if(existing){expect(existing.role).toBe('guest');}else{const member=await(await request.post('/api/project/add_member',{data:{id:901001,member_uids:[910004],role:'guest'}})).json();expect(member.errcode).toBe(0);}const before=(await(await request.get('/api/interface/get?id=901016')).json()).data;await login(page,'outsider');await page.goto('/project/901001/interface/api/901016');await page.getByRole('tab',{name:'编辑',exact:true}).click();await page.getByText('Query',{exact:true}).click();await field(page,info.project.name,'req_query[0].example').fill('denied-guest-change');await page.getByPlaceholder('/path',{exact:true}).fill('/form/{guestDenied}');await field(page,info.project.name,'req_params[0].desc').fill('denied path metadata');await page.getByText('Headers',{exact:true}).click();await field(page,info.project.name,'req_headers[0].value').fill('denied-header');await page.getByText('Body',{exact:true}).click();await field(page,info.project.name,'req_body_form[0].example').fill('denied-body');const pending=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname==='/api/interface/up');await page.getByRole('button',{name:/保\s*存/}).click();expect((await(await pending).json()).errcode).not.toBe(0);await expect(page.getByText('没有权限',{exact:false}).first()).toBeVisible();const after=(await(await request.get('/api/interface/get?id=901016')).json()).data;expect(after.path).toBe(before.path);expect(after.req_params).toEqual(before.req_params);expect(after.req_query).toEqual(before.req_query);expect(after.req_headers).toEqual(before.req_headers);expect(after.req_body_form).toEqual(before.req_body_form);await page.reload();await page.getByRole('tab',{name:'编辑',exact:true}).click();await page.getByText('Query',{exact:true}).click();await expect(field(page,info.project.name,'req_query[0].example')).toHaveValue(before.req_query[0].example);await page.screenshot({path:info.outputPath('guest-unchanged.png'),fullPage:false});
});
for(const role of ['owner','developer'])test('path rename and removal clears stale parameter metadata '+role,async({page},info)=>{
 page.setDefaultTimeout(12000);await login(page,role);const path='/path-rename-'+role+'-'+Date.now();const added=await(await page.request.post('/api/interface/add',{data:{project_id:901001,catid:901002,title:'Synthetic path rename '+role,path:path+'/{before}',method:'GET',tag:[],req_params:[{name:'before',desc:'before-desc',example:'before-example'}],res_body_type:'text',res_body:'ok'}})).json();expect(added.errcode).toBe(0);const id=added.data._id;await info.attach('synthetic-id',{body:JSON.stringify({id}),contentType:'application/json'});await page.goto('/project/901001/interface/api/'+id);await page.getByRole('tab',{name:'编辑',exact:true}).click();await page.getByPlaceholder('/path',{exact:true}).fill(path+'/{after}');await expect(field(page,info.project.name,'req_params[0].name')).toHaveValue('after');await field(page,info.project.name,'req_params[0].desc').fill('after-desc');await field(page,info.project.name,'req_params[0].example').fill('after-example');
 async function save(){const pending=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname==='/api/interface/up');await page.getByRole('button',{name:/保\s*存/}).click();expect((await(await pending).json()).errcode).toBe(0);await expect(page.getByText('保存成功',{exact:false}).first()).toBeVisible();return(await(await page.request.get('/api/interface/get?id='+id)).json()).data;}
 const renamed=await save();expect(renamed.req_params.map(({name,desc,example})=>({name,desc,example}))).toEqual([{name:'after',desc:'after-desc',example:'after-example'}]);await page.reload();await page.getByRole('tab',{name:'编辑',exact:true}).click();await expect(field(page,info.project.name,'req_params[0].name')).toHaveValue('after');await page.getByPlaceholder('/path',{exact:true}).fill(path);await expect(field(page,info.project.name,'req_params[0].name')).toHaveCount(0);expect((await save()).req_params).toEqual([]);await page.reload();await page.getByRole('tab',{name:'编辑',exact:true}).click();await expect(field(page,info.project.name,'req_params[0].name')).toHaveCount(0);await page.screenshot({path:info.outputPath('path-cleared.png'),fullPage:false});
});
