const {test,expect}=require('@playwright/test');
async function setup(page,request,info,role,json5=false,body={}){
 page.setDefaultTimeout(12000);const password='SyntheticParityOnly_901000!';expect((await(await request.post('/api/user/login',{data:{email:'owner@ui-parity.invalid',password}})).json()).errcode).toBe(0);async function api(path,data){const result=await(await request.post(path,{data})).json();expect(result.errcode).toBe(0);return result.data;}
 const project=await api('/api/project/add',{name:'Synthetic body '+Date.now(),group_id:901000,project_type:'private'});await api('/api/project/up',{id:project._id,is_json5:json5});await api('/api/project/add_member',{id:project._id,member_uids:[910003],role:'dev'});await api('/api/project/add_member',{id:project._id,member_uids:[910004],role:'guest'});const cat=(await(await request.get('/api/interface/getCatMenu?project_id='+project._id)).json()).data[0];const item=await api('/api/interface/add',{project_id:project._id,catid:cat._id,title:'Synthetic body fixture',path:'/body',method:'POST',tag:[],req_body_type:'raw',req_body_other:'Synthetic request raw',req_body_is_json_schema:false,req_body_form:[{name:'hidden',type:'text',example:'stale',required:'1'}],res_body_type:'raw',res_body:'Synthetic response raw',res_body_is_json_schema:false,...body});await info.attach('body-fixture',{body:JSON.stringify({project:project._id,id:item._id,role,json5}),contentType:'application/json'});
 await page.goto('/login');await page.getByPlaceholder('Email',{exact:true}).fill((role==='guest'?'outsider':role)+'@ui-parity.invalid');await page.getByPlaceholder('Password',{exact:true}).fill(password);await page.getByRole('button',{name:/^登\s*录$/}).click();await expect(page).toHaveURL(/\/group/);await page.goto('/project/'+project._id+'/interface/api/'+item._id);await page.getByRole('tab',{name:'编辑',exact:true}).click();await expect(page.locator('#title')).toBeVisible();const read=async()=>{const r=await(await request.get('/api/interface/get?id='+item._id)).json();expect(r.errcode).toBe(0);return r.data;};const before=await read();const observations=[];
 async function save(){const wait=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/interface/up'&&r.request().method()==='POST');await expect(page.getByRole('button',{name:/^保\s*存$/})).toBeEnabled();await page.getByRole('button',{name:/^保\s*存$/}).click();const response=await wait,result=await response.json(),payload=response.request().postDataJSON(),after=await read();observations.push({result,payload,after});if(role==='guest'){expect(result.errcode).not.toBe(0);await expect(page.getByText(/没有权限/).first()).toBeVisible();for(const k of ['req_body_type','req_body_other','req_body_form','res_body_type','res_body'])expect(after[k]).toEqual(before[k]);}else if(info.project.name==='new'){expect(result.errcode).toBe(0);await expect(page.getByText('保存成功').first()).toBeVisible();}else{expect([0,40011]).toContain(result.errcode);await expect(page.getByText(result.errcode===0?'保存成功':'服务器出错...',{exact:true}).first()).toBeVisible();}return {result,payload,after};}
 return {project,item,api,read,before,save,observations};
}

function link(page,name){return page.locator('a.interface-item').filter({hasText:new RegExp('^'+name+'$')});}
function selected(page,name){return link(page,name).locator('xpath=ancestor::*[contains(@class,"ant-tree-node-content-wrapper")][1]');}
async function seedNav(f,count=1){const ca=await f.api('/api/interface/add_cat',{project_id:f.project._id,name:'Nav Alpha',desc:'original category'}),cb=await f.api('/api/interface/add_cat',{project_id:f.project._id,name:'Nav Beta',desc:'second category'});const items=[];for(let n=1;n<=count;n++)items.push(await f.api('/api/interface/add',{project_id:f.project._id,catid:ca._id,title:'Alpha endpoint '+n,path:'/alpha-route-'+n,method:'GET',res_body_type:'json',res_body_is_json_schema:true,res_body:'{"type":"object","properties":{}}'}));const beta=await f.api('/api/interface/add',{project_id:f.project._id,catid:cb._id,title:'Beta endpoint',path:'/beta-route',method:'GET',res_body_type:'json',res_body_is_json_schema:true,res_body:'{"type":"object","properties":{}}'});return {ca,cb,items,beta};}
for(const role of ['owner','developer','guest'])test('tree search expand route highlight back and modal navigation '+role,async({page,request},info)=>{
 const f=await setup(page,request,info,role),n=await seedNav(f);await info.attach('navigation-fixture',{body:JSON.stringify({project:f.project._id,...n}),contentType:'application/json'});await page.goto('/project/'+f.project._id+'/interface/api');await link(page,'Nav Alpha').click();await expect(page).toHaveURL(new RegExp('/cat_'+n.ca._id+'$'));await expect(selected(page,'Nav Alpha')).toHaveClass(/ant-tree-node-selected/);await expect(link(page,'Alpha endpoint 1')).toBeVisible();
 const branch=info.project.name==='new'?page.locator('.ant-tree-treenode').filter({has:link(page,'Nav Alpha')}):link(page,'Nav Alpha').locator('xpath=ancestor::li[1]');await branch.locator('.ant-tree-switcher').first().click();await expect(link(page,'Alpha endpoint 1')).toBeHidden();await branch.locator('.ant-tree-switcher').first().click();await expect(link(page,'Alpha endpoint 1')).toBeVisible();
 const search=page.getByPlaceholder('搜索接口',{exact:true});await search.fill('Alpha endpoint');await expect(link(page,'Alpha endpoint 1')).toBeVisible();await expect(link(page,'Beta endpoint')).toHaveCount(0);await search.fill('/beta-route');await expect(link(page,'Beta endpoint')).toBeVisible();await expect(link(page,'Alpha endpoint 1')).toHaveCount(0);await search.fill('');await expect(link(page,'Nav Alpha')).toBeVisible();await expect(link(page,'Nav Beta')).toBeVisible();await link(page,'Nav Beta').click();await expect(selected(page,'Nav Beta')).toHaveClass(/ant-tree-node-selected/);const response=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/interface/get'&&new URL(r.url()).searchParams.get('id')===String(n.beta._id));await link(page,'Beta endpoint').click();expect((await(await response).json()).errcode).toBe(0);await expect(page).toHaveURL(new RegExp('/'+n.beta._id+'$'));await expect(selected(page,'Beta endpoint')).toHaveClass(/ant-tree-node-selected/);await page.goBack();await expect(page).toHaveURL(new RegExp('/cat_'+n.cb._id+'$'));await expect(selected(page,'Nav Beta')).toHaveClass(/ant-tree-node-selected/);
 const node=page.locator('.container-title').filter({has:link(page,'Nav Beta')});await node.hover();await node.locator('.anticon-edit').click();const modal=page.locator('.ant-modal:visible');await modal.getByPlaceholder('分类名称',{exact:true}).fill('discarded navigation draft');await page.goBack();await expect(page).toHaveURL(new RegExp('/cat_'+n.ca._id+'$'));if(info.project.name==='new')await expect(modal).toHaveCount(0);else if(await modal.count()){await info.attach('legacy-modal-survives-back',{body:JSON.stringify({status:'failed'}),contentType:'application/json'});await modal.getByRole('button',{name:/取\s*消/}).click();}await expect(selected(page,'Nav Alpha')).toHaveClass(/ant-tree-node-selected/);await page.locator('.item-all-interface').getByRole('link').click();const table=page.locator('.table-interfacelist');await table.getByRole('link',{name:'Alpha endpoint 1',exact:true}).click();await expect(page).toHaveURL(new RegExp('/'+n.items[0]._id+'$'));await page.goBack();await expect(page).toHaveURL(new RegExp('/interface/api$'));const url=page.url();await table.getByText('/alpha-route-1',{exact:true}).click();await expect(page).toHaveURL(url);await page.screenshot({path:info.outputPath('tree-table-navigation.png')});const cats=(await(await request.get('/api/interface/list_menu?project_id='+f.project._id)).json());expect(cats.errcode).toBe(0);expect(cats.data.find(x=>x._id===n.cb._id).name).toBe('Nav Beta');await info.attach('navigation-final',{body:JSON.stringify({project:f.project._id,menu:cats.data}),contentType:'application/json'});
});
for(const role of ['owner','developer','guest'])test('last category page recovers after moving final row '+role,async({page,request},info)=>{
 const f=await setup(page,request,info,role),n=await seedNav(f,21);await info.attach('pagination-fixture',{body:JSON.stringify({project:f.project._id,...n}),contentType:'application/json'});await page.goto('/project/'+f.project._id+'/interface/api/cat_'+n.ca._id);const table=page.locator('.table-interfacelist');await expect(table.locator('tbody tr')).toHaveCount(20);const listReply=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/interface/list_cat'&&new URL(r.url()).searchParams.get('page')==='2');await page.locator('.ant-pagination-item-2').click();expect((await(await listReply).json()).errcode).toBe(0);await expect(table.locator('tbody tr')).toHaveCount(1);const row=table.locator('tbody tr').first(),title=await row.getByRole('link').innerText(),moved=n.items.find(i=>i.title===title);expect(moved).toBeTruthy();await row.locator('.ant-select.path').click();const saved=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/interface/up'&&r.request().method()==='POST');await page.locator('.ant-select-dropdown:visible').getByText('Nav Beta',{exact:true}).last().click();const result=await(await saved).json();expect(result.errcode===0).toBe(role!=='guest');await expect(page.getByText(role==='guest'?/没有权限/:'修改成功').first()).toBeVisible();const current=(await(await request.get('/api/interface/get?id='+moved._id)).json());expect(current.errcode).toBe(0);expect(current.data.catid).toBe(role==='guest'?n.ca._id:n.cb._id);if(role!=='guest'){await expect(table.locator('tbody tr')).toHaveCount(20);await expect(table.getByRole('link',{name:title,exact:true})).toHaveCount(0);await expect(page.locator('.ant-pagination-item-1')).toHaveClass(/ant-pagination-item-active/);}else await expect(table.locator('tbody tr')).toHaveCount(1);await page.screenshot({path:info.outputPath('category-page-after-move.png')});await page.reload();await expect(table.locator('tbody tr')).toHaveCount(20);await info.attach('pagination-final',{body:JSON.stringify({id:moved._id,role,catid:current.data.catid,project:f.project._id}),contentType:'application/json'});
});
