const {test,expect}=require('@playwright/test');
async function setup(page,request,info){
 page.setDefaultTimeout(12000);const password='SyntheticParityOnly_901000!';expect((await(await request.post('/api/user/login',{data:{email:'owner@ui-parity.invalid',password}})).json()).errcode).toBe(0);async function api(path,data){const r=await(await request.post(path,{data})).json();expect(r.errcode).toBe(0);return r.data;}
 const projects=[];for(const n of [1,2])projects.push(await api('/api/project/add',{name:'Synthetic pending '+n+' '+Date.now(),group_id:901000,project_type:'private'}));const cats=[];for(const p of projects)cats.push((await(await request.get('/api/interface/getCatMenu?project_id='+p._id)).json()).data[0]);await info.attach('pending-fixture',{body:JSON.stringify({projects:projects.map(p=>p._id),cats:cats.map(c=>c._id)}),contentType:'application/json'});
 await page.goto('/login');await page.getByPlaceholder('Email',{exact:true}).fill('owner@ui-parity.invalid');await page.getByPlaceholder('Password',{exact:true}).fill(password);await page.getByRole('button',{name:/^登\s*录$/}).click();await expect(page).toHaveURL(/\/group/);
 const modal=page.locator('.ant-modal:visible');async function open(kind){await page.waitForTimeout(350);await page.mouse.move(1000,400);if(kind==='category')await page.getByRole('button',{name:'添加分类',exact:true}).click();else if(kind==='list')await page.getByRole('button',{name:'添加接口',exact:true}).click();else{const cat=page.locator('.container-title').filter({has:page.locator('a.interface-item').filter({hasText:/^公共分类$/})});await cat.hover();await cat.locator('.anticon-plus').click();}await expect(modal).toBeVisible();await page.waitForTimeout(250);}
 async function fill(kind,title,path='/pending'){await modal.getByPlaceholder(kind==='category'?'分类名称':'接口名称',{exact:true}).fill(title);if(kind!=='category')await modal.getByPlaceholder('/path',{exact:true}).fill(path);}
 const read=async index=>(await(await request.get('/api/interface/list_menu?project_id='+projects[index]._id)).json()).data;
 return {projects,cats,modal,open,fill,read};
}
for(const kind of ['menu','list','category'])test('pending '+kind+' blocks dismissal duplicate and retries transport failure',async({page,request},info)=>{
 test.skip(info.project.name==='old','Candidate lifecycle regression; legacy pending behavior retained as known gap.');const f=await setup(page,request,info);await page.goto('/project/'+f.projects[0]._id+'/interface/api');await f.open(kind);await f.fill(kind,'Pending first');let release;const gate=new Promise(r=>release=r),server=[];const endpoint='/api/interface/'+(kind==='category'?'add_cat':'add');await page.route('**'+endpoint,async route=>{const response=await route.fetch();server.push(await response.json());await gate;await route.fulfill({response});});const pending=page.waitForResponse(r=>new URL(r.url()).pathname===endpoint&&r.request().method()==='POST');await f.modal.getByRole('button',{name:/提\s*交/}).dblclick();await expect.poll(()=>server.length).toBe(1);expect(server[0].errcode).toBe(0);await expect(f.modal.getByRole('button',{name:/取\s*消/})).toBeDisabled();await expect(f.modal.locator('.ant-modal-close')).toHaveCount(0);await expect(f.modal.getByText(/正在提交|正在创建/)).toBeVisible();await page.keyboard.press('Escape');await page.mouse.click(10,500);await expect(f.modal).toBeVisible();await page.screenshot({path:info.outputPath('pending-dismiss-disabled.png')});release();expect((await(await pending).json()).errcode).toBe(0);await expect(f.modal).toHaveCount(0);await expect(page.getByText(kind==='category'?'接口分类添加成功':'接口添加成功').first()).toBeVisible();await page.unroute('**'+endpoint);
 if(kind!=='category')await page.goto('/project/'+f.projects[0]._id+'/interface/api');await f.open(kind);await f.fill(kind,'Pending retry','/retry');for(const failure of ['network','http']){await page.route('**'+endpoint,route=>failure==='network'?route.abort('failed'):route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({errcode:503,errmsg:'Synthetic pending unavailable'})}));await f.modal.getByRole('button',{name:/提\s*交/}).click();await expect(page.getByText(failure==='http'?'Synthetic pending unavailable':kind==='category'?'分类提交失败，请重试':'接口创建失败，请重试',{exact:true}).first()).toBeVisible();await expect(f.modal.getByRole('button',{name:/提\s*交/})).toBeEnabled();await expect(f.modal.getByRole('button',{name:/取\s*消/})).toBeEnabled();await page.unroute('**'+endpoint);}
 const retry=page.waitForResponse(r=>new URL(r.url()).pathname===endpoint&&r.request().method()==='POST');await f.modal.getByRole('button',{name:/提\s*交/}).click();expect((await(await retry).json()).errcode).toBe(0);await expect(f.modal).toHaveCount(0);const rows=await f.read(0);expect(kind==='category'?rows.filter(c=>c.name.startsWith('Pending')).length:rows.flatMap(c=>c.list).length).toBe(2);await info.attach('pending-final',{body:JSON.stringify(rows),contentType:'application/json'});
});
for(const kind of ['menu','list','category'])test('late '+kind+' completion cannot navigate or close another project draft',async({page,request},info)=>{
 test.skip(info.project.name==='old','Candidate route-generation regression.');const f=await setup(page,request,info);await page.goto('/group/901000');await page.getByRole('heading',{name:f.projects[0].name,exact:true}).click();await f.open(kind);await f.fill(kind,'Old completed create');let release;const gate=new Promise(r=>release=r),server=[];const endpoint='/api/interface/'+(kind==='category'?'add_cat':'add');await page.route('**'+endpoint,async route=>{const response=await route.fetch();server.push(await response.json());await gate;await route.fulfill({response});});const pending=page.waitForResponse(r=>new URL(r.url()).pathname===endpoint&&r.request().method()==='POST');await f.modal.getByRole('button',{name:/提\s*交/}).click();await expect.poll(()=>server.length).toBe(1);expect(server[0].errcode).toBe(0);await page.goBack();await expect(page).toHaveURL(/\/group\/901000$/);await page.getByRole('heading',{name:f.projects[1].name,exact:true}).click();await f.open(kind);await f.fill(kind,'New project untouched draft','/new-draft');release();expect((await(await pending).json()).errcode).toBe(0);await page.waitForTimeout(400);await expect(page).toHaveURL(new RegExp('/project/'+f.projects[1]._id+'/interface/api$'));await expect(f.modal).toBeVisible();await expect(f.modal.getByPlaceholder(kind==='category'?'分类名称':'接口名称',{exact:true})).toHaveValue('New project untouched draft');await expect(f.modal.getByRole('button',{name:/提\s*交/})).toBeEnabled();await f.modal.getByRole('button',{name:/取\s*消/}).click();const old=await f.read(0),next=await f.read(1);expect(kind==='category'?old.filter(c=>c.name==='Old completed create').length:old.flatMap(c=>c.list).length).toBe(1);expect(kind==='category'?next.length:next.flatMap(c=>c.list).length).toBe(kind==='category'?1:0);await info.attach('late-final',{body:JSON.stringify({old,next}),contentType:'application/json'});
});
