const {test,expect}=require('@playwright/test');
async function login(page,role){await page.goto('/login');await page.getByPlaceholder('Email',{exact:true}).fill(role+'@ui-parity.invalid');await page.getByPlaceholder('Password',{exact:true}).fill('SyntheticParityOnly_901000!');await page.getByRole('button',{name:/^登\s*录$/}).click();await expect(page).toHaveURL(/\/group/);}
for(const role of ['owner','developer','guest'])test('list status and tag filters combine and reset '+role,async({page,request},info)=>{
 page.setDefaultTimeout(12000);expect((await(await request.post('/api/user/login',{data:{email:'owner@ui-parity.invalid',password:'SyntheticParityOnly_901000!'}})).json()).errcode).toBe(0);
 async function api(path,data){const result=await(await request.post(path,{data})).json();expect(result.errcode).toBe(0);return result.data;}
 const project=await api('/api/project/add',{name:'Synthetic filters '+role+' '+Date.now(),group_id:901000,project_type:'private'});if(role!=='owner')await api('/api/project/add_member',{id:project._id,member_uids:[role==='guest'?910004:910003],role:role==='guest'?'guest':'dev'});const cats=(await(await request.get('/api/interface/getCatMenu?project_id='+project._id)).json()).data;const ids=[];
 for(const [title,status,tag] of [['Done review','done',['review']],['Undone review','undone',['review']],['Done synthetic','done',['synthetic']]])ids.push((await api('/api/interface/add',{project_id:project._id,catid:cats[0]._id,title,path:'/'+title.replaceAll(' ','-'),method:'GET',status,tag}))._id);
 await info.attach('fixture',{body:JSON.stringify({project:project._id,ids}),contentType:'application/json'});await login(page,role==='guest'?'outsider':role);await page.goto('/project/'+project._id+'/interface/api');const table=page.locator('.table-interfacelist');const rows=table.locator('tbody tr');await expect(rows).toHaveCount(3);
 async function filter(column,value,reset=false){const reply=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/interface/list');await table.locator('th').filter({hasText:column}).locator('.anticon-filter').click();const popup=page.locator('.ant-table-filter-dropdown:visible');await expect(popup).toBeVisible();if(reset)await popup.getByText('重置',{exact:true}).click();else await popup.getByText(value,{exact:true}).click();const ok=popup.getByText(/^确\s*定$/);if(await ok.isVisible())await ok.click();await expect(popup).toBeHidden();expect((await(await reply).json()).errcode).toBe(0);}
 await filter('状态','未完成');await expect(rows).toHaveCount(1);await expect(rows).toContainText('Undone review');await filter('tag','review');await expect(rows).toHaveCount(1);await filter('状态','',true);await expect(rows).toHaveCount(2);await filter('tag','',true);await expect(rows).toHaveCount(3);
 await expect(table.locator('tbody input[type="checkbox"]')).toHaveCount(0);await expect(table.locator('.ant-table-column-sorter')).toHaveCount(0);await page.evaluate(()=>window.scrollTo(0,0));await page.waitForTimeout(350);await page.screenshot({path:info.outputPath('list-filter-cleared.png')});
});
