const {test,expect}=require('@playwright/test');
async function login(page,role){await page.goto('/login');await page.getByPlaceholder('Email',{exact:true}).fill(role+'@ui-parity.invalid');await page.getByPlaceholder('Password',{exact:true}).fill('SyntheticParityOnly_901000!');await page.getByRole('button',{name:/^登\s*录$/}).click();await expect(page).toHaveURL(/\/group/);}
for(const role of ['owner','developer'])test('bulk cancel reopen parse and query body isolation '+role,async({page},info)=>{
page.setDefaultTimeout(12000);await login(page,role);await page.goto('/project/901001/interface/api/901016');await page.getByRole('tab',{name:'编辑',exact:true}).click();
const text=page.getByPlaceholder('每行一个name:examples');
async function open(section){await page.waitForTimeout(400);await page.getByText(section,{exact:true}).click();await page.getByText('批量添加',{exact:true}).filter({visible:true}).click();await expect(text).toBeVisible();await page.waitForTimeout(350);}
await open('Query');const initial=await text.inputValue();await text.fill('discard:no');await page.getByRole('button',{name:/取\s*消/}).click();await open('Query');await expect(text).toHaveValue(initial);await page.locator('.ant-modal:visible .ant-modal-close').click();
if(info.project.name==='new'){await open('Query');await text.fill('\n\n');await page.getByRole('button',{name:/^导\s*入$/}).click();await open('Query');await expect(text).toHaveValue('');await text.fill(initial);await page.getByRole('button',{name:/^导\s*入$/}).click();}await open('Query');await text.fill('alpha:one:two\nbeta:中文\nmalformed\n\n');await page.getByRole('button',{name:/^导\s*入$/}).click();if(info.project.name==='new'){await expect(page.getByText('第 3 行格式错误，请输入 name:example，参数名称不能为空',{exact:true})).toBeVisible();await expect(text).toHaveValue('alpha:one:two\nbeta:中文\nmalformed\n\n');await page.getByRole('button',{name:/取\s*消/}).click();await open('Query');await expect(text).toHaveValue(initial);await text.fill('alpha:one:two\nbeta:中文\n\n');await page.getByRole('button',{name:/^导\s*入$/}).click();}await open('Query');await expect(text).toHaveValue('alpha:one:two\nbeta:中文\n');await page.getByRole('button',{name:/^导\s*入$/}).click();
await open('Body');await expect(text).not.toHaveValue('alpha:one:two\nbeta:中文\n');await text.fill('bodyOnly:three:four');await page.getByRole('button',{name:/^导\s*入$/}).click();
const pending=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname==='/api/interface/up');await page.getByRole('button',{name:/保\s*存/}).click();expect((await(await pending).json()).errcode).toBe(0);await expect(page.getByText('保存成功',{exact:false}).first()).toBeVisible();
const reply=await(await page.request.get('/api/interface/get?id=901016')).json();expect(reply.errcode).toBe(0);expect(reply.data.req_query.map(x=>[x.name,x.example])).toEqual([['alpha','one:two'],['beta','中文']]);expect(reply.data.req_body_form.map(x=>[x.name,x.example])).toEqual([['bodyOnly','three:four']]);await page.reload();await page.getByRole('tab',{name:'编辑',exact:true}).click();await open('Query');await expect(text).toHaveValue('alpha:one:two\nbeta:中文\n');await page.screenshot({path:info.outputPath('bulk-query.png'),fullPage:false});await page.getByRole('button',{name:/取\s*消/}).click();await open('Body');await expect(text).toHaveValue('bodyOnly:three:four\n');await page.getByRole('button',{name:/取\s*消/}).click();await expect(text).toBeHidden();await page.screenshot({path:info.outputPath('body-editor.png'),fullPage:false});
});
