const {test,expect}=require('@playwright/test');

async function verifyRemarkDb(info,id,after){const {execFileSync}=require('node:child_process'),version=info.project.name;expect(['old','new']).toContain(version);expect(Number.isSafeInteger(id)).toBe(true);const script='db=db.getSiblingDB("parity_fast_interfaces_'+version+'");print(JSON.stringify(db.interface.findOne({_id:'+id+'},{_id:1,desc:1,markdown:1})));';const row=JSON.parse(execFileSync('docker',['exec','parity-fast-interfaces-mongo-'+version,version==='old'?'mongo':'mongosh','--quiet','--eval',script],{encoding:'utf8'}));expect(row.desc).toBe(after.desc);expect(row.markdown).toBe(after.markdown);await info.attach('remark-db-readback',{body:JSON.stringify(row),contentType:'application/json'});}

async function setup(page,request,info,role,json5=false,body={}){
 page.setDefaultTimeout(12000);const password='SyntheticParityOnly_901000!';expect((await(await request.post('/api/user/login',{data:{email:'owner@ui-parity.invalid',password}})).json()).errcode).toBe(0);async function api(path,data){const result=await(await request.post(path,{data})).json();expect(result.errcode).toBe(0);return result.data;}
 const project=await api('/api/project/add',{name:'Synthetic body '+Date.now(),group_id:901000,project_type:'private'});await api('/api/project/up',{id:project._id,is_json5:json5});await api('/api/project/add_member',{id:project._id,member_uids:[910003],role:'dev'});await api('/api/project/add_member',{id:project._id,member_uids:[910004],role:'guest'});const cat=(await(await request.get('/api/interface/getCatMenu?project_id='+project._id)).json()).data[0];const item=await api('/api/interface/add',{project_id:project._id,catid:cat._id,title:'Synthetic body fixture',path:'/body',method:'POST',tag:[],req_body_type:'raw',req_body_other:'Synthetic request raw',req_body_is_json_schema:false,req_body_form:[{name:'hidden',type:'text',example:'stale',required:'1'}],res_body_type:'raw',res_body:'Synthetic response raw',res_body_is_json_schema:false,...body});await info.attach('body-fixture',{body:JSON.stringify({project:project._id,id:item._id,role,json5}),contentType:'application/json'});
 await page.goto('/login');await page.getByPlaceholder('Email',{exact:true}).fill((role==='guest'?'outsider':role)+'@ui-parity.invalid');await page.getByPlaceholder('Password',{exact:true}).fill(password);await page.getByRole('button',{name:/^登\s*录$/}).click();await expect(page).toHaveURL(/\/group/);await page.goto('/project/'+project._id+'/interface/api/'+item._id);await page.getByRole('tab',{name:'编辑',exact:true}).click();await expect(page.locator('#title')).toBeVisible();const read=async()=>{const r=await(await request.get('/api/interface/get?id='+item._id)).json();expect(r.errcode).toBe(0);return r.data;};const before=await read();const observations=[];
 async function save(){const wait=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/interface/up'&&r.request().method()==='POST');await expect(page.getByRole('button',{name:/^保\s*存$/})).toBeEnabled();await page.getByRole('button',{name:/^保\s*存$/}).click();const response=await wait,result=await response.json(),payload=response.request().postDataJSON(),after=await read();observations.push({result,payload,after});if(role==='guest'){expect(result.errcode).not.toBe(0);await expect(page.getByText(/没有权限/).first()).toBeVisible();for(const k of ['req_body_type','req_body_other','req_body_form','res_body_type','res_body'])expect(after[k]).toEqual(before[k]);}else if(info.project.name==='new'){expect(result.errcode).toBe(0);await expect(page.getByText('保存成功').first()).toBeVisible();}else{expect([0,40011]).toContain(result.errcode);await expect(page.getByText(result.errcode===0?'保存成功':'服务器出错...',{exact:true}).first()).toBeVisible();}return {result,payload,after};}
 return {project,item,api,read,before,save,observations};
}



for(const role of ['owner','developer','guest'])test('remark table row column alignment remove and reload '+role,async({page,request},info)=>{
 const initial='<table><thead><tr><th>A</th><th>B</th></tr></thead><tbody><tr><td>One</td><td>Two</td></tr><tr><td>Three</td><td>Four</td></tr></tbody></table>';const f=await setup(page,request,info,role,false,{desc:initial,markdown:'',res_body_type:'json',res_body_is_json_schema:true,res_body:'{"type":"object","properties":{}}'}),editable=page.locator('#desc [contenteditable=true]:visible'),old=info.project.name==='old';
 async function action(oldName,newName){await editable.locator('td').first().click();await editable.locator('td').first().click({button:'right'});const menu=page.locator(old?'.te-popup-table-utils:visible':'.toastui-editor-context-menu:visible');await menu.getByText(old?oldName:newName,{exact:true}).click();}
 await expect(editable.locator('tr')).toHaveCount(3);await action('Add row','Add row to down');await expect(editable.locator('tr')).toHaveCount(4);await action('Add col','Add column to right');await expect(editable.locator('th')).toHaveCount(3);await action('Remove row','Remove row');await expect(editable.locator('tr')).toHaveCount(3);await action('Remove col','Remove column');await expect(editable.locator('th')).toHaveCount(2);
 for(const align of ['left','center','right']){await action('Align '+align,'Align column to '+align);await expect(editable.locator('td').first()).toHaveCSS('text-align',new RegExp('^(?:-webkit-)?'+align+'$'));}
 const saved=await f.save();await verifyRemarkDb(info,f.item._id,saved.after);await page.reload();await page.getByRole('tab',{name:'编辑',exact:true}).click();await expect(editable.locator('tr')).toHaveCount(3);if(role!=='guest')await expect(editable.locator('td').first()).toHaveCSS('text-align',/^(?:-webkit-)?right$/);else expect(saved.after.desc).toBe(initial);await editable.scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath('table-structure.png')});
 await action('Remove table','Remove table');await expect(editable.locator('table')).toHaveCount(0);const removed=await f.save();await verifyRemarkDb(info,f.item._id,removed.after);await page.reload();await page.getByRole('tab',{name:'编辑',exact:true}).click();await expect(editable.locator('table')).toHaveCount(role==='guest'?1:0);await info.attach('table-structure-final',{body:JSON.stringify({id:f.item._id,role,observations:f.observations}),contentType:'application/json'});
});
for(const role of ['owner','developer','guest'])test('remark list indent outdent and local image file '+role,async({page,request},info)=>{
 const f=await setup(page,request,info,role,false,{desc:'<p>Original structure note</p>',markdown:'Original structure note',res_body_type:'json',res_body_is_json_schema:true,res_body:'{"type":"object","properties":{}}'}),remark=page.locator('#desc'),editable=remark.locator('[contenteditable=true]:visible'),old=info.project.name==='old';
 await remark.getByText('Markdown',{exact:true}).click();const md=old?remark.locator('.CodeMirror textarea').first():remark.locator('.toastui-editor-md-container [contenteditable=true]');await md.focus();await page.keyboard.press('ControlOrMeta+A');await page.keyboard.insertText('- Parent\n- Child');await remark.getByText('WYSIWYG',{exact:true}).click();await editable.locator('li').last().click();const button=n=>remark.locator('button.'+(old?'tui-':'')+n);await button('indent').click();await expect(editable.locator('ul ul')).toHaveCount(1);await button('outdent').click();await expect(editable.locator('ul ul')).toHaveCount(0);await button('indent').click();await expect(editable.locator('ul ul')).toHaveCount(1);const saved=await f.save();await verifyRemarkDb(info,f.item._id,saved.after);await page.reload();await page.getByRole('tab',{name:'编辑',exact:true}).click();await expect(editable.locator('ul ul')).toHaveCount(role==='guest'?0:1);
 await editable.click();await page.keyboard.press('ControlOrMeta+End');await button('image').click();const popup=remark.locator(old?'.te-popup-add-image:visible':'.toastui-editor-popup-add-image:visible');await popup.getByText('File',{exact:true}).click();await popup.locator('input[type=file]').setInputFiles({name:'synthetic-pixel.png',mimeType:'image/png',buffer:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Y9ZlS8AAAAASUVORK5CYII=','base64')});await popup.locator(old?'.te-alt-text-input':'#toastuiAltTextInput').fill('Synthetic local pixel');await popup.getByRole('button',{name:'OK',exact:true}).click();await expect(editable.locator('img:not(.ProseMirror-separator)')).toHaveCount(1);const image=await f.save();await verifyRemarkDb(info,f.item._id,image.after);if(role!=='guest')expect(image.after.desc).toContain('data:image/png;base64,');await page.reload();await page.getByRole('tab',{name:'编辑',exact:true}).click();await expect(editable.locator('img:not(.ProseMirror-separator)')).toHaveCount(role==='guest'?0:1);await remark.scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath('list-file.png')});await info.attach('list-file-final',{body:JSON.stringify({id:f.item._id,role,observations:f.observations}),contentType:'application/json'});
});
for(const role of ['owner','developer','guest'])test('remark direct context targets clicked table without prior focus '+role,async({page,request},info)=>{
 const html='<p>Before tables</p><table><thead><tr><th>First</th></tr></thead><tbody><tr><td>First row</td></tr></tbody></table><p>Between tables</p><table><thead><tr><th>Second</th></tr></thead><tbody><tr><td>Second row</td></tr></tbody></table>';
 const f=await setup(page,request,info,role,false,{desc:html,markdown:'',res_body_type:'json',res_body_is_json_schema:true,res_body:'{"type":"object","properties":{}}'}),editable=page.locator('#desc [contenteditable=true]:visible'),old=info.project.name==='old',tables=editable.locator('table');
 async function addAt(index){await tables.nth(index).locator('td').first().click({button:'right'});await page.locator(old?'.te-popup-table-utils:visible':'.toastui-editor-context-menu:visible').getByText(old?'Add row':'Add row to down',{exact:true}).click();}
 await expect(tables).toHaveCount(2);await addAt(1);await expect(tables.nth(1).locator('tr')).toHaveCount(3);await expect(tables.nth(0).locator('tr')).toHaveCount(2);await tables.nth(0).locator('td').first().click();await addAt(1);await expect(tables.nth(1).locator('tr')).toHaveCount(4);await expect(tables.nth(0).locator('tr')).toHaveCount(2);const saved=await f.save();await verifyRemarkDb(info,f.item._id,saved.after);await page.reload();await page.getByRole('tab',{name:'编辑',exact:true}).click();await expect(tables.nth(1).locator('tr')).toHaveCount(role==='guest'?2:4);await expect(tables.nth(0).locator('tr')).toHaveCount(2);await editable.scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath('direct-context.png')});await info.attach('direct-context-final',{body:JSON.stringify({id:f.item._id,role,observations:f.observations}),contentType:'application/json'});
});
test('remark existing noncollapsed selection and keyboard menu remain unchanged',async({page,request},info)=>{
 const f=await setup(page,request,info,'owner',false,{desc:'<p>Intro</p><table><thead><tr><th>First</th></tr></thead><tbody><tr><td>SelectionKeep</td></tr></tbody></table><table><thead><tr><th>Second</th></tr></thead><tbody><tr><td>OtherCell</td></tr></tbody></table>',markdown:''}),editable=page.locator('#desc [contenteditable=true]:visible'),tables=editable.locator('table');await tables.first().locator('td').dblclick();const selected=await page.evaluate(()=>getSelection().toString());expect(selected).toContain('SelectionKeep');await page.keyboard.press('Shift+F10');expect(await page.evaluate(()=>getSelection().toString())).toBe(selected);await page.keyboard.press('Escape');await tables.nth(1).locator('td').click({button:'right'});expect(await page.evaluate(()=>getSelection().toString())).toBe(selected);await page.keyboard.press('Escape');expect((await f.read()).desc).toContain('SelectionKeep');await info.attach('selection-preserved',{body:JSON.stringify({selected,keyboardUnchanged:true,contextUnchanged:true}),contentType:'application/json'});
});
test('HTML-only remark initialization sanitizes and does not mark a clean draft dirty',async({page,request},info)=>{
 test.skip(info.project.name==='old','Candidate HTML parser integration safety');const f=await setup(page,request,info,'owner',false,{desc:'<p onclick="window.__syntheticRemarkClick=true">Synthetic safe text</p><a href="javascript:window.__syntheticRemarkClick=true">Safe link text</a>',markdown:''});const editable=page.locator('#desc [contenteditable=true]:visible');await expect(editable.locator('[onclick]')).toHaveCount(0);await expect(editable.locator('[href^="javascript:"]')).toHaveCount(0);await editable.getByText('Synthetic safe text',{exact:true}).click();expect(await page.evaluate(()=>window.__syntheticRemarkClick)).toBeUndefined();await page.getByRole('tab',{name:'预览',exact:true}).first().click();await expect(page.locator('.ant-modal:visible')).toHaveCount(0);expect((await f.read()).markdown).toBe('');
});
