const {test,expect}=require('@playwright/test');
test.beforeEach(async({page})=>page.setDefaultTimeout(12000));
async function api(page,url,data){const r= data===undefined?await page.request.get(url):await page.request.post(url,{data});expect(r.status(),url).toBe(200);const b=await r.json();expect(b.errcode,url).toBe(0);return b.data;}
async function login(page,role='owner'){await page.context().clearCookies();await page.goto('/login');await page.getByPlaceholder('Email',{exact:true}).fill(role+'@ui-parity.invalid');await page.getByPlaceholder('Password',{exact:true}).fill('SyntheticParityOnly_901000!');await page.getByRole('button',{name:/^登\s*录$/}).click();await expect(page).toHaveURL(/group/);}
async function setup(page,count=2){await login(page);const p=await api(page,'/api/project/add',{name:'Synthetic B closure '+Date.now(),group_id:901000,project_type:'private'});await api(page,'/api/project/up',{id:p._id,env:[{name:'local',domain:'http://127.0.0.1:3000/mock/'+p._id}]});const cat=(await api(page,'/api/interface/getCatMenu?project_id='+p._id))[0];const i=await api(page,'/api/interface/add',{project_id:p._id,catid:cat._id,title:'Closure source',path:'/closure',method:'GET'});await api(page,'/api/interface/up',{id:i._id,res_body_type:'json',res_body_is_json_schema:false,res_body:'{"code":0,"text":"合成测试"}',req_query:[{name:'first',required:'0',desc:'first',example:'one'},{name:'second',required:'0',desc:'second',example:'two'}]});const col=await api(page,'/api/col/add_col',{project_id:p._id,name:'Closure collection'});const cases=[];for(let n=0;n<count;n++)cases.push(await api(page,'/api/col/add_case',{project_id:p._id,col_id:col._id,interface_id:i._id,casename:'Closure case '+n}));const fixture={project:p._id,iface:i._id,col:col._id,cases};page.scopeBFixture=fixture;return fixture;}
async function saveResponse(page,path,action){const wait=page.waitForResponse(r=>new URL(r.url()).pathname===path);await action();const b=await(await wait).json();expect(b.errcode,path).toBe(0);return b.data;}
async function select(page,loc,text){await loc.scrollIntoViewIfNeeded();await loc.click();const input=loc.locator('input');if(await input.isEditable()){await input.fill(text);await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');}else{await page.locator('.ant-select-dropdown:visible .ant-select-item-option-content').getByText(text,{exact:true}).click();}await expect(loc).toContainText(text);}
async function ace(page,root,text){await expect(root).toBeVisible();await expect(root.locator('.ace_content')).toContainText('code');await root.locator('textarea').focus();await page.keyboard.press('Meta+A');await page.keyboard.insertText(text);await expect(root.locator('.ace_content')).toContainText(text);}




async function echoFixture(page){const {execFileSync}=require('node:child_process');const details=JSON.parse(execFileSync('docker',['inspect','parity-fast-collections-echo'],{encoding:'utf8'}))[0];const binding=details.NetworkSettings.Ports['3001/tcp'][0];expect(binding.HostIp).toBe('127.0.0.1');expect(details.Config.Cmd).toEqual(['node','/echo.cjs']);const mount=details.Mounts.find(m=>m.Destination==='/echo.cjs');expect(mount.RW).toBe(false);const fs=require('node:fs'),crypto=require('node:crypto');const digest=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');expect(digest(mount.Source)).toBe(digest(require('node:path').join(__dirname,'parity-collections-echo.cjs')));expect(fs.statSync(mount.Source).mtimeMs).toBeLessThanOrEqual(Date.parse(details.State.StartedAt));const origin='http://127.0.0.1:'+binding.HostPort;expect(await(await page.request.get(origin+'/fixture-identity')).json()).toEqual({fixture:'parity-fast-collections-echo',run:'fastb1003'});return origin;}
async function editor(page,text){const root=page.locator('.pretty-editor');await expect(root).toBeVisible();await root.locator('textarea').focus();await page.keyboard.press('Meta+A');await page.keyboard.insertText(text);await expect(root.locator('.ace_content')).toContainText(text);}

test('ordinary JSON raw and form bodies preserve method path query header required and optional values',async({page},info)=>{const f=await setup(page,0);await echoFixture(page);await api(page,'/api/project/up',{id:f.project,env:[{name:'echo',domain:'http://parity-fast-collections-echo:3001',header:[{name:'x-parity-synthetic',value:'fastb1003'}],global:[{name:'fromEnv',value:'environment-value'}]}]});const results=[];for(const [kind,method,contentType] of [['json','POST','application/json'],['raw','PUT','text/plain'],['form','PATCH','application/x-www-form-urlencoded']]){await api(page,'/api/interface/up',{id:f.iface,path:'/echo/{id}',method,req_body_type:kind,req_body_is_json_schema:false,req_body_other:kind==='json'?'{}':'',req_headers:[{name:'Content-Type',value:contentType,required:'1'},{name:'x-fixture',example:'initial',required:'1'}],req_params:[{name:'id'}],req_query:[{name:'required',required:'1',example:'must'},{name:'optional',required:'0',example:'omit'}],req_body_form:[{name:'first',type:'text',required:'1',example:'initial'},{name:'second',type:'text',required:'0',example:'omit'}]});await page.goto(`/project/${f.project}/interface/api/${f.iface}`);await page.getByText('运行',{exact:true}).click();await page.locator('#req_params_0').fill('path-123');await page.locator('#req_query_0').fill('required-value');await expect(page.locator('.key-value-wrap').filter({has:page.locator('#req_query_0')}).getByRole('checkbox')).toBeDisabled();await page.locator('.key-value-wrap').filter({has:page.locator('#req_query_1')}).getByRole('checkbox').uncheck();await page.locator('#req_headers_1').fill('header-value');if(kind==='json')await editor(page,'{"text":"合成正文","value":"{{ global.fromEnv }}"}');if(kind==='raw')await editor(page,'RAW 合成正文');if(kind==='form'){const rows=page.locator('.POST .key-value-wrap');await rows.nth(0).getByPlaceholder('参数值').fill('form-value');await expect(rows.nth(0).getByRole('checkbox')).toBeDisabled();await rows.nth(1).getByRole('checkbox').uncheck();}const returned=await saveResponse(page,'/api/interface/proxy',()=>page.getByRole('button',{name:/^发\s*送$/}).click());const echoed=returned.res.body;expect(echoed.method).toBe(method);expect(echoed.path).toBe('/echo/path-123');expect(echoed.query).toEqual({required:'required-value'});expect(echoed.header).toBe('header-value');if(kind==='json')expect(JSON.parse(echoed.body)).toEqual({text:'合成正文',value:'environment-value'});if(kind==='raw')expect(echoed.body).toBe('RAW 合成正文');if(kind==='form')expect(echoed.body).toBe('first=form-value');await expect(page.locator('.pretty-editor-body')).toContainText('parity-fast-collections-echo');results.push({kind,method,path:echoed.path,body:echoed.body});await page.screenshot({path:info.outputPath(kind+'-request.png'),animations:'disabled'});}await info.attach('body-roundtrips',{body:JSON.stringify(results),contentType:'application/json'});});

test('browser CORS success network error and JSON XML plain text response display',async({page},info)=>{const f=await setup(page,0);const browser=await echoFixture(page);await api(page,'/api/project/up',{id:f.project,env:[{name:'browser-echo',domain:browser,header:[{name:'x-parity-synthetic',value:'fastb1003'}]}]});for(const format of ['json','xml','text']){await api(page,'/api/interface/up',{id:f.iface,path:'/response',req_query:[{name:'format',required:'1',example:format}]});await page.goto(`/project/${f.project}/interface/api/${f.iface}`);await page.getByText('运行',{exact:true}).click();const toggle=page.getByRole('switch',{name:/服务端.*浏览器/});if(info.project.name==='new'){if(await toggle.getAttribute('aria-checked')==='true')await toggle.click();}else{const legacy=page.locator('.ant-switch').first();if((await legacy.getAttribute('class')).includes('ant-switch-checked'))await legacy.click();}await page.getByRole('button',{name:/^发\s*送$/}).click();await expect(page.locator('.res-code')).toContainText('200');await expect(page.locator('.pretty-editor-header')).toContainText('x-fixture-result');await expect(page.locator('.pretty-editor-body')).toContainText(format==='json'?'parity-fast-collections-echo':format==='xml'?'合成 XML':'Synthetic text 合成');await page.screenshot({path:info.outputPath(format+'-response.png'),animations:'disabled'});}await api(page,'/api/project/up',{id:f.project,env:[{name:'unreachable',domain:'http://127.0.0.1:1',header:[]}]});await page.reload();await page.getByText('运行',{exact:true}).click();await page.getByRole('button',{name:/^发\s*送$/}).click();await expect(page.locator('.pretty-editor-body')).toContainText(/CORS|Browser request failed|Network Error/);});
