const {test,expect}=require('@playwright/test');
test.beforeEach(async({page})=>page.setDefaultTimeout(12000));
async function api(page,url,data){const r= data===undefined?await page.request.get(url):await page.request.post(url,{data});expect(r.status(),url).toBe(200);const b=await r.json();expect(b.errcode,url).toBe(0);return b.data;}
async function login(page,role='owner'){await page.context().clearCookies();await page.goto('/login');await page.getByPlaceholder('Email',{exact:true}).fill(role+'@ui-parity.invalid');await page.getByPlaceholder('Password',{exact:true}).fill('SyntheticParityOnly_901000!');await page.getByRole('button',{name:/^登\s*录$/}).click();await expect(page).toHaveURL(/group/);}
async function setup(page,count=2){await login(page);const p=await api(page,'/api/project/add',{name:'Synthetic B closure '+Date.now(),group_id:901000,project_type:'private'});await api(page,'/api/project/up',{id:p._id,env:[{name:'local',domain:'http://127.0.0.1:3000/mock/'+p._id}]});const cat=(await api(page,'/api/interface/getCatMenu?project_id='+p._id))[0];const i=await api(page,'/api/interface/add',{project_id:p._id,catid:cat._id,title:'Closure source',path:'/closure',method:'GET'});await api(page,'/api/interface/up',{id:i._id,res_body_type:'json',res_body_is_json_schema:false,res_body:'{"code":0,"text":"合成测试"}',req_query:[{name:'first',required:'0',desc:'first',example:'one'},{name:'second',required:'0',desc:'second',example:'two'}]});const col=await api(page,'/api/col/add_col',{project_id:p._id,name:'Closure collection'});const cases=[];for(let n=0;n<count;n++)cases.push(await api(page,'/api/col/add_case',{project_id:p._id,col_id:col._id,interface_id:i._id,casename:'Closure case '+n}));const fixture={project:p._id,iface:i._id,col:col._id,cases};page.scopeBFixture=fixture;return fixture;}
async function saveResponse(page,path,action){const wait=page.waitForResponse(r=>new URL(r.url()).pathname===path);await action();const b=await(await wait).json();expect(b.errcode,path).toBe(0);return b.data;}
async function select(page,loc,text){await loc.scrollIntoViewIfNeeded();await loc.click();const input=loc.locator('input');if(await input.isEditable()){await input.fill(text);await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');}else{await page.locator('.ant-select-dropdown:visible .ant-select-item-option-content').getByText(text,{exact:true}).click();}await expect(loc).toContainText(text);}
async function ace(page,root,text){await expect(root).toBeVisible();await expect(root.locator('.ace_content')).toContainText('code');await root.locator('textarea').focus();await page.keyboard.press('Meta+A');await page.keyboard.insertText(text);await expect(root.locator('.ace_content')).toContainText(text);}



test('case editor reconciles changed source fields and missing source without stale controls',async({page},info)=>{const f=await setup(page,1);await api(page,'/api/interface/up',{id:f.iface,req_query:[{name:'replacement',required:'1',example:'new-source'}]});await page.goto(`/project/${f.project}/interface/case/${f.cases[0]._id}`);await expect(page.locator('#req_query_0')).toBeVisible();await expect(page.locator('input.key[value="replacement"]')).toBeVisible();expect((await api(page,'/api/col/case?caseid='+f.cases[0]._id)).req_query.map(x=>x.name)).toEqual(['replacement']);await expect(page.locator('#req_query_1')).toHaveCount(0);const errors=[];page.on('pageerror',e=>errors.push(e.message));await api(page,'/api/interface/del',{id:f.iface});await page.reload();await expect(page.getByText(/不存在的case|来源接口不存在|找不到对应的接口/).first()).toBeVisible();await expect(page.getByRole('button',{name:/更\s*新/})).toHaveCount(0);const link=page.getByRole('link',{name:'对应接口',exact:true});if(await link.count())expect(await link.getAttribute('href')).not.toContain('undefined');expect(errors).toEqual([]);await page.screenshot({path:info.outputPath('case-source-removed.png'),animations:'disabled'});});

test('late case load cannot overwrite next case name source link or environment',async({page},info)=>{const f=await setup(page,2);let release,started;const gate=new Promise(r=>release=r),entered=new Promise(r=>started=r);await page.route('**/api/col/case?caseid='+f.cases[0]._id,async r=>{const response=await r.fetch();started();await Promise.race([gate,new Promise(r=>setTimeout(r,30000))]);await r.fulfill({response});});await page.goto(`/project/${f.project}/interface/case/${f.cases[0]._id}`,{waitUntil:'domcontentloaded'});await entered;await page.locator('.menu-title[title="Closure case 1"]').click();await expect(page.locator('.edit-case-name input')).toHaveValue('Closure case 1');release();await page.waitForTimeout(500);await expect(page.locator('.edit-case-name input')).toHaveValue('Closure case 1');await expect(page.getByRole('link',{name:'对应接口',exact:true})).toHaveAttribute('href',`/project/${f.project}/interface/api/${f.iface}`);await page.screenshot({path:info.outputPath('case-late-load.png'),animations:'disabled'});});
