const {test,expect}=require('@playwright/test');
async function login(page,role='owner'){await page.goto('/login');await page.getByPlaceholder('Email',{exact:true}).fill(role+'@ui-parity.invalid');await page.getByPlaceholder('Password',{exact:true}).fill('SyntheticParityOnly_901000!');await page.getByRole('button',{name:/^登\s*录$/}).click();await expect(page).toHaveURL(/\/group/);}
async function response(page,path,action){const p=page.waitForResponse(r=>new URL(r.url()).pathname===path);await action();const r=await p;expect(r.status()).toBe(200);const b=await r.json();expect(b.errcode,JSON.stringify(b)).toBe(0);return b.data;}
async function fixture(page,info,kind){const b=await(await page.request.post('/api/project/add',{data:{name:'Synthetic '+kind+' '+info.project.name+' '+Date.now(),group_id:901000,project_type:'private',desc:'Synthetic UI acceptance only'}})).json();expect(b.errcode).toBe(0);await info.attach('fixture',{body:JSON.stringify({project:b.data._id,kind}),contentType:'application/json'});return b.data._id;}
async function choice(page,selector,text){await selector.click();await page.locator('.ant-select-dropdown:visible').getByText(text,{exact:true}).last().click();}
for(const role of ['owner','developer'])test('Wiki edit cancel reopen update and reload '+role,async({page},info)=>{
 page.setDefaultTimeout(10000);await login(page);const id=await fixture(page,info,'wiki');if(role==='developer'){expect((await(await page.request.post('/api/project/add_member',{data:{id,member_uids:[910003],role:'dev'}})).json()).errcode).toBe(0);await login(page,role);}
 const initial='SYNTHETIC_WIKI_BASE_'+role;expect((await(await page.request.post('/api/plugin/wiki_desc/up',{data:{project_id:id,desc:'<h2>'+initial+'</h2><table><tbody><tr><td>Table cell</td></tr></tbody></table><a href="https://example.invalid/">Reference</a>',markdown:'## '+initial,email_notice:false}})).json()).errcode).toBe(0);await page.goto('/project/'+id+'/wiki');await expect(page.getByRole('heading',{name:initial})).toBeVisible();await expect(page.locator('.wiki-view-content table')).toContainText('Table cell');await expect(page.locator('.wiki-view-content a[href="https://example.invalid/"]')).toHaveCount(1);
 await page.getByRole('button',{name:/编\s*辑/}).click();const editor=page.locator('[contenteditable=true]:visible').last();await expect(editor).toBeVisible();await editor.fill('Synthetic discarded wiki');await page.getByRole('button',{name:/取\s*消/}).click();await expect(page.getByRole('heading',{name:initial})).toBeVisible();await page.getByRole('button',{name:/编\s*辑/}).click();await expect(editor).toContainText(initial);await editor.fill('SYNTHETIC_WIKI_SAVED_'+role);await page.getByRole('checkbox',{name:'通知相关人员',exact:true}).uncheck();await response(page,'/api/plugin/wiki_desc/up',()=>page.getByRole('button',{name:/更\s*新/}).click());await page.reload();await expect(page.locator('.wiki-view-content')).toContainText('SYNTHETIC_WIKI_SAVED_'+role);await page.screenshot({path:info.outputPath('wiki-'+role+'.png'),fullPage:true});
});
for(const role of ['owner','developer'])test('project activity renders real log and detail dialog '+role,async({page},info)=>{
 page.setDefaultTimeout(9000);await login(page,role);await page.goto('/project/901001/activity');await expect(page.locator('.news-box')).toBeVisible();await expect(page.locator('.ant-timeline-item').first()).toBeVisible();const count=await page.locator('.ant-timeline-item').count();const detail=page.getByRole('button',{name:'改动详情',exact:true});if(await detail.count()){await detail.first().click();await expect(page.getByRole('dialog')).toBeVisible();await page.locator('.ant-modal-close').click();await expect(page.getByRole('dialog')).toHaveCount(0);await detail.first().click();await page.locator('.ant-modal-close').click();}await info.attach('activity-count',{body:JSON.stringify({count,details:await detail.count()}),contentType:'application/json'});await page.screenshot({path:info.outputPath('activity-'+role+'.png'),fullPage:true});
});
test('project members add role notification import cancel and delete',async({page},info)=>{
 page.setDefaultTimeout(10000);await login(page);const id=await fixture(page,info,'members');await page.goto('/project/'+id+'/members');await page.getByRole('button',{name:/添加成员$/}).click();const dialog=page.getByRole('dialog');await dialog.locator('.ant-select').first().locator('input').fill('Synthetic outsider');await page.locator('.ant-select-dropdown:visible').getByText('Synthetic outsider',{exact:true}).click();await choice(page,dialog.locator('.ant-select').last(),'访客');await response(page,'/api/project/add_member',()=>dialog.getByRole('button',{name:/确\s*定/}).click());const row=page.getByRole('row').filter({has:page.getByText('Synthetic outsider',{exact:true})});await expect(row).toContainText('访客');await response(page,'/api/project/change_member_role',()=>choice(page,row.locator('.ant-select'),'开发者'));await page.reload();await expect(row).toContainText('开发者');
 await page.getByRole('button',{name:/批量导入成员$/}).click();await choice(page,dialog.locator('.ant-select'),'Synthetic parity project');await dialog.getByRole('button',{name:/取\s*消/}).click();const members=(await(await page.request.get('/api/project/get_member_list?id='+id)).json()).data;await info.attach('members-after-cancel',{body:JSON.stringify(members),contentType:'application/json'});expect(members.filter(m=>m.uid===910003)).toHaveLength(0);
 await row.locator('button.btn-danger').click();await page.locator('body').click({position:{x:1000,y:800}});await expect(row).toBeVisible();await row.locator('button.btn-danger').click();await response(page,'/api/project/del_member',()=>page.getByRole('button',{name:/确\s*定/}).click());await expect(row).toHaveCount(0);await page.screenshot({path:info.outputPath('members.png'),fullPage:true});
});
for(const role of ['owner','developer'])test('Wiki Markdown update and repeated reload preserve content '+role,async({page},info)=>{
 page.setDefaultTimeout(12000);await login(page);const id=await fixture(page,info,'wiki');if(role==='developer'){expect((await(await page.request.post('/api/project/add_member',{data:{id,member_uids:[910003],role:'dev'}})).json()).errcode).toBe(0);await login(page,role);}await page.goto('/project/'+id+'/wiki');await page.getByRole('button',{name:/编\s*辑/}).click();await page.getByText('Markdown',{exact:true}).click();const text='# Synthetic Markdown '+info.project.name+'\n\n| Column |\n| --- |\n| Value |';
 if(info.project.name==='old'){const input=page.locator('#desc .CodeMirror textarea').first();await input.focus();await page.keyboard.press('Meta+A');await page.keyboard.insertText(text);}else{const editor=page.locator('.toastui-editor-md-container [contenteditable=true]');await editor.fill(text);}
 await page.getByRole('checkbox',{name:'通知相关人员',exact:true}).uncheck();const data=await response(page,'/api/plugin/wiki_desc/up',()=>page.getByRole('button',{name:/更\s*新/}).click());await page.reload();await expect(page.locator('.wiki-view-content')).toContainText('Synthetic Markdown '+info.project.name);await expect(page.locator('.wiki-view-content table')).toContainText('Value');await page.reload();await expect(page.locator('.wiki-view-content')).toContainText('Synthetic Markdown '+info.project.name);await page.screenshot({path:info.outputPath('wiki-markdown.png'),fullPage:true});
});

test('developer cannot create owner membership in isolated project',async({page,browser},info)=>{
 await login(page);const id=await fixture(page,info,'members');expect((await(await page.request.post('/api/project/add_member',{data:{id,member_uids:[910003],role:'dev'}})).json()).errcode).toBe(0);const c=await browser.newContext({baseURL:info.project.use.baseURL});try{const dev=await c.newPage();await login(dev,'developer');await dev.goto('/project/'+id+'/members');await expect(dev.getByRole('button',{name:/添加成员$/})).toHaveCount(0);const before=(await(await page.request.get('/api/project/get_member_list?id='+id)).json()).data;const result=await(await dev.request.post('/api/project/add_member',{data:{id,member_uids:[910004],role:'owner'}})).json();await info.attach('developer-owner-admission',{body:JSON.stringify({id,errcode:result.errcode}),contentType:'application/json'});if(info.project.name==='new'){expect(result.errcode).not.toBe(0);expect((await(await page.request.get('/api/project/get_member_list?id='+id)).json()).data).toEqual(before);}else expect(result.errcode).toBe(0);}finally{const members=(await(await page.request.get('/api/project/get_member_list?id='+id)).json()).data;if(members.some(m=>m.uid===910004))expect((await(await page.request.post('/api/project/del_member',{data:{id,member_uid:910004}})).json()).errcode).toBe(0);await c.close();}
});
