const {test,expect}=require('@playwright/test');
const {execFileSync}=require('node:child_process');
async function fixture(browser,request,info){
  const password='SyntheticParityOnly_901000!';expect((await(await request.post('/api/user/login',{data:{email:'owner@ui-parity.invalid',password}})).json()).errcode).toBe(0);
  async function api(path,data){const r=await(await request.post(path,{data})).json();expect(r.errcode).toBe(0);return r.data;}
  const project=await api('/api/project/add',{name:'Synthetic edit lease '+Date.now(),group_id:901000,project_type:'private'});
  await api('/api/project/add_member',{id:project._id,member_uids:[910003],role:'dev'});await api('/api/project/add_member',{id:project._id,member_uids:[910004],role:'guest'});
  const cat=(await(await request.get('/api/interface/getCatMenu?project_id='+project._id)).json()).data[0];const item=await api('/api/interface/add',{project_id:project._id,catid:cat._id,title:'Synthetic lock fixture',path:'/lock',method:'GET',tag:[],res_body_type:'json',res_body_is_json_schema:true,res_body:'{"type":"object","properties":{}}'});
  await info.attach('lock-fixture',{body:JSON.stringify({project:project._id,id:item._id}),contentType:'application/json'});const contexts=[];
  const query=script=>JSON.parse(execFileSync('docker',['exec','parity-fast-interfaces-mongo-'+info.project.name,info.project.name==='old'?'mongo':'mongosh','--quiet','--eval','db=db.getSiblingDB('+JSON.stringify('parity_fast_interfaces_'+info.project.name)+');'+script],{encoding:'utf8'}));
  const lock=()=>query('var r=db.interface.findOne({_id:'+item._id+'},{edit_uid:1,edit_lock_expires_at:1,edit_lock_token:1});r.lease=!!r.edit_lock_token;delete r.edit_lock_token;print(JSON.stringify(r));');
  async function client(role,edit=true,route,init){const context=await browser.newContext({baseURL:info.project.use.baseURL,viewport:{width:1920,height:1080}});contexts.push(context);const page=await context.newPage();page.setDefaultTimeout(12000);if(init)await page.addInitScript(init);if(route)await page.routeWebSocket('**/api/interface/solve_conflict*',route);await page.goto('/login');await page.getByPlaceholder('Email',{exact:true}).fill(role+'@ui-parity.invalid');await page.getByPlaceholder('Password',{exact:true}).fill(password);await page.getByRole('button',{name:/^登\s*录$/}).click();await expect(page).toHaveURL(/\/group/);await page.goto('/project/'+project._id+'/interface/api/'+item._id);if(edit)await page.getByRole('tab',{name:'编辑',exact:true}).click();return page;}
  return {api,project,item,client,lock,query,close:async()=>{for(const c of contexts)await c.close();}};
}
const blocked=page=>page.getByText('正在编辑该接口，请稍后再试...',{exact:true});
test('rejected same-user and guest windows cannot release owner lease',async({browser,request},info)=>{
 const f=await fixture(browser,request,info),states={};try{
  const guest=await f.client('outsider');await expect(guest.locator('#title')).toBeVisible();states.guest=f.lock();expect(states.guest.edit_uid).toBe(info.project.name==='new'?0:910004);if(info.project.name==='new')await expect(guest.getByText('没有编辑权限，保存将被拒绝。',{exact:true})).toBeVisible();await guest.close();await expect.poll(()=>f.lock().edit_uid).toBe(0);
  const owner=await f.client('owner');await expect(owner.locator('#title')).toBeVisible();states.owner=f.lock();expect(states.owner.edit_uid).toBe(910002);
  const denied=await f.client('developer');await expect(blocked(denied)).toBeVisible();await expect(denied.locator('#title')).toHaveCount(0);await denied.screenshot({path:info.outputPath('second-editor-blocked.png')});await denied.close();await expect.poll(()=>f.lock().edit_uid).toBe(info.project.name==='new'?910002:0);states.afterDeniedClose=f.lock();
  if(info.project.name==='old'){const third=await f.client('developer');await expect(third.locator('#title')).toBeVisible();states.third=f.lock();await info.attach('legacy-lock-defect',{body:JSON.stringify(states),contentType:'application/json'});return;}
  const same=await f.client('owner');await expect(blocked(same)).toBeVisible();await same.close();expect(f.lock().edit_uid).toBe(910002);const readonly=await f.client('outsider');await expect(readonly.locator('#title')).toBeVisible();await readonly.close();expect(f.lock().edit_uid).toBe(910002);
  const result=(await(await request.get('/api/interface/get?id='+f.item._id)).json());expect(result.errcode).toBe(0);expect(result.data).not.toHaveProperty('edit_lock_token');expect(result.data).not.toHaveProperty('edit_lock_expires_at');const listed=await(await request.get('/api/interface/list?project_id='+f.project._id+'&page=1&limit=10')).json();expect(listed.errcode).toBe(0);expect(JSON.stringify(listed.data)).not.toContain('edit_lock_token');expect(JSON.stringify(listed.data)).not.toContain('edit_lock_expires_at');
  await owner.close();await expect.poll(()=>f.lock().edit_uid).toBe(0);const next=await f.client('developer');await expect(next.locator('#title')).toBeVisible();expect(f.lock().edit_uid).toBe(910003);await next.screenshot({path:info.outputPath('next-owner-after-close.png')});await next.close();await expect.poll(()=>f.lock().edit_uid).toBe(0);await info.attach('lock-db-states',{body:JSON.stringify(states),contentType:'application/json'});
 }finally{await f.close();}
});
test('simultaneous same-user claims grant one connection',async({browser,request},info)=>{
 test.skip(info.project.name==='old','Legacy same-uid connections are not connection-owned leases.');const f=await fixture(browser,request,info);try{const a=await f.client('owner',false),b=await f.client('owner',false);await Promise.all([a.getByRole('tab',{name:'编辑',exact:true}).click(),b.getByRole('tab',{name:'编辑',exact:true}).click()]);await expect.poll(async()=> (await a.locator('#title').count())+(await b.locator('#title').count())).toBe(1);await expect.poll(async()=> (await blocked(a).count())+(await blocked(b).count())).toBe(1);const winner=await a.locator('#title').count()?a:b,loser=winner===a?b:a;await loser.close();expect(f.lock().edit_uid).toBe(910002);await expect(winner.locator('#title')).toBeVisible();await winner.close();await expect.poll(()=>f.lock().edit_uid).toBe(0);}finally{await f.close();}
});
test('disconnect preserves draft blocks save and reconnect acquires fresh lease',async({browser,request},info)=>{
 test.skip(info.project.name==='old','Candidate lease-loss feedback regression.');const f=await fixture(browser,request,info);try{const owner=await f.client('owner',true,undefined,()=>{const Native=window.WebSocket;window.parityEditSockets=[];window.WebSocket=class extends Native{constructor(...args){super(...args);if(String(args[0]).includes('/api/interface/solve_conflict'))window.parityEditSockets.push(this);}};});await expect(owner.locator('#title')).toBeVisible();await owner.locator('#title').fill('Unsaved disconnected draft');await owner.evaluate(()=>window.parityEditSockets.forEach(socket=>socket.close(1000,'synthetic disconnect')));await expect(owner.getByText(/协作连接已断开/)).toBeVisible();await expect(owner.getByRole('button',{name:/^保\s*存$/})).toBeDisabled();await expect(owner.locator('#title')).toHaveValue('Unsaved disconnected draft');await expect.poll(()=>f.lock().edit_uid).toBe(0);await owner.screenshot({path:info.outputPath('disconnected-draft-retained.png')});await owner.close();const again=await f.client('owner');await expect(again.locator('#title')).toHaveValue('Synthetic lock fixture');await again.locator('#title').fill('Reconnected saved title');const pending=again.waitForResponse(r=>new URL(r.url()).pathname==='/api/interface/up'&&r.request().method()==='POST');await again.getByRole('button',{name:/^保\s*存$/}).click();expect((await(await pending).json()).errcode).toBe(0);await expect(again.getByText('保存成功').first()).toBeVisible();expect(f.query('print(JSON.stringify(db.interface.findOne({_id:'+f.item._id+'},{title:1})))').title).toBe('Reconnected saved title');}finally{await f.close();}
});
test('expired takeover and late close keep new owner plus legacy data recovery',async({browser,request},info)=>{
 test.skip(info.project.name==='old','Candidate atomic expiring lease regression.');const f=await fixture(browser,request,info);try{const old=await f.client('owner');await expect(old.locator('#title')).toBeVisible();f.query('db.interface.updateOne({_id:'+f.item._id+'},{$set:{edit_lock_expires_at:0}});print(JSON.stringify({ok:true}));');const next=await f.client('developer');await expect(next.locator('#title')).toBeVisible();expect(f.lock().edit_uid).toBe(910003);await old.close();expect(f.lock().edit_uid).toBe(910003);await next.close();await expect.poll(()=>f.lock().edit_uid).toBe(0);f.query('db.interface.updateOne({_id:'+f.item._id+'},{$set:{edit_uid:910002},$unset:{edit_lock_token:"",edit_lock_expires_at:""}});print(JSON.stringify({ok:true}));');const recovered=await f.client('developer');await expect(recovered.locator('#title')).toBeVisible();expect(f.lock().edit_uid).toBe(910003);expect(f.lock().lease).toBe(true);}finally{await f.close();}
});
test('real pong renews lease and revoked developer loses lock without losing draft',async({browser,request},info)=>{
 test.skip(info.project.name==='old','Candidate live lease authorization regression.');const f=await fixture(browser,request,info);try{const dev=await f.client('developer');await expect(dev.locator('#title')).toBeVisible();const initial=f.lock();await expect.poll(()=>f.lock().edit_lock_expires_at,{timeout:23000,intervals:[1000]}).toBeGreaterThan(initial.edit_lock_expires_at);await dev.locator('#title').fill('Revoked unsaved draft');await f.api('/api/project/del_member',{id:f.project._id,member_uid:910003});await expect.poll(()=>f.lock().edit_uid,{timeout:23000,intervals:[1000]}).toBe(0);await expect(dev.getByRole('button',{name:/^保\s*存$/})).toBeDisabled();await expect(dev.locator('#title')).toHaveValue('Revoked unsaved draft');await expect(dev.getByText(/编辑权限已失效|协作连接已断开/).first()).toBeVisible();await dev.screenshot({path:info.outputPath('revoked-draft-retained.png')});}finally{await f.close();}
});
test('server crash leaves bounded lease and restart recovers after expiry',async({browser,request},info)=>{
 test.skip(info.project.name==='old','Legacy lock has no expiry; do not disrupt old runtime.');const f=await fixture(browser,request,info);try{const owner=await f.client('owner');await expect(owner.locator('#title')).toBeVisible();const before=f.lock();expect(before.edit_lock_expires_at-Date.now()).toBeLessThanOrEqual(45000);execFileSync('docker',['kill','--signal','KILL','parity-fast-interfaces-new']);execFileSync('docker',['start','parity-fast-interfaces-new']);await expect.poll(async()=>{try{return (await(await request.get('/api/interface/get?id='+f.item._id)).json()).errcode;}catch(_){return -1;}},{timeout:15000}).toBe(0);expect(f.lock().edit_uid).toBe(910002);const denied=await f.client('developer');await expect(blocked(denied)).toBeVisible();await denied.close();expect(f.lock().edit_uid).toBe(910002);await expect.poll(()=>Date.now(),{timeout:50000,intervals:[1000]}).toBeGreaterThan(before.edit_lock_expires_at);const recovered=await f.client('developer');await expect(recovered.locator('#title')).toBeVisible();expect(f.lock().edit_uid).toBe(910003);await info.attach('crash-recovery',{body:JSON.stringify({before,after:f.lock()}),contentType:'application/json'});}finally{await f.close();}
});
for(const failure of ['close','timeout'])test('initial collaboration '+failure+' is explicit and does not grant editing',async({browser,request},info)=>{
 test.skip(info.project.name==='old','Candidate explicit collaboration failure regression.');const f=await fixture(browser,request,info);try{const failed=await f.client('owner',true,ws=>{if(failure==='close')ws.close({code:1013,reason:'synthetic unavailable'});});await expect(failed.getByText(failure==='close'?/协作连接已断开/:/协作连接超时/)).toBeVisible();await expect(failed.locator('#title')).toHaveCount(0);expect(f.lock().edit_uid).toBe(0);await failed.screenshot({path:info.outputPath('initial-collaboration-failure.png')});await failed.close();const recovered=await f.client('owner');await expect(recovered.locator('#title')).toBeVisible();expect(f.lock().edit_uid).toBe(910002);}finally{await f.close();}
});
