const {test,expect}=require('@playwright/test');
test.beforeEach(async({page})=>page.setDefaultTimeout(12000));
async function api(page,url,data){const r= data===undefined?await page.request.get(url):await page.request.post(url,{data});expect(r.status(),url).toBe(200);const b=await r.json();expect(b.errcode,url).toBe(0);return b.data;}
async function login(page,role='owner'){await page.context().clearCookies();await page.goto('/login');await page.getByPlaceholder('Email',{exact:true}).fill(role+'@ui-parity.invalid');await page.getByPlaceholder('Password',{exact:true}).fill('SyntheticParityOnly_901000!');await page.getByRole('button',{name:/^登\s*录$/}).click();await expect(page).toHaveURL(/group/);}
async function setup(page,count=2){await login(page);const p=await api(page,'/api/project/add',{name:'Synthetic B closure '+Date.now(),group_id:901000,project_type:'private'});await api(page,'/api/project/up',{id:p._id,env:[{name:'local',domain:'http://127.0.0.1:3000/mock/'+p._id}]});const cat=(await api(page,'/api/interface/getCatMenu?project_id='+p._id))[0];const i=await api(page,'/api/interface/add',{project_id:p._id,catid:cat._id,title:'Closure source',path:'/closure',method:'GET'});await api(page,'/api/interface/up',{id:i._id,res_body_type:'json',res_body_is_json_schema:false,res_body:'{"code":0,"text":"合成测试"}',req_query:[{name:'first',required:'0',desc:'first',example:'one'},{name:'second',required:'0',desc:'second',example:'two'}]});const col=await api(page,'/api/col/add_col',{project_id:p._id,name:'Closure collection'});const cases=[];for(let n=0;n<count;n++)cases.push(await api(page,'/api/col/add_case',{project_id:p._id,col_id:col._id,interface_id:i._id,casename:'Closure case '+n}));const fixture={project:p._id,iface:i._id,col:col._id,cases};page.scopeBFixture=fixture;return fixture;}
async function saveResponse(page,path,action){const wait=page.waitForResponse(r=>new URL(r.url()).pathname===path);await action();const b=await(await wait).json();expect(b.errcode,path).toBe(0);return b.data;}
async function select(page,loc,text){await loc.scrollIntoViewIfNeeded();await loc.click();const input=loc.locator('input');if(await input.isEditable()){await input.fill(text);await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');}else{await page.locator('.ant-select-dropdown:visible .ant-select-item-option-content').getByText(text,{exact:true}).click();}await expect(loc).toContainText(text);}
async function ace(page,root,text){await expect(root).toBeVisible();await expect(root.locator('.ace_content')).toContainText('code');await root.locator('textarea').focus();await page.keyboard.press('Meta+A');await page.keyboard.insertText(text);await expect(root.locator('.ace_content')).toContainText(text);}



test('token automation executes imported public source environment and denies private source',async({page},info)=>{test.skip(info.project.name==='old','target-owned imported-case authorization contract');const f=await setup(page,0);const source=await api(page,'/api/project/add',{name:'Automation source '+Date.now(),group_id:901000,project_type:'public'});await api(page,'/api/project/up',{id:source._id,project_type:'public',env:[{name:'source-local',domain:'http://127.0.0.1:3000/mock/'+source._id}]});const cat=(await api(page,'/api/interface/getCatMenu?project_id='+source._id))[0];const endpoint=await api(page,'/api/interface/add',{project_id:source._id,catid:cat._id,title:'Automation public source',path:'/source',method:'GET'});await api(page,'/api/interface/up',{id:endpoint._id,res_body_type:'json',res_body_is_json_schema:false,res_body:'{"code":0,"text":"自动化来源"}'});const record=await api(page,'/api/col/add_case',{project_id:f.project,col_id:f.col,interface_id:endpoint._id,casename:'Token source case'});await api(page,'/api/col/up_col',{col_id:f.col,checkHttpCodeIs200:true});await page.goto(`/project/${f.project}/interface/col/${f.col}`);await expect(page.getByRole('cell',{name:'Token source case',exact:true})).toBeVisible();await page.getByRole('button',{name:'服务端测试',exact:true}).click();const d=page.getByRole('dialog');await d.getByText('选择测试用例环境',{exact:true}).click();await d.locator('.case-env .ant-select').click();await page.locator('.ant-select-dropdown:visible').getByText(/^source-local:/).last().click();await d.locator('.ant-select').last().click();await page.locator('.ant-select-dropdown:visible').getByText('json',{exact:true}).last().click();const url=new URL(await d.locator('.autoTestUrl a').getAttribute('href'),info.project.use.baseURL);expect(url.searchParams.get('env_'+source._id)).toContain('source-local');url.searchParams.set('email','false');const r=await(await page.request.get(url.href)).json();expect(r.numbs).toBe(1);expect(r.list[0].id).toBe(record._id);expect(r.list[0].code).toBe(0);expect(r.list[0].res_body).toEqual({code:0,text:'自动化来源'});expect(r.list[0].url).toContain('/mock/'+source._id+'/source');await page.screenshot({path:info.outputPath('token-source-environment.png'),mask:[d.locator('.autoTestUrl')],animations:'disabled'});await api(page,'/api/project/up',{id:source._id,project_type:'private'});const denied=await(await page.request.get(url.href)).json();expect(denied.errcode).toBe(403);expect(denied.data).toBeNull();await info.attach('token-source-summary',{body:JSON.stringify({target:f.project,source:source._id,case:record._id,successCode:r.list[0].code,privateSource:denied.errcode}),contentType:'application/json'});});

