const {test,expect}=require('@playwright/test');
async function setup(page,request,info,role,json5=false,body={}){
 page.setDefaultTimeout(12000);const password='SyntheticParityOnly_901000!';expect((await(await request.post('/api/user/login',{data:{email:'owner@ui-parity.invalid',password}})).json()).errcode).toBe(0);async function api(path,data){const result=await(await request.post(path,{data})).json();expect(result.errcode).toBe(0);return result.data;}
 const project=await api('/api/project/add',{name:'Synthetic body '+Date.now(),group_id:901000,project_type:'private'});await api('/api/project/up',{id:project._id,is_json5:json5});await api('/api/project/add_member',{id:project._id,member_uids:[910003],role:'dev'});await api('/api/project/add_member',{id:project._id,member_uids:[910004],role:'guest'});const cat=(await(await request.get('/api/interface/getCatMenu?project_id='+project._id)).json()).data[0];const item=await api('/api/interface/add',{project_id:project._id,catid:cat._id,title:'Synthetic body fixture',path:'/body',method:'POST',tag:[],req_body_type:'raw',req_body_other:'Synthetic request raw',req_body_is_json_schema:false,req_body_form:[{name:'hidden',type:'text',example:'stale',required:'1'}],res_body_type:'raw',res_body:'Synthetic response raw',res_body_is_json_schema:false,...body});await info.attach('body-fixture',{body:JSON.stringify({project:project._id,id:item._id,role,json5}),contentType:'application/json'});
 await page.goto('/login');await page.getByPlaceholder('Email',{exact:true}).fill((role==='guest'?'outsider':role)+'@ui-parity.invalid');await page.getByPlaceholder('Password',{exact:true}).fill(password);await page.getByRole('button',{name:/^登\s*录$/}).click();await expect(page).toHaveURL(/\/group/);await page.goto('/project/'+project._id+'/interface/api/'+item._id);await page.getByRole('tab',{name:'编辑',exact:true}).click();await expect(page.locator('#title')).toBeVisible();const read=async()=>{const r=await(await request.get('/api/interface/get?id='+item._id)).json();expect(r.errcode).toBe(0);return r.data;};const before=await read();const observations=[];
 async function save(){const wait=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/interface/up'&&r.request().method()==='POST');await expect(page.getByRole('button',{name:/^保\s*存$/})).toBeEnabled();await page.getByRole('button',{name:/^保\s*存$/}).click();const response=await wait,result=await response.json(),payload=response.request().postDataJSON(),after=await read();observations.push({result,payload,after});if(role==='guest'){expect(result.errcode).not.toBe(0);await expect(page.getByText(/没有权限/).first()).toBeVisible();for(const k of ['req_body_type','req_body_other','req_body_form','res_body_type','res_body'])expect(after[k]).toEqual(before[k]);}else if(info.project.name==='new'){expect(result.errcode).toBe(0);await expect(page.getByText('保存成功').first()).toBeVisible();}else{expect([0,40011]).toContain(result.errcode);await expect(page.getByText(result.errcode===0?'保存成功':'服务器出错...',{exact:true}).first()).toBeVisible();}return {result,payload,after};}
 return {project,item,api,read,before,save,observations};
}
function field(page,version,key){const id=version==='old'?key:key.replace(/[.\[\]]/g,'_').replace(/__+/g,'_').replace(/_$/,'');return page.locator('[id="'+id+'"]');}
for(const role of ['owner','developer','guest'])test('raw false flags file form switching and hidden payload '+role,async({page,request},info)=>{
 const f=await setup(page,request,info,role);const flag=page.locator('h2.interface-title .ant-switch');if(info.project.name==='new')await expect(flag).not.toHaveClass(/ant-switch-checked/);else await expect(flag).toHaveClass(/ant-switch-checked/);await page.locator('#req_body_other').fill('Edited synthetic request raw');await page.locator('#res_body').fill('Edited synthetic response raw');let saved=await f.save();if(info.project.name==='new'){expect(saved.payload.req_body_is_json_schema).toBe(false);expect(saved.payload.res_body_is_json_schema).toBe(false);expect(saved.payload.req_body_form).toEqual([]);}else{expect(saved.payload.res_body_is_json_schema).toBe(true);}if(role!=='guest'){expect(saved.after.req_body_other).toBe('Edited synthetic request raw');expect(saved.after.res_body).toBe('Edited synthetic response raw');}
 await page.getByRole('radio',{name:'file',exact:true}).check();await page.locator('#req_body_other').fill('Synthetic file description');saved=await f.save();expect(saved.payload.req_body_type).toBe('file');if(role!=='guest')expect(saved.after.req_body_other).toBe('Synthetic file description');
 await page.getByRole('radio',{name:'form',exact:true}).check();await field(page,info.project.name,'req_body_form[0].name').fill('activeForm');await field(page,info.project.name,'req_body_form[0].example').fill('active-example');saved=await f.save();expect(saved.payload.req_body_type).toBe('form');if(info.project.name==='new')expect(saved.payload.req_body_other).toBe('');if(role!=='guest'){expect(saved.after.req_body_form[0].name).toBe('activeForm');expect(saved.after.req_body_form[0].example).toBe('active-example');}
 await page.getByRole('radio',{name:'raw',exact:true}).check();await page.locator('#req_body_other').fill('Roundtrip request raw');await page.locator('#res_body').fill('Roundtrip response raw');saved=await f.save();if(role!=='guest'){expect(saved.after.req_body_type).toBe('raw');expect(saved.after.req_body_other).toBe('Roundtrip request raw');expect(saved.after.res_body).toBe('Roundtrip response raw');}await page.reload();await page.getByRole('tab',{name:'编辑',exact:true}).click();if(info.project.name==='old'){const reopened={request:await page.locator('#req_body_other').inputValue(),response:await page.locator('#res_body').inputValue()};expect(reopened.request).not.toBe(role==='guest'?f.before.req_body_other:'Roundtrip request raw');await info.attach('legacy-hidden-schema-overwrites-raw-on-reopen',{body:JSON.stringify({id:f.item._id,reopened}),contentType:'application/json'});}else{await expect(page.locator('#req_body_other')).toHaveValue(role==='guest'?f.before.req_body_other:'Roundtrip request raw');await expect(page.locator('#res_body')).toHaveValue(role==='guest'?f.before.res_body:'Roundtrip response raw');}await page.screenshot({path:info.outputPath('raw-form-file-roundtrip.png')});await info.attach('body-final',{body:JSON.stringify({id:f.item._id,observations:f.observations}),contentType:'application/json'});
});
async function source(page,index,text){const editor=page.locator('.interface-editor.ace_editor:visible').nth(index);await editor.click({position:{x:90,y:20}});await page.keyboard.press('ControlOrMeta+A');await page.keyboard.insertText(text);return editor;}
for(const enabled of [true,false])for(const role of ['owner','developer','guest'])test('JSON5 policy preview fullscreen and source recovery '+enabled+' '+role,async({page,request},info)=>{
 const f=await setup(page,request,info,role,enabled,{req_body_type:'json',req_body_other:'{"input":1}',req_body_is_json_schema:false,res_body_type:'json',res_body:'{"reply":true}',res_body_is_json_schema:false,req_body_form:[]});
 if(info.project.name==='old'&&!enabled){await expect(page.locator('h2.interface-title .ant-switch')).toHaveClass(/ant-switch-checked/);await info.attach('legacy-explicit-false-overwrite',{body:JSON.stringify({id:f.item._id,stored:false,visibleSchema:true,json5:false}),contentType:'application/json'});return;}
 await expect(page.locator('.interface-editor.ace_editor:visible')).toHaveCount(2);const requests=[];page.on('request',r=>{if(new URL(r.url()).pathname==='/api/interface/up'&&r.method()==='POST')requests.push(r.postDataJSON());});await source(page,1,'{ invalid');await page.getByRole('tab',{name:'预览',exact:true}).last().click();await expect(page.locator('#mock-preview')).toContainText('解析出错');await page.getByRole('tab',{name:'模板',exact:true}).click();await page.getByRole('button',{name:/^保\s*存$/}).click();await expect(page.getByText('返回body json格式有问题，请检查！',{exact:true}).last()).toBeVisible();expect(requests).toHaveLength(0);
 const requestText='{input: 7, // request\n name: "synthetic"}',responseText='{reply: true, // response\n count: 2}';await source(page,0,requestText);await source(page,1,responseText);if(!enabled){await page.getByRole('button',{name:/^保\s*存$/}).click();await expect(page.getByText('返回body json格式有问题，请检查！',{exact:true}).last()).toBeVisible();expect(requests).toHaveLength(0);await source(page,0,'{"input":7,"name":"synthetic"}');await source(page,1,'{"reply":true,"count":2}');}
 await page.getByRole('tab',{name:'预览',exact:true}).last().click();await expect(page.locator('#mock-preview')).toContainText(/reply/);await expect(page.locator('#mock-preview')).toContainText(/true/);await page.getByRole('tab',{name:'模板',exact:true}).click();for(const index of [0,1]){const editor=page.locator('.interface-editor.ace_editor:visible').nth(index);await editor.click({position:{x:90,y:20}});await page.keyboard.press('F9');await expect(editor).toHaveClass(/fullScreen/);await page.screenshot({path:info.outputPath('fullscreen-'+index+'.png')});await page.keyboard.press('F9');await expect(editor).not.toHaveClass(/fullScreen/);await expect(page.locator('body')).not.toHaveClass(/fullScreen/);await page.locator('#title').click();await editor.click({position:{x:90,y:20}});await expect(page.locator('.ace_text-input:focus')).toHaveCount(1);}
 const saved=await f.save();expect(saved.payload.req_body_is_json_schema).toBe(false);expect(saved.payload.res_body_is_json_schema).toBe(false);if(role!=='guest'){if(enabled){expect(saved.after.req_body_other).toBe(requestText);expect(saved.after.res_body).toBe(responseText);}else{expect(JSON.parse(saved.after.req_body_other)).toEqual({input:7,name:'synthetic'});expect(JSON.parse(saved.after.res_body)).toEqual({reply:true,count:2});}}
 await page.reload();await page.getByRole('tab',{name:'编辑',exact:true}).click();await expect(page.locator('.interface-editor.ace_editor:visible')).toHaveCount(2);await expect(page.locator('.interface-editor.ace_editor:visible').nth(1)).toContainText('reply');await info.attach('json5-final',{body:JSON.stringify({id:f.item._id,enabled,role,observations:f.observations}),contentType:'application/json'});
});
test('fullscreen editor navigation back clears body state and reopens focused',async({page,request},info)=>{
 const f=await setup(page,request,info,'owner',true,{req_body_type:'json',req_body_other:'{"input":1}',req_body_is_json_schema:false,res_body_type:'json',res_body:'{"reply":true}',res_body_is_json_schema:false,req_body_form:[]});const editor=page.locator('.interface-editor.ace_editor:visible').last();await editor.click({position:{x:90,y:20}});await page.keyboard.press('F9');await expect(editor).toHaveClass(/fullScreen/);await page.goBack();const modal=page.locator('.ant-modal:visible');if(await modal.count())await modal.getByRole('button',{name:/确\s*定/}).click();await expect(page).toHaveURL(/\/group/);await expect(page.locator('body')).not.toHaveClass(/fullScreen/);await expect(page.locator('.ace_editor.fullScreen')).toHaveCount(0);await page.goto('/project/'+f.project._id+'/interface/api/'+f.item._id);await page.getByRole('tab',{name:'编辑',exact:true}).click();const reopened=page.locator('.interface-editor.ace_editor:visible').last();await reopened.click({position:{x:90,y:20}});await expect(page.locator('.ace_text-input:focus')).toHaveCount(1);await page.keyboard.press('F9');await expect(reopened).toHaveClass(/fullScreen/);await page.keyboard.press('F9');await expect(reopened).not.toHaveClass(/fullScreen/);await page.screenshot({path:info.outputPath('fullscreen-back-reopened.png')});
});
for(const role of ['owner','developer','guest'])test('historical raw true flags normalize without data loss '+role,async({page,request},info)=>{
 const f=await setup(page,request,info,role,false,{req_body_is_json_schema:true,res_body_is_json_schema:true});
 if(info.project.name==='old'){await expect(page.locator('h2.interface-title .ant-switch')).toHaveClass(/ant-switch-checked/);await info.attach('legacy-raw-hidden-schema-flag',{body:JSON.stringify({id:f.item._id,raw:true,schema:true}),contentType:'application/json'});return;}
 await expect(page.locator('#req_body_other')).toHaveValue('Synthetic request raw');await expect(page.locator('#res_body')).toHaveValue('Synthetic response raw');await expect(page.locator('h2.interface-title .ant-switch')).not.toHaveClass(/ant-switch-checked/);await page.locator('#title').fill('Historical raw metadata edit');const s=await f.save();expect(s.payload.req_body_is_json_schema).toBe(false);expect(s.payload.res_body_is_json_schema).toBe(false);if(role!=='guest'){expect(s.after.req_body_other).toBe('Synthetic request raw');expect(s.after.res_body).toBe('Synthetic response raw');expect(s.after.req_body_is_json_schema).toBe(false);expect(s.after.res_body_is_json_schema).toBe(false);}await page.reload();await page.getByRole('tab',{name:'编辑',exact:true}).click();await expect(page.locator('#req_body_other')).toHaveValue('Synthetic request raw');await expect(page.locator('#res_body')).toHaveValue('Synthetic response raw');await info.attach('historical-final',{body:JSON.stringify({id:f.item._id,observations:f.observations}),contentType:'application/json'});
});
for(const role of ['owner','developer','guest'])test('JSON raw JSON source roundtrip and GET inactive payload '+role,async({page,request},info)=>{
 const f=await setup(page,request,info,role,true,{req_body_type:'json',req_body_other:'{"input":1}',res_body_type:'json',res_body:'{"reply":true}',req_body_form:[]});await source(page,0,'{"input":9}');await source(page,1,'{"reply":"changed"}');await page.getByRole('radio',{name:'raw',exact:true}).check();await page.getByRole('radio',{name:'RAW',exact:true}).locator('xpath=ancestor::label[1]').click();await expect(page.locator('#req_body_other')).toHaveValue('{"input":9}');await expect(page.locator('#res_body')).toHaveValue('{"reply":"changed"}');await page.locator('#req_body_other').fill('{"input":10}');await page.locator('#res_body').fill('{"reply":"roundtrip"}');await page.getByRole('radio',{name:'json',exact:true}).check();await page.getByRole('radio',{name:'JSON',exact:true}).locator('xpath=ancestor::label[1]').click();await expect(page.locator('.interface-editor.ace_editor:visible').first()).toContainText('10');await expect(page.locator('.interface-editor.ace_editor:visible').last()).toContainText('roundtrip');const s=await f.save();expect(JSON.parse(s.payload.req_body_other)).toEqual({input:10});expect(JSON.parse(s.payload.res_body)).toEqual({reply:'roundtrip'});await page.screenshot({path:info.outputPath('json-raw-roundtrip.png')});await page.locator('.ant-form-item').filter({has:page.locator('.ant-form-item-label').filter({hasText:'接口路径'})}).locator('.ant-select').first().click();await page.locator('.ant-select-dropdown:visible').getByText('GET',{exact:true}).last().click();const getSaved=await f.save();expect(getSaved.payload.method).toBe('GET');expect(getSaved.payload.req_body_form).toEqual([]);if(info.project.name==='new'){expect(getSaved.payload.req_body_other).toBe('');expect(getSaved.payload.req_body_is_json_schema).toBe(false);}await page.reload();await page.getByRole('tab',{name:'编辑',exact:true}).click();await expect(page.locator('.interface-editor.ace_editor:visible').last()).toContainText(role==='guest'?'true':'roundtrip');await info.attach('roundtrip-final',{body:JSON.stringify({id:f.item._id,observations:f.observations}),contentType:'application/json'});
});
for(const role of ['owner','developer','guest'])test('schema preview uses current unsaved schema and reports invalid source '+role,async({page,request},info)=>{
 const initial={type:'object',properties:{oldField:{type:'string'}}},changed={type:'object',required:['currentField'],properties:{currentField:{type:'string',enum:['current']}}};const f=await setup(page,request,info,role,false,{req_body_type:'form',req_body_form:[],res_body_type:'json',res_body_is_json_schema:true,res_body:JSON.stringify(initial)});const modal=page.locator('.ant-modal:visible');if(info.project.name==='new')await page.getByRole('button',{name:'高级设置 根节点',exact:true}).click();else await page.locator('input[value="root"]:visible').last().locator('xpath=ancestor::div[@class="ant-row-flex ant-row-flex-middle"][1]').locator('.anticon-setting').click();if(info.project.name==='new')await modal.getByLabel('根节点 高级设置内容',{exact:true}).fill(JSON.stringify(changed));else{await modal.locator('.ace_text-input').focus();await page.keyboard.press('ControlOrMeta+A');await page.keyboard.insertText(JSON.stringify(changed));}await modal.getByRole('button',{name:info.project.name==='new'?/^应\s*用$/:/^确\s*定$/}).click();const response=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/interface/schema2json');await page.getByRole('tab',{name:'预览',exact:true}).last().click();const res=await response,payload=res.request().postDataJSON(),result=await res.json();await info.attach('schema-preview-response',{body:JSON.stringify({id:f.item._id,payload,result}),contentType:'application/json'});expect(payload.schema).toEqual(changed);await expect(page.locator('#mock-preview')).toContainText('currentField');expect(JSON.parse((await f.read()).res_body)).toEqual(initial);await page.getByRole('tab',{name:'模板',exact:true}).click();if(info.project.name==='new'){const editor=page.locator('.schema-editor-modern').filter({visible:true});await editor.getByRole('tab',{name:'JSON（完整 Schema）',exact:true}).click();await editor.getByLabel('JSON Schema',{exact:true}).fill('{invalid');let calls=0;page.on('request',r=>{if(new URL(r.url()).pathname==='/api/interface/schema2json')calls++;});await page.getByRole('tab',{name:'预览',exact:true}).last().click();await expect(page.locator('#mock-preview')).toContainText('Schema JSON 无效');expect(calls).toBe(0);await page.getByRole('tab',{name:'模板',exact:true}).click();await editor.getByLabel('JSON Schema',{exact:true}).fill(JSON.stringify(changed));}await f.save();await info.attach('schema-preview-final',{body:JSON.stringify({id:f.item._id,observations:f.observations}),contentType:'application/json'});
});
