const {test,expect}=require('@playwright/test');
async function login(page){await page.goto('/login');await page.getByPlaceholder('Email',{exact:true}).fill('owner@ui-parity.invalid');await page.getByPlaceholder('Password',{exact:true}).fill('SyntheticParityOnly_901000!');await page.getByRole('button',{name:/^登\s*录$/}).click();await expect(page).toHaveURL(/\/group/);}
async function read(page){const b=await(await page.request.get('/api/project/get?id=901001')).json();expect(b.errcode).toBe(0);return b.data;}
for(const failure of ['business','rejected','network'])for(const [tab,selector,field]of [['请求配置','.project-request','pre_script'],['全局mock脚本','.project-mock','project_mock_script']])test('save failure must be an error and retry persists '+tab+' '+failure,async({page},info)=>{
 page.setDefaultTimeout(10000);await login(page);const before=await read(page);await page.goto('/project/901001/setting');await page.getByRole('tab',{name:tab,exact:true}).click();
 const panel=page;const editor=panel.locator('.ace_text-input').first();await editor.focus();await page.keyboard.press('Meta+A');await page.keyboard.insertText('// synthetic retry '+info.project.name+' '+tab);
 await page.route('**/api/project/up',route=>failure==='network'?route.abort('failed'):route.fulfill({status:200,contentType:'application/json',body:JSON.stringify({errcode:failure==='rejected'?400:40011,errmsg:'Synthetic save refused'})}));
 await panel.getByRole('button',{name:/保\s*存/}).click();await expect(page.getByText(failure!=='business'?'保存失败，请检查网络后重试':'保存失败, Synthetic save refused',{exact:true})).toBeVisible();await page.screenshot({path:info.outputPath('save-failure.png'),fullPage:true});
 expect((await read(page))[field]).toBe(before[field]);await expect(page.locator('.ant-message-error').last()).toBeVisible();await expect(page.locator('.ant-message-success')).toHaveCount(0);
 await page.unroute('**/api/project/up');const pending=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/project/up'&&r.request().method()==='POST');await panel.getByRole('button',{name:/保\s*存/}).click();expect((await(await pending).json()).errcode).toBe(0);await expect(page.getByText('保存成功',{exact:true})).toBeVisible();await page.reload();await page.getByRole('tab',{name:tab,exact:true}).click();expect((await read(page))[field]).toBe('// synthetic retry '+info.project.name+' '+tab);await expect(page.locator('.ace_content').first()).toContainText('synthetic retry');
});
