const {test,expect}=require('@playwright/test');
async function login(page,role){await page.goto('/login');await page.getByPlaceholder('Email',{exact:true}).fill(role+'@ui-parity.invalid');await page.getByPlaceholder('Password',{exact:true}).fill('SyntheticParityOnly_901000!');await page.getByRole('button',{name:/^登\s*录$/}).click();await expect(page).toHaveURL(/\/group/);}
for(const width of [1024,1920])for(const role of ['owner','developer','guest'])test('table desktop width '+width+' '+role,async({page,request},info)=>{
 await page.setViewportSize({width,height:1080});page.setDefaultTimeout(12000);expect((await(await request.post('/api/user/login',{data:{email:'owner@ui-parity.invalid',password:'SyntheticParityOnly_901000!'}})).json()).errcode).toBe(0);
 async function api(path,data){const result=await(await request.post(path,{data})).json();expect(result.errcode).toBe(0);return result.data;}
 const project=await api('/api/project/add',{name:'Synthetic filters '+role+' '+Date.now(),group_id:901000,project_type:role==='public-nonmember'?'public':'private'});if(role==='developer'||role==='guest')await api('/api/project/add_member',{id:project._id,member_uids:[role==='guest'?910004:910003],role:role==='guest'?'guest':'dev'});const cats=(await(await request.get('/api/interface/getCatMenu?project_id='+project._id)).json()).data;const targetCat=await api('/api/interface/add_cat',{project_id:project._id,name:'Desktop target',desc:''});const ids=[];
 for(const [title,status,tag] of [['Done review','done',['review']],['Undone review','undone',['review']],['Done synthetic','done',['synthetic']]])ids.push((await api('/api/interface/add',{project_id:project._id,catid:cats[0]._id,title,path:'/synthetic-interface-with-a-long-path-for-desktop-layout-'+title.replaceAll(' ','-'),method:'GET',status,tag}))._id);
 await info.attach('fixture',{body:JSON.stringify({project:project._id,ids}),contentType:'application/json'});await login(page,role==='guest'||role==='public-nonmember'?'outsider':role);await page.goto('/project/'+project._id+'/interface/api');const table=page.locator('.table-interfacelist');const rows=table.locator('tbody tr');await expect(rows).toHaveCount(3);
 const layout=await table.evaluate(el=>({document:document.documentElement.scrollWidth,viewport:innerWidth,table:el.clientWidth,scroll:el.scrollWidth,css:getComputedStyle(el.querySelector('table')).tableLayout,columns:[...el.querySelectorAll('th')].map(e=>({text:e.innerText,x:e.getBoundingClientRect().x,right:e.getBoundingClientRect().right,width:e.getBoundingClientRect().width})),outer:el.outerHTML.slice(0,6000)}));await info.attach('layout',{body:JSON.stringify(layout),contentType:'application/json'});await page.screenshot({path:info.outputPath('table-before-filter.png')});
 expect(layout.document).toBe(width);expect(layout.scroll).toBeLessThanOrEqual(layout.table);expect(layout.css).toBe('fixed');expect(layout.columns[4].right).toBeLessThanOrEqual(width);
 async function filter(column,value,reset=false){const reply=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/interface/list');await table.locator('th').filter({hasText:column}).locator('.anticon-filter').click();const popup=page.locator('.ant-table-filter-dropdown:visible');await expect(popup).toBeVisible();if(reset)await popup.getByText('重置',{exact:true}).click();else await popup.getByText(value,{exact:true}).click();const ok=popup.getByText(/^确\s*定$/);if(await ok.isVisible())await ok.click();await expect(popup).toBeHidden();expect((await(await reply).json()).errcode).toBe(0);}
 await filter('状态','未完成');await expect(rows).toHaveCount(1);await expect(rows).toContainText('Undone review');await filter('tag','review');await expect(rows).toHaveCount(1);await filter('状态','',true);await expect(rows).toHaveCount(2);await filter('tag','',true);await expect(rows).toHaveCount(3);
 const row=rows.filter({hasText:'Undone review'});async function mutate(select,value){await select.click();const reply=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/interface/up'&&r.request().method()==='POST');await page.locator('.ant-select-dropdown:visible').getByText(value,{exact:true}).last().click();const result=await(await reply).json();expect(result.errcode===0).toBe(role!=='guest');await expect(page.getByText(role==='guest'?/没有权限/:'修改成功').first()).toBeVisible();}
 await mutate(row.locator('.ant-select').nth(1),'已完成');await mutate(row.locator('.ant-select.path'),'Desktop target');const read=(await(await request.get('/api/interface/get?id='+ids[1])).json());expect(read.errcode).toBe(0);expect(read.data.status).toBe(role==='guest'?'undone':'done');expect(read.data.catid).toBe(role==='guest'?cats[0]._id:targetCat._id);await page.reload();await expect(rows).toHaveCount(3);await expect(rows.filter({hasText:'Undone review'})).toContainText(role==='guest'?'未完成':'已完成');await info.attach('layout-final-record',{body:JSON.stringify({id:ids[1],status:read.data.status,catid:read.data.catid,project:project._id}),contentType:'application/json'});
 const category=table.locator('.ant-select.path').first();const box=await category.boundingBox(),arrow=await category.locator('.ant-select-arrow, .ant-select-suffix').boundingBox();expect(box.height).toBeLessThanOrEqual(34);expect(Math.abs(arrow.y+arrow.height/2-box.y-box.height/2)).toBeLessThan(8);await expect(table.locator('tbody input[type="checkbox"]')).toHaveCount(0);await expect(table.locator('.ant-table-column-sorter')).toHaveCount(0);await page.evaluate(()=>window.scrollTo(0,0));await page.waitForTimeout(350);await page.screenshot({path:info.outputPath('list-filter-cleared.png')});
});
