const {test,expect}=require('@playwright/test');
test.beforeEach(async({page})=>page.setDefaultTimeout(12000));
async function api(page,url,data){const r= data===undefined?await page.request.get(url):await page.request.post(url,{data});expect(r.status(),url).toBe(200);const b=await r.json();expect(b.errcode,url).toBe(0);return b.data;}
async function login(page,role='owner'){await page.context().clearCookies();await page.goto('/login');await page.getByPlaceholder('Email',{exact:true}).fill(role+'@ui-parity.invalid');await page.getByPlaceholder('Password',{exact:true}).fill('SyntheticParityOnly_901000!');await page.getByRole('button',{name:/^登\s*录$/}).click();await expect(page).toHaveURL(/group/);}
async function setup(page,count=2){await login(page);const p=await api(page,'/api/project/add',{name:'Synthetic B closure '+Date.now(),group_id:901000,project_type:'private'});await api(page,'/api/project/up',{id:p._id,env:[{name:'local',domain:'http://127.0.0.1:3000/mock/'+p._id}]});const cat=(await api(page,'/api/interface/getCatMenu?project_id='+p._id))[0];const i=await api(page,'/api/interface/add',{project_id:p._id,catid:cat._id,title:'Closure source',path:'/closure',method:'GET'});await api(page,'/api/interface/up',{id:i._id,res_body_type:'json',res_body_is_json_schema:false,res_body:'{"code":0,"text":"合成测试"}',req_query:[{name:'first',required:'0',desc:'first',example:'one'},{name:'second',required:'0',desc:'second',example:'two'}]});const col=await api(page,'/api/col/add_col',{project_id:p._id,name:'Closure collection'});const cases=[];for(let n=0;n<count;n++)cases.push(await api(page,'/api/col/add_case',{project_id:p._id,col_id:col._id,interface_id:i._id,casename:'Closure case '+n}));const fixture={project:p._id,iface:i._id,col:col._id,cases};page.scopeBFixture=fixture;return fixture;}
async function saveResponse(page,path,action){const wait=page.waitForResponse(r=>new URL(r.url()).pathname===path);await action();const b=await(await wait).json();expect(b.errcode,path).toBe(0);return b.data;}
async function select(page,loc,text){await loc.scrollIntoViewIfNeeded();await loc.click();const input=loc.locator('input');if(await input.isEditable()){await input.fill(text);await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');}else{await page.locator('.ant-select-dropdown:visible .ant-select-item-option-content').getByText(text,{exact:true}).click();}await expect(loc).toContainText(text);}
async function ace(page,root,text){await expect(root).toBeVisible();await expect(root.locator('.ace_content')).toContainText('code');await root.locator('textarea').focus();await page.keyboard.press('Meta+A');await page.keyboard.insertText(text);await expect(root.locator('.ace_content')).toContainText(text);}




async function expression(page,id,{kind='constant',value='expression',fn=false}={}){
 const input=page.locator('#'+id),field=page.locator('.key-value-wrap').filter({has:input}),before=await input.inputValue();await input.focus();await page.keyboard.press('Home');await field.locator('.ant-input-group-addon').click();const d=page.getByRole('dialog',{name:/高级参数设置/});await d.getByPlaceholder('基础参数值',{exact:true}).fill('discard');await d.getByRole('button',{name:/取\s*消$/}).click();await expect(input).toHaveValue(before);await input.fill('');await field.locator('.ant-input-group-addon').click();
 if(kind==='mock'){await d.getByText('mock数据',{exact:true}).click();await d.getByPlaceholder('搜索mock数据').fill('@guid');await d.locator('.modal-postman-form-mock').getByText('@guid',{exact:true}).click();}
 else await d.getByPlaceholder('基础参数值',{exact:true}).fill(value);
 if(fn){await d.locator('.show-more').first().click();await d.getByText('upper',{exact:true}).click();}
 await d.getByRole('button',{name:/插\s*入$/}).click();const inserted=await input.inputValue();await expect(input).toHaveValue(/\{\{/);await input.focus();await page.keyboard.press('Home');for(let n=0;n<3;n++)await page.keyboard.press('ArrowRight');await field.locator('.ant-input-group-addon').click();await expect(d.locator('.modal-postman-expression')).toContainText(kind==='mock'?'@guid':value);await d.locator('.ant-modal-close').click();await expect(input).toHaveValue(inserted);const box=field.getByRole('checkbox');if(await box.count()&&await box.isEnabled())await box.check();return inserted;
}
test('parameter modal path query header form indices and mock function insertion survive case save and actual request',async({page},info)=>{
 const f=await setup(page,1);await api(page,'/api/project/up',{id:f.project,env:[{name:'echo',domain:'http://parity-fast-collections-echo:3001',header:[{name:'x-parity-synthetic',value:'fastb1003'}]}]});await api(page,'/api/interface/up',{id:f.iface,path:'/echo/{first}/{second}',method:'POST',req_body_type:'form',req_params:[{name:'first',example:'LEFT'},{name:'second',example:'RIGHT'}],req_query:[{name:'first',required:'1',example:'LEFT'},{name:'second',required:'0',example:'RIGHT'}],req_headers:[{name:'Content-Type',value:'application/x-www-form-urlencoded'},{name:'x-fixture',example:'LEFT'},{name:'x-second',example:'RIGHT'},{name:'x-parity-synthetic',value:'fastb1003'}],req_body_form:[{name:'first',type:'text',required:'1',example:'LEFT'},{name:'second',type:'text',required:'0',example:'RIGHT'}]});
 await page.goto(`/project/${f.project}/interface/case/${f.cases[0]._id}`);await expect(page.locator('#req_query_0')).toBeVisible();await expect(page.locator('.url .ant-select').nth(1)).toContainText('echo');await page.locator('#req_params_0').fill('LEFT');await page.locator('#req_query_0').fill('LEFT');await page.locator('#req_headers_1').fill('LEFT');await page.locator('#req_body_form_0').fill('LEFT');const saved={};for(const [id,options]of [['req_params_1',{value:'path',fn:true}],['req_query_1',{kind:'mock'}],['req_headers_2',{value:'header',fn:true}],['req_body_form_1',{value:'form',fn:true}]])saved[id]=await expression(page,id,options);
 const name=page.locator('.edit-case-name input');await name.fill('Exact parameter case');await saveResponse(page,'/api/col/up_case',()=>page.getByRole('button',{name:/更\s*新$/}).click());await page.reload();await expect(name).toHaveValue('Exact parameter case');await expect(page.locator('.url .ant-select').nth(1)).toContainText('echo');for(const [id,value]of Object.entries(saved))await expect(page.locator('#'+id)).toHaveValue(value);for(const id of ['req_params_0','req_query_0','req_headers_1','req_body_form_0'])await expect(page.locator('#'+id)).toHaveValue('LEFT');
 const result=await saveResponse(page,'/api/interface/proxy',()=>page.getByRole('button',{name:/^发\s*送$/}).click()),echo=result.res.body;expect(echo.path).toBe('/echo/LEFT/PATH');expect(echo.query.first).toBe('LEFT');expect(echo.query.second).toMatch(/^[a-f0-9-]{36}$/i);expect(echo.header).toBe('LEFT');expect(echo.body).toBe('first=LEFT&second=FORM');await expect(page.locator('.pretty-editor-body')).toContainText('FORM');const record=await api(page,'/api/col/case?caseid='+f.cases[0]._id);expect(record.casename).toBe('Exact parameter case');expect(record.req_headers.find(x=>x.name==='x-second').value).toBe(saved.req_headers_2);await page.screenshot({path:info.outputPath('parameter-all-indices.png'),animations:'disabled'});page.scopeBExpectedCase=record;
});
test('JSON body expression inserts only selected string and preserves neighboring fields',async({page},info)=>{
 const f=await setup(page,1);await api(page,'/api/project/up',{id:f.project,env:[{name:'echo',domain:'http://parity-fast-collections-echo:3001',header:[{name:'x-parity-synthetic',value:'fastb1003'}]}]});await api(page,'/api/interface/up',{id:f.iface,path:'/echo',method:'POST',req_body_type:'json',req_body_is_json_schema:false,req_body_other:'{"first":"","second":"KEEP"}',req_headers:[{name:'Content-Type',value:'application/json'},{name:'x-parity-synthetic',value:'fastb1003'}]});await api(page,'/api/col/up_case',{id:f.cases[0]._id,req_body_type:'json',req_body_other:'{"first":"","second":"KEEP"}'});await page.goto(`/project/${f.project}/interface/case/${f.cases[0]._id}`);const editor=page.locator('.pretty-editor'),text='{"first":"","second":"KEEP"}';await editor.locator('textarea').focus();await page.keyboard.press('Meta+A');await page.keyboard.insertText(text);for(let n=0;n<text.length-10;n++)await page.keyboard.press('ArrowLeft');await page.getByRole('button',{name:'高级参数设置',exact:true}).click();const d=page.getByRole('dialog',{name:/高级参数设置/});await d.getByPlaceholder('基础参数值',{exact:true}).fill('json');await d.locator('.show-more').first().click();await d.getByText('upper',{exact:true}).click();await d.getByRole('button',{name:/插\s*入$/}).click();await saveResponse(page,'/api/col/up_case',()=>page.getByRole('button',{name:/更\s*新$/}).click());await page.reload();const record=await api(page,'/api/col/case?caseid='+f.cases[0]._id);expect(JSON.parse(record.req_body_other)).toEqual({first:expect.stringContaining('upper'),second:'KEEP'});const result=await saveResponse(page,'/api/interface/proxy',()=>page.getByRole('button',{name:/^发\s*送$/}).click());expect(JSON.parse(result.res.body.body)).toEqual({first:'JSON',second:'KEEP'});await expect(page.locator('.pretty-editor-body')).toContainText('KEEP');await page.screenshot({path:info.outputPath('json-expression-exact-field.png'),animations:'disabled'});page.scopeBExpectedCase=record;
});
test.afterEach(async({page},info)=>{const f=page.scopeBFixture,expected=page.scopeBExpectedCase;if(!f||!expected)return;const{expected:guard}=require('./parity-collections-guard.cjs'),e=guard(info.project.name),{execFileSync}=require('node:child_process'),prefix=info.project.name==='new'?'await ':'';const js=`var m=${prefix}db.getCollection('_ui_parity_fixture').findOne({_id:'yapi-ui-parity-v1'});if(!m||m.synthetic!==true||m.run!=='fastb1003'||m.fixtureSha256!==${JSON.stringify(e.hash)})throw Error('Wrong fixture');var r=${prefix}db.interface_case.findOne({_id:${f.cases[0]._id},project_id:${f.project}});print(JSON.stringify(r))`;const stored=JSON.parse(execFileSync('docker',['exec',e.mongo,info.project.name==='new'?'mongosh':'mongo','--quiet',e.database,'--eval',info.project.name==='new'?'(async()=>{'+js+'})()':js],{encoding:'utf8'}).trim());for(const key of ['casename','req_params','req_query','req_headers','req_body_form','req_body_other'])if(stored[key]!==undefined){if(Array.isArray(stored[key])){const values=rows=>rows.map(x=>({name:x.name,value:x.value,enable:x.enable}));expect(values(stored[key])).toEqual(values(expected[key]));}else expect(stored[key]).toEqual(expected[key]);}await info.attach('synthetic-parameter-case-db',{body:JSON.stringify(stored),contentType:'application/json'});});
