const {test,expect}=require('@playwright/test');
async function login(page,role='admin'){await page.goto('/login');await page.getByPlaceholder('Email',{exact:true}).fill(role+'@ui-parity.invalid');await page.getByPlaceholder('Password',{exact:true}).fill('SyntheticParityOnly_901000!');await page.getByRole('button',{name:/^登\s*录$/}).click();await expect(page).toHaveURL(/\/group/);}
async function post(page,path,action){const pending=page.waitForResponse(r=>r.request().method()==='POST'&&new URL(r.url()).pathname===path);await action();const r=await pending;expect(r.status()).toBe(200);const b=await r.json();expect(b.errcode,JSON.stringify(b)).toBe(0);return b.data;}
async function group(page,id){const b=await(await page.request.get('/api/group/get?id='+id)).json();expect(b.errcode).toBe(0);return b.data;}
test('CRUD admin group cancel create edit custom fields and delete confirmation',async({page},info)=>{
 page.setDefaultTimeout(12000);await login(page);const name='Synthetic CRUD '+info.project.name+' '+Date.now();
 await page.locator('.anticon-folder-add').click();const modal=page.locator('.add-group-modal');await expect(modal).toBeVisible();
 await modal.getByPlaceholder('请输入分组名称').fill(name+' discarded');await modal.getByPlaceholder('请输入分组描述').fill('discarded description');await modal.getByRole('button',{name:/取\s*消/}).click();
 await page.locator('.anticon-folder-add').click();await expect(modal.getByPlaceholder('请输入分组名称')).toHaveValue('');await expect(modal.getByPlaceholder('请输入分组描述')).toHaveValue('');
 await modal.getByPlaceholder('请输入分组名称').fill(name);await modal.getByPlaceholder('请输入分组描述').fill('Synthetic group only');const created=await post(page,'/api/group/add',()=>modal.getByRole('button',{name:/确\s*定/}).click());const id=created._id;await info.attach('created-id',{body:JSON.stringify({id,name}),contentType:'application/json'});
 expect((await group(page,id)).group_name).toBe(name);await page.goto('/group/'+id);await page.getByRole('tab',{name:'分组设置',exact:true}).click();await expect(page.getByPlaceholder('请输入分组名称')).toHaveValue(name);
 await page.getByPlaceholder('请输入分组名称').fill(name+' edited');await page.getByPlaceholder('请输入分组描述').fill('Updated synthetic 中文');await page.getByPlaceholder('请输入自定义字段名称').fill('Review state');await page.locator('.panel-group .ant-switch').click();await post(page,'/api/group/up',()=>page.getByRole('button',{name:/保\s*存/}).click());
 const saved=await group(page,id);expect(saved.group_desc).toBe('Updated synthetic 中文');expect(saved.custom_field1).toMatchObject({name:'Review state',enable:true});await page.reload();await page.getByRole('tab',{name:'分组设置',exact:true}).click();await expect(page.getByPlaceholder('请输入分组名称')).toHaveValue(name+' edited');
 await page.getByRole('button',{name:/查\s*看/}).click();await page.getByRole('button',{name:/^删\s*除$/}).click();await page.getByRole('button',{name:/取\s*消/}).click();expect((await group(page,id)).group_name).toBe(name+' edited');
 await page.getByRole('button',{name:/^删\s*除$/}).click();await page.locator('#group_name').fill('wrong synthetic name');await page.getByRole('button',{name:/确\s*定/}).click();await expect(page.getByText('分组名称有误',{exact:true})).toBeVisible();expect((await group(page,id)).group_name).toBe(name+' edited');
 await page.locator('#group_name').fill(name+' edited');await post(page,'/api/group/del',()=>page.getByRole('button',{name:/确\s*定/}).click());if(info.project.name==='new')await expect(page).not.toHaveURL('/group/'+id);else await info.attach('legacy-navigation-defect',{body:'Old version remains on deleted group route; new version navigates to a surviving group.',contentType:'text/plain'});const missing=await page.request.get('/api/group/get?id='+id);if(missing.status()===200){const body=await missing.json();expect(!body.data||body.errcode!==0).toBe(true);}else expect(missing.status()).toBe(404);await page.screenshot({path:info.outputPath('group-deleted.png'),fullPage:true});
});
