const {test,expect}=require('@playwright/test');
async function login(page){await page.goto('/login');await page.getByPlaceholder('Email',{exact:true}).fill('owner@ui-parity.invalid');await page.getByPlaceholder('Password',{exact:true}).fill('SyntheticParityOnly_901000!');await page.getByRole('button',{name:/^登\s*录$/}).click();await expect(page).toHaveURL(/\/group/);}
async function select(page,el,text){await el.click();await page.locator('.ant-select-dropdown:visible').getByText(text,{exact:true}).last().click();}
test('malformed import error releases loading and valid retry persists',async({page},info)=>{
 page.setDefaultTimeout(10000);await login(page);const b=await(await page.request.post('/api/project/add',{data:{name:'Synthetic retry '+Date.now(),group_id:901000,project_type:'private'}})).json();expect(b.errcode).toBe(0);const id=b.data._id;await page.goto('/project/'+id+'/data');await select(page,page.locator('.dataImportTile .ant-select').first(),'json');await select(page,page.locator('.dataSync .ant-select').first(),'普通模式');const input=page.locator('input[type=file]');await input.setInputFiles({name:'synthetic-invalid.json',mimeType:'application/json',buffer:Buffer.from('{invalid')});await expect(page.locator('.ant-message-error').last()).toBeVisible();await expect(page.locator('.ant-spin-spinning')).toHaveCount(0);let list=await(await page.request.get('/api/interface/list_menu?project_id='+id)).json();expect(list.data.flatMap(c=>c.list)).toHaveLength(0);
 const data=[{name:'Synthetic retry',list:[{title:'Synthetic recovered',path:'/retry',method:'GET',res_body:'{}',res_body_is_json_schema:true}]}];const pending=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/interface/add');await input.setInputFiles({name:'synthetic-valid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(data))});expect((await(await pending).json()).errcode).toBe(0);await expect(page.locator('.ant-spin-spinning')).toHaveCount(0);await page.reload();list=await(await page.request.get('/api/interface/list_menu?project_id='+id)).json();expect(list.data.flatMap(c=>c.list).map(x=>x.path)).toEqual(['/retry']);await page.screenshot({path:info.outputPath('import-recovered.png'),fullPage:true});
});
test('Swagger URL empty gate and isolated network failure are visible and retryable',async({page},info)=>{
 page.setDefaultTimeout(10000);await login(page);await page.goto('/project/901001/data');await select(page,page.locator('.dataImportTile .ant-select').first(),'Swagger');await page.locator('.dataSync .ant-switch').click();const upload=page.getByRole('button',{name:/^上\s*传$/});await upload.click();await expect(page.getByText('url 不能为空',{exact:true})).toBeVisible();await page.getByPlaceholder('http://demo.swagger.io/v2/swagger.json').fill('http://127.0.0.1:9/synthetic-only');const p=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/project/swagger_url');await upload.click();const b=await(await p).json();expect(b.errcode).not.toBe(0);await expect(page.locator('.ant-message-error').last()).toBeVisible();await expect(upload).toBeEnabled();await expect(page.locator('.ant-spin-spinning')).toHaveCount(0);await page.screenshot({path:info.outputPath('url-network-failure.png'),fullPage:true});
});
