const {test,expect}=require('@playwright/test');
async function login(page,role){await page.goto('/login');await page.getByPlaceholder('Email',{exact:true}).fill(role+'@ui-parity.invalid');await page.getByPlaceholder('Password',{exact:true}).fill('SyntheticParityOnly_901000!');await page.getByRole('button',{name:/^登\s*录$/}).click();await expect(page).toHaveURL(/\/group/);}
for(const role of ['owner','developer','guest','public-nonmember'])test('list status and tag filters combine and reset '+role,async({page,request},info)=>{
 page.setDefaultTimeout(12000);expect((await(await request.post('/api/user/login',{data:{email:'owner@ui-parity.invalid',password:'SyntheticParityOnly_901000!'}})).json()).errcode).toBe(0);
 async function api(path,data){const result=await(await request.post(path,{data})).json();expect(result.errcode).toBe(0);return result.data;}
 const project=await api('/api/project/add',{name:'Synthetic filters '+role+' '+Date.now(),group_id:901000,project_type:role==='public-nonmember'?'public':'private'});if(role==='developer'||role==='guest')await api('/api/project/add_member',{id:project._id,member_uids:[role==='guest'?910004:910003],role:role==='guest'?'guest':'dev'});const cats=(await(await request.get('/api/interface/getCatMenu?project_id='+project._id)).json()).data;const ids=[];
 for(const [title,status,tag] of [['Done review','done',['review']],['Undone review','undone',['review']],['Done synthetic','done',['synthetic']]])ids.push((await api('/api/interface/add',{project_id:project._id,catid:cats[0]._id,title,path:'/'+title.replaceAll(' ','-'),method:'GET',status,tag}))._id);
 await info.attach('fixture',{body:JSON.stringify({project:project._id,ids}),contentType:'application/json'});await login(page,role==='guest'||role==='public-nonmember'?'outsider':role);await page.goto('/project/'+project._id+'/interface/api');const table=page.locator('.table-interfacelist');const rows=table.locator('tbody tr');await expect(rows).toHaveCount(3);
 async function filter(column,value,reset=false){const reply=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/interface/list');await table.locator('th').filter({hasText:column}).locator('.anticon-filter').click();const popup=page.locator('.ant-table-filter-dropdown:visible');await expect(popup).toBeVisible();if(reset)await popup.getByText('重置',{exact:true}).click();else await popup.getByText(value,{exact:true}).click();const ok=popup.getByText(/^确\s*定$/);if(await ok.isVisible())await ok.click();await expect(popup).toBeHidden();expect((await(await reply).json()).errcode).toBe(0);}
 await filter('状态','未完成');await expect(rows).toHaveCount(1);await expect(rows).toContainText('Undone review');await filter('tag','review');await expect(rows).toHaveCount(1);await filter('状态','',true);await expect(rows).toHaveCount(2);await filter('tag','',true);await expect(rows).toHaveCount(3);
 const category=table.locator('.ant-select.path').first();const box=await category.boundingBox(),arrow=await category.locator('.ant-select-arrow, .ant-select-suffix').boundingBox();expect(box.height).toBeLessThanOrEqual(34);expect(Math.abs(arrow.y+arrow.height/2-box.y-box.height/2)).toBeLessThan(8);await expect(table.locator('tbody input[type="checkbox"]')).toHaveCount(0);await expect(table.locator('.ant-table-column-sorter')).toHaveCount(0);await page.evaluate(()=>window.scrollTo(0,0));await page.waitForTimeout(350);await page.screenshot({path:info.outputPath('list-filter-cleared.png')});
});

test('private nonmember interface list denies data and creation controls',async({page,request},info)=>{
 expect((await(await request.post('/api/user/login',{data:{email:'owner@ui-parity.invalid',password:'SyntheticParityOnly_901000!'}})).json()).errcode).toBe(0);const created=await(await request.post('/api/project/add',{data:{name:'Synthetic private nonmember '+Date.now(),group_id:901000,project_type:'private'}})).json();expect(created.errcode).toBe(0);const id=created.data._id;await login(page,'outsider');const response=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/project/get');await page.goto('/project/'+id+'/interface/api');expect((await(await response).json()).errcode).not.toBe(0);await expect(page.getByRole('button',{name:'添加接口',exact:true})).toHaveCount(0);await expect(page.locator('.table-interfacelist')).toHaveCount(0);const denied=await(await page.request.get('/api/interface/list?project_id='+id+'&page=1&limit=20')).json();expect(denied.errcode).not.toBe(0);await page.screenshot({path:info.outputPath('private-nonmember-denied.png')});
});
