const {test,expect}=require('@playwright/test');

async function verifyRemarkDb(info,id,after){const {execFileSync}=require('node:child_process'),version=info.project.name;expect(['old','new']).toContain(version);expect(Number.isSafeInteger(id)).toBe(true);const script='db=db.getSiblingDB("parity_fast_interfaces_'+version+'");print(JSON.stringify(db.interface.findOne({_id:'+id+'},{_id:1,desc:1,markdown:1})));';const row=JSON.parse(execFileSync('docker',['exec','parity-fast-interfaces-mongo-'+version,version==='old'?'mongo':'mongosh','--quiet','--eval',script],{encoding:'utf8'}));expect(row.desc).toBe(after.desc);expect(row.markdown).toBe(after.markdown);await info.attach('remark-db-readback',{body:JSON.stringify(row),contentType:'application/json'});}

async function setup(page,request,info,role,json5=false,body={}){
 page.setDefaultTimeout(12000);const password='SyntheticParityOnly_901000!';expect((await(await request.post('/api/user/login',{data:{email:'owner@ui-parity.invalid',password}})).json()).errcode).toBe(0);async function api(path,data){const result=await(await request.post(path,{data})).json();expect(result.errcode).toBe(0);return result.data;}
 const project=await api('/api/project/add',{name:'Synthetic body '+Date.now(),group_id:901000,project_type:'private'});await api('/api/project/up',{id:project._id,is_json5:json5});await api('/api/project/add_member',{id:project._id,member_uids:[910003],role:'dev'});await api('/api/project/add_member',{id:project._id,member_uids:[910004],role:'guest'});const cat=(await(await request.get('/api/interface/getCatMenu?project_id='+project._id)).json()).data[0];const item=await api('/api/interface/add',{project_id:project._id,catid:cat._id,title:'Synthetic body fixture',path:'/body',method:'POST',tag:[],req_body_type:'raw',req_body_other:'Synthetic request raw',req_body_is_json_schema:false,req_body_form:[{name:'hidden',type:'text',example:'stale',required:'1'}],res_body_type:'raw',res_body:'Synthetic response raw',res_body_is_json_schema:false,...body});await info.attach('body-fixture',{body:JSON.stringify({project:project._id,id:item._id,role,json5}),contentType:'application/json'});
 await page.goto('/login');await page.getByPlaceholder('Email',{exact:true}).fill((role==='guest'?'outsider':role)+'@ui-parity.invalid');await page.getByPlaceholder('Password',{exact:true}).fill(password);await page.getByRole('button',{name:/^登\s*录$/}).click();await expect(page).toHaveURL(/\/group/);await page.goto('/project/'+project._id+'/interface/api/'+item._id);await page.getByRole('tab',{name:'编辑',exact:true}).click();await expect(page.locator('#title')).toBeVisible();const read=async()=>{const r=await(await request.get('/api/interface/get?id='+item._id)).json();expect(r.errcode).toBe(0);return r.data;};const before=await read();const observations=[];
 async function save(){const wait=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/interface/up'&&r.request().method()==='POST');await expect(page.getByRole('button',{name:/^保\s*存$/})).toBeEnabled();await page.getByRole('button',{name:/^保\s*存$/}).click();const response=await wait,result=await response.json(),payload=response.request().postDataJSON(),after=await read();observations.push({result,payload,after});if(role==='guest'){expect(result.errcode).not.toBe(0);await expect(page.getByText(/没有权限/).first()).toBeVisible();for(const k of ['req_body_type','req_body_other','req_body_form','res_body_type','res_body'])expect(after[k]).toEqual(before[k]);}else if(info.project.name==='new'){expect(result.errcode).toBe(0);await expect(page.getByText('保存成功').first()).toBeVisible();}else{expect([0,40011]).toContain(result.errcode);await expect(page.getByText(result.errcode===0?'保存成功':'服务器出错...',{exact:true}).first()).toBeVisible();}return {result,payload,after};}
 return {project,item,api,read,before,save,observations};
}

for(const role of ['owner','developer','guest'])test('remark formatting toolbar save and reload '+role,async({page,request},info)=>{
 test.setTimeout(120000);const f=await setup(page,request,info,role,false,{desc:'<p>Original toolbar note</p>',markdown:'Original toolbar note',res_body_type:'json',res_body_is_json_schema:true,res_body:'{"type":"object","properties":{}}'}),remark=page.locator('#desc'),editable=remark.locator('[contenteditable=true]:visible');
 const cases=[['bold','bold','strong,b'],['italic','italic','em,i'],['strike','strike','del,s,strike'],['quote','quote','blockquote'],['ul','bullet-list','ul'],['ol','ordered-list','ol'],['task','task-list','ul'],['code','code','code'],['codeblock','codeblock','pre'],['hrline','hrline','hr']];
 for(const [oldButton,newButton,selector] of cases){
  await remark.getByText('Markdown',{exact:true}).click();const md=info.project.name==='new'?remark.locator('.toastui-editor-md-container [contenteditable=true]'):remark.locator('.CodeMirror textarea').first();await md.focus();await page.keyboard.press('ControlOrMeta+A');await page.keyboard.insertText('Synthetic '+newButton+' note');await remark.getByText('WYSIWYG',{exact:true}).click();await editable.click();await page.keyboard.press('ControlOrMeta+A');if(newButton==='hrline')await page.keyboard.press('ArrowRight');await remark.locator('button.'+(info.project.name==='old'?'tui-'+oldButton:newButton)).click();await info.attach('toolbar-'+newButton,{body:await editable.innerHTML(),contentType:'text/html'});await expect(editable.locator(selector).first()).toBeVisible();const result=await f.save();await verifyRemarkDb(info,f.item._id,result.after);if(role!=='guest'){expect(result.after.markdown).toBe(result.payload.markdown);expect(result.after.desc).toBe(result.payload.desc);}else expect(result.after.markdown).toBe('Original toolbar note');await page.reload();await page.getByRole('tab',{name:'编辑',exact:true}).click();if(role!=='guest')await expect(editable.locator(selector).first()).toBeVisible();else await expect(editable).toContainText('Original toolbar note');
 }
 await remark.scrollIntoViewIfNeeded();await page.screenshot({path:info.outputPath('toolbar-final.png')});await info.attach('toolbar-final',{body:JSON.stringify({id:f.item._id,role,observations:f.observations}),contentType:'application/json'});
});
