const {test,expect}=require('@playwright/test');
async function setup(page,request,info,role){
 page.setDefaultTimeout(12000);const password='SyntheticParityOnly_901000!';expect((await(await request.post('/api/user/login',{data:{email:'owner@ui-parity.invalid',password}})).json()).errcode).toBe(0);async function api(path,data){const r=await(await request.post(path,{data})).json();expect(r.errcode).toBe(0);return r.data;}
 const p=await api('/api/project/add',{name:'Synthetic metadata '+Date.now(),group_id:901000,project_type:'private'});await api('/api/project/add_member',{id:p._id,member_uids:[910003],role:'dev'});await api('/api/project/add_member',{id:p._id,member_uids:[910004],role:'guest'});await api('/api/project/up_tag',{id:p._id,tag:[{name:'Synthetic metadata tag',desc:'local fixture'}]});const cat=(await(await request.get('/api/interface/getCatMenu?project_id='+p._id)).json()).data[0];const next=await api('/api/interface/add_cat',{project_id:p._id,name:'Synthetic target category',desc:'metadata target'});const item=await api('/api/interface/add',{project_id:p._id,catid:cat._id,title:'Synthetic original title',path:'/original',method:'GET',tag:[],status:'undone',api_opened:false,res_body_type:'json',res_body_is_json_schema:true,res_body:'{"type":"object","properties":{}}'});
 const other=await api('/api/interface/add',{project_id:p._id,catid:cat._id,title:'Synthetic other interface',path:'/other',method:'GET',tag:[],res_body_type:'json',res_body_is_json_schema:true,res_body:'{"type":"object","properties":{}}'});
 await info.attach('metadata-fixture',{body:JSON.stringify({project:p._id,id:item._id,cat:cat._id,target:next._id,role}),contentType:'application/json'});await page.goto('/login');await page.getByPlaceholder('Email',{exact:true}).fill((role==='guest'?'outsider':role)+'@ui-parity.invalid');await page.getByPlaceholder('Password',{exact:true}).fill(password);await page.getByRole('button',{name:/^登\s*录$/}).click();await expect(page).toHaveURL(/\/group/);await page.goto('/project/'+p._id+'/interface/api/'+item._id);await page.getByRole('tab',{name:'编辑',exact:true}).click();await expect(page.locator('#title')).toBeVisible();
 const read=async()=>{const r=await(await request.get('/api/interface/get?id='+item._id)).json();expect(r.errcode).toBe(0);return r.data;};const field=label=>page.locator('.ant-form-item').filter({has:page.locator('.ant-form-item-label').filter({hasText:label})});async function select(label,value){await field(label).locator('.ant-select').first().click();await page.locator('.ant-select-dropdown:visible').getByText(value,{exact:true}).last().click();}
 return {p,item,other,cat,next,api,read,field,select};
}
for(const role of ['owner','developer','guest'])test('metadata exact fields and permission '+role,async({page,request},info)=>{
 const f=await setup(page,request,info,role),before=await f.read();await page.locator('#title').fill('Synthetic edited metadata');await f.select('选择分类','Synthetic target category');await f.select('接口路径','POST');await page.getByPlaceholder('/path',{exact:true}).fill('/metadata-changed');await f.select('Tag','Synthetic metadata tag');await page.keyboard.press('Escape');await f.select('状态','已完成');await page.getByPlaceholder('请输入',{exact:true}).fill('Synthetic custom reviewed');await f.field('开放接口').locator('.ant-switch').click();const notice=f.field('消息通知').locator('.ant-switch');await notice.click();await notice.click();if((await notice.getAttribute('class')).includes('ant-switch-checked'))await notice.click();
 const pending=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/interface/up'&&r.request().method()==='POST');await page.getByRole('button',{name:/^保\s*存$/}).click();const response=await pending,body=response.request().postDataJSON(),result=await response.json();expect(body.title).toBe('Synthetic edited metadata');expect(body.catid).toBe(String(f.next._id));expect(body.method).toBe('POST');expect(body.path).toBe('/metadata-changed');expect(body.status).toBe('done');expect(body.tag).toEqual(['Synthetic metadata tag']);expect(body.custom_field_value).toBe('Synthetic custom reviewed');expect(body.api_opened).toBe(true);expect(body.switch_notice).toBe(false);const after=await f.read();await info.attach('metadata-response',{body:JSON.stringify({body,result,before,after}),contentType:'application/json'});
 if(role==='guest'){expect(result.errcode).not.toBe(0);await expect(page.getByText('没有权限',{exact:false}).first()).toBeVisible();for(const k of ['title','catid','method','path','status','tag','custom_field_value','api_opened'])expect(after[k]).toEqual(before[k]);}else{if(info.project.name==='old'){expect(result.errcode).toBe(40011);await expect(page.getByText('服务器出错...',{exact:true}).first()).toBeVisible();await info.attach('legacy-save-error-after-write',{body:JSON.stringify({id:f.item._id,result}),contentType:'application/json'});}else{expect(result.errcode).toBe(0);await expect(page.getByText('保存成功').first()).toBeVisible();}for(const k of ['title','method','path','status','tag','custom_field_value','api_opened'])expect(after[k]).toEqual(body[k]);expect(after.catid).toBe(f.next._id);}
 await page.reload();await page.getByRole('tab',{name:'编辑',exact:true}).click();await expect(page.locator('#title')).toHaveValue(role==='guest'?before.title:'Synthetic edited metadata');await page.screenshot({path:info.outputPath('metadata-reopened.png')});await info.attach('metadata-final',{body:JSON.stringify({id:f.item._id,before,after,payload:body}),contentType:'application/json'});
});
for(const role of ['owner','developer'])test('save failure preserves dirty draft and retry remains pending '+role,async({page,request},info)=>{
 const f=await setup(page,request,info,role);await page.locator('#title').fill('Synthetic unsaved failure draft');const original=await f.read();
 for(const failure of ['logical','network','http']){
  await page.route('**/api/interface/up',route=>failure==='network'?route.abort('failed'):route.fulfill({status:failure==='http'?503:200,contentType:'application/json',body:JSON.stringify({errcode:400,errmsg:'Synthetic save rejected'})}));const pending=failure==='network'?null:page.waitForResponse(r=>new URL(r.url()).pathname==='/api/interface/up');await page.getByRole('button',{name:/^保\s*存$/}).click();await expect(page.getByText(failure==='network'?'保存失败，请重试':'Synthetic save rejected',{exact:true}).first()).toBeVisible();await expect(page.locator('#title')).toHaveValue('Synthetic unsaved failure draft');expect((await f.read()).title).toBe(original.title);await expect(page.getByRole('button',{name:/^保\s*存$/})).toBeEnabled();await page.getByRole('tab',{name:'预览',exact:true}).first().click();const modal=page.locator('.ant-modal:visible');if(info.project.name==='old'){await expect(modal).toHaveCount(0);await expect(page.locator('#title')).toHaveCount(0);expect((await f.read()).title).toBe(original.title);await info.attach('legacy-dirty-cleared-after-failed-save',{body:JSON.stringify({id:f.item._id,role,persistedTitle:original.title,lostDraft:'Synthetic unsaved failure draft'}),contentType:'application/json'});await page.screenshot({path:info.outputPath('legacy-failed-save-draft-lost.png')});return;}await expect(modal).toContainText('离开页面会丢失');await modal.getByRole('button',{name:/取\s*消/}).click();await expect(page.locator('#title')).toHaveValue('Synthetic unsaved failure draft');await page.unroute('**/api/interface/up');if(failure!=='network')await pending;
 }
 let release;const gate=new Promise(r=>release=r),calls=[];await page.route('**/api/interface/up',async route=>{const response=await route.fetch();calls.push(await response.json());await gate;await route.fulfill({response});});await page.getByRole('button',{name:/^保\s*存$/}).click();await expect.poll(()=>calls.length).toBe(1);expect(calls[0].errcode).toBe(0);await page.waitForTimeout(3300);await expect(page.getByRole('button',{name:/^保\s*存$/})).toBeDisabled();await page.locator('#title').fill('Synthetic newer local draft');release();await expect(page.getByText('保存成功').first()).toBeVisible();await expect(page.getByRole('button',{name:/^保\s*存$/})).toBeEnabled();await expect(page.locator('#title')).toHaveValue('Synthetic newer local draft');expect((await f.read()).title).toBe('Synthetic unsaved failure draft');await page.getByRole('tab',{name:'预览',exact:true}).first().click();await expect(page.locator('.ant-modal:visible')).toContainText('离开页面会丢失');await page.locator('.ant-modal:visible').getByRole('button',{name:/取\s*消/}).click();await page.unroute('**/api/interface/up');const saved=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/interface/up');await page.getByRole('button',{name:/^保\s*存$/}).click();expect((await(await saved).json()).errcode).toBe(0);await expect(page.getByText('保存成功').first()).toBeVisible();await page.getByRole('tab',{name:'预览',exact:true}).first().click();await expect(page.locator('.ant-modal:visible')).toHaveCount(0);await expect(page.getByText('Synthetic newer local draft',{exact:true}).first()).toBeVisible();await info.attach('save-failure-final',{body:JSON.stringify({id:f.item._id,after:await f.read(),calls:calls.length}),contentType:'application/json'});
});
for(const role of ['owner','developer'])test('late save response does not change another interface draft '+role,async({page,request},info)=>{
 test.skip(info.project.name==='old','Candidate late save response isolation.');const f=await setup(page,request,info,role);await page.locator('#title').fill('Synthetic original pending save');let release;const gate=new Promise(r=>release=r),server=[];await page.route('**/api/interface/up',async route=>{const response=await route.fetch();server.push(await response.json());await gate;await route.fulfill({response});});const response=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/interface/up');await page.getByRole('button',{name:/^保\s*存$/}).click();await expect.poll(()=>server.length).toBe(1);expect(server[0].errcode).toBe(0);await page.locator('a.interface-item').getByText('Synthetic other interface',{exact:true}).click();await expect(page.locator('.ant-modal:visible')).toContainText('离开页面会丢失');await page.locator('.ant-modal:visible').getByRole('button',{name:/确\s*定/}).click();await expect(page).toHaveURL(new RegExp('/api/'+f.other._id+'$'));await page.getByRole('tab',{name:'编辑',exact:true}).click();await page.locator('#title').fill('Synthetic other local draft');release();expect((await(await response).json()).errcode).toBe(0);await page.waitForTimeout(400);await expect(page.locator('#title')).toHaveValue('Synthetic other local draft');await expect(page).toHaveURL(new RegExp('/api/'+f.other._id+'$'));await page.getByRole('tab',{name:'预览',exact:true}).first().click();await expect(page.locator('.ant-modal:visible')).toContainText('离开页面会丢失');await page.locator('.ant-modal:visible').getByRole('button',{name:/取\s*消/}).click();const old=await f.read(),next=(await(await request.get('/api/interface/get?id='+f.other._id)).json()).data;expect(old.title).toBe('Synthetic original pending save');expect(next.title).toBe('Synthetic other interface');await info.attach('late-save-final',{body:JSON.stringify({oldId:f.item._id,newId:f.other._id,oldTitle:old.title,newTitle:next.title}),contentType:'application/json'});await page.screenshot({path:info.outputPath('late-save-other-draft.png')});
});
for(const role of ['owner','developer','guest'])test('metadata required invalid and duplicate path validation '+role,async({page,request},info)=>{
 const f=await setup(page,request,info,role),before=await f.read(),posts=[];page.on('request',r=>{if(new URL(r.url()).pathname==='/api/interface/up'&&r.method()==='POST')posts.push(r.postDataJSON());});await page.locator('#title').fill('');await page.getByPlaceholder('/path',{exact:true}).fill('');await page.getByRole('button',{name:/^保\s*存$/}).click();await expect(page.getByText('请输入接口路径!',{exact:true})).toBeVisible();await expect(page.getByText(/请输入接口名称，长度不超过/).first()).toBeVisible();expect(posts).toHaveLength(0);await page.locator('#title').fill('Synthetic invalid path draft');
 for(const value of ['/has space','/other']){await page.getByPlaceholder('/path',{exact:true}).fill(value);await expect(page.getByRole('button',{name:/^保\s*存$/})).toBeEnabled();const response=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/interface/up'&&r.request().method()==='POST');await page.getByRole('button',{name:/^保\s*存$/}).click();const result=await(await response).json();expect(result.errcode).not.toBe(0);await expect(page.getByText(role==='guest'?/没有权限/:value==='/other'?/已存在的接口/:/path第一位必需/).first()).toBeVisible();const after=await f.read();expect(after.path).toBe(before.path);expect(after.title).toBe(before.title);}
 await page.screenshot({path:info.outputPath('validation-error-visible.png')});await page.reload();await page.getByRole('tab',{name:'编辑',exact:true}).click();await expect(page.locator('#title')).toHaveValue(before.title);await expect(page.getByPlaceholder('/path',{exact:true})).toHaveValue(before.path);await info.attach('metadata-validation-final',{body:JSON.stringify({id:f.item._id,postCount:posts.length,after:await f.read()}),contentType:'application/json'});
});
for(const role of ['owner','developer','guest'])test('metadata notification enabled payload and role '+role,async({page,request},info)=>{
 const f=await setup(page,request,info,role),before=await f.read();await page.locator('#title').fill('Synthetic notice enabled '+role);const notice=f.field('消息通知').locator('.ant-switch');if(!(await notice.getAttribute('class')).includes('ant-switch-checked'))await notice.click();const response=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/interface/up'&&r.request().method()==='POST');await page.getByRole('button',{name:/^保\s*存$/}).click();const saved=await response,result=await saved.json();expect(saved.request().postDataJSON().switch_notice).toBe(true);const after=await f.read();await info.attach('notification-final',{body:JSON.stringify({id:f.item._id,role,result,beforeTitle:before.title,afterTitle:after.title}),contentType:'application/json'});if(role==='guest'){expect(result.errcode).not.toBe(0);await expect(page.getByText(/没有权限/).first()).toBeVisible();expect(after.title).toBe(before.title);}else{expect(result.errcode).toBe(0);await expect(page.getByText('保存成功').first()).toBeVisible();expect(after.title).toBe('Synthetic notice enabled '+role);}await page.screenshot({path:info.outputPath('notification-enabled-save.png')});
});
test('guest pending save denies once and preserves local draft',async({page,request},info)=>{
 test.skip(info.project.name==='old','Legacy dirty-loss defects recorded separately.');const f=await setup(page,request,info,'guest'),before=await f.read();await page.locator('#title').fill('Synthetic guest denied draft');let release;const gate=new Promise(r=>release=r),results=[];await page.route('**/api/interface/up',async route=>{const response=await route.fetch();results.push(await response.json());await gate;await route.fulfill({response});});const response=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/interface/up');await page.getByRole('button',{name:/^保\s*存$/}).dblclick();await expect.poll(()=>results.length).toBe(1);expect(results[0].errcode).not.toBe(0);await page.waitForTimeout(3300);await expect(page.getByRole('button',{name:/^保\s*存$/})).toBeDisabled();release();expect((await(await response).json()).errcode).not.toBe(0);await expect(page.getByText(/没有权限/).first()).toBeVisible();await expect(page.locator('#title')).toHaveValue('Synthetic guest denied draft');await page.getByRole('tab',{name:'预览',exact:true}).first().click();await expect(page.locator('.ant-modal:visible')).toContainText('离开页面会丢失');await page.locator('.ant-modal:visible').getByRole('button',{name:/取\s*消/}).click();expect((await f.read()).title).toBe(before.title);await page.reload();await page.getByRole('tab',{name:'编辑',exact:true}).click();await expect(page.locator('#title')).toHaveValue(before.title);await info.attach('guest-save-final',{body:JSON.stringify({id:f.item._id,requests:results.length,title:before.title}),contentType:'application/json'});
});
