const {test,expect}=require('@playwright/test');
const password='SyntheticParityOnly_901000!';
async function setup(page,request,info,role,schema,side){
  page.setDefaultTimeout(12000);
  expect((await(await request.post('/api/user/login',{data:{email:'owner@ui-parity.invalid',password}})).json()).errcode).toBe(0);
  async function api(path,data){const r=await(await request.post(path,{data})).json();expect(r.errcode).toBe(0);return r.data;}
  const p=await api('/api/project/add',{name:'Synthetic schema '+role+' '+Date.now(),group_id:901000,project_type:'private'});
  if(role!=='owner')await api('/api/project/add_member',{id:p._id,member_uids:[role==='guest'?910004:910003],role:role==='guest'?'guest':'dev'});
  const cats=(await(await request.get('/api/interface/getCatMenu?project_id='+p._id)).json()).data;
  const i=await api('/api/interface/add',{project_id:p._id,catid:cats[0]._id,title:'Synthetic schema fixture',path:'/schema',method:'POST',tag:[],req_body_type:side==='request'?'json':'form',req_body_form:[],req_body_is_json_schema:side==='request',req_body_other:side==='request'?JSON.stringify(schema):'',res_body_type:side==='request'?'raw':'json',res_body_is_json_schema:side!=='request',res_body:side==='request'?'Synthetic raw':JSON.stringify(schema)});
  await info.attach('schema-fixture',{body:JSON.stringify({project:p._id,id:i._id,schema}),contentType:'application/json'});
  await page.goto('/login');await page.getByPlaceholder('Email',{exact:true}).fill((role==='guest'?'outsider':role)+'@ui-parity.invalid');await page.getByPlaceholder('Password',{exact:true}).fill(password);await page.getByRole('button',{name:/^登\s*录$/}).click();await expect(page).toHaveURL(/\/group/);
  await page.goto('/project/'+p._id+'/interface/api/'+i._id);await page.getByRole('tab',{name:'编辑',exact:true}).click();
  return async()=>{const r=await(await request.get('/api/interface/get?id='+i._id)).json();expect(r.errcode).toBe(0);return JSON.parse(r.data[side==='request'?'req_body_other':'res_body']);};
}

for(const side of ['request','response'])for(const role of ['owner','developer','guest'])test('schema source refs combinators exact formatting persistence '+side+' '+role,async({page,request},info)=>{
 const initial={type:'object',$defs:{value:{type:['string','null'],minLength:2}},properties:{value:{$ref:'#/$defs/value'},choice:{oneOf:[{type:'number',minimum:0},{const:'auto'}]}},allOf:[{required:['value']}],additionalProperties:false,'x-extension':{nested:{retain:[1,false,null]}}};const read=await setup(page,request,info,role,initial,side),id=Number(new URL(page.url()).pathname.split('/').pop()),changed={...initial,description:'Full source retained'},source=JSON.stringify(changed,null,4),old=info.project.name==='old',field=side==='request'?'req_body_other':'res_body',modal=page.locator('.ant-modal:visible');
 async function open(){if(old)await page.locator('input[value="root"]:visible').last().locator('xpath=ancestor::div[@class="ant-row-flex ant-row-flex-middle"][1]').locator('.anticon-setting').click();else await page.locator('.schema-editor-modern:visible').getByRole('tab',{name:'JSON（完整 Schema）',exact:true}).click();}
 async function value(){return old?await modal.locator('.ace_editor').evaluate(e=>e.env.editor.getValue()):page.getByLabel('JSON Schema',{exact:true}).inputValue();}
 await open();expect(JSON.parse(await value())).toEqual(initial);if(old){const input=modal.locator('.ace_text-input');await input.focus();await input.press('ControlOrMeta+A');await page.keyboard.insertText(source);await modal.getByRole('button',{name:/^确\s*定$/}).click();}else{await page.getByLabel('JSON Schema',{exact:true}).fill(source);await page.locator('.schema-editor-modern:visible').getByRole('tab',{name:'可视化 Schema',exact:true}).click();await open();expect(await value()).toBe(source);}
 const reply=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/interface/up'&&r.request().method()==='POST');await page.getByRole('button',{name:/^保\s*存$/}).click();const response=await reply,result=await response.json();if(!old&&role!=='guest')expect(response.request().postDataJSON()[field]).toBe(source);expect(result.errcode===0).toBe(role!=='guest');await expect(page.getByText(role==='guest'?/没有权限/:'保存成功').first()).toBeVisible();const expected=role==='guest'?initial:changed;expect(await read()).toEqual(expected);
 const {execFileSync}=require('node:child_process');const row=JSON.parse(execFileSync('docker',['exec','parity-fast-interfaces-mongo-'+info.project.name,old?'mongo':'mongosh','--quiet','--eval','db=db.getSiblingDB("parity_fast_interfaces_'+info.project.name+'");print(JSON.stringify(db.interface.findOne({_id:'+id+'},{_id:1,res_body:1,req_body_other:1})));'],{encoding:'utf8'}));expect(JSON.parse(row[field])).toEqual(expected);if(!old&&role!=='guest')expect(row[field]).toBe(source);await info.attach('schema-json-db',{body:JSON.stringify(row),contentType:'application/json'});
 await page.reload();await page.getByRole('tab',{name:'编辑',exact:true}).click();await open();expect(JSON.parse(await value())).toEqual(expected);if(!old&&role!=='guest')expect(await value()).toBe(row[field]);await page.screenshot({path:info.outputPath('full-source-roundtrip.png')});await info.attach('source-capability',{body:JSON.stringify({oldFullTab:!old,legacyAlternative:old?'root advanced source':null,role}),contentType:'application/json'});
});
