const {test,expect}=require('@playwright/test');
const fs=require('node:fs/promises');
async function login(page,role='owner'){await page.context().clearCookies();await page.goto('/login');await page.getByPlaceholder('Email',{exact:true}).fill(role+'@ui-parity.invalid');await page.getByPlaceholder('Password',{exact:true}).fill('SyntheticParityOnly_901000!');await page.getByRole('button',{name:/^登\s*录$/}).click();await expect(page).toHaveURL(/\/group/);}
async function select(page,locator,text){await locator.click();const menu=page.locator('.ant-select-dropdown:visible');for(let i=0;i<16&&!(await menu.getByText(text,{exact:true}).last().isVisible());i++){await menu.hover();await page.mouse.wheel(0,260);await page.waitForTimeout(80)}await menu.getByText(text,{exact:true}).last().click();}
async function responseFor(page,path,action){const pending=page.waitForResponse(r=>new URL(r.url()).pathname===path);await action();const r=await pending;expect(r.status()).toBe(200);const b=await r.json();expect(b.errcode,JSON.stringify(b)).toBe(0);await dbReadback(test.info(),path,r.request().postDataJSON()||Object.fromEntries(new URL(r.url()).searchParams),b.data);return b.data;}
async function fixtureProject(page,info,kind){const r=await(await page.request.post('/api/project/add',{data:{name:'Synthetic B '+kind+' '+Date.now(),group_id:901000,project_type:'private'}})).json();expect(r.errcode).toBe(0);return r.data._id;}
for(const role of ['owner','developer'])test('collection CRUD cancel reopen clone delete '+role,async({page},info)=>{
 page.setDefaultTimeout(12000);await login(page,role);await page.goto('/project/901001/interface/col/901040');const name='Synthetic collection '+role+' '+info.project.name+' '+Date.now();
 await page.getByRole('button',{name:'添加集合',exact:true}).click();const dialog=page.getByRole('dialog');await dialog.locator('#colName').fill('Discarded');await dialog.getByRole('button',{name:/取\s*消/}).click();await page.getByRole('button',{name:'添加集合',exact:true}).click();await expect(dialog.locator('#colName')).toHaveValue('');await dialog.locator('#colName').fill(name);await dialog.locator('#colDesc').fill('Synthetic collection only');const created=await responseFor(page,'/api/col/add_col',()=>dialog.getByRole('button',{name:/确\s*定/}).click());await info.attach('created-collection',{body:JSON.stringify({created,name}),contentType:'application/json'});
 let row=page.locator('.menu-title').filter({has:page.getByText(name,{exact:true})});await row.hover();await row.locator('.anticon-edit').click();await expect(dialog.locator('#colName')).toHaveValue(name);await dialog.locator('#colName').fill(name+' edited');await responseFor(page,'/api/col/up_col',()=>dialog.getByRole('button',{name:/确\s*定/}).click());await page.reload();row=page.locator('.menu-title').filter({has:page.getByText(name+' edited',{exact:true})});await expect(row).toBeVisible();await row.hover();await responseFor(page,'/api/col/add_col',()=>row.locator('.anticon-copy').click());const copy=page.locator('.menu-title').filter({has:page.getByText(name+' edited copy',{exact:true})});await expect(copy).toBeVisible();
 await page.mouse.move(1000,160);await copy.hover();await copy.locator('.anticon-delete').click();await page.getByRole('button',{name:/取\s*消/}).click();await expect(copy).toBeVisible();await page.mouse.move(1000,160);await copy.hover();await copy.locator('.anticon-delete').click();await responseFor(page,'/api/col/del_col',()=>page.getByRole('button',{name:/确\s*认/}).click());await expect(copy).toHaveCount(0);await expect(row).toBeVisible();await row.hover();await row.locator('.anticon-delete').click();await responseFor(page,'/api/col/del_col',()=>page.getByRole('button',{name:/确\s*认/}).click());await expect(row).toHaveCount(0);await expect(page.getByRole('dialog')).toHaveCount(0);await page.goto('/project/901001/interface/col/901040');await expect(page.getByRole('cell',{name:'Synthetic GET sample',exact:true})).toContainText('Synthetic GET sample');await page.screenshot({path:info.outputPath('collection-tree-after-cleanup.png'),fullPage:true});
});
test('collection case order persists and guest cannot reorder',async({page,browser},info)=>{
 page.setDefaultTimeout(12000);await login(page);const id=await fixtureProject(page,info,'ordering');const cat=(await(await page.request.get('/api/interface/getCatMenu?project_id='+id)).json()).data[0];const iface=await(await page.request.post('/api/interface/add',{data:{project_id:id,catid:cat._id,title:'Order source',path:'/order',method:'GET'}})).json();expect(iface.errcode).toBe(0);const col=await(await page.request.post('/api/col/add_col',{data:{project_id:id,name:'Synthetic order collection'}})).json();expect(col.errcode).toBe(0);const cases=[];for(let i=0;i<3;i++){const r=await(await page.request.post('/api/col/add_case',{data:{project_id:id,col_id:col.data._id,interface_id:iface.data._id,casename:'Order case '+i}})).json();expect(r.errcode).toBe(0);cases.push(r.data._id)}await page.request.post('/api/col/up_case_index',{data:cases.map((id,index)=>({id,index}))});const member=await(await page.request.post('/api/project/add_member',{data:{id,member_uids:[910004],role:'guest'}})).json();expect(member.errcode).toBe(0);
 await page.goto('/project/'+id+'/interface/col/'+col.data._id);await expect(page.getByRole('cell',{name:'Order case 2',exact:true})).toBeVisible();
 if(info.project.name==='new'){await expect(page.getByRole('button',{name:'上移用例 Order case 0',exact:true})).toBeDisabled();await expect(page.getByRole('button',{name:'下移用例 Order case 2',exact:true})).toBeDisabled();await responseFor(page,'/api/col/up_case_index',()=>page.getByRole('button',{name:'下移用例 Order case 0',exact:true}).click());}else{const src=page.getByRole('row').filter({has:page.getByRole('cell',{name:'Order case 0',exact:true})}),dst=page.getByRole('row').filter({has:page.getByRole('cell',{name:'Order case 1',exact:true})});await responseFor(page,'/api/col/up_case_index',()=>src.dragTo(dst));}
 await page.reload();await expect(page.getByRole('cell',{name:'Order case 2',exact:true})).toBeVisible();const getOrder=async()=>{const r=await(await page.request.get('/api/col/case_list?col_id='+col.data._id)).json();return r.data.map(x=>x._id)};const before=await getOrder();expect(before).toEqual([cases[1],cases[0],cases[2]]);
 const sourceCase=page.locator('.menu-title[title="Order case 0"]');await sourceCase.hover();const cloned=await responseFor(page,'/api/col/add_case',()=>sourceCase.locator('.anticon-copy').click());expect(cloned.casename).toBe('Order case 0_copy');const cloneRow=page.locator('.menu-title[title="Order case 0_copy"]');await expect(cloneRow).toBeVisible();await page.mouse.move(1000,160);await cloneRow.hover();await cloneRow.locator('.anticon-delete').click();await page.getByRole('button',{name:/取\s*消/}).click();expect((await(await page.request.get('/api/col/case?caseid='+cloned._id)).json()).errcode).toBe(0);await page.mouse.move(1000,160);await cloneRow.hover();await cloneRow.locator('.anticon-delete').click();await responseFor(page,'/api/col/del_case',()=>page.getByRole('button',{name:/确\s*认/}).click());await expect(cloneRow).toHaveCount(0);expect(await getOrder()).toEqual(before);
 const guest=await browser.newContext({baseURL:info.project.use.baseURL,viewport:{width:1920,height:1080}});const gp=await guest.newPage();await login(gp,'outsider');await gp.goto('/project/'+id+'/interface/col/'+col.data._id);await expect(gp.getByRole('cell',{name:'Order case 2',exact:true})).toBeVisible();const denial=await(await gp.request.post('/api/col/up_case_index',{data:cases.map((id,index)=>({id,index}))})).json();await info.attach('guest-order-result',{body:JSON.stringify(denial),contentType:'application/json'});if(info.project.name==='new'){expect(denial.errcode).not.toBe(0);expect(await getOrder()).toEqual(before);await expect(gp.getByRole('button',{name:/[上下]移用例/})).toHaveCount(0);}else{await info.attach('legacy-order-permission-defect',{body:'Old endpoint permits guest reorder; synthetic owner restores expected order.',contentType:'text/plain'});await page.request.post('/api/col/up_case_index',{data:before.map((id,index)=>({id,index}))})}await guest.close();
});

for(const role of ['owner','developer'])test('rules persist cancellation and rejected response '+role,async({page},info)=>{
 page.setDefaultTimeout(10000);await login(page,role);await page.goto('/project/901001/interface/col/901040');await page.getByRole('button',{name:'通用规则配置',exact:true}).click();const d=page.getByRole('dialog');const original=await d.getByPlaceholder('字段名',{exact:true}).inputValue();await d.getByPlaceholder('字段名',{exact:true}).fill('discarded');await d.getByRole('button',{name:/取\s*消/}).click();await page.getByRole('button',{name:'通用规则配置',exact:true}).click();const reopened=await d.getByPlaceholder('字段名',{exact:true}).inputValue();await info.attach('cancel-observation',{body:JSON.stringify({original,reopened}),contentType:'application/json'});if(info.project.name==='new')expect.soft(reopened).toBe(original);await d.getByPlaceholder('字段名',{exact:true}).fill('syntheticCode');await d.getByPlaceholder('值',{exact:true}).fill('7');if(info.project.name==='old'){const pending=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/col/up_col');await d.getByRole('button',{name:/确\s*定/}).click();const result=await(await pending).json();expect(result.errcode).toBe(400);await info.attach('legacy-save-failure',{body:JSON.stringify({errcode:result.errcode,reason:'immutable _id'}),contentType:'application/json'});return;}await responseFor(page,'/api/col/up_col',()=>d.getByRole('button',{name:/确\s*定/}).click());await expect(page.getByText('配置测试集成功',{exact:true})).toBeVisible();await page.reload();await page.getByRole('button',{name:'通用规则配置',exact:true}).click();await expect(d.getByPlaceholder('字段名',{exact:true})).toHaveValue('syntheticCode');await expect(d.getByPlaceholder('值',{exact:true})).toHaveValue('7');await d.getByPlaceholder('字段名',{exact:true}).fill('code');await d.getByPlaceholder('值',{exact:true}).fill('0');await responseFor(page,'/api/col/up_col',()=>d.getByRole('button',{name:/确\s*定/}).click());
 await page.getByRole('button',{name:'通用规则配置',exact:true}).click();await d.getByPlaceholder('字段名',{exact:true}).fill('rejected');await page.route('**/api/col/up_col',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({errcode:403,errmsg:'Synthetic save rejected'})}));await d.getByRole('button',{name:/确\s*定/}).click();await expect(page.getByText('Synthetic save rejected',{exact:true})).toBeVisible();if(info.project.name==='new')await expect.soft(d).toBeVisible();await page.screenshot({path:info.outputPath('rules-rejection.png')});
});

test('docs local fixture preview discard accept history restore new-only',async({page},info)=>{
 test.skip(info.project.name==='old','new-only: no historical AI feature');page.setDefaultTimeout(30000);await login(page);const reset=await page.request.post('/api/documentation/restore',{headers:{'X-YApi-Docs-Intent':'review'},data:{projectId:901001,interfaceId:901003,version:0}});expect((await reset.json()).errcode).toBe(0);await page.goto('/project/901001/interface/api/901003');const read=async()=>(await(await page.request.get('/api/interface/get?id=901003')).json()).data;const before=await read();await page.getByTestId('documentation-ai-button').click();const d=page.getByRole('dialog');await expect(d.getByTestId('documentation-outbound')).toBeVisible();await expect(d.getByRole('button',{name:/生成文档建议$/})).toBeDisabled();await d.getByRole('checkbox').check();await responseFor(page,'/api/documentation/proposal',()=>d.getByRole('button',{name:/生成文档建议$/}).click());await expect(d.getByRole('region',{name:'AI 文档建议预览'})).toBeVisible();expect((await read()).markdown).toBe(before.markdown);await d.getByRole('button',{name:'丢弃建议',exact:true}).click();await expect(d.getByRole('region',{name:'AI 文档建议预览'})).toHaveCount(0);expect((await read()).markdown).toBe(before.markdown);await responseFor(page,'/api/documentation/proposal',()=>d.getByRole('button',{name:/生成文档建议$/}).click());await page.screenshot({path:info.outputPath('docs-preview.png')});await responseFor(page,'/api/documentation/accept',()=>d.getByRole('button',{name:'审核完成，采纳此建议',exact:true}).click());await expect(d.getByRole('heading',{name:'文档修订历史',exact:true})).toBeVisible();expect((await read()).markdown).toContain('Controlled local fixture');await d.getByRole('button',{name:'恢复原始文档（版本 0）',exact:true}).click();const restore=page.getByRole('dialog',{name:'确认恢复文档'});await restore.getByRole('button',{name:/取\s*消/}).click();expect((await read()).markdown).toContain('Controlled local fixture');await d.getByRole('button',{name:'恢复原始文档（版本 0）',exact:true}).click();await responseFor(page,'/api/documentation/restore',()=>restore.getByRole('button',{name:'确认恢复',exact:true}).click());expect((await read()).markdown).toBe(before.markdown);expect((await read()).req_query.map(({_id,...x})=>x)).toEqual(before.req_query.map(({_id,...x})=>x));await page.keyboard.press('Escape');await page.reload();await page.getByTestId('documentation-ai-button').click();await d.getByRole('button',{name:'查看历史与恢复',exact:true}).click();await expect(d.getByRole('heading',{name:'文档修订历史',exact:true})).toBeVisible();await page.screenshot({path:info.outputPath('docs-restored.png')});
});

for(const role of ['owner','developer'])test('mock expectation rows cancel save match disable delete '+role,async({page},info)=>{
 page.setDefaultTimeout(10000);await login(page,role);await page.goto('/project/901001/interface/api/901014');await page.getByText('高级Mock',{exact:true}).click();const open=()=>page.getByRole('button',{name:'添加期望',exact:true}).click();await open();const d=page.getByRole('dialog');await d.getByPlaceholder('请输入期望名称',{exact:true}).fill('Discarded synthetic');await d.getByRole('button',{name:/取\s*消/}).click();await open();await expect(d.getByPlaceholder('请输入期望名称',{exact:true})).not.toHaveValue('Discarded synthetic');const name='Synthetic B expectation '+role+' '+Date.now();await d.getByPlaceholder('请输入期望名称',{exact:true}).fill(name);await d.getByRole('button',{name:/添加参数/}).click();await expect(d.locator('.paramsArr')).toHaveCount(2);await d.locator('.paramsArr').last().locator('.dynamic-delete-button').click();await d.locator('.paramsArr').first().locator('input').first().fill('verbose');await d.locator('.paramsArr').first().getByPlaceholder('参数值').fill('yes');await d.locator('.headers').first().locator('input').first().fill('X-Synthetic');await d.locator('.headers').first().getByPlaceholder('参数值').fill('paired');const created=await responseFor(page,'/api/plugin/advmock/case/save',()=>d.getByRole('button',{name:/确\s*定/}).click());await expect(d).toHaveCount(0);const row=page.getByRole('row').filter({has:page.getByText(name,{exact:true})});await expect(row).toBeVisible();await page.reload();await page.getByText('高级Mock',{exact:true}).click();await expect(row).toBeVisible();const r=await page.request.post('/mock/901001/raw-json?verbose=yes',{data:{message:'synthetic'}});expect(r.status()).toBe(200);expect(r.headers()['x-synthetic']).toBe('paired');expect((await r.json()).code).toBe(0);await row.getByRole('button',{name:/编\s*辑/}).click();await expect(d.getByPlaceholder('请输入期望名称',{exact:true})).toHaveValue(name);await expect(d.locator('.paramsArr').first().getByPlaceholder('参数值')).toHaveValue('yes');await d.getByRole('button',{name:/取\s*消/}).click();await responseFor(page,'/api/plugin/advmock/case/hide',()=>row.getByRole('button',{name:'已开启',exact:true}).click());const off=await page.request.post('/mock/901001/raw-json?verbose=yes',{data:{message:'synthetic'}});expect(off.headers()['x-synthetic']).toBeUndefined();await page.screenshot({path:info.outputPath('mock-disabled.png')});await row.getByRole('button',{name:/删\s*除/}).click();await page.getByRole('button',{name:/取\s*消/}).click();await expect(row).toBeVisible();await row.getByRole('button',{name:/删\s*除/}).click();await responseFor(page,'/api/plugin/advmock/case/del',()=>page.getByRole('button',{name:/确\s*定/}).click());await expect(row).toHaveCount(0);
});

test('case update parameters reload link and repeat send',async({page},info)=>{
 page.setDefaultTimeout(12000);await login(page);await page.goto('/project/901001/interface/case/901050');const value=page.getByPlaceholder('参数值').first();await value.fill('55');await responseFor(page,'/api/col/up_case',()=>page.getByRole('button',{name:/更\s*新/}).click());await page.reload();await expect(value).toHaveValue('55');const saved=(await(await page.request.get('/api/col/case?caseid=901050')).json()).data;expect(saved.req_params[0].value).toBe('55');await page.getByRole('button',{name:/发\s*送/}).click();await expect(page.locator('body')).toContainText('200');await page.getByRole('button',{name:/发\s*送/}).click();await expect(page.locator('body')).toContainText('200');await page.getByText('对应接口',{exact:true}).click();await expect(page).toHaveURL(/\/api\/901003/);await page.goBack();await expect(value).toHaveValue('55');await page.screenshot({path:info.outputPath('case-saved.png')});await value.fill('42');await responseFor(page,'/api/col/up_case',()=>page.getByRole('button',{name:/更\s*新/}).click());
});

test('collection run repeat start reports reload',async({page},info)=>{
 page.setDefaultTimeout(12000);await login(page);await page.goto('/project/901001/interface/col/901040');await expect(page.getByRole('cell',{name:'Synthetic form',exact:true})).toBeVisible();let calls=0;await page.route('**/api/interface/proxy',async route=>{calls++;await new Promise(r=>setTimeout(r,250));await route.continue()});const saves=[];page.on('response',async r=>{if(new URL(r.url()).pathname==='/api/col/up_col')saves.push((await r.json()).errcode)});const start=page.getByRole('button',{name:'开始测试',exact:true});await start.dblclick({delay:30});await expect(page.getByRole('button',{name:'测试报告',exact:true})).toHaveCount(3,{timeout:20000});await expect.poll(()=>saves.length).toBeGreaterThan(0);await info.attach('run-observation',{body:JSON.stringify({proxyCalls:calls,saveErrcodes:saves}),contentType:'application/json'});if(info.project.name==='new')expect.soft(calls).toBe(3);expect(saves.every(x=>x===0)).toBe(true);await page.getByRole('button',{name:'测试报告',exact:true}).first().click();const d=page.getByRole('dialog');await expect(d).toBeVisible();await page.screenshot({path:info.outputPath('collection-report.png')});await d.locator('.ant-modal-close').click();await page.getByRole('button',{name:'测试报告',exact:true}).last().click();await expect(d).toBeVisible();await d.locator('.ant-modal-close').click();await page.reload();await expect(page.getByRole('button',{name:'测试报告',exact:true})).toHaveCount(3);
});

for(const role of ['owner','developer'])test('runner expression cancel apply and save inline collection '+role,async({page},info)=>{
 page.setDefaultTimeout(10000);await login(page,role);await page.goto('/project/901001/interface/api/901003');await page.getByText('运行',{exact:true}).click();const input=page.getByPlaceholder('参数值').first();await input.fill('42');const edit=page.locator('.ant-input-group-addon').filter({has:page.locator('.anticon-edit')}).first();await edit.click();let d=page.getByRole('dialog');await d.getByPlaceholder('基础参数值',{exact:true}).fill('discarded');await d.getByRole('button',{name:/取\s*消/}).click();await expect(input).toHaveValue('42');await edit.click();await expect(d.getByPlaceholder('基础参数值',{exact:true})).toHaveValue('');await d.getByPlaceholder('基础参数值',{exact:true}).fill('77');await d.getByRole('button',{name:/插\s*入/}).click();await expect(input).toHaveValue(/77/);await page.getByRole('button',{name:/保\s*存/}).click();d=page.getByRole('dialog',{name:'添加到集合'});await d.getByPlaceholder('请输入接口用例名称').fill('Discarded case');await d.getByRole('button',{name:/取\s*消/}).click();await page.getByRole('button',{name:/保\s*存/}).click();const name='Synthetic inline '+role+' '+Date.now();await d.getByPlaceholder('请输入接口用例名称').fill(name+' case');await d.getByText('添加新集合',{exact:true}).click();await d.getByPlaceholder('请输入集合名称',{exact:true}).fill(name);await d.getByPlaceholder('请输入集合描述',{exact:true}).fill('Synthetic inline fixture');const col=await responseFor(page,'/api/col/add_col',()=>d.getByRole('button',{name:/^添\s*加$/}).click());await expect(d.locator('.col-item.selected')).toContainText(name);const c=await responseFor(page,'/api/col/add_case',()=>d.getByRole('button',{name:/确\s*定/}).click());await expect(d).toHaveCount(0);const data=(await(await page.request.get('/api/col/case?caseid='+c._id)).json()).data;expect(data.col_id).toBe(col._id);if(info.project.name==='new')expect(data.casename).toBe(name+' case');expect(data.req_params[0].value).toContain('77');await page.goto('/project/901001/interface/case/'+c._id);await expect(page.getByPlaceholder('参数值').first()).toHaveValue(/77/);await page.screenshot({path:info.outputPath('inline-saved-case.png')});
});

test('collection import cancel reopen source switch clears selected IDs',async({page},info)=>{
 page.setDefaultTimeout(10000);await login(page);const name='Synthetic import '+Date.now();const c=(await(await page.request.post('/api/col/add_col',{data:{project_id:901001,name}})).json()).data;await page.goto('/project/901001/interface/col/'+c._id);const row=page.locator('.menu-title').filter({has:page.getByText(name,{exact:true})});await row.hover();await row.locator('.anticon-plus').click();const d=page.getByRole('dialog',{name:'导入接口到集合'});await expect(d.getByRole('row').filter({has:page.getByText('01 Rich examples',{exact:true})})).toBeVisible();const cat=d.getByRole('row').filter({has:page.getByText('01 Rich examples',{exact:true})});await cat.getByRole('checkbox').check();await d.getByRole('button',{name:/取\s*消/}).click();await row.hover();await row.locator('.anticon-plus').click();const count=await d.getByRole('checkbox',{checked:true}).count();await info.attach('import-reopen',{body:JSON.stringify({checked:count}),contentType:'application/json'});if(info.project.name==='new')expect.soft(count).toBe(0);await select(page,d.locator('.select-project .ant-select'),'Synthetic public project');await expect(d.getByText('Public endpoints',{exact:true})).toBeVisible();await expect(d.getByRole('checkbox',{checked:true})).toHaveCount(0);if(info.project.name==='new'){
 let submitted=0;page.on('request',r=>{if(new URL(r.url()).pathname==='/api/col/add_case_list')submitted++});await d.getByRole('button',{name:/确\s*定/}).click();await expect(page.getByText('请选择要导入的接口',{exact:true})).toBeVisible();expect(submitted).toBe(0);expect((await(await page.request.get('/api/col/case_list?col_id='+c._id)).json()).data).toHaveLength(0);
 await d.getByRole('row').filter({has:page.getByText('Public endpoints',{exact:true})}).getByRole('checkbox').check();await responseFor(page,'/api/col/add_case_list',()=>d.getByRole('button',{name:/确\s*定/}).click());const data=(await(await page.request.get('/api/col/case_list?col_id='+c._id)).json()).data;expect(data.map(x=>x.interface_id)).toEqual([901019]);await page.reload();await expect(page.getByRole('cell',{name:'Public sample',exact:true})).toBeVisible();
 }else{const req=page.waitForRequest(r=>new URL(r.url()).pathname==='/api/col/add_case_list');await d.getByRole('button',{name:/确\s*定/}).click();const payload=(await req).postDataJSON();await info.attach('legacy-hidden-selected-ids',{body:JSON.stringify({ids:payload.interface_list,source:payload.project_id}),contentType:'application/json'});}
 await page.screenshot({path:info.outputPath('import-source-changed.png')});
});
async function dbReadback(info, endpoint, request, result) {
 if(process.env.PARITY_DB_READBACK!=='1')return;
 const map={add_col:['interface_col',result&&result._id],up_col:['interface_col',request.col_id],del_col:['interface_col',request.col_id||request.id],add_case:['interface_case',result&&result._id],up_case:['interface_case',request.id],del_case:['interface_case',request.id||request.caseid]};
 const operation=endpoint.split('/').pop();const target=map[operation];if(!target||!Number.isSafeInteger(Number(target[1])))return;
 const [collection,rawId]=target,id=Number(rawId),version=info.project.name;
 const projection={_id:1,name:1,casename:1,col_id:1,project_id:1,interface_id:1,index:1,checkHttpCodeIs200:1,checkResponseField:1,checkResponseSchema:1,req_params:1};
 const script=`var marker=${version==='new'?'await ':''}db.getCollection('_ui_parity_fixture').findOne({synthetic:true});if(!marker)throw Error('Unmarked DB');var readbackRows = ${version==='new'?'await ':''}db.getCollection(${JSON.stringify(collection)}).find({_id:${id}},${JSON.stringify(projection)}).toArray();print(JSON.stringify(readbackRows))`;
 const {execFileSync}=require('node:child_process');const data=JSON.parse(execFileSync('docker',['exec','parity-fast-collections-'+version+'-mongo',version==='new'?'mongosh':'mongo','--quiet','mongodb://127.0.0.1:27017/parity_fast_collections_'+version+'_fastb1003','--eval',version==='new'?'(async()=>{'+script+'})()':script],{encoding:'utf8'}).trim());
 expect(data.length).toBe(operation.startsWith('del_')?0:1);await info.attach('db-'+operation+'-'+id,{body:JSON.stringify(data),contentType:'application/json'});
}

for(const role of ['owner','developer','outsider'])test('collection tree search clear route and role boundary '+role,async({page},info)=>{
 page.setDefaultTimeout(10000);await login(page);if(role==='outsider'){const result=await(await page.request.post('/api/project/add_member',{data:{id:901001,member_uids:[910004],role:'guest'}})).json();expect(result.errcode).toBe(0);}if(role!=='owner')await login(page,role);await page.goto('/project/901001/interface/col/901040');await expect(page.getByRole('cell',{name:'Synthetic GET sample',exact:true})).toBeVisible();const search=page.getByPlaceholder('搜索测试集合');await search.fill('Synthetic GET sample');await page.locator('.menu-title[title="Synthetic GET sample"]').click();await expect(page).toHaveURL(/\/case\/901050$/);await search.fill('');if(info.project.name==='old'){await info.attach('legacy-filter-clear-observation',{body:JSON.stringify({restored:await page.locator('.menu-title[title="Synthetic raw JSON"]').isVisible()}),contentType:'application/json'});await page.reload();}await expect(page.locator('.menu-title[title="Synthetic raw JSON"]')).toBeVisible();await page.locator('.menu-title[title="Synthetic raw JSON"]').click();await expect(page).toHaveURL(/\/case\/901051$/);await page.goBack();await expect(page).toHaveURL(/\/case\/901050$/);await page.screenshot({path:info.outputPath('tree-search-'+role+'.png')});
 if(role==='outsider'){await page.goto('/project/901001/interface/api/901014');await page.getByText('高级Mock',{exact:true}).click();await expect(page.getByRole('button',{name:'添加期望',exact:true})).toBeDisabled();const denied=await(await page.request.post('/api/plugin/advmock/case/save',{data:{interface_id:901014,project_id:901001,name:'Denied guest',res_body:'{}'}})).json();expect(denied.errcode).not.toBe(0);const read=(await(await page.request.get('/api/col/case_list?col_id=901040')).json()).colData;expect((await(await page.request.post('/api/col/up_col',{data:{col_id:901040,checkHttpCodeIs200:!read.checkHttpCodeIs200}})).json()).errcode).not.toBe(0);}
});

test('collection route change discards pending run response new-only',async({page},info)=>{
 test.skip(info.project.name==='old','legacy late-run behavior characterized separately');page.setDefaultTimeout(10000);await login(page);await page.goto('/project/901001/interface/col/901040');await expect(page.getByRole('cell',{name:'Synthetic GET sample',exact:true})).toBeVisible();let release;const gate=new Promise(r=>release=r);let entered;const started=new Promise(r=>entered=r);await page.route('**/api/interface/proxy',async route=>{entered();await Promise.race([gate,new Promise(r=>setTimeout(r,5000))]);await route.continue()});const saved=[];page.on('request',r=>{if(new URL(r.url()).pathname==='/api/col/up_col')saved.push(r.postDataJSON().col_id)});await page.getByRole('button',{name:'开始测试',exact:true}).click();await Promise.race([started,new Promise((_,reject)=>setTimeout(()=>reject(Error('Request did not start')),10000))]);await page.locator('.menu-title').filter({has:page.getByText('Empty collection',{exact:true})}).click();await expect(page).toHaveURL(/\/col\/901041$/);release();await expect(page.getByRole('button',{name:'开始测试',exact:true})).toBeEnabled();await page.waitForTimeout(700);expect(saved).toEqual([]);await expect(page.getByRole('button',{name:'测试报告',exact:true})).toHaveCount(0);await page.screenshot({path:info.outputPath('pending-route-changed.png')});
});
