const {test,expect}=require('@playwright/test');
async function login(page,role='admin'){await page.goto('/login');await page.getByPlaceholder('Email',{exact:true}).fill(role+'@ui-parity.invalid');await page.getByPlaceholder('Password',{exact:true}).fill('SyntheticParityOnly_901000!');await page.getByRole('button',{name:/^登\s*录$/}).click();await expect(page).toHaveURL(/\/group/);}
async function choice(page,el,text){await el.click();await page.locator('.ant-select-dropdown:visible').getByText(text,{exact:true}).last().click();}
async function post(page,path,action){const p=page.waitForResponse(r=>new URL(r.url()).pathname===path&&r.request().method()==='POST');await action();const b=await(await p).json();expect(b.errcode).toBe(0);return b.data;}
for(const actor of ['admin','owner'])test('group selected member roles duplicate and cancel deletion persist exact member '+actor,async({page},info)=>{
 page.setDefaultTimeout(10000);await login(page);const created=await(await page.request.post('/api/group/add',{data:{group_name:'Synthetic members '+info.project.name+' '+Date.now(),group_desc:'Synthetic only',owner_uids:[910002]}})).json();expect(created.errcode).toBe(0);const id=created.data._id;if(actor==='owner')await login(page,'owner');
 await page.goto('/group/'+id);await page.getByRole('tab',{name:'成员列表',exact:true}).click();await page.getByRole('button',{name:/添加成员$/}).click();const dialog=page.getByRole('dialog');await dialog.locator('.ant-select input').first().fill('Synthetic outsider');await page.locator('.ant-select-dropdown:visible').getByText('Synthetic outsider',{exact:true}).click();await choice(page,dialog.locator('.ant-select').last(),'访客');await post(page,'/api/group/add_member',()=>dialog.getByRole('button',{name:/确\s*定/}).click());
 const row=page.getByRole('row').filter({has:page.getByText('Synthetic outsider',{exact:true})});await expect(row).toContainText('访客');for(const role of ['开发者','组长','访客']){await post(page,'/api/group/change_member_role',()=>choice(page,row.locator('.ant-select'),role));await page.reload();await page.getByRole('tab',{name:'成员列表',exact:true}).click();await expect(row).toContainText(role);}
 const duplicate=await(await page.request.post('/api/group/add_member',{data:{id,member_uids:[910004],role:'guest'}})).json();expect(duplicate.errcode).toBe(0);expect(duplicate.data.add_members).toHaveLength(0);expect(duplicate.data.exist_members).toHaveLength(1);await expect(row).toHaveCount(1);
 await row.locator('.btn-danger').click();await page.locator('body').click({position:{x:1000,y:800}});await expect(row).toBeVisible();await row.locator('.btn-danger').click();await post(page,'/api/group/del_member',()=>page.getByRole('button',{name:/确\s*定/}).click());await expect(row).toHaveCount(0);await page.reload();await page.getByRole('tab',{name:'成员列表',exact:true}).click();await expect(row).toHaveCount(0);await page.screenshot({path:info.outputPath('group-members.png'),fullPage:true});
});
for(const role of ['developer','outsider'])test('group nonowner UI and direct member mutations denied '+role,async({page},info)=>{
 page.setDefaultTimeout(10000);await login(page);const made=await(await page.request.post('/api/group/add',{data:{group_name:'Synthetic denial '+Date.now(),group_desc:'Synthetic only',owner_uids:[910002]}})).json();expect(made.errcode).toBe(0);const id=made.data._id,uid=role==='developer'?910003:910004;expect((await(await page.request.post('/api/group/add_member',{data:{id,member_uids:[uid],role:role==='developer'?'dev':'guest'}})).json()).errcode).toBe(0);await login(page,role);await page.goto('/group/'+id);await page.getByRole('tab',{name:'成员列表',exact:true}).click();await expect(page.getByRole('button',{name:/添加成员$/})).toHaveCount(0);for(const [endpoint,data]of [['change_member_role',{id,member_uid:uid,role:'owner'}],['del_member',{id,member_uid:910002}],['add_member',{id,member_uids:[role==='developer'?910004:910003],role:'owner'}]]){const r=await(await page.request.post('/api/group/'+endpoint,{data})).json();const after=await(await page.request.get('/api/group/get_member_list?id='+id)).json();await info.attach('direct-'+endpoint,{body:JSON.stringify({group:id,actor:uid,errcode:r.errcode,members:after.data.map(({uid,role})=>({uid,role}))}),contentType:'application/json'});expect(r.errcode).not.toBe(0);}const result=(await(await page.request.get('/api/group/get_member_list?id='+id)).json()).data;expect(result.find(x=>x.uid===uid).role).toBe(role==='developer'?'dev':'guest');expect(result.find(x=>x.uid===910002).role).toBe('owner');await page.screenshot({path:info.outputPath('group-denial.png'),fullPage:true});
});
