const {test,expect}=require('@playwright/test');
test.beforeEach(async({page})=>page.setDefaultTimeout(12000));
async function api(page,url,data){const r= data===undefined?await page.request.get(url):await page.request.post(url,{data});expect(r.status(),url).toBe(200);const b=await r.json();expect(b.errcode,url).toBe(0);return b.data;}
async function login(page,role='owner'){await page.context().clearCookies();await page.goto('/login');await page.getByPlaceholder('Email',{exact:true}).fill(role+'@ui-parity.invalid');await page.getByPlaceholder('Password',{exact:true}).fill('SyntheticParityOnly_901000!');await page.getByRole('button',{name:/^登\s*录$/}).click();await expect(page).toHaveURL(/group/);}
async function setup(page,count=2){await login(page);const p=await api(page,'/api/project/add',{name:'Synthetic B closure '+Date.now(),group_id:901000,project_type:'private'});await api(page,'/api/project/up',{id:p._id,env:[{name:'local',domain:'http://127.0.0.1:3000/mock/'+p._id}]});const cat=(await api(page,'/api/interface/getCatMenu?project_id='+p._id))[0];const i=await api(page,'/api/interface/add',{project_id:p._id,catid:cat._id,title:'Closure source',path:'/closure',method:'GET'});await api(page,'/api/interface/up',{id:i._id,res_body_type:'json',res_body_is_json_schema:false,res_body:'{"code":0,"text":"合成测试"}',req_query:[{name:'first',required:'0',desc:'first',example:'one'},{name:'second',required:'0',desc:'second',example:'two'}]});const col=await api(page,'/api/col/add_col',{project_id:p._id,name:'Closure collection'});const cases=[];for(let n=0;n<count;n++)cases.push(await api(page,'/api/col/add_case',{project_id:p._id,col_id:col._id,interface_id:i._id,casename:'Closure case '+n}));const fixture={project:p._id,iface:i._id,col:col._id,cases};page.scopeBFixture=fixture;return fixture;}
async function saveResponse(page,path,action){const wait=page.waitForResponse(r=>new URL(r.url()).pathname===path);await action();const b=await(await wait).json();expect(b.errcode,path).toBe(0);return b.data;}
async function select(page,loc,text){await loc.scrollIntoViewIfNeeded();await loc.click();const input=loc.locator('input');if(await input.isEditable()){await input.fill(text);await page.keyboard.press('ArrowDown');await page.keyboard.press('Enter');}else{await page.locator('.ant-select-dropdown:visible .ant-select-item-option-content').getByText(text,{exact:true}).click();}await expect(loc).toContainText(text);}
async function ace(page,root,text){await expect(root).toBeVisible();await expect(root.locator('.ace_content')).toContainText('code');await root.locator('textarea').focus();await page.keyboard.press('Meta+A');await page.keyboard.insertText(text);await expect(root.locator('.ace_content')).toContainText(text);}




test.beforeEach(async({},info)=>test.skip(info.project.name==='old','new-only documentation workflow'));
async function docs(page,f,action,body){const url='/api/documentation/'+action;const ids={projectId:f.project,interfaceId:f.iface};const r=body===undefined?await page.request.get(url,{params:ids}):await page.request.post(url,{headers:{'X-YApi-Docs-Intent':'review'},data:{...ids,...body}});const result=await r.json();expect(result.errcode).toBe(0);return result.data;}
async function openDocs(page,f){await page.goto(`/project/${f.project}/interface/api/${f.iface}`);await page.getByTestId('documentation-ai-button').click();const d=page.getByRole('dialog',{name:'AI 文档助手 · 先预览，再人工采纳',exact:true});await expect(d.getByTestId('documentation-outbound')).toBeVisible();return d;}
test('AI gate binds displayed provider version payload and resets consent on close and payload change',async({page},info)=>{const f=await setup(page,0);const expected=await docs(page,f,'get');let d=await openDocs(page,f);expect(JSON.parse(await d.getByTestId('documentation-outbound').innerText())).toEqual(expected.outbound);await expect(d).toContainText(expected.provider.baseURL);await expect(d).toContainText(expected.provider.model);await expect(d).toContainText('版本 '+expected.document.version);await expect(d.getByRole('button',{name:/生成文档建议$/})).toBeDisabled();await d.getByRole('checkbox').check();await page.keyboard.press('Escape');await expect(d).toHaveCount(0);await page.getByTestId('documentation-ai-button').click();await expect(d.getByRole('checkbox')).not.toBeChecked();await d.getByRole('checkbox').check();await api(page,'/api/interface/up',{id:f.iface,markdown:'Newer local document'});const result=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/documentation/proposal');await d.getByRole('button',{name:/生成文档建议$/}).click();expect((await(await result).json()).errcode).toBe(409);await expect(d).toContainText('文档已发生变化');expect((await docs(page,f,'get')).document.markdown).toBe('Newer local document');await d.locator('.ant-modal-close').click();await page.getByTestId('documentation-ai-button').click();await expect(d.getByRole('checkbox')).not.toBeChecked();await expect(d.getByTestId('documentation-outbound')).toContainText('Newer local document');await page.screenshot({path:info.outputPath('ai-exact-payload.png'),animations:'disabled'});});
test('AI proposal transport retry is idempotent discard writes nothing and stale accept preserves legacy edit',async({page},info)=>{const f=await setup(page,0);const before=await docs(page,f,'get');const d=await openDocs(page,f);await d.getByRole('checkbox').check();const ids=[];await page.route('**/api/documentation/proposal',async r=>{ids.push(r.request().postDataJSON().requestId);if(ids.length===1){const response=await r.fetch();expect((await response.json()).errcode).toBe(0);await r.abort('failed');}else await r.continue();});await d.getByRole('button',{name:/生成文档建议$/}).click();await expect(d.getByRole('alert').filter({hasText:/Network Error|请求失败/})).toBeVisible();await saveResponse(page,'/api/documentation/proposal',()=>d.getByRole('button',{name:/生成文档建议$/}).click());expect(ids).toHaveLength(2);expect(ids[0]).toBe(ids[1]);await expect(d.getByRole('region',{name:'AI 文档建议预览'})).toBeVisible();await expect(d.getByRole('region',{name:'Markdown 差异'})).toContainText('Controlled local fixture');await expect(d.getByRole('region',{name:'req_query[0].desc 差异',exact:true})).toContainText('Synthetic reviewed query description');expect((await docs(page,f,'get')).document.version).toBe(before.document.version);await d.getByRole('button',{name:'丢弃建议',exact:true}).click();expect((await docs(page,f,'get')).document.version).toBe(before.document.version);await saveResponse(page,'/api/documentation/proposal',()=>d.getByRole('button',{name:/生成文档建议$/}).click());expect(ids[2]).not.toBe(ids[0]);await api(page,'/api/interface/up',{id:f.iface,markdown:'Concurrent synthetic legacy edit'});const accept=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/documentation/accept');await d.getByRole('button',{name:'审核完成，采纳此建议',exact:true}).dblclick({delay:10});expect((await(await accept).json()).errcode).toBe(409);await expect(d).toContainText('文档已发生变化');await expect(d.getByRole('region',{name:'AI 文档建议预览'})).toHaveCount(0);expect((await docs(page,f,'get')).document.markdown).toBe('Concurrent synthetic legacy edit');await page.screenshot({path:info.outputPath('ai-stale-accept.png'),animations:'disabled'});});
test('AI history loads earlier immutable versions without duplicates and restore cancel repeat preserves lineage',async({page},info)=>{const f=await setup(page,0);const initialVersion=(await docs(page,f,'get')).document.version;for(let i=1;i<=52;i++)await api(page,'/api/interface/up',{id:f.iface,markdown:'Synthetic historical document '+i});const d=await openDocs(page,f);await d.getByRole('button',{name:'查看历史与恢复',exact:true}).click();const region=d.getByRole('region',{name:'文档修订历史',exact:true});await expect(region.getByText('版本 52',{exact:true})).toBeVisible();await region.getByRole('button',{name:'加载更早历史',exact:true}).click();await expect(region.getByText('版本 0',{exact:true})).toBeVisible();const versions=await region.locator('strong').allTextContents();expect(versions).toHaveLength(initialVersion+53);expect(new Set(versions).size).toBe(initialVersion+53);const allHistory=await api(page,'/api/documentation/history?projectId='+f.project+'&interfaceId='+f.iface+'&limit=100');for(const index of[0,25,allHistory.revisions.length-1]){const details=region.locator('details').nth(index);await details.locator('summary').click();const snapshot=allHistory.revisions[index].after;await expect(details.locator('pre').first()).toHaveText(snapshot.markdown||snapshot.desc||'（空）');if(snapshot.descriptionSnapshot)expect(JSON.parse(await details.locator('pre').nth(1).innerText())).toEqual(snapshot.descriptionSnapshot);}await expect(region).toContainText('操作人');await expect(region).toContainText('legacy');const before=await docs(page,f,'history');await region.getByRole('button',{name:'恢复原始文档（版本 0）',exact:true}).click();const confirm=page.getByRole('dialog',{name:'确认恢复文档',exact:true});await confirm.getByRole('button',{name:/取\s*消$/}).click();expect((await docs(page,f,'history')).currentVersion).toBe(before.currentVersion);await region.getByRole('button',{name:'恢复原始文档（版本 0）',exact:true}).click();let count=0;page.on('request',r=>{if(new URL(r.url()).pathname==='/api/documentation/restore')count++});await saveResponse(page,'/api/documentation/restore',()=>confirm.getByRole('button',{name:'确认恢复',exact:true}).dblclick({delay:10}));await expect(confirm).toHaveCount(0);const after=await docs(page,f,'history');expect(after.currentVersion).toBe(before.currentVersion+1);expect(after.revisions[0].kind).toBe('restore');expect(count).toBe(1);await expect(d.getByRole('checkbox')).not.toBeChecked();await page.screenshot({path:info.outputPath('ai-history-restored.png'),animations:'disabled'});});

test('AI loading escape settles and restore confirmation cannot survive interface navigation',async({page},info)=>{const f=await setup(page,0);const cat=(await api(page,'/api/interface/getCatMenu?project_id='+f.project))[0];const other=await api(page,'/api/interface/add',{project_id:f.project,catid:cat._id,title:'Other synthetic documentation',path:'/other-doc',method:'GET'});await api(page,'/api/interface/up',{id:other._id,markdown:'Other revision'});await page.goto(`/project/${f.project}/interface/api/${f.iface}`);await page.locator('a.interface-item').filter({hasText:'Other synthetic documentation'}).click();await expect(page).toHaveURL(new RegExp('/api/'+other._id+'$'));let release,started;const gate=new Promise(r=>release=r),entered=new Promise(r=>started=r);await page.route('**/api/documentation/get?*',async r=>{started();await gate;await r.continue()});await page.getByTestId('documentation-ai-button').click();await entered;const d=page.getByRole('dialog',{name:'AI 文档助手 · 先预览，再人工采纳',exact:true});await page.keyboard.press('Escape');await expect(d).toBeVisible();release();await expect(d.getByTestId('documentation-outbound')).toBeVisible();await page.unroute('**/api/documentation/get?*');await d.getByRole('button',{name:'查看历史与恢复',exact:true}).click();await d.getByRole('button',{name:'恢复原始文档（版本 0）',exact:true}).click();await expect(page.getByRole('dialog',{name:'确认恢复文档',exact:true})).toBeVisible();await page.goBack();await expect(page).toHaveURL(new RegExp('/api/'+f.iface+'$'));await expect(page.getByRole('dialog')).toHaveCount(0);expect((await docs(page,f,'get')).document.markdown||'').toBe('');await page.screenshot({path:info.outputPath('ai-restore-navigation.png'),animations:'disabled'});});

test('AI unconfigured provider disables outbound generation in controlled UI response',async({page},info)=>{const f=await setup(page,0);await page.route('**/api/documentation/get?*',async r=>{const response=await r.fetch();const body=await response.json();expect(body.errcode).toBe(0);body.data.provider={configured:false,baseURL:null,model:null};await r.fulfill({response,json:body});});await page.goto(`/project/${f.project}/interface/api/${f.iface}`);await page.getByTestId('documentation-ai-button').click();const d=page.getByRole('dialog');await expect(d).toContainText('尚未配置 AI 服务');await expect(d.getByRole('checkbox')).toHaveCount(0);await expect(d.getByRole('button',{name:/生成文档建议$/})).toBeDisabled();await d.locator('.ant-modal-close').click();await expect(d).toHaveCount(0);await info.attach('fixture-boundary',{body:'Provider configured=false is a controlled HTTP UI fixture, not a deployment configuration claim.',contentType:'text/plain'});});

test('AI repeated acceptance commits once clears proposal consent and shows stored field snapshots',async({page},info)=>{const f=await setup(page,0);const before=await docs(page,f,'get');const d=await openDocs(page,f);await d.getByRole('checkbox').check();await saveResponse(page,'/api/documentation/proposal',()=>d.getByRole('button',{name:/生成文档建议$/}).click());await expect(d.getByRole('region',{name:'描述（HTML 源码，安全文本显示） 差异',exact:true})).toContainText('<h2>');await expect(d.getByRole('region',{name:'AI 文档建议预览'}).locator('h2')).toHaveCount(0);let writes=0;await page.route('**/api/documentation/accept',async r=>{writes++;await new Promise(r=>setTimeout(r,250));await r.continue();});await saveResponse(page,'/api/documentation/accept',()=>d.getByRole('button',{name:'审核完成，采纳此建议',exact:true}).dblclick({delay:15}));await expect(d.getByRole('region',{name:'AI 文档建议预览'})).toHaveCount(0);await expect(d.getByRole('checkbox')).not.toBeChecked();expect(writes).toBe(1);const after=await docs(page,f,'get');expect(after.document.version).toBe(before.document.version+1);expect(after.document.markdown).toContain('Controlled local fixture');const history=await docs(page,f,'history');expect(history.revisions[0].after.descriptionSnapshot).toBeTruthy();const region=d.getByRole('region',{name:'文档修订历史',exact:true});await region.locator('summary').first().click();await expect(region.locator('details[open]')).toContainText('Synthetic reviewed query description');await page.keyboard.press('Escape');await page.reload();await page.getByTestId('documentation-ai-button').click();await expect(d.getByTestId('documentation-outbound')).toContainText('Controlled local fixture');await page.screenshot({path:info.outputPath('ai-accepted-reloaded.png'),animations:'disabled'});});

test.afterEach(async({page},info)=>{const f=page.scopeBFixture;if(!f||info.project.name==='old')return;const{expected}=require('./parity-collections-guard.cjs'),e=expected('new'),{execFileSync}=require('node:child_process');expect(Number.isSafeInteger(f.iface)).toBe(true);const js=`(async()=>{var marker=await db.getCollection('_ui_parity_fixture').findOne({_id:'yapi-ui-parity-v1'});if(!marker||marker.synthetic!==true||marker.run!=='fastb1003'||marker.fixtureSha256!==${JSON.stringify(e.hash)})throw Error('Wrong fixture');var document=await db.interface.findOne({_id:${f.iface},project_id:${f.project}},{_id:1,project_id:1,docs_revision:1,docs_revision_head:1,markdown:1,desc:1,req_query:1,req_body_type:1,req_body_other:1,res_body_type:1,res_body:1});print(JSON.stringify(document))})()`;const raw=execFileSync('docker',['exec',e.mongo,'mongosh','--quiet',e.database,'--eval',js],{encoding:'utf8'});const stored=JSON.parse(raw.trim());const actual=await docs(page,f,'get');expect(stored.docs_revision||0).toBe(actual.document.version);expect(stored.markdown||'').toBe(actual.document.markdown||'');const interfaceData=await api(page,'/api/interface/get?id='+f.iface);for(const field of ['req_body_type','req_body_other','res_body_type','res_body'])expect(stored[field]).toBe(interfaceData[field]);await info.attach('synthetic-docs-db-readback',{body:JSON.stringify(stored),contentType:'application/json'});});

test('AI stale restore confirmation rejects a later legacy document edit',async({page},info)=>{const f=await setup(page,0);await api(page,'/api/interface/up',{id:f.iface,markdown:'Reviewed historical document'});const d=await openDocs(page,f);await d.getByRole('button',{name:'查看历史与恢复',exact:true}).click();await d.getByRole('button',{name:'恢复原始文档（版本 0）',exact:true}).click();await api(page,'/api/interface/up',{id:f.iface,markdown:'Concurrent newer document must survive'});const result=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/documentation/restore');await page.getByRole('dialog',{name:'确认恢复文档',exact:true}).getByRole('button',{name:'确认恢复',exact:true}).click();const body=await(await result).json();expect(body.errcode).toBe(409);await expect(d).toContainText('文档已发生变化');expect((await docs(page,f,'get')).document.markdown).toBe('Concurrent newer document must survive');await expect(page.getByRole('dialog',{name:'确认恢复文档',exact:true})).toHaveCount(0);await d.locator('.ant-modal-close').click();await page.getByTestId('documentation-ai-button').click();await expect(d.getByTestId('documentation-outbound')).toContainText('Concurrent newer document must survive');await d.getByRole('button',{name:'查看历史与恢复',exact:true}).click();await d.getByRole('button',{name:'恢复原始文档（版本 0）',exact:true}).click();await saveResponse(page,'/api/documentation/restore',()=>page.getByRole('dialog',{name:'确认恢复文档',exact:true}).getByRole('button',{name:'确认恢复',exact:true}).click());await expect(page.getByRole('dialog',{name:'确认恢复文档',exact:true})).toHaveCount(0);await page.screenshot({path:info.outputPath('ai-stale-restore.png'),animations:'disabled'});});

test('AI history renders incomplete legacy snapshots explicitly and safe field text',async({page},info)=>{const f=await setup(page,0);await api(page,'/api/interface/up',{id:f.iface,markdown:'Historical <script>text only</script>'});await page.route('**/api/documentation/history?*',async r=>{const response=await r.fetch();const body=await response.json();expect(body.errcode).toBe(0);body.data.revisions[0].fieldHistoryAvailable=false;delete body.data.revisions[0].after.descriptionSnapshot;await r.fulfill({response,json:body});});const d=await openDocs(page,f);await d.getByRole('button',{name:'查看历史与恢复',exact:true}).click();const history=d.getByRole('region',{name:'文档修订历史',exact:true});await expect(history).toContainText('旧历史：仅包含顶层文档');await history.locator('summary').first().click();await expect(history.locator('details[open]')).toContainText('<script>text only</script>');await expect(history.locator('details[open] script')).toHaveCount(0);await info.attach('fixture-boundary',{body:'Incomplete legacy fieldHistoryAvailable=false is a controlled history HTTP response fixture; actual legacy storage integrity remains covered by store tests.',contentType:'text/plain'});await page.screenshot({path:info.outputPath('ai-incomplete-history.png'),animations:'disabled'});});

test('AI restore lost response retry never creates a duplicate revision',async({page},info)=>{const f=await setup(page,0);await api(page,'/api/interface/up',{id:f.iface,markdown:'Restore transport fixture'});const before=await docs(page,f,'get');const d=await openDocs(page,f);await d.getByRole('button',{name:'查看历史与恢复',exact:true}).click();await d.getByRole('button',{name:'恢复原始文档（版本 0）',exact:true}).click();const confirm=page.getByRole('dialog',{name:'确认恢复文档',exact:true});const requests=[];await page.route('**/api/documentation/restore',async r=>{requests.push(r.request().postDataJSON());if(requests.length===1){const response=await r.fetch();expect((await response.json()).errcode).toBe(0);await r.abort('failed');}else await r.continue();});await confirm.getByRole('button',{name:/确认恢复$/}).click();await expect(d).toContainText('Network Error');await expect(confirm).toBeVisible();const retry=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/documentation/restore');await confirm.getByRole('button',{name:/确认恢复$/}).click();expect((await(await retry).json()).errcode).toBe(409);expect(requests[0].expectedVersion).toBe(before.document.version);expect(requests[1]).toEqual(requests[0]);expect((await docs(page,f,'get')).document.version).toBe(before.document.version+1);await expect(confirm).toHaveCount(0);await page.screenshot({path:info.outputPath('ai-restore-retry.png'),animations:'disabled'});});

test('AI guest reads review but cannot generate accept or restore',async({page},info)=>{const f=await setup(page,0);await api(page,'/api/project/add_member',{id:f.project,member_uids:[910004],role:'guest'});await login(page,'outsider');const d=await openDocs(page,f);await d.getByRole('checkbox').check();const response=page.waitForResponse(r=>new URL(r.url()).pathname==='/api/documentation/proposal');await d.getByRole('button',{name:/生成文档建议$/}).click();expect((await(await response).json()).errcode).toBe(403);await expect(d).toContainText('FORBIDDEN');const before=await docs(page,f,'get');for(const [action,body] of[['accept',{proposalId:'synthetic-invalid'}],['restore',{version:0,expectedVersion:before.document.version}]]){const denied=await(await page.request.post('/api/documentation/'+action,{headers:{'X-YApi-Docs-Intent':'review'},data:{projectId:f.project,interfaceId:f.iface,...body}})).json();expect(denied.errcode).toBe(403);}expect((await docs(page,f,'get')).document.version).toBe(before.document.version);await page.screenshot({path:info.outputPath('ai-guest-denied.png'),animations:'disabled'});});

for(const action of ['accept','restore'])for(const failure of ['business','network'])test(`AI saved ${action} receipt survives ${failure} read failures and retries reads only`,async({page},info)=>{
  const f=await setup(page,0);
  await api(page,'/api/project/add_member',{id:f.project,member_uids:[910003],role:'dev'});
  await login(page,'developer');
  const before=await docs(page,f,'get');
  const d=await openDocs(page,f);
  if(action==='accept'){
    await d.getByRole('checkbox').check();
    await saveResponse(page,'/api/documentation/proposal',()=>d.getByRole('button',{name:/生成文档建议$/}).click());
  }else{
    await d.getByRole('button',{name:'查看历史与恢复',exact:true}).click();
    await d.getByRole('checkbox').check();
    await d.getByRole('button',{name:'恢复原始文档（版本 0）',exact:true}).click();
  }
  let writes=0,parentReads=0,readFailures=0;
  page.on('request',r=>{const u=new URL(r.url());if(u.pathname==='/api/documentation/'+action)writes++;if(writes&&u.pathname==='/api/interface/get'&&u.searchParams.get('id')===String(f.iface))parentReads++;});
  await page.route('**/api/documentation/get?*',async r=>{
    if(writes&&readFailures<2){readFailures++;if(failure==='network')await r.abort('failed');else await r.fulfill({json:{errcode:500,errmsg:'Synthetic read failure'}});}
    else await r.continue();
  });
  await saveResponse(page,'/api/documentation/'+action,()=>action==='accept'?d.getByRole('button',{name:'审核完成，采纳此建议',exact:true}).click():page.getByRole('dialog',{name:'确认恢复文档',exact:true}).getByRole('button',{name:/确认恢复$/}).click());
  await expect(d).toContainText('文档已保存，但读取失败');
  await expect(d.getByRole('region',{name:'AI 文档建议预览'})).toHaveCount(0);
  await expect(page.getByRole('dialog',{name:'确认恢复文档',exact:true})).toHaveCount(0);
  await expect(d.getByRole('checkbox')).not.toBeChecked();
  await expect(d.getByRole('checkbox')).toBeDisabled();
  await expect.poll(()=>parentReads).toBe(1);
  const retry=d.getByRole('button',{name:'重新加载已保存文档',exact:true});
  await retry.click();await expect.poll(()=>readFailures).toBe(2);await expect(retry).toBeEnabled();
  await expect(d).toContainText('文档已保存，但读取失败');expect(writes).toBe(1);expect(parentReads).toBe(1);
  await page.screenshot({path:info.outputPath(`ai-${action}-${failure}-saved-receipt.png`),animations:'disabled'});
  await retry.click();await expect(retry).toHaveCount(0);await expect(d.getByRole('checkbox')).toBeEnabled();
  expect(writes).toBe(1);expect(parentReads).toBe(1);
  await page.unroute('**/api/documentation/get?*');
  const after=await docs(page,f,'get');expect(after.document.version).toBe(before.document.version+1);
  if(action==='accept')expect(after.document.markdown).toContain('Controlled local fixture');
  else expect(after.document.markdown||'').toBe('');
  await d.locator('.ant-modal-close').click();await page.getByTestId('documentation-ai-button').click();await expect(d).toContainText('版本 '+after.document.version);
  expect(writes).toBe(1);
});

test('AI saved restore history failure keeps receipt until document and history reload',async({page},info)=>{
  const f=await setup(page,0),before=await docs(page,f,'get'),d=await openDocs(page,f);
  await d.getByRole('button',{name:'查看历史与恢复',exact:true}).click();
  await d.getByRole('button',{name:'恢复原始文档（版本 0）',exact:true}).click();
  let writes=0,failures=0;page.on('request',r=>{if(new URL(r.url()).pathname==='/api/documentation/restore')writes++;});
  await page.route('**/api/documentation/history?*',async r=>{if(writes&&failures++<1)await r.fulfill({json:{errcode:500,errmsg:'Synthetic history failure'}});else await r.continue();});
  await saveResponse(page,'/api/documentation/restore',()=>page.getByRole('dialog',{name:'确认恢复文档',exact:true}).getByRole('button',{name:/确认恢复$/}).click());
  await expect(d).toContainText('文档已保存，但读取失败');await expect(d.getByRole('button',{name:'恢复原始文档（版本 0）',exact:true})).toBeDisabled();
  await d.getByRole('button',{name:'重新加载已保存文档',exact:true}).click();await expect(d.getByRole('button',{name:'重新加载已保存文档',exact:true})).toHaveCount(0);
  expect(writes).toBe(1);expect((await docs(page,f,'get')).document.version).toBe(before.document.version+1);
  await page.screenshot({path:info.outputPath('ai-restored-history-recovered.png'),animations:'disabled'});
});


test('Docs JSON raw JSON transitions keep stale inactive flags harmless and active invalid schema rejected',async({page},info)=>{
 const f=await setup(page,0),schema=JSON.stringify({type:'object',properties:{name:{type:'string',description:'Original field'}}});
 await api(page,'/api/interface/up',{id:f.iface,req_body_type:'json',req_body_is_json_schema:true,req_body_other:schema,res_body_type:'json',res_body_is_json_schema:true,res_body:schema});
 const raw='  RAW <not-json>\nbytes: \\"exact\\"  ';
 await api(page,'/api/interface/up',{id:f.iface,req_body_type:'raw',req_body_is_json_schema:true,req_body_other:raw,res_body_type:'raw',res_body_is_json_schema:true,res_body:raw});
 await api(page,'/api/interface/up',{id:f.iface,markdown:'Raw body documentation edit'});
 const rawVersion=(await docs(page,f,'get')).document.version;
 let stored=await api(page,'/api/interface/get?id='+f.iface);expect(stored.req_body_other).toBe(raw);expect(stored.res_body).toBe(raw);
 await api(page,'/api/interface/up',{id:f.iface,req_body_type:'json',req_body_other:schema,res_body_type:'json',res_body:schema});
 const before=(await docs(page,f,'get')).document.version;
 const rejected=await(await page.request.post('/api/interface/up',{data:{id:f.iface,req_body_other:'not a valid schema',req_body_type:'json',req_body_is_json_schema:true}})).json();expect(rejected.errcode).not.toBe(0);expect((await docs(page,f,'get')).document.version).toBe(before);expect((await api(page,'/api/interface/get?id='+f.iface)).req_body_other).toBe(schema);
 // Restore is documentation-only: semantic body schema stays current, older incompatible annotations fail safely.
 const d=await openDocs(page,f);await expect(d.getByTestId('documentation-outbound')).toContainText('Original field');await d.getByRole('button',{name:'查看历史与恢复',exact:true}).click();await expect(d.getByRole('region',{name:'文档修订历史',exact:true})).toContainText('Raw body documentation edit');
 await d.locator('.ant-modal-close').click();await page.reload();stored=await api(page,'/api/interface/get?id='+f.iface);expect(stored.req_body_other).toBe(schema);expect(stored.res_body).toBe(schema);expect(rawVersion).toBeLessThan(before);
 await info.attach('raw-transition-contract',{body:JSON.stringify({rawVersion,finalVersion:before,invalidSchemaErrcode:rejected.errcode,rawBytesVerified:true}),contentType:'application/json'});await page.getByTestId('documentation-ai-button').click();await expect(d.getByTestId('documentation-outbound')).toContainText('Original field');await d.scrollIntoViewIfNeeded();await expect(d).toBeInViewport();await expect.poll(()=>d.evaluate(e=>({opacity:getComputedStyle(e).opacity,width:e.getBoundingClientRect().width}))).toEqual({opacity:'1',width:960});await info.attach('docs-visible-bounds',{body:JSON.stringify(await d.boundingBox()),contentType:'application/json'});await page.screenshot({path:info.outputPath('docs-json-raw-json.png')});
});
