'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
require('../util-polyfill');const yapi=require('../server/yapi');const C=require('../server/controllers/interfaceCol');
yapi.commons={...require('../server/utils/commons'),resReturn:(data,errcode=0,errmsg='')=>({data,errcode,errmsg}),saveLog(){},time:()=>1};
function fixture(){const writes=[],reads=[];const c=Object.create(C.prototype);Object.assign(c,{getUid:()=>1,getUsername:()=> 'Synthetic',checkAuth:async p=>p===10,
 colModel:{get:async id=>({21:{_id:21,project_id:10,name:'own'},22:{_id:22,project_id:20,name:'private'},23:{_id:23,project_id:10,name:'own2'}}[id])},
 projectModel:{get:async id=>({_id:id,project_type:id===30?'public':'private'}),up:async()=>{}},
 interfaceModel:{get:async id=>({31:{_id:31,project_id:10,title:'own'},32:{_id:32,project_id:20,title:'private'},33:{_id:33,project_id:30,title:'public'}}[id])},
 caseModel:{save:async data=>{writes.push({...data});return{_id:100+ writes.length}},get:async id=>id===41?{_id:41,col_id:21,project_id:10,interface_id:31}:id===42?{_id:42,col_id:22,project_id:20,interface_id:32}:null,up:async(id,data)=>writes.push({id,...data}),list:async id=>{reads.push(id);return[{toObject:()=>({_id:41,project_id:id===22?20:10,interface_id:id===22?32:31,col_id:id,index:0}),project_id:id===22?20:10,interface_id:id===22?32:31,index:0}]}}});return {c,writes,reads};}
async function invoke(f,method,body){const ctx={request:{body},query:body};await f.c[method](ctx);return ctx.body;}
test('add and import derive live target scope before any writes',async()=>{for(const method of ['addCase','addCaseList']){for(const col_id of [22,999]){const f=fixture();const r=await invoke(f,method,{project_id:10,col_id,interface_id:31,interface_list:[31],casename:'Synthetic'});assert.notEqual(r.errcode,0);assert.equal(f.writes.length,0);}}});
test('import preflights all source visibility and preserves public cross-project sources',async()=>{const f=fixture();assert.notEqual((await invoke(f,'addCaseList',{project_id:10,col_id:21,interface_list:[31,32]})).errcode,0);assert.equal(f.writes.length,0);assert.equal((await invoke(f,'addCaseList',{project_id:10,col_id:21,interface_list:[31,33]})).errcode,0);assert.equal(f.writes.length,2);assert.ok(f.writes.every(r=>r.project_id===10&&r.col_id===21));});
test('single copy rejects private source and permits an authorized source',async()=>{const f=fixture();assert.notEqual((await invoke(f,'addCase',{project_id:10,col_id:21,interface_id:32,casename:'Synthetic'})).errcode,0);assert.equal(f.writes.length,0);assert.equal((await invoke(f,'addCase',{project_id:10,col_id:21,interface_id:31,casename:'Synthetic'})).errcode,0);});
test('clone denies forged destination and private source before listing or saving',async()=>{for(const [col_id,new_col_id]of[[21,22],[22,21],[999,21],[21,999]]){const f=fixture();assert.notEqual((await invoke(f,'cloneCaseList',{project_id:10,col_id,new_col_id})).errcode,0);assert.deepEqual(f.reads,[]);assert.deepEqual(f.writes,[]);}});
test('authorized clone keeps destination scope and ownership',async()=>{const f=fixture();assert.equal((await invoke(f,'cloneCaseList',{project_id:10,col_id:21,new_col_id:23})).errcode,0);assert.equal(f.writes[0].col_id,23);assert.equal(f.writes[0].project_id,10);assert.equal(f.writes[0].uid,1);});
test('case move rejects cross-project or missing targets without modifying case',async()=>{for(const col_id of [22,999]){const f=fixture();assert.notEqual((await invoke(f,'upCase',{id:41,col_id})).errcode,0);assert.deepEqual(f.writes,[]);}const f=fixture();assert.equal((await invoke(f,'upCase',{id:41,col_id:23})).errcode,0);assert.equal(f.writes[0].col_id,23);});
test('direct case read rejects private source and missing ids before returning body',async()=>{for(const caseid of [42,999]){const f=fixture();assert.notEqual((await invoke(f,'getCase',{caseid})).errcode,0);}});
