'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const {initialSchemaMode,parseBodyJson,clearInactiveBodies}=require('../client/containers/Project/Interface/InterfaceList/bodyModes');
test('explicit false remains false with JSON5 disabled; only undefined receives project default',()=>{assert.equal(initialSchemaMode('json',false,false),false);assert.equal(initialSchemaMode('json',true,true),true);assert.equal(initialSchemaMode('json',undefined,false),true);assert.equal(initialSchemaMode('json',undefined,true),false);assert.equal(initialSchemaMode(undefined,false,false),false);});
test('inactive raw file and form never initialize Schema editors even with historical true flag',()=>{for(const type of ['raw','file','form'])for(const stored of [true,false,undefined])assert.equal(initialSchemaMode(type,stored,false),false);});
test('body parser enforces strict JSON unless JSON5 is explicitly enabled',()=>{assert.deepEqual(parseBodyJson('{"value":1}',false),{value:1});assert.throws(()=>parseBodyJson('{value:1, // note\n}',false));assert.deepEqual(parseBodyJson('{value:1, // note\n}',true),{value:1});for(const enabled of [false,true])assert.throws(()=>parseBodyJson('{ broken',enabled));});
test('JSON and raw/file requests drop inactive form rows and preserve active text',()=>{for(const type of ['json','raw','file']){const data={req_body_type:type,req_body_form:[{name:'stale'}],req_body_other:'active',req_body_is_json_schema:true,res_body_type:'raw',res_body_is_json_schema:true};clearInactiveBodies(data,true);assert.deepEqual(data.req_body_form,[]);assert.equal(data.req_body_other,'active');assert.equal(data.req_body_is_json_schema,type==='json');assert.equal(data.res_body_is_json_schema,false);}});
test('form and methods without body clear inactive source and Schema flags',()=>{const form={req_body_type:'form',req_body_form:[{name:'active'}],req_body_other:'stale',req_body_is_json_schema:true,res_body_type:'json',res_body_is_json_schema:false};clearInactiveBodies(form,true);assert.deepEqual(form.req_body_form,[{name:'active'}]);assert.equal(form.req_body_other,'');assert.equal(form.req_body_is_json_schema,false);assert.equal(form.res_body_is_json_schema,false);clearInactiveBodies(form,false);assert.deepEqual(form.req_body_form,[]);assert.equal(form.req_body_other,'');});
