'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module');
class Component{constructor(props){this.props=props;}setState(value,callback){this.state={...this.state,...value};if(callback)callback();}}
const file=path.resolve(__dirname,'../client/containers/Project/Interface/InterfaceList/InterfaceList.js');
const {code}=require('@babel/core').transformSync(fs.readFileSync(file,'utf8'),{filename:file,babelrc:false,configFile:false,presets:[['@babel/preset-env',{targets:{node:'current'},modules:'commonjs'}],['@babel/preset-react',{runtime:'classic'}]],plugins:[['@babel/plugin-proposal-decorators',{legacy:true}]]});
const loaded=new Module(file,module);loaded.filename=file;loaded.require=id=>id==='react'?{PureComponent:Component}:id==='react-redux'?{connect:()=>C=>C}:id==='prop-types'?require('prop-types'):id==='antd'?{Select:{}}:{};loaded._compile(code,file);const List=loaded.exports.default;
function harness(actionId='cat_12'){const props={match:{params:{id:'9',actionId}},catTableList:[{_id:1}],totalTableList:[{_id:1}],count:21,totalCount:21};const view=new List(props);view.actionId=actionId;view.state.current=2;const requests=[];view.handleRequest=p=>requests.push({page:view.state.current,params:p.match.params});return {view,props,requests};}
test('category final row removal reloads page one from fresh count',()=>{const h=harness();h.view.componentWillReceiveProps({...h.props,catTableList:[],count:20});assert.equal(h.view.state.current,1);assert.deepEqual(h.requests,[{page:1,params:h.props.match.params}]);});
test('all-interface final page shrink recovers to last remaining page',()=>{const h=harness(undefined);h.view.actionId=undefined;h.props.match.params.actionId=undefined;h.view.state.current=4;h.view.componentWillReceiveProps({...h.props,totalTableList:[],totalCount:41});assert.equal(h.view.state.current,3);assert.equal(h.requests[0].page,3);});
test('zero records recovers once to page one and avoids invalid page zero',()=>{const h=harness();h.view.componentWillReceiveProps({...h.props,catTableList:[],count:0});assert.equal(h.view.state.current,1);assert.equal(h.requests.length,1);h.view.componentWillReceiveProps({...h.props,catTableList:[],count:0});assert.equal(h.requests.length,1);});
test('guest rejection or unrelated props do not jump a valid current page',()=>{const h=harness();h.view.componentWillReceiveProps({...h.props});h.view.componentWillReceiveProps({...h.props,catTableList:[{_id:1}],count:21});assert.equal(h.view.state.current,2);assert.equal(h.requests.length,0);});
test('route category change resets to one using new scope instead of stale total',()=>{const h=harness();const next={...h.props,match:{params:{id:'9',actionId:'cat_13'}},catTableList:[],count:0};h.view.componentWillReceiveProps(next);assert.equal(h.view.state.current,1);assert.deepEqual(h.requests,[{page:1,params:next.match.params}]);});
