'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const Module=require('node:module');
const file=path.resolve(__dirname,'../client/containers/Project/Interface/InterfaceList/InterfaceEditForm.js');
const errors=[];
const previewRequests=[];
const axios={post:async(url,body)=>{previewRequests.push({url,body});return {data:{currentField:"current"}};}};
class Component{constructor(props){this.props=props;}setState(value){this.state={...this.state,...value};}}
const {code}=require('@babel/core').transformSync(fs.readFileSync(file,'utf8'),{filename:file,babelrc:false,configFile:false,presets:[['@babel/preset-env',{targets:{node:'current'},modules:'commonjs'}],['@babel/preset-react',{runtime:'classic'}]],plugins:[['@babel/plugin-proposal-decorators',{legacy:true}]]});
const loaded=new Module(file,module);loaded.filename=file;loaded.require=id=>id==='axios'?axios:id==='react'?{PureComponent:Component}:id==='react-redux'?{connect:()=>C=>C}:id==='prop-types'?require('prop-types'):id==='underscore'?require('underscore'):id==='json5'?require('json5'):id==='antd'?{Form:{create:()=>C=>C},Tabs:{},Input:{},Select:{},Radio:{},message:{error:value=>errors.push(value)}}:id.endsWith('variable.js')?{HTTP_METHOD:{GET:{default_tab:'query',request_body:false}}}:id==='./normalizeSchema'?value=>value:id==='./bodyModes'?require('../client/containers/Project/Interface/InterfaceList/bodyModes.js'):{};loaded._compile(code,file);const Form=loaded.exports.default;
const event={preventDefault(){}};
function harness({validate,submit=async()=>true}={}){const dirty=[],calls=[];const values={title:'synthetic',path:'/synthetic',req_headers:[],req_query:[],req_params:[],req_body_form:[],res_body_type:'raw',res_body:'synthetic'};const form=new Form({curdata:{method:'GET',res_body_type:'raw',res_body:'synthetic'},form:{getFieldsValue:()=>values,validateFields:validate||((cb)=>cb(null,{...values}))},onSubmit:async v=>{calls.push(v);return submit(v);},changeEditStatus:value=>dirty.push(value)});form._isMounted=true;form.editor={getHTML:()=>'<p>synthetic</p>',getMarkdown:()=>'synthetic',destroy(){}};return {form,dirty,calls};}
test('logical save rejection preserves dirty and releases pending guard',async()=>{const h=harness({submit:async()=>false});h.form.markDirty();await h.form.handleSubmit(event);assert.deepEqual(h.dirty,[true]);assert.equal(h.form.state.submitStatus,false);});
test('transport error is visible and same draft remains retryable',async()=>{let failed=true;const h=harness({submit:async()=>{if(failed)throw Error('synthetic transport');return true;}});h.form.markDirty();await h.form.handleSubmit(event);assert.equal(errors.at(-1),'保存失败，请重试');assert.deepEqual(h.dirty,[true]);failed=false;await h.form.handleSubmit(event);assert.deepEqual(h.dirty,[true,false]);assert.equal(h.calls.length,2);});
test('pending save suppresses repeated submits until real completion',async()=>{let finish;const h=harness({submit:()=>new Promise(resolve=>finish=resolve)});const pending=h.form.handleSubmit(event);await Promise.resolve();await h.form.handleSubmit(event);assert.equal(h.calls.length,1);assert.equal(h.form.state.submitStatus,true);finish(true);await pending;assert.equal(h.form.state.submitStatus,false);});
test('new edits during pending save retain dirty state until next successful save',async()=>{let finish;const h=harness({submit:()=>new Promise(resolve=>finish=resolve)});h.form.markDirty();const first=h.form.handleSubmit(event);await Promise.resolve();h.form.markDirty();finish(true);await first;assert.deepEqual(h.dirty,[true,true]);const second=h.form.handleSubmit(event);await Promise.resolve();finish(true);await second;assert.deepEqual(h.dirty,[true,true,false]);});
test('new edits during deferred validation are not cleared by an older successful snapshot',async()=>{let finish;const h=harness({validate:cb=>finish=cb});h.form.markDirty();const pending=h.form.handleSubmit(event);h.form.markDirty();finish(null,{res_body_type:'raw',res_body:'synthetic'});await pending;assert.equal(h.calls.length,1);assert.deepEqual(h.dirty,[true,true]);});
test('unmounted editor cannot submit late validation or clear another editor dirty state',async()=>{let finish;const h=harness({validate:cb=>finish=cb});const pending=h.form.handleSubmit(event);h.form.componentWillUnmount();const count=h.dirty.length;finish(null,{});await pending;assert.equal(h.calls.length,0);assert.equal(h.dirty.length,count);});
test('required validation failure releases synchronous guard without request',async()=>{const h=harness({validate:cb=>cb({title:'required'}, {})});await h.form.handleSubmit(event);assert.equal(h.calls.length,0);assert.equal(h.form.state.submitStatus,false);});

test('schema preview reads current draft instead of stale hidden RAW field',async()=>{const h=harness();const current={type:'object',properties:{currentField:{type:'string'}}};h.form.state.res_body=JSON.stringify(current);h.form.props.form.getFieldValue=key=>key==='res_body_is_json_schema'?true:JSON.stringify({type:'object',properties:{oldField:{type:'string'}}});const previews=[];h.form.mockPreview={setValue:value=>previews.push(value)};await h.form.handleMockPreview();assert.deepEqual(previewRequests.at(-1),{url:'/api/interface/schema2json',body:{schema:current}});assert.match(previews[0],/currentField/);});
test('invalid schema preview reports error without issuing stale generation request',async()=>{const h=harness();h.form.props.form.getFieldValue=()=>true;h.form.schemaValidity.response=false;const previews=[];h.form.mockPreview={setValue:value=>previews.push(value)};const count=previewRequests.length;await h.form.handleMockPreview();assert.equal(previewRequests.length,count);assert.equal(previews[0],'解析出错: Schema JSON 无效');});
