'use strict';
const test=require('node:test'),assert=require('node:assert/strict');require('../util-polyfill');
const yapi=require('../server/yapi'),Controller=require('../server/controllers/log'),Model=require('../server/models/log');yapi.commons={...require('../server/utils/commons'),resReturn:(data,errcode=0)=>({data,errcode})};
const project=(type='private')=>({project_type:type,toObject:()=>({basepath:''})});
function deniedData(){return new Proxy({},{get:()=>()=>assert.fail('unauthorized request queried history or counts')});}
for(const method of ['list','listByUpdate'])for(const missing of [false,true])test(`log ${method} rejects ${missing?'missing':'private denied'} before history, interface lookup or counts`,async()=>{let checks=0;const c={projectModel:{getBaseInfo:async()=>missing?null:project()},interfaceModel:deniedData(),Model:deniedData(),checkAuth:async(...args)=>{checks++;assert.deepEqual(args,[901001,'project','view']);return false;}};const params={type:'project',typeid:901001,apis:[{method:'GET',path:'/private'}]};const ctx={params,request:{query:params}};await Controller.prototype[method].call(c,ctx);assert.equal(ctx.body.errcode,missing?404:405);assert.equal(checks,missing?0:1);});
for(const role of ['public','guest'])test(`log ${role} reads remain allowed for list and import history`,async()=>{const c={projectModel:{getBaseInfo:async()=>project(role==='public'?'public':'private')},checkAuth:async()=>role==='guest',interfaceModel:{getByPath:async()=>[{id:77}]},Model:{listWithPaging:async()=>[{_id:1}],listCount:async()=>1,listWithCatid:async()=>[{_id:1}]}};for(const method of ['list','listByUpdate']){const params={type:'project',typeid:901001,apis:[{method:'GET',path:'/allowed'}]};const ctx={params,request:{query:params}};await Controller.prototype[method].call(c,ctx);assert.equal(ctx.body.errcode,0);}});
test('mixed group filters both count and pagination before data queries and omits group-only activity for nonmembers',async()=>{const calls=[];let granted=false;const c={groupModel:{get:async()=>({_id:1})},projectModel:{list:async()=>[{_id:11,name:'public',project_type:'public'},{_id:12,name:'private',project_type:'private'}]},checkAuth:async(id,type)=>type==='project'&&granted,Model:{listWithPagingByGroup:async(...args)=>{calls.push(['page',...args]);return[];},listCountByGroup:async(...args)=>{calls.push(['count',...args]);return 0;}}};c.Model.listCountByGroup=async(...args)=>{calls.push(['count',...args]);return 0;};for(const allowed of [false,true,false]){granted=allowed;const ctx={request:{query:{type:'group',typeid:1,page:2,limit:5}}};await Controller.prototype.list.call(c,ctx);assert.equal(ctx.body.errcode,0);const ids=allowed?[11,12]:[11];assert.deepEqual(calls.splice(0),[['page',1,ids,2,5,false],['count',1,ids,false]]);}});
test('group query and count omit group branch together when caller is not a member',async()=>{let query,count;const chain={sort:()=>chain,skip:()=>chain,limit:()=>chain,exec:async()=>[]};const c={model:{find:x=>(query=x,chain),countDocuments:x=>(count=x,0)}};await Model.prototype.listWithPagingByGroup.call(c,1,[11],1,10,false);await Model.prototype.listCountByGroup.call(c,1,[11],false);assert.deepEqual(query,{$or:[{type:'project',typeid:{$in:[11]}}]});assert.deepEqual(count,query);});
test('missing group and unsupported scope fail closed before data lookup',async()=>{const c={groupModel:{get:async()=>null},Model:deniedData(),projectModel:deniedData(),checkAuth:()=>assert.fail('missing group auth')};for(const type of ['group','user']){const ctx={request:{query:{type,typeid:1}}};await Controller.prototype.list.call(c,ctx);assert.equal(ctx.body.errcode,type==='group'?404:400);}});
