'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const babel=require('@babel/core');
function component(file,axios,message,environment={}){
 const filename=path.resolve(__dirname,'../client/containers/Project/Interface/InterfaceCol/'+file);
 const code=babel.transformSync(fs.readFileSync(filename,'utf8'),{filename,babelrc:false,configFile:false,presets:[['@babel/preset-env',{targets:{node:'24'}}],'@babel/preset-react'],plugins:[['@babel/plugin-proposal-decorators',{legacy:true}],['@babel/plugin-transform-class-properties',{loose:true}]]}).code;
 const module={exports:{}};const identity=x=>x;
 const imports={react:require('react'),'prop-types':require('prop-types'),'react-redux':{connect:()=>identity},'react-router':{withRouter:identity},'react-router-dom':{withRouter:identity},axios,antd:{message,Select:{Option:()=>null},Tree:{TreeNode:()=>null},Form:{create:()=>identity},Modal:{}},underscore:{debounce:x=>x},immer:{},'copy-to-clipboard':()=>{},'client/plugin.js':{},'common/postmanLib.js':{},'common/utils.js':{},'common/createContext':()=>{},'client/utils/requestMode':{REQUEST_MODE:{SERVER:'server',BROWSER:'browser'},getRequestMode:()=> 'server',setRequestMode:()=>{}}};
 vm.runInNewContext(code,{...environment,module,exports:module.exports,require:name=>{if(name in imports)return imports[name];if(name==='../../../../common.js'||name.startsWith('../../../../reducer/')||name.startsWith('../../../../components')||name.startsWith('client/components/')||name.startsWith('client/utils/')||name.startsWith('./'))return {};throw Error('Unexpected import '+name);}},{filename});return module.exports.default;
}
function caseHarness(post){const refresh=[],messages=[];const Class=component('InterfaceCaseContent.js',{post},{error:x=>messages.push(x),success:x=>messages.push(x)});const props={currCase:{_id:1,casename:'old'},match:{params:{id:'10',actionId:'1'}},fetchCaseData:id=>refresh.push(id),fetchInterfaceColList:()=>refresh.push('tree')};const instance=new Class(props);instance.postman={state:{}};instance.state.editCasename='new';return{instance,refresh,messages};}
test('case update serializes repeat click and ignores late refresh after route changes',async()=>{let release,calls=0;const h=caseHarness(()=>{calls++;return new Promise(r=>release=r)});const first=h.instance.updateCase();await h.instance.updateCase();assert.equal(calls,1);h.instance.props={...h.instance.props,currCase:{_id:2,casename:'other'},match:{params:{id:'10',actionId:'2'}}};release({data:{errcode:0}});await first;assert.deepEqual(h.refresh,[]);assert.deepEqual(h.messages,[]);assert.equal(h.instance.activeCaseSave,null);});
test('case application and transport rejection surface failure and allow retry',async()=>{let call=0;const h=caseHarness(async()=>{call++;if(call===1)return{data:{errcode:40033,errmsg:'denied'}};if(call===2)throw Error('offline');return{data:{errcode:0}}});await h.instance.updateCase();await h.instance.updateCase();assert.deepEqual(h.refresh,[]);assert.equal(h.messages.length,2);await h.instance.updateCase();assert.deepEqual(h.refresh,['tree',1]);});
test('order snapshots persist serially and only final snapshot refreshes tree',async()=>{const calls=[],releases=[],refresh=[];const Class=component('InterfaceColContent.js',{post:(_,body)=>{calls.push(JSON.parse(JSON.stringify(body)));return new Promise(r=>releases.push(r));}},{error:()=>{}});const h=new Class({currColId:5,match:{params:{id:'10'}},fetchInterfaceColList:id=>refresh.push(id)});h.state.rows=[{_id:1},{_id:2}];const first=h.onDrop();h.state.rows=[{_id:2},{_id:1}];const second=h.onDrop();await new Promise(setImmediate);assert.equal(calls.length,1);releases[0]({data:{errcode:0}});await first;await new Promise(setImmediate);assert.equal(calls.length,2);assert.deepEqual(calls[1],[{id:2,index:0},{id:1,index:1}]);assert.deepEqual(refresh,[]);releases[1]({data:{errcode:0}});await second;assert.deepEqual(refresh,['10']);});
test('order application rejection is visible and next snapshot can still save',async()=>{let count=0;const errors=[],refresh=[];const Class=component('InterfaceColContent.js',{post:async()=>({data:++count===1?{errcode:40033,errmsg:'denied'}:{errcode:0}})},{error:x=>errors.push(x)});const h=new Class({currColId:5,match:{params:{id:'10'}},fetchInterfaceColList:id=>refresh.push(id)});h.state.rows=[{_id:1}];await h.onDrop();assert.deepEqual(errors,['denied']);assert.deepEqual(refresh,[]);await h.onDrop();assert.deepEqual(refresh,['10']);});
test('case fallback route without explicit action ID can save its current case',async()=>{const h=caseHarness(async()=>({data:{errcode:0}}));delete h.instance.props.match.params.actionId;await h.instance.updateCase();assert.deepEqual(h.refresh,['tree',1]);});
test('an order completion after unmount cannot refresh a different project view',async()=>{let release;const refresh=[];const Class=component('InterfaceColContent.js',{post:()=>new Promise(r=>release=r)},{error:()=>{}});const h=new Class({currColId:5,match:{params:{id:'10'}},fetchInterfaceColList:id=>refresh.push(id)});h.state.rows=[{_id:1}];const pending=h.onDrop();await new Promise(setImmediate);h.componentWillUnmount();release({data:{errcode:0}});await pending;assert.deepEqual(refresh,[]);});

test('rule dialog identity prevents a stale draft writing the next route',async()=>{let writes=0;const Class=component('InterfaceColContent.js',{post:async()=>{writes++;return{data:{errcode:0}}}},{error:()=>{},success:()=>{}});const h=new Class({currColId:5,match:{params:{actionId:'5'}}});h.setState=x=>Object.assign(h.state,x);h.loadedCollectionId=5;h.openCommonSetting();assert.equal(h.state.commonSettingModalVisible,true);h.props={currColId:6,match:{params:{actionId:'6'}}};await h.handleCommonSetting();assert.equal(writes,0);h.loadedCollectionId=6;h.openCommonSetting();await h.handleCommonSetting();assert.equal(writes,1);});
test('assertion permission errors without logs display the server error',async()=>{const Class=component('InterfaceColContent.js',{post:async()=>({data:{errcode:403,errmsg:'Forbidden',data:null}})},{error:()=>{}});const h=new Class({currColId:5});const errors=[];await h.handleScriptTest({_id:7,interface_id:8},{},errors,{});assert.equal(errors[0].message,'Forbidden');});

test('collection reducers discard old route and old generation environment data',()=>{const filename=path.resolve(__dirname,'../client/reducer/modules/interfaceCol.js');const code=babel.transformSync(fs.readFileSync(filename,'utf8'),{filename,babelrc:false,configFile:false,presets:[['@babel/preset-env',{targets:{node:'24'}}]]}).code;const module={exports:{}};vm.runInNewContext(code,{module,exports:module.exports,require:()=>({get:async()=>({data:{errcode:0,data:[]}})})});const m=module.exports,old={},current={};let state=m.default(undefined,{type:'init'});state=m.default(state,m.setColData({currColId:6,collectionLoad:current}));const action=m.fetchCaseEnvList(5,old);action.payload={data:{errcode:0,data:['stale']}};assert.equal(m.default(state,action),state);action.meta.colId=6;assert.equal(m.default(state,action),state);action.meta.load=current;assert.deepEqual(Array.from(m.default(state,action).envList),['stale']);});
test('failed metadata or environment load never enables rules or starts an empty report write',async()=>{for(const failure of ['metadata','environment','rejected']){let writes=0;const Class=component('InterfaceColContent.js',{post:async()=>{writes++;return{data:{errcode:0}}}},{error:()=>{}});const h=new Class({currColId:5,match:{params:{actionId:'5'}},setColData:()=>{},fetchCaseList:async()=>failure==='metadata'?{error:true,payload:new Error('failed')}:{payload:{data:{errcode:0,colData:{test_report:'{}'},data:[]}}},fetchCaseEnvList:async()=>{if(failure==='rejected')throw Error('failed');return{payload:{data:{errcode:403,data:null}}}}});h.setState=x=>Object.assign(h.state,x);h.savedCommonSetting={checkResponseField:{name:'stale'}};await h.handleColIdChange(5);assert.equal(h.loadedCollectionId,null);assert.equal(h.savedCommonSetting,null);assert.equal(h.isCurrentCollectionLoaded(),false);h.openCommonSetting();await h.executeTests();assert.equal(writes,0);assert.equal(h.state.commonSettingModalVisible,false);}});
test('successful empty collection is loaded and usable after a failed generation',async()=>{let writes=0;const Class=component('InterfaceColContent.js',{post:async()=>{writes++;return{data:{errcode:0}}}},{error:()=>{}});const h=new Class({currColId:5,match:{params:{actionId:'5'}},setColData:()=>{},fetchCaseList:async()=>({payload:{data:{errcode:0,colData:{test_report:'{}'},data:[]}}}),fetchCaseEnvList:async()=>({payload:{data:{errcode:0,data:[]}}})});h.setState=x=>Object.assign(h.state,x);h.handleColdata=rows=>h.state.rows=rows;await h.handleColIdChange(5);assert.equal(h.isCurrentCollectionLoaded(),true);await h.executeTests();assert.equal(writes,1);});

test('case loading ignores an old response and a missing source leaves no usable document',async()=>{let release;const Class=component('InterfaceCaseContent.js',{get:async()=>({data:{errcode:0,data:{env:[{name:'current'}]}}})},{});const props={setColData:()=>{},fetchCaseData:(id)=>id===1?new Promise(r=>release=r):Promise.resolve({payload:{data:{errcode:0,data:{_id:id,interface_id:9,project_id:10,casename:'current'}}}})};const h=new Class(props);h.setState=x=>Object.assign(h.state,x);const old=h.loadCase(1,5);await h.loadCase(2,5);release({payload:{data:{errcode:0,data:{_id:1,interface_id:8,project_id:10,casename:'old'}}}});await old;assert.equal(h.state.loadedCaseId,2);assert.equal(h.state.editCasename,'current');h.props.fetchCaseData=async()=>({payload:{data:{errcode:400,errmsg:'来源接口不存在'}}});await h.loadCase(3,5);assert.equal(h.state.loadedCaseId,null);assert.equal(h.state.caseLoading,false);assert.equal(h.state.caseLoadError,'来源接口不存在');});

for(const boundary of ['source','post','refresh'])for(const change of ['route','unmount'])test('case clone ignores '+change+' during '+boundary,async()=>{let release,entered;const gate=new Promise(r=>release=r),start=new Promise(r=>entered=r),events=[];const wait=async stage=>{if(stage===boundary){entered();await gate;}};const Class=component('InterfaceColMenu.js',{get:async url=>{if(url.includes('/case?')){await wait('source');return{data:{errcode:0,data:{_id:1,project_id:10,col_id:5,casename:'one'}}};}events.push('read');await wait('refresh');return{data:{errcode:0,data:[]}};},post:async()=>{events.push('write');await wait('post');return{data:{errcode:0,data:{col_id:5}}};}},{error:()=>events.push('error'),success:()=>{}});const props={match:{params:{id:'10'}},location:{pathname:'/project/10/interface/col/5'},setColData:()=>events.push('redux'),history:{push:()=>events.push('navigate')}};const h=new Class(props);h.setState=x=>Object.assign(h.state,x);const pending=h.caseCopy(1);await start;if(change==='unmount')h.componentWillUnmount();else{const next={...props,location:{pathname:'/project/10/interface/col/6'}};h.componentWillReceiveProps(next);h.props=next;}release();await pending;assert.equal(events.includes('redux'),false);assert.equal(events.includes('navigate'),false);assert.equal(events.includes('error'),false);assert.equal(events.includes('write'),boundary!=='source');assert.equal(events.includes('read'),boundary==='refresh');});

test('clone refresh observes history navigation before router props or unmount arrive',async()=>{let release;const actions=[],errors=[];const Class=component('InterfaceColMenu.js',{get:async url=>url.includes('/case?')?{data:{errcode:0,data:{_id:1,col_id:5,project_id:10,casename:'one'}}}:new Promise(r=>release=r),post:async()=>({data:{errcode:0,data:{col_id:5}}})},{error:x=>errors.push(x),success:()=>{}});const h=new Class({match:{params:{id:'10'}},location:{pathname:'/project/10/interface/col/5'},history:{location:{pathname:'/project/10/interface/col/5'},push:x=>actions.push(x)},setColData:x=>actions.push(x)});h.setState=x=>Object.assign(h.state,x);const pending=h.caseCopy(1);await new Promise(setImmediate);h.props.history.location={pathname:'/project/10/setting'};release({data:{errcode:0,data:[]}});await pending;assert.deepEqual(actions,[]);assert.deepEqual(errors,[]);});

test('clone refresh cannot navigate when browser URL changes before compat history snapshot',async()=>{let release;const actions=[],window={location:{pathname:'/project/10/interface/col/5'}};const Class=component('InterfaceColMenu.js',{get:async url=>url.includes('/case?')?{data:{errcode:0,data:{_id:1,col_id:5,project_id:10,casename:'one'}}}:new Promise(r=>release=r),post:async()=>({data:{errcode:0,data:{col_id:5}}})},{error:()=>{},success:()=>{}},{window});const h=new Class({match:{params:{id:'10'}},location:{pathname:window.location.pathname},history:{location:{pathname:window.location.pathname},push:x=>actions.push(x)},setColData:x=>actions.push(x)});h.setState=x=>Object.assign(h.state,x);const pending=h.caseCopy(1);await new Promise(setImmediate);window.location.pathname='/project/10/setting';release({data:{errcode:0,data:[]}});await pending;assert.deepEqual(actions,[]);});
