'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
require('../util-polyfill');const yapi=require('../server/yapi'),C=require('../server/controllers/interfaceCol');
yapi.commons={...require('../server/utils/commons'),resReturn:(data,errcode=0,errmsg='')=>({data,errcode,errmsg})};
function fixture(){const calls=[],c=Object.create(C.prototype),record={_id:41,col_id:21,project_id:10,interface_id:31};const acl={edit:true,source:true,public:false};Object.assign(c,{getUid:()=>1,checkAuth:async(p,t,role)=>p===10?acl.edit:acl.source,colModel:{get:async id=>id===21?{_id:21,project_id:10}:null},caseModel:{get:async id=>id===41?record:null,list:async()=>[record]},interfaceModel:{get:async id=>id===31?{_id:31,project_id:20}:null},projectModel:{get:async id=>({_id:id,project_type:acl.public?'public':'private'}),getBaseInfo:async id=>({_id:id,project_type:'private',env:[{name:'source'}]})}});return{c,calls,acl,record};}
async function run(f,overrides={}){const ctx={request:{body:{case_id:41,col_id:21,interface_id:31,response:{status:200,body:{},header:{}},...overrides}}};await f.c.runCaseScript(ctx);return ctx.body;}
test('case assertion uses persisted target scope with live public or private source visibility',async()=>{const original=yapi.commons.runCaseScript;try{const f=fixture();yapi.commons.runCaseScript=async(p,col,iface,scope)=>{f.calls.push({col,iface,scope:require('../server/sandbox/trusted-scope').read(scope)});return{errcode:0}};assert.equal((await run(f)).errcode,0);f.acl.source=false;assert.equal((await run(f)).errcode,403);f.acl.public=true;assert.equal((await run(f)).errcode,0);assert.deepEqual(f.calls.map(x=>x.scope.projectId),['10','10']);}finally{yapi.commons.runCaseScript=original;}});
test('forged missing stale or guest cases never reach assertion execution',async()=>{const original=yapi.commons.runCaseScript;try{for(const change of [{case_id:999},{case_id:undefined},{col_id:22},{interface_id:99},{source_project_id:999,case_id:999}]){const f=fixture();yapi.commons.runCaseScript=async()=>{throw Error('MUST NOT EXECUTE')};assert.equal((await run(f,change)).errcode,403);}const f=fixture();let executed=0;yapi.commons.runCaseScript=async()=>{executed++;return{errcode:0}};f.acl.edit=false;assert.equal((await run(f)).errcode,403);f.acl.edit=true;f.record.project_id=999;assert.equal((await run(f)).errcode,403);assert.equal(executed,0);}finally{yapi.commons.runCaseScript=original;}});
test('environment read resolves live source project and rejects revoked source without data',async()=>{const f=fixture(),ctx={query:{col_id:21}};await f.c.getCaseEnvList(ctx);assert.equal(ctx.body.errcode,0);assert.equal(ctx.body.data[0]._id,20);f.acl.source=false;await f.c.getCaseEnvList(ctx);assert.notEqual(ctx.body.errcode,0);assert.equal(ctx.body.data,null);});
