'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {handleParamsValue:read,simpleJsonPathParse:path}=require('../common/utils');
const context={global:{value:'global-kept'},7:{body:{zero:0,no:false,empty:'',nil:null,rows:[{id:'first'},['nested']],word:'AbC'}},99:{body:{secret:'UNRELATED_SYNTHETIC_VALUE'}}};
const fails=value=>assert.throws(()=>read(value,context),error=>error.code==='MISSING_CASE_OUTPUT'&&!error.message.includes('UNRELATED_SYNTHETIC_VALUE'));
test('missing prior case and missing nested fields reject exact embedded and filtered expressions',()=>{for(const value of['{{ $.88.body.secret }}','$.88.body.secret','prefix-{{ $.88.body.secret }}','{{ $.7.body.absent }}','{{ $.7.body.nil.deeper }}','{{ $.7.body.rows[9].id }}','{{ $.88.body.secret | upper }}'])fails(value);});
test('existing falsy/null leaves and legal dot/numeric bracket references retain their values',()=>{for(const[key,value]of Object.entries({zero:0,no:false,empty:'',nil:null}))assert.equal(read(`{{ $.7.body.${key} }}`,context),value);assert.equal(read('{{ $.7.body.rows[0].id }}',context),'first');assert.equal(read('{{ $.7.body.rows.0.id }}',context),'first');assert.equal(read('{{ $.7.body.rows[1][0] }}',context),'nested');assert.equal(read('prefix-{{ $.7.body.zero }}',context),'prefix-0');});
test('prototype and inherited references never resolve to unrelated objects',()=>{for(const key of['__proto__','constructor','prototype','toString'])fails(`{{ $.7.body.${key} }}`);const inherited=Object.create({8:{body:{secret:'inherited'}}});assert.throws(()=>path('$.8.body.secret',inherited),{code:'MISSING_CASE_OUTPUT'});const own=JSON.parse('{"7":{"body":{"__proto__":"own","constructor":"own","prototype":"own"}}}');for(const key of['__proto__','constructor','prototype'])assert.throws(()=>path('$.7.body.'+key,own),{code:'MISSING_CASE_OUTPUT'});});
test('existing filters global references Mock literals and invalid nonpath inputs stay compatible',()=>{assert.equal(read('{{ $.7.body.word | lower }}',context),'abc');assert.equal(read('{{ global.value }}',context),'global-kept');assert.equal(read('literal',context),'literal');assert.equal(read('@integer(4,4)',context),4);assert.equal(path('not-a-path',context),null);assert.equal(read('{{ literal | missingFilter }}',context),'{{ literal | missingFilter }}');});
