'use strict';
const test=require('node:test'),assert=require('node:assert/strict');require('../util-polyfill');
const postman=require('../common/postmanLib');let requests=[];postman.crossRequest=async(o,pre,after,context,scope)=>{requests.push({context,scope:require('../server/sandbox/trusted-scope').read(scope)});return{res:{status:200}}};
const yapi=require('../server/yapi'),C=require('../server/controllers/interface');yapi.commons={...yapi.commons,resReturn:(data,errcode=0,errmsg='')=>({data,errcode,errmsg})};
function fixture(){requests=[];const acl={edit:true,view:true,public:false};const c=Object.create(C.prototype);Object.assign(c,{getUid:()=>1,checkAuth:async(id,t,role)=>id===10?acl.edit:acl.view,Model:{get:async id=>id===31?{_id:31,project_id:20}:id===32?{_id:32,project_id:10}:null},caseModel:{get:async id=>id===41?{_id:41,col_id:21,project_id:10,interface_id:31}:null},projectModel:{get:async()=>({project_type:acl.public?'public':'private'})}});yapi.getInst=()=>({get:async id=>id===21?{_id:21,project_id:10}:null});return{c,acl};}
async function run(f,patch={}){const ctx={request:{body:{options:{url:'http://synthetic.invalid/test',method:'GET'},case_id:41,col_id:21,project_id:10,interface_id:31,...patch}}};await f.c.proxy(ctx);return ctx.body;}
test('case proxy derives target network scope and preflight never executes a request',async()=>{const f=fixture();assert.equal((await run(f,{auth_only:true})).errcode,0);assert.equal(requests.length,0);assert.equal((await run(f)).errcode,0);assert.equal(requests.length,1);assert.equal(requests[0].scope.projectId,'10');assert.equal(requests[0].context.projectId,10);});
test('live private source revocation and target guest deny preflight and execution',async()=>{for(const auth_only of[true,false]){const f=fixture();f.acl.view=false;assert.equal((await run(f,{auth_only})).errcode,403);assert.equal(requests.length,0);f.acl.public=true;assert.equal((await run(f,{auth_only})).errcode,0);requests=[];f.acl.edit=false;assert.equal((await run(f,{auth_only})).errcode,403);assert.equal(requests.length,0);}});
test('forged case collection interface and project deny before any request',async()=>{for(const patch of[{case_id:999},{col_id:999},{interface_id:32},{interface_id:999},{project_id:20},{case_id:undefined}]){const f=fixture();assert.equal((await run(f,patch)).errcode,403);assert.equal(requests.length,0);}});
test('ordinary noncase proxy preserves same-project view contract and rejects identity mismatch',async()=>{const f=fixture();assert.equal((await run(f,{case_id:undefined,col_id:undefined,interface_id:32})).errcode,0);requests=[];assert.equal((await run(f,{case_id:undefined,col_id:undefined})).errcode,403);assert.equal(requests.length,0);});
