'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),babel=require('@babel/core');
function harness(cross){const filename=path.resolve(__dirname,'../client/components/Postman/Postman.js'),code=babel.transformSync(fs.readFileSync(filename,'utf8'),{filename,babelrc:false,configFile:false,presets:[['@babel/preset-env',{targets:{node:'24'}}],'@babel/preset-react'],plugins:[['@babel/plugin-transform-class-properties',{loose:true}]]}).code;const module={exports:{}},imports={react:require('react'),'prop-types':require('prop-types'),antd:{Input:{},Select:{},Collapse:{}},underscore:require('underscore'),'../../constants/variable.js':{HTTP_METHOD:{}},'../../common.js':{isJson:()=>false},'../../utils/requestMode':{REQUEST_MODE:{SERVER:'server',BROWSER:'browser'},getRequestMode:()=> 'server'},'common/postmanLib.js':{handleParams:()=>({url:'http://synthetic.invalid',method:'GET'}),crossRequest:cross,checkNameIsExistInArray:()=>false},'client/plugin.js':{emitHook:async()=>{}},'common/createContext':()=>({})};vm.runInNewContext(code,{module,exports:module.exports,require:n=>imports[n]||{},console});const h=new module.exports.default({data:{_id:1,req_headers:[]},projectId:10,interfaceId:1,curUid:1,type:'inter'});h.setState=(x,cb)=>{Object.assign(h.state,x);if(cb)cb()};h.resBodyValidator=()=>({valid:true});return h;}
const response=text=>({res:{header:{},body:text,status:200,statusText:'OK'}});
test('cancelled earlier request cannot overwrite a newer pending result',async()=>{const releases=[];const h=harness(()=>new Promise(r=>releases.push(r)));const first=h.reqRealInterface();await new Promise(setImmediate);await h.reqRealInterface();const second=h.reqRealInterface();await new Promise(setImmediate);releases[0](response('OLD'));await first;assert.equal(h.state.loading,true);assert.equal(h.state.test_res_body,null);releases[1](response('CURRENT'));await second;assert.equal(h.state.test_res_body,'CURRENT');});
test('route switch or unmount invalidates response and error becomes visible body',async()=>{let release;const h=harness(()=>new Promise(r=>release=r));const first=h.reqRealInterface();await new Promise(setImmediate);h.componentWillUnmount();release(response('OLD'));await first;assert.equal(h.state.test_res_body,null);const failed=harness(async()=>{throw Error('Synthetic denied')});await failed.reqRealInterface();assert.equal(failed.state.test_res_body,'Synthetic denied');assert.equal(failed.state.loading,false);});
test('empty environment safely clears selection and keeps request headers',()=>{const h=harness(async()=>response('ok'));h.initEnvState('deleted',[]);assert.equal(h.state.case_env,'');assert.deepEqual(Array.from(h.state.req_headers),[]);h.handleEnvOk([],0);assert.equal(h.state.case_env,'');});

test('inline environment confirmation replaces choices and inherited headers',()=>{const h=harness(async()=>response('ok'));h.state.envDropdownOpen=true;h.showEnvModal();assert.equal(h.state.envDropdownOpen,false);h.handleEnvOk([{name:'fresh',header:[{name:'x-fixture',value:'fresh'}]}],0);assert.equal(h.state.case_env,'fresh');assert.equal(h.state.env[0].name,'fresh');assert.equal(h.state.req_headers[0].value,'fresh');assert.equal(h.state.envModalVisible,false);});
