'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module'),{randomUUID}=require('node:crypto'),mongoose=require('mongoose');
const {activeSchema}=require('../server/services/documentation/schema-mode'),{snapshot,applyEdits}=require('../server/services/documentation/description-edits'),{outboundPayload}=require('../server/services/documentation/outbound');
const seed=method=>({_id:17,project_id:11,uid:9,title:'Synthetic historical schema',path:'/synthetic',method,catid:14,desc:'before',markdown:'before',req_body_type:'json',req_body_is_json_schema:true,req_body_other:'{ historical malformed schema',res_body_type:'json',res_body_is_json_schema:false,res_body:'{}'});
test('Docs request schema activation follows the existing product method table; response and legacy methods retain behavior',()=>{for(const method of['GET','HEAD','OPTIONS','get']){const doc=seed(method);assert.equal(activeSchema(doc,'req_body_other'),false);assert.equal(snapshot(doc).some(x=>x.field==='req_body_other'),false);assert.equal(applyEdits(doc,[]).req_body_other,doc.req_body_other);assert.match(outboundPayload(doc).req_body_other.omitted,/raw/);assert.throws(()=>applyEdits(doc,[{field:'req_body_other',pointer:'/description',description:'no'}]),{code:'INVALID_INPUT'});}for(const method of['POST','PUT','PATCH','DELETE',undefined]){const doc=seed(method);assert.equal(activeSchema(doc,'req_body_other'),true);assert.throws(()=>snapshot(doc),{code:'INVALID_INPUT'});}const doc={...seed('GET'),res_body_is_json_schema:true,res_body:'{ invalid response'};assert.throws(()=>snapshot(doc),{code:'INVALID_INPUT'});});
// Load real Interface.up and getSchema; substitute only application boot dependencies.
const filename=path.resolve(__dirname,'../server/models/interface.js'),loaded=new Module(filename,module);loaded.filename=filename;loaded.paths=Module._nodeModulePaths(path.dirname(filename));const originalRequire=loaded.require.bind(loaded);loaded.require=n=>n==='../yapi.js'?{commons:{time:()=>1791028800}}:n==='./base.js'?class{}:originalRequire(n);loaded._compile(fs.readFileSync(filename,'utf8'),filename);const Interface=loaded.exports;
function modelFor(connection,name){return connection.model(name,new mongoose.Schema({...Interface.prototype.getSchema(),_id:Number}));}
async function exercise(model,read,reset){const instance=new Interface();instance.model=model;await reset(seed('GET'));let result=await instance.up(17,{title:'Metadata changed'});assert.equal(result.nModified,1);let row=await read();assert.equal(row.title,'Metadata changed');assert.equal(row.req_body_other,seed('GET').req_body_other);assert.equal(row.docs_revision,1);result=await instance.up(17,{req_body_is_json_schema:false,req_body_other:''});assert.equal(result.nModified,1);row=await read();assert.equal(row.req_body_is_json_schema,false);assert.equal(row.req_body_other,'');assert.equal(row.docs_revision,2);await reset({...seed('POST'),req_body_other:'{"type":"object"}'});await assert.rejects(instance.up(17,{req_body_other:'{ invalid active schema'}),{code:'INVALID_INPUT'});row=await read();assert.equal(row.req_body_other,'{"type":"object"}');assert.equal(row.docs_revision,undefined);await reset(seed('POST'));await assert.rejects(instance.up(17,{title:'Must remain unchanged'}),{code:'INVALID_INPUT'});assert.equal((await read()).title,seed('POST').title);}
test('real Interface.up and Mongoose cast permit historical GET metadata/clear while active POST invalid schema rejects',async()=>{let row,nodes=new Map();const model=modelFor(new mongoose.Mongoose(),'synthetic_docs_method');model.collection.findOne=async()=>structuredClone(row);model.collection.updateOne=async(_,update)=>{row={...row,...structuredClone(update.$set)};for(const k of Object.keys(update.$unset||{}))delete row[k];return{acknowledged:true,matchedCount:1,modifiedCount:1};};model.db.collection=()=>({insertOne:async r=>nodes.set(r._id,structuredClone(r)),findOne:async q=>nodes.get(q._id)});await exercise(model,async()=>structuredClone(row),async value=>{row=structuredClone(value);nodes.clear();});});
const uri=process.env.YAPI_PARITY_DOCS_MONGO_URI||process.env.YAPI_TEST_MONGO_URI;
test('real Mongo Interface.up preserves inactive historical schema and persists clear without weakening active POST validation',{skip:!uri},async()=>{const url=new URL(uri);assert.ok((process.env.CI==='true'&&url.hostname==='127.0.0.1')||url.hostname==='parity-fast-collections-new-mongo');assert.equal(url.protocol,'mongodb:');assert.equal(url.username,'');assert.equal(url.password,'');const dbName='parity_fast_collections_dm_'+randomUUID().replaceAll('-',''),connection=await mongoose.createConnection(uri,{dbName,autoIndex:false}).asPromise();try{await connection.collection('_synthetic_fixture').insertOne({_id:dbName,synthetic:true});const model=modelFor(connection,'synthetic_docs_method');await exercise(model,()=>model.collection.findOne({_id:17}),async value=>{await model.collection.deleteMany({});await connection.collection('documentation_revisions').deleteMany({});await model.collection.insertOne(value);});}finally{try{if(await connection.collection('_synthetic_fixture').findOne({_id:dbName,synthetic:true}))await connection.dropDatabase();}finally{await connection.close();}}});
