'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const babel=require('@babel/core');
function component(file,axios,message,environment={}){
 const filename=path.resolve(__dirname,'../client/containers/Project/Interface/InterfaceCol/'+file);
 const code=babel.transformSync(fs.readFileSync(filename,'utf8'),{filename,babelrc:false,configFile:false,presets:[['@babel/preset-env',{targets:{node:'24'}}],'@babel/preset-react'],plugins:[['@babel/plugin-proposal-decorators',{legacy:true}],['@babel/plugin-transform-class-properties',{loose:true}]]}).code;
 const module={exports:{}};const identity=x=>x;
 const imports={react:require('react'),'prop-types':require('prop-types'),'react-redux':{connect:()=>identity},'react-router':{withRouter:identity},'react-router-dom':{withRouter:identity},axios,antd:{message,Select:{Option:()=>null},Tree:{TreeNode:()=>null},Form:{create:()=>identity},Modal:{}},underscore:{...require('underscore'),debounce:x=>x},immer:{},'copy-to-clipboard':()=>{},'client/plugin.js':{},'common/postmanLib.js':{},'common/utils.js':{},'common/createContext':()=>{},'client/utils/requestMode':{REQUEST_MODE:{SERVER:'server',BROWSER:'browser'},getRequestMode:()=> 'server',setRequestMode:()=>{}}};
 vm.runInNewContext(code,{...environment,module,exports:module.exports,require:name=>{if(name in imports)return imports[name];if(name==='../../../../common.js'||name.startsWith('../../../../reducer/')||name.startsWith('../../../../components')||name.startsWith('client/components/')||name.startsWith('client/utils/')||name.startsWith('./'))return {};throw Error('Unexpected import '+name);}},{filename});return module.exports.default;
}

// Dependency spies inspect dispatch only; no user script is evaluated.
test('case Test toggle controls browser collection script payload',async()=>{const payloads=[];const C=component('InterfaceColContent.js',{post:async(_,body)=>{payloads.push(body);return{data:{errcode:0}}}},{error:()=>{}});const h=new C({currColId:5});for(const enabled of[false,true]){await h.handleScriptTest({_id:7,interface_id:8,test_script:'synthetic script text',enable_script:enabled},{},[],{});assert.equal(payloads.at(-1).script,enabled?'synthetic script text':'');}});
test('collection global script toggle preserves edited content',()=>{const C=component('InterfaceColContent.js',{},{});const h=new C({currColId:5});h.setState=x=>Object.assign(h.state,x);h.state.commonSetting.checkScript={enable:false,content:'synthetic script text'};h.onChangeScriptEnable(true);assert.deepEqual(JSON.parse(JSON.stringify(h.state.commonSetting.checkScript)),{enable:true,content:'synthetic script text'});h.onChangeScriptEnable(false);assert.equal(h.state.commonSetting.checkScript.content,'synthetic script text');});
test('case Test toggle controls server automation script payload',async()=>{require('../util-polyfill');const yapi=require('../server/yapi');yapi.emitHook=()=>{};const C=require('../server/controllers/open'),h=Object.create(C.prototype),payloads=[],previous=yapi.commons;try{yapi.commons={...previous,runCaseScript:async body=>{payloads.push(body);return{errcode:0}}};for(const enabled of[false,true]){await h.handleScriptTest({col_id:5,interface_id:8,test_script:'synthetic script text',enable_script:enabled},{},[],{});assert.equal(payloads.at(-1).script,enabled?'synthetic script text':'');}}finally{yapi.commons=previous;}});

test('missing output collection errors persist a visible report and later independent cases still run',async()=>{const saved=[];const C=component('InterfaceColContent.js',{post:async(_,body)=>{saved.push(body);return{data:{errcode:0}}}},{error:()=>{}});const h=new C({currColId:5,envList:[],currProject:{}});h.isCurrentCollectionLoaded=()=>true;h.setState=x=>Object.assign(h.state,typeof x==='function'?x(h.state):x);h.state.rows=[{_id:7,project_id:10},{_id:8,project_id:10}];h.records={99:{body:{secret:'unrelated old run'}}};h.handleTest=async item=>{assert.equal(h.records[99],undefined);if(item._id===7){const error=new Error('MISSING_CASE_OUTPUT: synthetic missing output');error.code='MISSING_CASE_OUTPUT';throw error;}return{code:0,res_body:{ok:true},params:{}};};await h.executeTests();const report=JSON.parse(saved[0].test_report);assert.equal(report[7].code,400);assert.match(report[7].validRes[0].message,/MISSING_CASE_OUTPUT/);assert.equal(report[8].code,0);assert.equal(h.state.running,false);assert.doesNotMatch(saved[0].test_report,/unrelated old run/);});
