'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),babel=require('@babel/core');
function harness(cross,axios={}){const filename=path.resolve(__dirname,'../client/components/Postman/Postman.js'),code=babel.transformSync(fs.readFileSync(filename,'utf8'),{filename,babelrc:false,configFile:false,presets:[['@babel/preset-env',{targets:{node:'24'}}],'@babel/preset-react'],plugins:[['@babel/plugin-transform-class-properties',{loose:true}]]}).code;const module={exports:{}},imports={axios,json5:require('json5'),react:require('react'),'prop-types':require('prop-types'),antd:{Input:{},Select:{},Collapse:{}},underscore:require('underscore'),'../../constants/variable.js':{HTTP_METHOD:{}},'../../common.js':{isJson:()=>false},'../../utils/requestMode':{REQUEST_MODE:{SERVER:'server',BROWSER:'browser'},getRequestMode:()=> 'server'},'common/postmanLib.js':{handleParams:()=>({url:'http://synthetic.invalid',method:'GET'}),crossRequest:cross,checkNameIsExistInArray:()=>false},'client/plugin.js':{emitHook:async()=>{}},'common/createContext':()=>({})};vm.runInNewContext(code,{module,exports:module.exports,require:n=>imports[n]||{},console});const h=new module.exports.default({data:{_id:1,project_id:10,req_headers:[]},projectId:10,interfaceId:1,curUid:1,type:'inter'});h.setState=(x,cb)=>{Object.assign(h.state,x);if(cb)cb()};h.resBodyValidator=()=>({valid:true});h.state.initializing=false;h.initializedIdentity=h.requestIdentity(h.props.data);return h;}
const response=text=>({res:{header:{},body:text,status:200,statusText:'OK'}});
test('cancelled earlier request cannot overwrite a newer pending result',async()=>{const releases=[];const h=harness(()=>new Promise(r=>releases.push(r)));const first=h.reqRealInterface();await new Promise(setImmediate);await h.reqRealInterface();const second=h.reqRealInterface();await new Promise(setImmediate);releases[0](response('OLD'));await first;assert.equal(h.state.loading,true);assert.equal(h.state.test_res_body,null);releases[1](response('CURRENT'));await second;assert.equal(h.state.test_res_body,'CURRENT');});
test('route switch or unmount invalidates response and error becomes visible body',async()=>{let release;const h=harness(()=>new Promise(r=>release=r));const first=h.reqRealInterface();await new Promise(setImmediate);h.componentWillUnmount();release(response('OLD'));await first;assert.equal(h.state.test_res_body,null);const failed=harness(async()=>{throw Error('Synthetic denied')});await failed.reqRealInterface();assert.equal(failed.state.test_res_body,'Synthetic denied');assert.equal(failed.state.loading,false);});
test('empty environment safely clears selection and keeps request headers',()=>{const h=harness(async()=>response('ok'));h.initEnvState('deleted',[]);assert.equal(h.state.case_env,'');assert.deepEqual(Array.from(h.state.req_headers),[]);h.handleEnvOk([],0);assert.equal(h.state.case_env,'');});

test('inline environment confirmation replaces choices and inherited headers',()=>{const h=harness(async()=>response('ok'));h.state.envDropdownOpen=true;h.showEnvModal();assert.equal(h.state.envDropdownOpen,false);h.handleEnvOk([{name:'fresh',header:[{name:'x-fixture',value:'fresh'}]}],0);assert.equal(h.state.case_env,'fresh');assert.equal(h.state.env[0].name,'fresh');assert.equal(h.state.req_headers[0].value,'fresh');assert.equal(h.state.envModalVisible,false);});

test('pending schema conversion cannot send the previous interface and failure remains retryable',async()=>{let release,calls=0;const h=harness(async()=>{calls++;return response('ok')},{post:()=>new Promise(r=>release=r)});const target={_id:2,project_id:20,path:'/new',req_body_type:'json',req_body_is_json_schema:true,req_body_other:'{"type":"object"}',env:[]};const pending=h.initState(target);h.props={...h.props,data:target,projectId:20,interfaceId:2};await h.reqRealInterface();assert.equal(calls,0);assert.equal(h.state.path,'');release({data:{synthetic:'new'}});await pending;assert.equal(h.isRequestReady(),true);assert.equal(h.state.req_body_other,'{"synthetic":"new"}');await h.reqRealInterface();assert.equal(calls,1);await h.initState({...target,req_body_other:'invalid json'});await h.reqRealInterface();assert.equal(calls,1);assert.equal(h.state.path,'');assert.equal(h.state.initializationError,'请求初始化失败，请重试');await h.initState({...target,req_body_is_json_schema:false,req_body_other:'{}'});assert.equal(h.isRequestReady(),true);});

test('changing request context before document props update cannot send stale state',async()=>{let calls=0;const h=harness(async()=>{calls++;return response('ok')});h.props={...h.props,interfaceId:2,projectId:20};await h.reqRealInterface();assert.equal(calls,0);assert.equal(h.isRequestReady(),false);});
