'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const babel=require('@babel/core');
function component(file,axios,message){
 const filename=path.resolve(__dirname,'../client/containers/Project/Interface/InterfaceCol/'+file);
 const code=babel.transformSync(fs.readFileSync(filename,'utf8'),{filename,babelrc:false,configFile:false,presets:[['@babel/preset-env',{targets:{node:'24'}}],'@babel/preset-react'],plugins:[['@babel/plugin-proposal-decorators',{legacy:true}],['@babel/plugin-transform-class-properties',{loose:true}]]}).code;
 const module={exports:{}};const identity=x=>x;
 const imports={react:require('react'),'prop-types':require('prop-types'),'react-redux':{connect:()=>identity},'react-router':{withRouter:identity},'react-router-dom':{withRouter:identity},axios,antd:{message,Select:{Option:()=>null}},underscore:{},immer:{},'copy-to-clipboard':()=>{},'client/plugin.js':{},'common/postmanLib.js':{},'common/utils.js':{},'common/createContext':()=>{},'client/utils/requestMode':{REQUEST_MODE:{SERVER:'server',BROWSER:'browser'},getRequestMode:()=> 'server',setRequestMode:()=>{}}};
 vm.runInNewContext(code,{module,exports:module.exports,require:name=>{if(name in imports)return imports[name];if(name.startsWith('../../../../reducer/')||name.startsWith('../../../../components')||name.startsWith('client/components/')||name.startsWith('client/utils/')||name.startsWith('./'))return {};throw Error('Unexpected import '+name);}},{filename});return module.exports.default;
}
function caseHarness(post){const refresh=[],messages=[];const Class=component('InterfaceCaseContent.js',{post},{error:x=>messages.push(x),success:x=>messages.push(x)});const props={currCase:{_id:1,casename:'old'},match:{params:{id:'10',actionId:'1'}},fetchCaseData:id=>refresh.push(id),fetchInterfaceColList:()=>refresh.push('tree')};const instance=new Class(props);instance.postman={state:{}};instance.state.editCasename='new';return{instance,refresh,messages};}
test('case update serializes repeat click and ignores late refresh after route changes',async()=>{let release,calls=0;const h=caseHarness(()=>{calls++;return new Promise(r=>release=r)});const first=h.instance.updateCase();await h.instance.updateCase();assert.equal(calls,1);h.instance.props={...h.instance.props,currCase:{_id:2,casename:'other'},match:{params:{id:'10',actionId:'2'}}};release({data:{errcode:0}});await first;assert.deepEqual(h.refresh,[]);assert.deepEqual(h.messages,[]);assert.equal(h.instance.activeCaseSave,null);});
test('case application and transport rejection surface failure and allow retry',async()=>{let call=0;const h=caseHarness(async()=>{call++;if(call===1)return{data:{errcode:40033,errmsg:'denied'}};if(call===2)throw Error('offline');return{data:{errcode:0}}});await h.instance.updateCase();await h.instance.updateCase();assert.deepEqual(h.refresh,[]);assert.equal(h.messages.length,2);await h.instance.updateCase();assert.deepEqual(h.refresh,['tree',1]);});
test('order snapshots persist serially and only final snapshot refreshes tree',async()=>{const calls=[],releases=[],refresh=[];const Class=component('InterfaceColContent.js',{post:(_,body)=>{calls.push(JSON.parse(JSON.stringify(body)));return new Promise(r=>releases.push(r));}},{error:()=>{}});const h=new Class({currColId:5,match:{params:{id:'10'}},fetchInterfaceColList:id=>refresh.push(id)});h.state.rows=[{_id:1},{_id:2}];const first=h.onDrop();h.state.rows=[{_id:2},{_id:1}];const second=h.onDrop();await new Promise(setImmediate);assert.equal(calls.length,1);releases[0]({data:{errcode:0}});await first;await new Promise(setImmediate);assert.equal(calls.length,2);assert.deepEqual(calls[1],[{id:2,index:0},{id:1,index:1}]);assert.deepEqual(refresh,[]);releases[1]({data:{errcode:0}});await second;assert.deepEqual(refresh,['10']);});
test('order application rejection is visible and next snapshot can still save',async()=>{let count=0;const errors=[],refresh=[];const Class=component('InterfaceColContent.js',{post:async()=>({data:++count===1?{errcode:40033,errmsg:'denied'}:{errcode:0}})},{error:x=>errors.push(x)});const h=new Class({currColId:5,match:{params:{id:'10'}},fetchInterfaceColList:id=>refresh.push(id)});h.state.rows=[{_id:1}];await h.onDrop();assert.deepEqual(errors,['denied']);assert.deepEqual(refresh,[]);await h.onDrop();assert.deepEqual(refresh,['10']);});
test('case fallback route without explicit action ID can save its current case',async()=>{const h=caseHarness(async()=>({data:{errcode:0}}));delete h.instance.props.match.params.actionId;await h.instance.updateCase();assert.deepEqual(h.refresh,['tree',1]);});
test('an order completion after unmount cannot refresh a different project view',async()=>{let release;const refresh=[];const Class=component('InterfaceColContent.js',{post:()=>new Promise(r=>release=r)},{error:()=>{}});const h=new Class({currColId:5,match:{params:{id:'10'}},fetchInterfaceColList:id=>refresh.push(id)});h.state.rows=[{_id:1}];const pending=h.onDrop();await new Promise(setImmediate);h.componentWillUnmount();release({data:{errcode:0}});await pending;assert.deepEqual(refresh,[]);});

test('rule dialog identity prevents a stale draft writing the next route',async()=>{let writes=0;const Class=component('InterfaceColContent.js',{post:async()=>{writes++;return{data:{errcode:0}}}},{error:()=>{},success:()=>{}});const h=new Class({currColId:5,match:{params:{actionId:'5'}}});h.setState=x=>Object.assign(h.state,x);h.loadedCollectionId=5;h.openCommonSetting();assert.equal(h.state.commonSettingModalVisible,true);h.props={currColId:6,match:{params:{actionId:'6'}}};await h.handleCommonSetting();assert.equal(writes,0);h.loadedCollectionId=6;h.openCommonSetting();await h.handleCommonSetting();assert.equal(writes,1);});
test('assertion permission errors without logs display the server error',async()=>{const Class=component('InterfaceColContent.js',{post:async()=>({data:{errcode:403,errmsg:'Forbidden',data:null}})},{error:()=>{}});const h=new Class({currColId:5});const errors=[];await h.handleScriptTest({_id:7,interface_id:8},{},errors,{});assert.equal(errors[0].message,'Forbidden');});

test('collection reducers discard old route and old generation environment data',()=>{const filename=path.resolve(__dirname,'../client/reducer/modules/interfaceCol.js');const code=babel.transformSync(fs.readFileSync(filename,'utf8'),{filename,babelrc:false,configFile:false,presets:[['@babel/preset-env',{targets:{node:'24'}}]]}).code;const module={exports:{}};vm.runInNewContext(code,{module,exports:module.exports,require:()=>({get:async()=>({data:{errcode:0,data:[]}})})});const m=module.exports,old={},current={};let state=m.default(undefined,{type:'init'});state=m.default(state,m.setColData({currColId:6,collectionLoad:current}));const action=m.fetchCaseEnvList(5,old);action.payload={data:{errcode:0,data:['stale']}};assert.equal(m.default(state,action),state);action.meta.colId=6;assert.equal(m.default(state,action),state);action.meta.load=current;assert.deepEqual(Array.from(m.default(state,action).envList),['stale']);});
