'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
function load(get,errors,envRead=async()=>response()){const {code}=require('@babel/core').transformSync(fs.readFileSync(path.join(__dirname,'../client/containers/Project/Setting/ProjectEnv/index.js'),'utf8'),{babelrc:false,configFile:false,presets:[['@babel/preset-env',{targets:{node:'24'},modules:'commonjs'}],['@babel/preset-react',{runtime:'automatic'}]],plugins:[['@babel/plugin-proposal-decorators',{legacy:true}],['@babel/plugin-transform-class-properties',{loose:true}]]});const m={exports:{}};new Function('module','exports','require',code)(m,m.exports,n=>{if(n==='react-redux')return{connect:()=>C=>C};if(n==='axios')return{get};if(n.includes('reducer/modules/project'))return{getEnv:()=>({type:'yapi/project/PROJECT_GET_ENV',payload:envRead()})};if(n==='antd')return{Layout:{},message:{error:s=>errors.push(s),success:()=>{}}};if(n.endsWith('.scss')||n.includes('ProjectEnvContent')||n.includes('reducer/modules/project')||n.includes('EasyDragSort'))return{};return require(n);});m.exports.default.guardedGetEnv=m.exports.guardedGetEnv;return m.exports.default;}
const response=(env=[],role='dev')=>({data:{errcode:0,data:{_id:2,env,role}}});
function component(C,updateEnv,onOk){const c=new C({projectId:2,onOk,updateEnv,getProject:()=>assert.fail('inline replaced route project'),getEnv:()=>assert.fail('inline replaced route environments')});c.setState=s=>Object.assign(c.state,s);c._isMounted=true;c.state={...c.state,_id:2,env:[{name:'draft'}],canEdit:true};return c;}
test('inline source load uses local role and never dispatches route project replacement',async()=>{const c=component(load(async()=>response([{name:'source'}]),[]),()=>{},()=>{});await c.componentWillMount();assert.equal(c.state.env[0].name,'source');assert.equal(c.state.canEdit,true);});
for(const role of ['guest',false])test(`source ${role} view cannot mutate environment`,async()=>{const c=component(load(async()=>response([],role),[]),()=>assert.fail('readonly wrote'),()=>assert.fail('readonly completed'));await c.componentWillMount();await c.onSubmit({env:{name:'forbidden'}},0);assert.equal(c.state.canEdit,false);});
for(const failure of ['business','network'])test(`inline ${failure} mutation failure keeps draft and does not close, retry succeeds`,async()=>{let writes=0,closed=0;const errors=[],c=component(load(async()=>response([{name:'saved'}]),errors),async()=>{if(++writes===1){if(failure==='network')throw Error('synthetic');return{payload:{data:{errcode:400}}};}return{payload:{data:{errcode:0}}};},()=>closed++);await c.onSubmit({env:{name:'saved'}},0);assert.equal(closed,0);assert.equal(c.savedReceipt,undefined);assert.equal(c.state.env[0].name,'draft');assert.equal(errors.length,1);await c.onSubmit({env:{name:'saved'}},0);assert.equal(closed,1);assert.equal(writes,2);});
for(const failure of ['business','network'])test(`committed env plus ${failure} refresh failure retains receipt and retries read only`,async()=>{let reads=0,writes=0,closed=0;const errors=[],c=component(load(async()=>{if(++reads===1){if(failure==='network')throw Error('synthetic');return{data:{errcode:400}};}return response([{name:'saved'}]);},errors),async()=>{writes++;return{payload:{data:{errcode:0}}};},()=>closed++);await c.onSubmit({env:{name:'saved'}},0);assert.equal(closed,0);assert.equal(c.state.savedPendingRefresh,true);assert.equal(c.state.env[0].name,'saved');await c.onSubmit({env:{name:'duplicate'}},0);assert.equal(writes,1);await c.refreshSaved();assert.equal(writes,1);assert.equal(reads,2);assert.equal(closed,1);assert.equal(c.state.savedPendingRefresh,false);assert.deepEqual(errors,['已保存，但加载失败，请重新加载']);});
test('double submit waits for persistence before callback and sends one mutation',async()=>{let done,writes=0,closed=0;const wait=new Promise(r=>done=r),c=component(load(async()=>response([{name:'saved'}]),[]),async()=>{writes++;await wait;return{payload:{data:{errcode:0}}};},()=>closed++);const pending=c.onSubmit({env:{name:'saved'}},0);await c.onSubmit({env:{name:'duplicate'}},0);assert.equal(writes,1);assert.equal(closed,0);done();await pending;assert.equal(closed,1);});
for(const phase of ['post','local-read','project-read','environment-read'])test(`settings route leaving during ${phase} cannot replace destination Redux state`,async()=>{let release;const pending=new Promise(r=>release=r);let reads=0,dispatches=0,writes=0;const errors=[];const C=load(async()=>{reads++;if(phase==='local-read')await pending;return response();},errors);const c=component(C,async()=>{writes++;if(phase==='post')await pending;return{payload:{data:{errcode:0}}};},undefined);c.props.getProject=async(id,meta)=>{if(phase==='project-read')await pending;if(meta.isCurrent())dispatches++;return{payload:response()};};c.props.getEnv=async(id,meta)=>{if(phase==='environment-read')await pending;if(meta.isCurrent())dispatches++;return{payload:response()};};const result=c.onSubmit({env:{name:'saved'}},0);for(let n=0;n<8;n++)await Promise.resolve();const priorDispatches=dispatches;c.componentWillUnmount();release();await result;assert.equal(writes,1,'already committed source write is not cancelled');assert.equal(dispatches,priorDispatches,'no late action changes destination');if(phase==='post')assert.equal(reads,0,'unmounted POST completion starts no refresh');assert.deepEqual(errors,[]);});
test('owned environment action bridge discards a response after route changes',async()=>{let release,current=true;const pending=new Promise(r=>release=r);const C=load(async()=>response(),[],()=>pending);const action=C.guardedGetEnv(2,{isCurrent:()=>current});current=false;release(response());const done=await action;assert.equal(done.type,'yapi/project/ENV_REFRESH_IGNORED');});
test('owned environment action bridge retains normal fulfilled action semantics',async()=>{const C=load(async()=>response(),[],async()=>response([{name:'saved'}]));const done=await C.guardedGetEnv(2,{isCurrent:()=>true});assert.equal(done.type,'yapi/project/PROJECT_GET_ENV');assert.equal(done.payload.data.data.env[0].name,'saved');});
