'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),Module=require('node:module');
function load(relative,resolve){const filename=path.resolve(__dirname,'..',relative),m=new Module(filename,module);m.filename=filename;m.paths=Module._nodeModulePaths(path.dirname(filename));const actual=m.require.bind(m);m.require=n=>resolve(n,actual);m._compile(fs.readFileSync(filename,'utf8'),filename);return m.exports;}
function controller(empty=false){const calls={categories:[],imports:[]};class Base{getUid(){return 7;}}const cat={list:async()=>empty?[]:[{_id:1}],save:async data=>{calls.categories.push(data);return{_id:1};}};const yapi={emitHook:(name,registry)=>{registry.swagger=async()=>({cats:[],apis:[]});},getInst:()=>cat,WEBCONFIG:{port:1},commons:{time:()=>1,resReturn:(data,errcode,errmsg)=>({data,errcode,errmsg})}};const C=load('server/controllers/open.js',(n,actual)=>{if(n==='../yapi.js')return yapi;if(n==='./base.js')return Base;if(n.includes('/models/'))return class{};if(n==='../../common/HandleImportData')return async(...args)=>{calls.imports.push(args);if(args[11])await args[11]();args[7]('imported');};if(['../../common/postmanLib','../../common/utils.js','../utils/reportHtml','../../common/createContext'].includes(n))return{};return actual(n);});const instance=Object.create(C.prototype);instance.interfaceCatModel=cat;instance.projectModel={get:async()=>({basePath:''})};return{C,instance,calls};}
const request=()=>({params:{type:'swagger',json:'{}',project_id:11,merge:'normal',token:'synthetic'}});
test('default HTTP import cannot inject beforeWrite, Symbol name or UID capability',async()=>{const f=controller(true),r=request();r.params.beforeWrite='bypass';r.params.swaggerWriteGuard='bypass';r.params.uid=999;r.swaggerWriteGuard=()=>{throw Error('untrusted string key');};await f.instance.importData(r);assert.equal(r.body.errcode,0);assert.equal(f.calls.imports[0][11],undefined);assert.equal(f.calls.categories[0].uid,7);});
test('trusted Symbol guard denies before default-category write and before shared import',async()=>{const f=controller(true),r=request();r[f.C.swaggerWriteGuard]=async()=>{throw Error('revoked');};await assert.rejects(f.instance.importData(r),/revoked/);assert.equal(f.calls.categories.length,0);assert.equal(f.calls.imports.length,0);});
test('trusted internal closure uses saved actor for default category and reaches importer intact',async()=>{const f=controller(true),r=request();let checks=0;const guard=async()=>{checks++;return{uid:29};};r[f.C.swaggerWriteGuard]=guard;await f.instance.importData(r);assert.equal(r.body.errcode,0);assert.equal(checks,2);assert.equal(f.calls.categories[0].uid,29);assert.equal(f.calls.imports[0][11],guard);});
for(const mode of ['normal','good','merge'])test('shared import optional guard checks category, basepath and each interface '+mode,async()=>{const calls=[];let checks=0;const handle=load('common/HandleImportData.js',(n,actual)=>n==='axios'?{post:async(url)=>{calls.push(url);return{data:{errcode:0,data:url.endsWith('add_cat')?{_id:3}:[{}]}};}}:actual(n));const input=()=>({cats:[{name:'synthetic'}],basePath:'/synthetic',apis:[1,2].map(n=>({path:'/a'+n,method:'GET',catname:'synthetic'}))});await handle(input(),11,1,[],null,mode,()=>{},()=>{},()=>{},'synthetic',1,async()=>{checks++;});assert.equal(checks,4);assert.equal(calls.length,4);calls.length=0;await handle(input(),11,1,[],null,mode,()=>{},()=>{},()=>{},'synthetic',1);assert.equal(calls.length,4,'default imports keep their existing four operations');});
for(const deniedAt of [1,2,3,4])test('shared import stops before rejected mutation boundary '+deniedAt,async()=>{let checks=0,writes=0;const handle=load('common/HandleImportData.js',(n,actual)=>n==='axios'?{post:async url=>{writes++;return{data:{errcode:0,data:url.endsWith('add_cat')?{_id:3}:[{}]}};}}:actual(n));await assert.rejects(handle({cats:[{name:'synthetic'}],basePath:'/synthetic',apis:[1,2].map(n=>({path:'/a'+n,method:'GET'}))},11,1,[],null,'merge',()=>{},()=>{},()=>{},'synthetic',1,async()=>{if(++checks===deniedAt)throw Error('revoked');}),/revoked/);assert.equal(writes,deniedAt-1);});

for(const code of [42014,40033,500])test('normal import surfaces non-duplicate business error '+code,async()=>{const errors=[],success=[],calls=[];const handle=load('common/HandleImportData.js',(n,actual)=>n==='axios'?{post:async()=>{calls.push(1);return{data:{errcode:code,errmsg:'synthetic failure'}};}}:actual(n));await handle({cats:[],apis:[{path:'/one'},{path:'/two'}]},11,1,[],null,'normal',e=>errors.push(e),m=>success.push(m),()=>{},'synthetic',1);assert.equal(errors.length,1);assert.equal(success.length,0);assert.equal(calls.length,1);});
test('normal duplicate40022 preserves benign existing-interface behavior',async()=>{const errors=[],success=[];const handle=load('common/HandleImportData.js',(n,actual)=>n==='axios'?{post:async()=>({data:{errcode:40022,errmsg:'exists'}})}:actual(n));await handle({cats:[],apis:[{path:'/one'}]},11,1,[],null,'normal',e=>errors.push(e),m=>success.push(m),()=>{},'synthetic',1);assert.equal(errors.length,0);assert.match(success[0],/已存在的接口 1/);});
