'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
function load(http,errors=[]){const{code}=require('@babel/core').transformSync(fs.readFileSync(path.join(__dirname,'../exts/yapi-plugin-swagger-auto-sync/swaggerAutoSync/swaggerAutoSync.js'),'utf8'),{babelrc:false,configFile:false,presets:[['@babel/preset-env',{targets:{node:'24'},modules:'commonjs'}],['@babel/preset-react',{runtime:'automatic'}]],plugins:[['@babel/plugin-proposal-decorators',{legacy:true}],['@babel/plugin-transform-class-properties',{loose:true}]]});const m={exports:{}};new Function('module','exports','require',code)(m,m.exports,n=>{if(n==='axios')return http;if(n==='react-redux')return{connect:()=>C=>C};if(n==='antd')return{Form:{create:()=>C=>C},Select:{},message:{error:s=>errors.push(s),success:()=>{}}};if(n.startsWith('client/'))return{};return require(n);});return m.exports.default;}
function component(C,validate=async()=>({payload:{data:{errcode:0,data:{swagger:'2.0'}}}})){const fields={};const c=new C({projectId:2,projectMsg:{_id:999,role:'owner'},handleSwaggerUrlData:validate,form:{setFieldsValue:x=>Object.assign(fields,x),validateFields:cb=>cb(null,{sync_mode:'normal',sync_cron:'0 0 1 1 *',sync_json_url:'http://synthetic.invalid/swagger'})}});c.setState=s=>Object.assign(c.state,s);c.mounted=true;c.fields=fields;return c;}
for(const kind of ['empty','business','network','valid'])test(`Swagger URL ${kind} validation calls back once and checks business result`,async()=>{const c=component(load({}),async()=>{if(kind==='network')throw Error('synthetic');return{payload:{data:kind==='business'?{errcode:402}:{errcode:0,data:{swagger:'2.0'}}}};});const replies=[];await c.validSwaggerUrl(null,kind==='empty'?'':'http://synthetic.invalid',s=>replies.push(s));assert.equal(replies.length,1);assert.equal(Boolean(replies[0]),['business','network'].includes(kind));});
test('Swagger reads route project and explicitly populates fields, including latest failed execution',async()=>{const urls=[];const c=component(load({get:async(url,params)=>{urls.push([url,params]);return{data:{errcode:0,data:url.startsWith('/api/log')?{list:[{content:'自动同步接口状态:失败, synthetic'}]}:{sync_json_url:'http://synthetic.invalid/saved',sync_cron:'0 0 1 1 *',sync_mode:'good',is_sync_open:true}}};}}));assert.equal(await c.getSyncData(),true);assert.equal(urls[0][0],'/api/plugin/autoSync/get?project_id=2');assert.equal(c.fields.sync_mode,'good');assert.match(c.state.syncStatus,/失败/);});
test('Swagger guest never posts and rapid owner save posts once',async()=>{let writes=0,release;const pending=new Promise(r=>release=r);const c=component(load({post:async()=>{writes++;await pending;return{data:{errcode:0}};},get:async url=>({data:{errcode:0,data:url.startsWith('/api/log')?{list:[]}:{sync_mode:'normal'}}})}));c.props.projectMsg.role='guest';c.handleSubmit();assert.equal(writes,0);c.props.projectMsg.role='owner';c.state.ready=true;c.readyProject=2;c.handleSubmit();c.handleSubmit();assert.equal(writes,1);release();for(let n=0;n<12;n++)await Promise.resolve();assert.equal(c.state.saving,false);assert.equal(c.state.savedPending,false);});

const deferred=()=>{let resolve;const promise=new Promise(r=>resolve=r);return{promise,resolve};};
const response=data=>({data:{errcode:0,data}});
test('Swagger initial read gates writes and superseded reads cannot replace loaded settings',async()=>{const held=deferred();let reads=0,writes=0;const c=component(load({post:async()=>{writes++;return response({});},get:async url=>url.startsWith('/api/log')?response({list:[]}):++reads===1?held.promise:response({sync_mode:'merge',sync_json_url:'new'})}));const stale=c.getSyncData();c.handleSubmit();assert.equal(writes,0);assert.equal(c.state.ready,false);assert.equal(await c.getSyncData(),true);held.resolve(response({sync_mode:'normal',sync_json_url:'old'}));assert.equal(await stale,false);assert.equal(c.fields.sync_json_url,'new');assert.equal(c.state.loading,false);});
test('Swagger draft survives refresh and failed initial load has explicit retry',async()=>{let fail=true;const c=component(load({get:async url=>{if(fail)throw Error('synthetic load failed');return response(url.startsWith('/api/log')?{list:[]}:{sync_json_url:'saved'});}}));assert.equal(await c.getSyncData(),false);assert.equal(c.state.ready,false);assert.match(c.state.loadError,/failed/);fail=false;assert.equal(await c.getSyncData(),true);c.fields.sync_json_url='draft';c.markDirty();assert.equal(await c.getSyncData(),false);assert.equal(c.fields.sync_json_url,'draft');assert.match(c.state.loadError,/草稿/);});
test('Swagger project change and unmount discard both config and status responses',async()=>{for(const stage of ['config','status']){const held=deferred();const c=component(load({get:async url=>url.startsWith('/api/log')?(stage==='status'?held.promise:response({list:[]})):(stage==='config'?held.promise:response({sync_json_url:'old'}))}));const pending=c.getSyncData();await Promise.resolve();c.props.projectId=3;c.componentWillUnmount();held.resolve(response(stage==='config'?{sync_json_url:'old'}:{list:[]}));assert.equal(await pending,false);assert.equal(c.fields.sync_json_url,undefined);}});
test('Swagger committed save with failed refresh retries only GET',async()=>{let posts=0,fail=true;const c=component(load({post:async()=>{posts++;return response({});},get:async url=>{if(fail)throw Error('read failed');return response(url.startsWith('/api/log')?{list:[]}:{sync_mode:'normal'});}}));c.state.ready=true;c.readyProject=2;c.markDirty();c.handleSubmit();for(let i=0;i<16;i++)await Promise.resolve();assert.equal(c.state.savedPending,true);assert.equal(posts,1);c.handleSubmit();assert.equal(posts,1);fail=false;assert.equal(await c.getSyncData(),true);assert.equal(c.state.savedPending,false);assert.equal(posts,1);});
